### ISSUE TITLE
[bug] Nullifer beam effects disappear

### ISSUE THREAD

**Issue by Lucius15** [KnuckleCracker/CW4-bug-tracker#10]
1. No, it remains after restart.

2.  [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5000342/output_log.txt)

3. I've added tooltips in screenshots
![20200730121725_1](https://user-images.githubusercontent.com/63197755/88907869-d4149200-d261-11ea-9cbd-50a2ac550c00.jpg "Where effects disapperaed: beam covered in AC, but camera looking though creeper, then air and AC. Where effects still on place: camera looking throught creeper and then AC.")
![20200730122224_1](https://user-images.githubusercontent.com/63197755/88907877-d70f8280-d261-11ea-92de-7bb44ca55da7.jpg "Looking through creeper")
![20200730122951_1](https://user-images.githubusercontent.com/63197755/88907892-dd056380-d261-11ea-8cb7-cd94e68035ac.jpg "Beam and camera in AC")
![20200730123008_1](https://user-images.githubusercontent.com/63197755/88907904-df67bd80-d261-11ea-96aa-b9ecd83e9880.jpg "Effects are partially visible")

4. Beam effects disappear if you looking through different substances (like if nullifer beam covered in AC and your camera floating above it *in air*). But if your camera and beam in same things, then effects does not disappear.

**Additional context**
(sorry for my bad english)

**Comment by grabz-dev** [comment]
The nullifier beam sparks seem to disappear in deep AC. The sparks kinda flash on and off in disturbed AC.

![image](https://user-images.githubusercontent.com/51026936/95653465-41159500-0af9-11eb-84f4-ffeae96a4cdb.png)
![image](https://user-images.githubusercontent.com/51026936/95653466-4377ef00-0af9-11eb-98de-363a25f53c87.png)

**Comment by Lucius15** [comment]
Got some photos from new version and results are same.
![when AC at beam's level, effects are half disappeared](https://user-images.githubusercontent.com/63197755/95662863-ac378980-0b42-11eb-9d78-d39f7463b87e.jpg)
![looking straight through fully hide effects](https://user-images.githubusercontent.com/63197755/95662900-06384f00-0b43-11eb-89c7-4b88a0cb462c.jpg)
