### ISSUE TITLE
Charge Percent Without Overload

### ISSUE THREAD

**Issue by Commandthealien** [KnuckleCracker/CW4-bug-tracker#1001]
This is just a Quality Of Life thing but I find it slightly annoying to have no overload button but still have the percentage.
I just want it to not say the percentage when there is no overload button.

![image](https://user-images.githubusercontent.com/90158904/138281571-26a7eebb-e543-45a6-bd49-78e246413ed1.png)

**Comment by knucracker** [comment]
I've updated the nullifier display  to not show the charge percent unless it is greater than 0
