### ISSUE TITLE
[Bug.Minor] CW4 map submission tag character limit is applied incorrectly when newline delimited

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1005]
I found today while uploading a map that I was presented with the "Tags cannot have more than 20 characters" error when trying to submit the following in the tag text area
```
MATRIX
CUSTOM
AC
4RPL
MEDIUM
```
However, the following went through:
```
MATRIX,CUSTOM,AC,4RPL,MEDIUM
```
This leads me to believe that the length check may possibly be doing a comma split, meaning it incorrectly checks individual tag length for the newline syntax.

**Comment by knucracker** [comment]
I just gave it a shot, and am not able to reproduce this.  The code also 'looks' correct (but we all know how that can go).  Were you by chance doing this from linux under proton?  I've seen some really odd cases show up with text input under proton.  I do check for empty spaces and other white space around the tags, but maybe some other stuff is getting in somehow.

The code basically takes the entire 'string' and then tokenizes it based on comma or new_line characters.  That gives each tag back in an array and then those are iterated over, trimmed for white space, checked for size, and then added back together into a new final string that is comma separated and is used for submission to the server.

**Comment by grabz-dev** [comment]
Windows 10.

I unfortunately did not take a screenshot. Next time I upload a map I will try again and see if it happens once more, perhaps it was some weird one-off.
