### ISSUE TITLE
[Bug] Nullifier not working after load

### ISSUE THREAD

**Issue by Zeks** [KnuckleCracker/CW4-bug-tracker#1006]
Chronom of Nov 15. Nullifier on the top right island upon load has nullification line and skimmer factory has status Nullified, but upon pressing N the nullifier line vanishes and the factory continues operating

[ehhh.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7535010/ehhh.zip)

**Comment by knucracker** [comment]
In your save, the nullifier's "armed" state is set to off.  There appears to be a minor visual problem with the nullifier in that it draws the nullification line upon load, even if the nullifier is disarmed.  This corrects after the first frame.  

I've made a fix  so the nullifier won't draw the nullification line upon load if it is disarmed.
