### ISSUE TITLE
[Suggestion] Make pod not disappear when there are packets on its routes

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#1008]
It can be quite inconvenient when packets are routed over a pod its links while the pod has just run empty, which makes the pod disappear along with packets on its links. It would be nice if packets would be routed around a pod when the pod is empty, and the pod to stay alive while there are packets on its route.

**Comment by Karsten75** [comment]
I thought this was implemented. Can't find the release number, and not going to test. If not, then it's too late to include it, unfortunately. Should have been done, it was done in CW3.
