### ISSUE TITLE
[Bug] Score submission fails (Possibly due to #1007)

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#1009]
It seems that score submissions fail for maps with names as in issue #1007. At least, I played the map "You thought the previous map was bad?#1414" and it failed to submit scores. This might have been a one off glitch, or caused by something else, though I've never had that happen before.

**Comment by knucracker** [comment]
Not sure... in any case, I just tested it after the fixes for #1007 and it worked for me to submit a score on a mark v map that had a question mark in it.
