### ISSUE TITLE
[Bug.Minor] Attached beams with a fixed end point get messed up by rotation.  

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#1011]
If you have for example an airship with a beam attached with a fixed end point, and the airship rotates 90 degrees to the side, the beam rotates 90 degrees as well.   Trying to set the starting point or ending point has no affect on this, the beam is rotated internally, so it thinks it's still going to its end point, but the rotation makes it nowhere near that point.  

It's possible that fixing this bug may interfere with the beams on the sweeper, so it may not be feasible to easily fix.  

You can work around it, by not attaching and updating the start manually every frame, or by deleting the beam and re-creating it after the unit rotates.

**Comment by Karsten75** [comment]
Belatedly realized these were set from the UI, not from Controls.

**Comment by Karsten75** [comment]
Oh dear lord, I accidentally closed the wrong issue. My apologies.

**Comment by Karsten75** [comment]
and it never got any love.
