### ISSUE TITLE
[Suggestion] Collapse scores to best score with the same name when filtering with a group name

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1012]
**Is your feature request related to a problem? Please describe.**
Players who compete using group names have to restrain themselves from posting too many scores under said group name, due to running the risk of occupying the entire scoreboard with their scores and pushing all others' scores out.

**Describe the solution you'd like**
When filtering using a group name, discard all times except the best one from each unique name

**Comment by Karsten75** [comment]
This is congruent with another thought I have recently entertained (probably a tad harder to implement). In CW3 (and CW2, if memory serves) only an improved (or new) score could be submitted.  This might also reduce score spamming overall.

**Comment by grabz-dev** [comment]
> This is congruent with another thought I have recently entertained (probably a tad harder to implement). In CW3 (and CW2, if memory serves) only an improved (or new) score could be submitted. This might also reduce score spamming overall.

There is a potential downside to this (which is present in the previous games) where if a user submits a score, but then later wants to submit the same score for a group, they cannot - they must submit a better score. This is something I'd ideally like to avoid in CW4 when suggesting changes to the leaderboards.

**Comment by Karsten75** [comment]
For IXE, maybe track scores locally and only upload current best score, al la CW3. The "resubmit a score" issue is one we don't want, since it allows users to indefinitely resubmit a nuisance score.
