### ISSUE TITLE
[4RPL] BounceEdgeCollision has a one-off error

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1015]
![image](https://user-images.githubusercontent.com/51026936/145127101-9c2d31f4-e61d-4850-9223-bcc08e88ccb9.png)

Depending on what is intended, BounceEdgeCollision either bounces 1 cell too far on the right and top, or 1 cell too close on left and bottom. If I were to suggest a fix (should one be provided), I would fix the right and top interaction, as objects frequently get stuck out of bounds:
![image](https://user-images.githubusercontent.com/51026936/145127378-356b14d6-00b0-4ac7-91cd-51636785c96b.png)

**Comment by knucracker** [comment]
I've updated the API to be -1 on the map width and depth.
