### ISSUE TITLE
[Bug] UI Text Dissapeared

### ISSUE THREAD

**Issue by BuilderOfBlocks** [KnuckleCracker/CW4-bug-tracker#1019]
Computer was powered down while game was open. Upon restarting computer and game, many of the UI elements are missing text. Restarting computer does not fix it

[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/7794741/Player.log)

![20211230220204_1](https://user-images.githubusercontent.com/96891479/147790853-dc03e969-3f1b-4809-a40b-970fb54b7d60.jpg)
![20211230220206_1](https://user-images.githubusercontent.com/96891479/147790856-cd093730-a8d8-4fdd-8a22-4f62df20a178.jpg)

**Comment by knucracker** [comment]
The log file shows:
async texture load: failed to load OpenSans-Semibold SDF Atlas from D:/SteamLibrary/steamapps/common/Creeper World 4/CW4_Data/resources.assets.resS

So this file is either locked or corrupted.  I'd reinstall, or repair the install using steam.  That should fix the file.  This isn't a file that the game modifies at runtime (it is just a resource file that is part of the games installation), so it must have become corrupted when the computer shutdown.
