### ISSUE TITLE
[Bug] Walls don't work sometimes (?)

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#1023]
I was making a map and noticed that for whatever reason, walls don't let creeper through even when they clearly show as 0% power, when I set the decay rate to 700.

 I don't know what causes this issue. Just thought I would mention it as I feel like there shouldn't really be bugs in the game at this point.

Update1: it broke again, this time with 690, when I loaded the map again. Which is weird because it worked just fine before. Maybe it's a loading related issue. Maybe it's because I deleted a map with the exact same name before, but I don't think so?

Whatever the cause may be, I would like to see it fixed somehow if it's possible because I sometimes, like, actually use walls. I think it's somehow related to changing the decay rate and then reloading the map but I'm not sure.

**Comment by Karsten75** [comment]
I'm pretty sure you are aware that we ask for log files and saves if those can help to determine a problem? Got any of those?

**Comment by TrickyCorp** [comment]
Uhhhh I may have deleted those again instead of linking them, guess there's no point in keeping this open then

Edit: unless the log file and save file aren't the same? I tend to remove maps that don't work from my projects or whatever they are called in CW4.
