### ISSUE TITLE
[Bug] I have completely broken the energy packet dispatch for a group of units.

### ISSUE THREAD

**Issue by Zeks** [KnuckleCracker/CW4-bug-tracker#1028]
Colony map 424:

The central group of cannons and mortars will only occasionally receive the packets from the porter containters. The rift lab will *never* dispatch to them ...... unless you delete the factory. Or move it significantly with the editor. Or move the rift lab to be closer to those units than the factory so that it doesn't try to route past that point.

[424.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/8376690/424.zip)

**Comment by Karsten75** [comment]
Where is the log file?

**Comment by Karsten75** [comment]
![image](https://user-images.githubusercontent.com/22965021/160807805-734a6951-b2f5-4a4e-af94-267631f7214d.png)

This porter flies straight off the map,in a south-westerly direction. Something must have gone awry before the save was taken, wherever that was, unless that log file is still around, changes of figuring this out are slim.

**Comment by Zeks** [comment]
The "flies straight off the map" is reproducible by pressing "cancel route" after selecting all the porters in this save, saving and reloading. the behavior is reproduced after that too

[breaking.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/8380197/breaking.zip)
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/8380178/Player.log)
.
