### ISSUE TITLE
Crash on Close [Win7]

### ISSUE THREAD

**Issue by Sorrontis** [KnuckleCracker/CW4-bug-tracker#103]
_**On first time run of the game**_ - I played with the editor for a few seconds and closed the game.

Was in full screen mode. _[Steam overlay was on]_
Exited the editor as per standard procedure and closed game from main menu buttons.

Other Programs running:

1. Mozilla (1 tab) - Discord
2. Microsoft Security Essentials
3. CCleaner

Output-log attached,

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5512148/output_log.txt)

**From Windows7 Crash report**

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	CW4.exe
>   Application Version:	2018.4.28.54519
>   Application Timestamp:	5f74a6fd
>   Fault Module Name:	UnityPlayer.dll
>   Fault Module Version:	2018.4.28.54519
>   Fault Module Timestamp:	5f74a7a0
>   Exception Code:	c0000005
>   Exception Offset:	000000000072aba6
>   OS Version:	6.1.7601.2.1.0.768.3
>   Locale ID:	4105
>   Additional Information 1:	75f6
>   Additional Information 2:	75f66456d41666e42ebbd62c9f47f02e
>   Additional Information 3:	5058
>   Additional Information 4:	50581f3bd434e6f304812be7a270f300

**Comment by Sorrontis** [comment]
Multiple reattempts, with and without steam-overlay did not reproduce this error.

**Comment by Karsten75** [comment]
Closing, please re-open if it happens again.
