### ISSUE TITLE
[4RPL] SetUnitRotation does not update occupied cells

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#1031]
issuing the above call on an asymmetric unit (eg. Miner or Refinery for a standard unit) does not result in the correct cells being marked as occupied.

**Comment by knucracker** [comment]
Added #1032 
This does not perfectly address the issue, but rather exposes how the game deals with unit rotations like the miner.  The game only properly supports 90 degree rotations of units and the now exposed Set/GetOrientation APIS rotate the unit the same way the game rotates the unit during a build. 

The Rotation APIS will rotate the unit, but no changes have been made to them to update the map cells occupied by the unit. Non 90 degree rotations aren't supported by the map cells.
