### ISSUE TITLE
[Bug.Minor] Bombers building on top of one another 

### ISSUE THREAD

**Issue by buttRcaT** [KnuckleCracker/CW4-bug-tracker#1035]
![cw4ss_31](https://user-images.githubusercontent.com/105136815/167278873-6685149d-4949-4e4e-8d22-ae47eadc5802.jpg)
![image](https://user-images.githubusercontent.com/105136815/167278907-37d3d0db-27a3-4407-a14a-d9c85c3b5831.png)

They are both still able to be used, I've seen this happen to other units as well.
Built by dragging.

**Comment by Karsten75** [comment]
Can you detail the steps needed to recreate this?

Were you able to place more than 20 bombers using this?

**Comment by buttRcaT** [comment]
Um, I've tried to re-create it, but it won't happen, but I have ran into this bug with other units, so I can explain those.
So most of the time it happens when I drag build units, but one time I believe a nullifier was built over a cannon for some reason, and it was a normal click.

And yes, I built 21 bombers and they all worked.
