### ISSUE TITLE
[Bug] When I used alt+F4 to close the game, it remained running in steam, causing me to force close steam with task manager

### ISSUE THREAD

**Issue by 100288840** [KnuckleCracker/CW4-bug-tracker#1039]
When I used alt+F4 to close the game it remained running in steam, causing me to force close steam with task manager
Here is  my game log:
`Loading player data from E:/SteamLibrary/steamapps/common/Creeper World 4/CW4_Data/data.unity3d
Initialize engine version: 2019.4.23f1 (3f4e01f1a5ec)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/Creeper World 4/CW4_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1070 (ID=0x1ba1)
    Vendor:   
    VRAM:     8081 MB
    Driver:   30.0.15.1165
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.560000 ms
--InitGame.Init--
Game Version = 2.3.3
Unity Version = 2019.4.23f1
Command Line = ["E:\SteamLibrary\steamapps\common\Creeper World 4\CW4.exe"]
Data Loc = [C:\Users\s132\Documents/My Games/creeperworld4/]
Time Since Game Start = [0.1327173]
----------------------------------------------------------------------------------------------
OS = Windows 10  (10.0.19044) 64bit
System Memory = 16330
MP4 Supported = true
----------------------------------------------------------------------------------------------
Processor Type = Genuine Intel(R) CPU 0000 @ 2.60GHz
Processor Count = 16
Processor Frequency = 2592
----------------------------------------------------------------------------------------------
Graphic Device Name = NVIDIA GeForce GTX 1070
Graphic Device Version = Direct3D 11.0 [level 11.1]
Graphic Memory Size = 8081
Graphic Shader Level = 50
----------------------------------------------------------------------------------------------
Game Dimensions = 2560 x 1440
Resolution = 2560 x 1440 @ 75Hz
Displays = Display (0) Sys=[2560 x 1440] Rend=[2560 x 1440] ACTIVE  
DPI = 120
UI Scale = 1.8
Target Frame Rate = 30
----------------------------------------------------------------------------------------------
Settings: AA = 3
Settings: FPS = 1
Settings: SHADOWS = True
Settings: BLOOM = True
Settings: TERRAIN = True
----------------------------------------------------------------------------------------------
Device Type = Desktop
Language = ChineseSimplified
Supports Audio = True
----------------------------------------------------------------------------------------------
Max Texture Size = 16384
Max Cubemap Texture Size = 16384
Support Shadow = True
NPOT Support = Full
Support Render TargetCount = 8
Support 3D Texture = True
Support Compute Shader = True
Graphics Multithreaded = False
Supported Render Target Count = 8
Supports 2D Array Textures = True
Supports 32 bit Index Buffer = True
Supports Image effects = True
Supports GPU Draw Call Instancing = True
Uses Reversed Z Buffer = True
Supports Sparse Textures = True
Quality Level = 3
Gen = True [Can Confirm: False]

--GameLoad.Awake--
Checking Steam...
Steam is Running.
Mirror: adding Network[Early/Late]Update to Unity...
***SteamManager Awake***
Setting up callback
Setting up callback complete: Steamworks.Callback`1[Steamworks.GameRichPresenceJoinRequested_t]
GetLaunchCommandLine: 
Steam User ID: 76561199060025043
Setting up 8 worker threads for Enlighten.
  Thread -> id: 399c -> priority: 1 
  Thread -> id: 36ec -> priority: 1 
  Thread -> id: 1fd4 -> priority: 1 
  Thread -> id: 3d00 -> priority: 1 
  Thread -> id: 37f4 -> priority: 1 
  Thread -> id: 1b74 -> priority: 1 
  Thread -> id: 4344 -> priority: 1 
  Thread -> id: 2de4 -> priority: 1 
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.552800 ms
CMDLINE: [E:\SteamLibrary\steamapps\common\Creeper World 4\CW4.exe]
CMDLINE: [E:\SteamLibrary\steamapps\common\Creeper World 4\CW4.exe]
--InitGame.Init--
Checking Steam...
Steam is Running.
MVerseManager.Awake
SteamStatsAndAchievements Enabled for AppID: 848480
Steam User ID: 76561199060025043

Unloading 11 unused Assets to reduce memory usage. Loaded Objects now: 29794.
Total: 23.355200 ms (FindLiveObjects: 1.261200 ms CreateObjectMapping: 0.823800 ms MarkObjects: 21.196700 ms  DeleteObjects: 0.073300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29795.
Total: 25.177400 ms (FindLiveObjects: 1.311200 ms CreateObjectMapping: 0.538600 ms MarkObjects: 23.296800 ms  DeleteObjects: 0.030500 ms)

Received stats and achievements from Steam

STEAM STATS
------------------------------------------------------------
SteamStat: STAT_STORYMISSIONSCOMPLETED = 20
------------------------------------------------------------
Storing Steam Stats
StoreStats - success
--Launch Mission: [CHRONOM MAY 14, 2022]--
Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 29820.
Total: 23.138800 ms (FindLiveObjects: 1.167200 ms CreateObjectMapping: 0.286400 ms MarkObjects: 21.655000 ms  DeleteObjects: 0.029900 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 10.319500 ms

Unloading 1713 unused Assets to reduce memory usage. Loaded Objects now: 5965.
Total: 4.226200 ms (FindLiveObjects: 0.296400 ms CreateObjectMapping: 0.119700 ms MarkObjects: 1.667100 ms  DeleteObjects: 2.142500 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.345000 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 34 unused Assets to reduce memory usage. Loaded Objects now: 62978.
Total: 67.447000 ms (FindLiveObjects: 2.997800 ms CreateObjectMapping: 2.131900 ms MarkObjects: 62.135200 ms  DeleteObjects: 0.181900 ms)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
Deregistering WantsToQuit
-- GameSpace Destroyed --
UnloadTime: 31.221300 ms

Unloading 501 unused Assets to reduce memory usage. Loaded Objects now: 15029.
Total: 23.657800 ms (FindLiveObjects: 0.555300 ms CreateObjectMapping: 0.335900 ms MarkObjects: 21.360600 ms  DeleteObjects: 1.405500 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 15029.
Total: 21.151300 ms (FindLiveObjects: 0.535800 ms CreateObjectMapping: 0.326100 ms MarkObjects: 20.268700 ms  DeleteObjects: 0.019900 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.375000 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 83 unused Assets to reduce memory usage. Loaded Objects now: 62992.
Total: 69.627200 ms (FindLiveObjects: 3.091700 ms CreateObjectMapping: 2.156500 ms MarkObjects: 64.143700 ms  DeleteObjects: 0.234800 ms)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
Deregistering WantsToQuit
-- GameSpace Destroyed --
UnloadTime: 31.618500 ms

Unloading 595 unused Assets to reduce memory usage. Loaded Objects now: 15192.
Total: 29.678400 ms (FindLiveObjects: 0.607000 ms CreateObjectMapping: 0.557300 ms MarkObjects: 26.970500 ms  DeleteObjects: 1.543100 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 15192.
Total: 27.915600 ms (FindLiveObjects: 0.541400 ms CreateObjectMapping: 0.550300 ms MarkObjects: 26.803200 ms  DeleteObjects: 0.020300 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.339000 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 125 unused Assets to reduce memory usage. Loaded Objects now: 63012.
Total: 69.756900 ms (FindLiveObjects: 3.089500 ms CreateObjectMapping: 1.372500 ms MarkObjects: 64.675000 ms  DeleteObjects: 0.619700 ms)

Persist Time: 25
Zip Compression time: 29
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Deregistering WantsToQuit
-- GameSpace Destroyed --
UnloadTime: 37.818400 ms

Unloading 1384 unused Assets to reduce memory usage. Loaded Objects now: 15593.
Total: 34.708900 ms (FindLiveObjects: 0.745200 ms CreateObjectMapping: 0.746900 ms MarkObjects: 30.147700 ms  DeleteObjects: 3.068500 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 15593.
Total: 28.932600 ms (FindLiveObjects: 0.595700 ms CreateObjectMapping: 0.610000 ms MarkObjects: 27.705700 ms  DeleteObjects: 0.020700 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.346900 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 88 unused Assets to reduce memory usage. Loaded Objects now: 63251.
Total: 70.767700 ms (FindLiveObjects: 3.066600 ms CreateObjectMapping: 2.039000 ms MarkObjects: 65.365500 ms  DeleteObjects: 0.296400 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Deregistering WantsToQuit
-- GameSpace Destroyed --
UnloadTime: 32.144900 ms

Unloading 496 unused Assets to reduce memory usage. Loaded Objects now: 15295.
Total: 26.087800 ms (FindLiveObjects: 0.573200 ms CreateObjectMapping: 0.550200 ms MarkObjects: 23.598200 ms  DeleteObjects: 1.365700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 15295.
Total: 25.487500 ms (FindLiveObjects: 0.534300 ms CreateObjectMapping: 0.545300 ms MarkObjects: 24.386900 ms  DeleteObjects: 0.020500 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.337400 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 79 unused Assets to reduce memory usage. Loaded Objects now: 63264.
Total: 74.893200 ms (FindLiveObjects: 3.306300 ms CreateObjectMapping: 1.293200 ms MarkObjects: 69.725500 ms  DeleteObjects: 0.567700 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
Deregistering WantsToQuit
-- GameSpace Destroyed --
UnloadTime: 33.874900 ms

Unloading 851 unused Assets to reduce memory usage. Loaded Objects now: 15244.
Total: 27.859400 ms (FindLiveObjects: 0.612200 ms CreateObjectMapping: 0.554600 ms MarkObjects: 24.747600 ms  DeleteObjects: 1.944400 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 15244.
Total: 26.509700 ms (FindLiveObjects: 0.589200 ms CreateObjectMapping: 0.657300 ms MarkObjects: 25.241800 ms  DeleteObjects: 0.021000 ms)

Unloading 7 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.381500 ms
Registering WantsToQuit
--InitGame.Init--
Create World Threads: 16
StartMission

Unloading 77 unused Assets to reduce memory usage. Loaded Objects now: 63116.
Total: 69.090200 ms (FindLiveObjects: 2.976400 ms CreateObjectMapping: 1.492300 ms MarkObjects: 64.364400 ms  DeleteObjects: 0.256800 ms)

WantsToQuit
WantsToQuit
AutoSave
Persist Time: 26
Zip Compression time: 35
Deregistering WantsToQuit
-- GameSpace Destroyed --
`

**Comment by Fireswamp** [comment]
What you are experiencing is likely something that is known about but cannot be fixed because of how Steam works; it is currently logged as issue #264 and #846.

Basically if CW4 launches any other program and that program is still running, Steam will think that CW4 is still running.  Notably if you open scripts or the wiki, CW4 can launch a text editor or web browser.

**Comment by Karsten75** [comment]
> When I used alt+F4 to close the game it remained running in steam, causing me to force close steam with task manager Here is my game log:

Please do us a favor. next time, just drag and drop the game log (or any other file you wish to attach, don't copy/paste the entire text.

it says so right at the bottom of the window where you enter text. :)
