### ISSUE TITLE
[Suggestion] Deselect Walls/Crazonium by Clicking anywhere

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#1045]
While having selected a set of Walls/Crazonium, clicking anywhere does not deselect the walls. For all other units I tried, clicking anywhere on the map deselects them (moving them or not). This is mildly annoying.

Suggestion: Clicking anywhere on the map, while having Walls/Crazonium selected, deselects them.

**Comment by knucracker** [comment]
I think the reasoning for making it so that walls are not unselected, is that is can be easy to accidentally mis-click and not click on a wall.  This might have come up during play testing, I seem to remember something about it (or I'm dreaming it).

**Comment by PRG-YouTube** [comment]
Only in case the user wants to add walls to the selection that seems useful to me, in which case you could check for the shift/ctrl down (or whatever binded key).

In case the user does indeed want to do this, box selection becomes disabled after the first selection of walls? (just tried without shift/ctrl, that didn't work at least)

The issue I'm having with this feature is illustrated in the following video where I simulate advancing units past a wall (the trouble starts when the walls hit the selection box, which do not deselect upon unit movement and thus block unit selection until you unselect the walls manually) : https://youtu.be/8Td_hKNvkQ4

Note: I do not expect this to be changed at this point in time as it is a fairly minor issue, but it might be something to keep in mind for future games with similar unit interactions.

**Comment by knucracker** [comment]
I added "Wall" to the unit list that unselects when clicking on nothing.  Only does it if the multiselect key is not being held down
