### ISSUE TITLE
[4RPL] GetUnitPosition does not place any value on the stack if called on a non-existing unit

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#1046]
For units that does exist, GetUnitPosition returns a vector containing the position of the unit. 

If the unit does not exist, then nothing is returned. This means that extraordinary care has to be taken to inspect the stack in the eventuality that the unit does not exist. 

Recreate. On a map, place one unit (UID=1)

Run this code in the console:
```
	Trace (GetUnitPosition(1) )
	Trace (GetUnitPosition(7) )
```

Possible Console output is: 
```
[34, 1, 46, 0]
WARNING: Taking item from an empty stack: TRACE at line 3
```

**Comment by knucracker** [comment]
The API now returns V3(0,0,0) when the unit does not exist
