### ISSUE TITLE
[Bug] Players have the ability to stack rotatable units by rotating without moving their mouse

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1048]
![image](https://user-images.githubusercontent.com/51026936/177077199-e1a031dd-bbaa-4625-9c16-24a3892d4c5f.png)
**Steps to reproduce:**
1. Drag build a bunch of runways, miners, refineries, or other rotatable non-square custom units from left to right, rotated in the vertical position, without letting go of the left mouse button
2. Hit the rotate button. The first (in our case leftmost) unit gets rotated and clips into the other units
3. If we move our mouse now, the game will update the drag build order. If we do not move our mouse and let go, the game will queue up the order as is:
![image](https://user-images.githubusercontent.com/51026936/177077410-684bebbd-6c7b-4dbb-960c-998cfaad4a9c.png)

**Comment by knucracker** [comment]
The game will now refresh the build ghosts whenever the orientation key is pressed.  This accomplishes the same thing as moving the mouse more than 1 cell after the orientation key is pressed.
