### ISSUE TITLE
Different icons for some objectives in the submit score screen

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#105]
Screenshots
![image](https://user-images.githubusercontent.com/26010895/98582274-fb76f400-227f-11eb-968b-ee465c2304f5.png)

Describe the bug 

Complete a map and view the submit score screen. The overview part will have different icons for at least the totem and collect objectives than the play log, as seen in the screenshot.

**Comment by knucracker** [comment]
Updated the icons
