### ISSUE TITLE
[Suggestion] More options for search by map #

### ISSUE THREAD

**Issue by ras1** [KnuckleCracker/CW4-bug-tracker#1056]
**Is your feature request related to a problem? Please describe.**
Desired Result: Sort by thumbs, only maps with **ids >= #3000** are displayed
Actual Result: Sort by thumbs, only maps with **ids <= #3000** are displayed (see image below)

**Describe the solution you'd like**
Add another text box to specify **End #:**, add filter by a range of #'s, add filter for maps after #, and also preserve original up to # filter.
- 3000 and empty is **# >= 3000**
- empty and 3000 is **# <= 3000**
- 2000 and 3000 is **2000 >= map # <= 3000**

Or...

Reverse the way that the thumbs sort works with the **Start #:** field, so that instead of being the greatest # in the results, it would be the lowest #,

Or...

Add another checkbox to **Invert Start #** to toggle between either my Desired Result (above), or the Actual Result.

**Describe alternatives you've considered**
I page through the Sorted thumb map results for all #s until I find #3000+ maps, And I don't have do ranged searches for other groups because paging by # order takes too long

**Additional context**
![image](https://user-images.githubusercontent.com/28936883/183266147-e8df4c20-0973-4190-80dd-25498f55b555.png)

**Comment by Karsten75** [comment]
Some enhancement to search is certainly indicated. Not sure if current game will receive it or not.

**Comment by Karsten75** [comment]
Carry over to next game
