### ISSUE TITLE
[4RPL] [Bug] More SetUnitSettings issues

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1067]
This is an extension of #1066 posted by Fire

> Tested in 2.4.6:
> 
> The LifeTime parameter appears to be having the same issue,
> 
>     GetUnitSettings(1959) ->BlobTable
>     SetUnitSettings(1959 <-BlobTable)
> 
> The above code sets the LifeTime parameter of blob nests and skimmer factories to whatever the Count parameter is set to.

**Comment by knucracker** [comment]
Same as in #1066 there were some copy paste typos for LifeTime.  The blob nest and the skimmer factory were both affected.  Fixed in 2.4.7
