### ISSUE TITLE
[Bug.Minor] Map in colonies not showing as "in progress".

### ISSUE THREAD

**Issue by jaworeq** [KnuckleCracker/CW4-bug-tracker#1070]
I was playing a map, didn't finish it and exit the game using alt+f4 -> clicking "exit" button. After rebooting the game, trying to find the map, it's not listed when using "in progress" filter, even though I have some saves on it.

**Comment by Karsten75** [comment]
I am sorry for not noticing your issue earlier and responding to it. 

The first question we ask in these circumstances are whether you are using Microsoft OneDrive or a similar, real-time cloud backup system? It has come to our attention that these services cause results similar to what you indicate here. 

Secondly, in some rare cases, Steam Cloud Save can also cause these issues. 

Failing those, and without supporting documentation from you, there is not much we have to act on. If you have a log file showing the issue or any other  supporting material to aid in problem determination, there is precious little we can do, sicne this is clearly not a common instance.
