### ISSUE TITLE
[Bug] Blob payload is set to 50 on map load

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#1071]
If you save and load a map, any blobs have their payload set to 50.

Easiest to see on maps with blob payload set to something very high, such as More and More.  Blob site at 13.0 seconds without saving and loading:
![image](https://user-images.githubusercontent.com/68219054/199059955-f9714769-a593-4fa3-995c-f8a0ee922832.png)

By saving and loading at 7.0 seconds (both quicksave/quickload and normal save/normal load gave the effect), the blob site instead looks like this at 13.0 seconds:
![image](https://user-images.githubusercontent.com/68219054/199060311-41ffc1c2-ee72-4d82-ae2f-04b863989915.png)
Blobs were emitting 50 creeper instead of the expected 500 on that map.

I ran more detailed checks using the following code:
GetUnitsByType("blob" 0) ->blobs
GetUnitSettings(<-blobs[0]) trace
Running this code told me the payload of blobs was being set to 50.

**Comment by knucracker** [comment]
Fixed in 2.4.8.  The blob as not persisting the "payload" variable.
