### ISSUE TITLE
After PC hangs while on main meny at CW3 i cannot submit results anymore

### ISSUE THREAD

**Issue by ha11oga11o** [KnuckleCracker/CW4-bug-tracker#1082]
Hello,

i have strange issue last couple days with CW3 steam version. In some reason computer hang after i click colonial space icon, so i needed to shut down it completely to recover. 
Now i noticed that i cannot submit results after map played. I can pass menu by "continue w/o submitting. I deleted game, manually deleted game folder just in case, reinstalled but have exactly same issue. Pressing submit button do nothing. 

I will add recent log, hope it will show something useful. 

`Initialize engine version: 5.2.3f1 (f3d16a1fa2dd)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [aticfx32.dll 31.0.12027.9001]
    Renderer: Radeon RX 580 Series
    Vendor:   ATI
    VRAM:     3072 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=1
Begin MonoManager ReloadAssembly
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-UnityScript.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Assembly-UnityScript.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\System.Core.dll (this message is harmless)
- Completed reload, in  0.076 seconds
<RI> Initializing input.

<RI> Input initialized.

desktop: 1680x1050 60Hz; virtual: 1680x1050 at 0,0
<RI> Initialized touch support.

Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\System.dll (this message is harmless)
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\System.Xml.dll (this message is harmless)
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\UnityScript.Lang.dll (this message is harmless)
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Boo.Lang.dll (this message is harmless)
Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\System.Xml.Linq.dll (this message is harmless)
SteamManager.Awake
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

CW3SteamAchievements Awake
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

CW3SteamAchievements Enabled. 280220
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

SteamManager Initialization sucess.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 100 -> priority: 1 
Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.373600 ms
Using base settings dir: C:\Users\Korisnik\AppData\Roaming/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Using base game data dir: C:\Users\Korisnik\Documents/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Shader Quality: 30
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Quality: 0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Game Version: 2.12
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Checking for Update...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Checking for News...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 9 unused Assets to reduce memory usage. Loaded Objects now: 6366.
Total: 4.716300 ms (FindLiveObjects: 0.355000 ms CreateObjectMapping: 0.219000 ms MarkObjects: 4.103900 ms  DeleteObjects: 0.037400 ms)

Platform assembly: E:\SteamLibrary\steamapps\common\Creeper World 3\CW3_Data\Managed\Mono.Security.dll (this message is harmless)
--ACHIEVEMENTS-----------------------------------------------------------------

[ACH_0] [Training Wheels] = False

[ACH_1] [Warp Ready] = False

[ACH_2] [Junior Officer] = False

[ACH_3] [Master Commander] = False

[ACH_4] [MacGyver] = True

[ACH_5] [Peak of Good Living] = True

[ACH_6] [Box Art Mission Master] = True

[ACH_7] [Failure Has Its Own Reward] = True

[ACH_8] [Better Late Than Never] = False

[ACH_9] [Patton Would Be Proud] = False

[ACH_10] [Dudley DoRight] = False

[ACH_11] [Rotten Apple] = False

[ACH_12] [Happily Ever Before] = False

[ACH_13] [The Dark Lord] = False

[ACH_14] [Surgical Strike] = False

[ACH_15] [Forty-Niner] = False

[ACH_16] [Dr. Jones] = False

[ACH_17] [Nihilist] = False

[ACH_18] [Uninhibited Nihilist] = False

[ACH_19] [Brainiac] = False

[ACH_20] [Positronic Brain] = False

[ACH_21] [Fine Wine] = False

[ACH_22] [Size Matters] = False

[ACH_23] [G-Man] = False

[ACH_24] [MadMag's Mansion] = False

[ACH_25] [Shhhh!] = False

[ACH_26] [Machine Lover] = False

[ACH_27] [Unlimited Possibilities] = False

[ACH_28] [Unlimited Potential] = True

[ACH_29] [Critic] = True

[ACH_30] [Architect] = False

[ACH_31] [Ejection Seat] = True

[ACH_32] [Rain Man] = True

[ACH_33] [Can't Touch This] = False

[ACH_34] [Nip in the Bud] = False

[ACH_35] [Turtler] = True

[ACH_36] [Many Machines on Ix] = True

[ACH_37] [Varro Hale Award] = True

[ACH_38] [Aliana Abraxis Award] = True

[ACH_39] [Dax Joven Award] = True

[ACH_40] [Arc Eternal Pioneer] = True

[ACH_41] [Prospector Zone Pioneer] = True

[ACH_42] [Tormented Space Pioneer] = True

[ACH_43] [Colonial Space Pioneer] = True

[ACH_44] [Projects Pioneer] = True

[ACH_45] [Alpha Sector Pioneer] = False

[ACH_46] [DMD Pioneer] = True

[ACH_47] [First Collector] = True

[ACH_48] [First Relay] = True

[ACH_49] [First Reactor] = True

[ACH_50] [First Shield] = True

[ACH_51] [First Ore Mine] = True

[ACH_52] [First Siphon] = True

[ACH_53] [First Terp] = True

[ACH_54] [First Guppy] = True

[ACH_55] [First Pulse Cannon] = True

[ACH_56] [First Mortar] = True

[ACH_57] [First Strafer] = True

[ACH_58] [First Bomber] = True

[ACH_59] [First Nullifier] = True

[ACH_60] [First Sprayer] = True

[ACH_61] [First Beam] = True

[ACH_62] [First Sniper] = True

[ACH_63] [First Forge] = True

[ACH_64] [First Bertha] = True

[ACH_65] [First Thor] = True

[ACH_66] [Collector Lover] = True

[ACH_67] [Relay Lover] = True

[ACH_68] [Reactor Lover] = True

[ACH_69] [Shield Lover] = True

[ACH_70] [Ore Mine Lover] = True

[ACH_71] [Siphon Lover] = True

[ACH_72] [Terp Lover] = True

[ACH_73] [Guppy Lover] = True

[ACH_74] [Pulse Cannon Lover] = True

[ACH_75] [Mortar Lover] = True

[ACH_76] [Strafer Lover] = True

[ACH_77] [Bomber Lover] = True

[ACH_78] [Nullifier Lover] = True

[ACH_79] [Sprayer Lover] = True

[ACH_80] [Beam Lover] = True

[ACH_81] [Sniper Lover] = True

[ACH_82] [Whoops!] = True

[ACH_83] [Bertha Lover] = True

[ACH_84] [Thor Lover] = True

[ACH_85] [Collector Master] = True

[ACH_86] [Relay Master] = True

[ACH_87] [Reactor Master] = True

[ACH_88] [Shield Master] = False

[ACH_89] [Ore Mine Master] = True

[ACH_90] [Siphon Master] = True

[ACH_91] [Terp Master] = True

[ACH_92] [Guppy Master] = True

[ACH_93] [Pulse Cannon Master] = True

[ACH_94] [Mortar Master] = True

[ACH_95] [Strafer Master] = False

[ACH_96] [Bomber Master] = True

[ACH_97] [Nullifier Master] = True

[ACH_98] [Sprayer Master] = True

[ACH_99] [Beam Master] = True

[ACH_100] [Sniper Master] = True

[ACH_101] [Forge Master] = True

[ACH_102] [Bertha Master] = True

[ACH_103] [Thor Master] = False

[ACH_104] [First Emitter] = True

[ACH_105] [First Spore Tower] = True

[ACH_106] [First Runner] = True

[ACH_107] [First Runner Nest] = True

[ACH_108] [First Air Exclusion Tower] = True

[ACH_109] [Emitter Assassin] = True

[ACH_110] [Spore Tower Assassin] = True

[ACH_111] [Runner Assassin] = True

[ACH_112] [Runner Nest Assassin] = True

[ACH_113] [Air Exclusion Tower Assassin] = True

[ACH_114] [Emitter Ender] = True

[ACH_115] [Spore Tower Ender] = True

[ACH_116] [Runner Ender] = True

[ACH_117] [Runner Nest Ender] = True

[ACH_118] [Air Exclusion Tower Ender] = True

[ACH_119] [First Inhibitor] = True

[ACH_120] [Inhibitor Ender] = True

[ACH_121] [Mobility Award] = True

[ACH_122] [Upwardly Mobile] = True

[ACH_123] [Vagrant] = False

[ACH_124] [Gunslinger] = False

[ACH_125] [Fire in the Hole] = False

[ACH_126] [R.I.P] = True

[ACH_127] [Industrial Nightmare] = True

[ACH_128] [Strategic Reserve] = True

[ACH_129] [Rainy Day Reserve] = True

[ACH_130] [Self Improvement] = False

[ACH_131] [Focused] = True

[ACH_132] [Wrath of the Gods] = True

[ACH_133] [Apexian] = False

[ACH_134] [Hawking Achievement] = True

[ACH_135] [No Fly] = False

[ACH_136] [Area Denial] = False

[ACH_137] [Not gonna Vapen] = False

[ACH_138] [Born Leader] = True

-------------------------------------------------------------------------------

--STATS------------------------------------------------------------------------

[STAT_AOO] = 0

[STAT_INHIBITORS] = 0

[STAT_COMPLETEDDMD] = 2

[STAT_MISSIONSCOMPLETE] = 1595

[STAT_BUILTCOLLECTORS] = 64335

[STAT_BUILTRELAYS] = 174343

[STAT_BUILTREACTORS] = 252019

[STAT_BUILTSHIELDS] = 164

[STAT_BUILTOREMINES] = 16634

[STAT_BUILTSIPHONS] = 15848

[STAT_BUILTTERPS] = 57746

[STAT_BUILTGUPPIES] = 9719

[STAT_BUILTPULSECANNONS] = 63019

[STAT_BUILTMORTARS] = 162155

[STAT_BUILTSTRAFERS] = 801

[STAT_BUILTBOMBERS] = 3757

[STAT_BUILTNULLIFIERS] = 26658

[STAT_BUILTSPRAYERS] = 20237

[STAT_BUILTBEAMS] = 64996

[STAT_BUILTSNIPERS] = 15059

[STAT_BUILTFORGES] = 3554

[STAT_BUILTBERTHAS] = 7882

[STAT_BUILTTHORS] = 89

[STAT_KILLEDEMITTERS] = 33288

[STAT_KILLEDSPORETOWERS] = 8417

[STAT_KILLEDRUNNERS] = 2084992

[STAT_KILLEDRUNNERNESTS] = 5311

[STAT_KILLEDAIREXCLUSIONTOWERS] = 3734

[STAT_KILLEDINHIBITORS] = 1134

-------------------------------------------------------------------------------

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/.\/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/lib/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/.\lib/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/lib/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/.\/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/lib/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/.\lib/System/Library/Frameworks/Security.framework/Security
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Creeper World 3/CW3_Data/Mono/lib/System/Library/Frameworks/Security.framework/Security
News: CREEPER WORLD 4 NOW AVAILABLE! -> |u=https://store.steampowered.com/app/848480/Creeper_World_4/ Open_Web_Page
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 7.715800 ms
TerrainLevels = {71,4,8,28,23,76,40,43,42,41}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

TerrainBrightness = {50,50,50,50,50,50,50,50,50,50}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 490 unused Assets to reduce memory usage. Loaded Objects now: 10189.
Total: 10.044000 ms (FindLiveObjects: 0.718000 ms CreateObjectMapping: 0.280300 ms MarkObjects: 8.612400 ms  DeleteObjects: 0.432000 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 10262.
Total: 10.402200 ms (FindLiveObjects: 0.970200 ms CreateObjectMapping: 0.235100 ms MarkObjects: 9.173200 ms  DeleteObjects: 0.022900 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 10281.
Total: 7.783700 ms (FindLiveObjects: 0.391700 ms CreateObjectMapping: 0.128500 ms MarkObjects: 7.253800 ms  DeleteObjects: 0.008900 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 16.127100 ms
TerrainLevels = {71,4,8,28,23,76,40,43,42,41}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

TerrainBrightness = {50,50,50,50,50,50,50,50,50,50}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 190 unused Assets to reduce memory usage. Loaded Objects now: 10233.
Total: 7.196800 ms (FindLiveObjects: 0.420400 ms CreateObjectMapping: 0.148300 ms MarkObjects: 5.172200 ms  DeleteObjects: 1.455100 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 10233.
Total: 5.776200 ms (FindLiveObjects: 0.426500 ms CreateObjectMapping: 0.139400 ms MarkObjects: 5.199400 ms  DeleteObjects: 0.010300 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 10265.
Total: 5.917100 ms (FindLiveObjects: 0.620100 ms CreateObjectMapping: 0.155900 ms MarkObjects: 5.122400 ms  DeleteObjects: 0.018200 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 10282.
Total: 15.594200 ms (FindLiveObjects: 1.398600 ms CreateObjectMapping: 0.662900 ms MarkObjects: 13.509800 ms  DeleteObjects: 0.021600 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 8.949100 ms
Using base settings dir: C:\Users\Korisnik\AppData\Roaming/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Using base game data dir: C:\Users\Korisnik\Documents/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Shader Quality: 30
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Quality: 0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Game Version: 2.12
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Checking for News...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 109 unused Assets to reduce memory usage. Loaded Objects now: 6436.
Total: 3.565500 ms (FindLiveObjects: 0.253200 ms CreateObjectMapping: 0.095300 ms MarkObjects: 3.136100 ms  DeleteObjects: 0.080000 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 6436.
Total: 3.813900 ms (FindLiveObjects: 0.332400 ms CreateObjectMapping: 0.093800 ms MarkObjects: 3.380100 ms  DeleteObjects: 0.006300 ms)

News: CREEPER WORLD 4 NOW AVAILABLE! -> |u=https://store.steampowered.com/app/848480/Creeper_World_4/ Open_Web_Page
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 2.107100 ms
TerrainLevels = {0,0,0,0,0,0,0,0,0,0}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

TerrainBrightness = {50,50,50,50,50,50,50,50,50,50}
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 192 unused Assets to reduce memory usage. Loaded Objects now: 10073.
Total: 6.067200 ms (FindLiveObjects: 0.419900 ms CreateObjectMapping: 0.147600 ms MarkObjects: 5.326800 ms  DeleteObjects: 0.172200 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 10119.
Total: 7.767700 ms (FindLiveObjects: 0.659400 ms CreateObjectMapping: 0.246600 ms MarkObjects: 6.828800 ms  DeleteObjects: 0.032100 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 10136.
Total: 12.103601 ms (FindLiveObjects: 0.784400 ms CreateObjectMapping: 0.634400 ms MarkObjects: 10.659400 ms  DeleteObjects: 0.024400 ms)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 10.130501 ms

Unloading 256 unused Assets to reduce memory usage. Loaded Objects now: 1184.
Total: 2.730500 ms (FindLiveObjects: 0.051800 ms CreateObjectMapping: 0.050300 ms MarkObjects: 1.386100 ms  DeleteObjects: 1.241700 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 1184.
Total: 1.720900 ms (FindLiveObjects: 0.084500 ms CreateObjectMapping: 0.053800 ms MarkObjects: 1.578900 ms  DeleteObjects: 0.002700 ms)

Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.385600 ms
Using base settings dir: C:\Users\Korisnik\AppData\Roaming/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Using base game data dir: C:\Users\Korisnik\Documents/creeperworld3/
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Shader Quality: 30
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Quality: 0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Game Version: 2.12
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Checking for News...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 6390.
Total: 4.021300 ms (FindLiveObjects: 0.303700 ms CreateObjectMapping: 0.098200 ms MarkObjects: 3.608600 ms  DeleteObjects: 0.010100 ms)

News: CREEPER WORLD 4 NOW AVAILABLE! -> |u=https://store.steampowered.com/app/848480/Creeper_World_4/ Open_Web_Page
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

`
Many thnx in advance.

**Comment by knucracker** [comment]
Those problems basically indicate a network issue.  (Anywhere from you to
the KnuckleCracker server which is near Dallas, Texas). The server has some
instability a couple days ago (which is when you sent this message), so it
could be you just got unlucky and used it during that window.  Has it
started working again since you sent this message?

**Comment by ha11oga11o** [comment]
Hey, thanks for responding. It did not started. Only submit does not work. I can fetch maps, submit score from 0-10 for map, all that works with CW4 also. There i have no issues at all. I suppose its same servers? 
Simply when i press button to submit my best score i does nothing. 

Is there any additional folders, configs, anything to delete beside steam folder? I deleted game via steam itself and manually deleted its folder because it hads not empty. I dont care about data, it will fetch it from cloud anyways. 
I can do whatever troubleshooting is needed, but i really dont know what exactly. 

Cheers!

**Comment by ha11oga11o** [comment]
It seems i forgot to mention when game crash happened and when i got it back all settings were default. So i had to set all back. 

TY

**Comment by knucracker** [comment]
This directory is where the game stores everything:
"c:\Users\YOUR_USER\Documents\My Games\creeperworld4"
Turn off steam cloud sync, rename that directory, then start the game and
you will start from scratch.
I would rename the directory rather than deleting it, in case you want
anything back from it.

**Comment by ha11oga11o** [comment]
Hello,

thanks for guidance and im so sorry for bother you. I did uninstall game, disabled cloud, deleted game folder under steam and under users, but after fresh download i have exactly same issue. Its strange why game preserver default setting which i had reseted at crash. And had to set that back for my liking. Like creeper transparency, splash screen, sound volume,...  Where that data is stored? It seems it did not deleted that somehow. 
Is there any other folder i need to delete to reinstall it? 
We are talking about CW3, - not CW4 which works totally fine. 

Thanks

**Comment by ha11oga11o** [comment]
Hello, i tried multiple combinations. Multiple folders deletion, settings deletion. I even deleted two xml files which i was asking where game settings is stored at C:\Users\user\AppData\Roaming\creeperworld3. Nothing allows me to submit score when i finish map. 
I even installed steam and game at work on fresh windows laptop and i have exactly same issue. Can someone who can please check is my account banned on servers? Anything weird? 
And if this is not place for bug tracking for CW3 please point me where it is, i couldn't find it. 

Many thnx in advance.

**Comment by ha11oga11o** [comment]
Thanks to #Grabz at Discord i got A hint that name is missing for submitting. It was so tiny and so obvious mistake on my side, that actually was invisible. 
Maybe just in case, when time allows add popup that name is missing instead dead button? 

Anyways, thanks for help.
