### ISSUE TITLE
[bug] Info text does not start at the beginning when playing with lower resolution

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#109]
When I play at i.e 1280x720, and I click the info button, I see this:
![image](https://user-images.githubusercontent.com/16858356/98589681-ef198800-22cd-11eb-9a75-3ff4cd3276c1.png)
Tower looks like: 
![image](https://user-images.githubusercontent.com/16858356/98589940-5df6e100-22ce-11eb-9e99-a1dfb09922c3.png)

These are the UI/res Settings: 
![image](https://user-images.githubusercontent.com/16858356/98590032-7ebf3680-22ce-11eb-9ab4-4c551fb51ad5.png)

When I have these settings (1920x1080), everything is fine
![image](https://user-images.githubusercontent.com/16858356/98590191-bf1eb480-22ce-11eb-89c2-5f7f78cbb5e1.png)

**Comment by knucracker** [comment]
The info panel wasn't anchored properly and I wasn't scrolling the page back to the top when loading a new page.
