### ISSUE TITLE
[bug] Mouse pointer lost in scores table

### ISSUE THREAD

**Issue by Lucius15** [KnuckleCracker/CW4-bug-tracker#11]
1.  I've tested it many times after restart and it still here.

2.  [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5000621/output_log.txt)

3. ![20200730132331_1](https://user-images.githubusercontent.com/63197755/88912633-38d2eb00-d268-11ea-9384-1ec606099d6e.jpg)

4. To recreate, start new mission and get an opportunity to rift jump. When ready, push rift jump and then quickly activate freecamera mode. Wait until score table appear and your muse pointer completely lost. Any combinations (like SHIFT-R,  SHIFT-F or R ) are useless. To exit game, you have to close it via steam or just kill game process. But progress is saved (i've unlocked next mission after restart). 

**Additional context**
Also, mouse can be moved  in a small area (1 or 2 tiles) but no more.

**Comment by knucracker** [comment]
Fix: I force the game out of free view after the exit dialog appears.
