### ISSUE TITLE
[bug] Farsite overview: Info panels might be cut at screenedge

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#110]
without any movement, the description of Not My Mars looks like
![image](https://user-images.githubusercontent.com/16858356/98590855-ba0e3500-22cf-11eb-8879-20f5fdc9a9c8.png)

This is the upper part of the screen (fullscreen)
It should be displayed complete

**Comment by BilboGCL** [comment]
In addition: I think it would be a good thing to move around with the arrow keys/wasd (like before?)

**Comment by knucracker** [comment]
There's a separate issue for arrow key movement. Right now you can move by clicking and dragging. I will look into arrow key movement. Closing this issue
