### ISSUE TITLE
Videos don't export to the correct location until told otherwise

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#111]
Describe the bug 

Exporting an MP4 from the recorder will default to creepwerworld4demo rather than creeperworld4 parent folder.

Presumably this is because windows explorer remembered that was the previous export location.
Exporting a video to the correct location exports subsequent videos to that same location though.

**Comment by knucracker** [comment]
This is one of (the only?) place in the demo where the save dialog can be brought up. So I changed the 'unique id' used by the dialog to be different between the demo and the full game when it shows for saving videos. That should keep their remembered locations separate.
