### ISSUE TITLE
[bug] ERN Portal [?] help buttons non functional

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#112]
![image](https://user-images.githubusercontent.com/51026936/98594751-66064f00-22d5-11eb-99a8-c209404761b3.png)
Clicking the [?] help buttons in ERN Portal are non functional.

**Comment by knucracker** [comment]
Removed the help buttons from the ERN Portal interface. This help will eventually end up in the info button pane and/or on the wiki.
