### ISSUE TITLE
clicking on an empty place should deselect selected unit

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#117]
Steps to reproduce:
1: Select a tower
2: Click on an empty field
expected result:
Tower unselected, 
real result:
Tower stays selected

Why is this an issue?
When you want to drag-select a couple of i.e. cannons and mortars and move them but you start unintentional on a tower, you can not start a new drag-selection until you have deselected said tower

IMHO a bug, ymmv

**Comment by knucracker** [comment]
This is a little tricky. Some units that don't 'move' still can be selected and then told to 'move' (and that has an action). This is true for bombers for instance, and some custom units.  So I whitelisted a set of units to auto cancel when attempting to 'move' them.
--
Tower
Pylon
Miner
Refinery
Nullifier
Runway
Rocket
Platform
MRift
--

These units will cancel their selection when you select them and then click elsewhere.  I don't know if this will have a side effect or not. Time will tell...
