### ISSUE TITLE
factory is not on info panel

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#118]
At least at level "We are never alone", the factory is not on the info panel.

**Comment by Karsten75** [comment]
None of the base units has been incorporated in the Info system. There are also additional sections on hints/tiups/strategies that needs completion and then possible inclusion in Info. 

I recall hearing knucracker say that this is part of the "known incomplete" parts of the game.

**Comment by knucracker** [comment]
I've added the factor and ern portal to the info page. I also added resources, and an Overview page.
The overview is the default page that is shown and it has a link to the top of the game help on the wiki. It's the catch-all.
