### ISSUE TITLE
[bug] Rotation impossible on touchpad

### ISSUE THREAD

**Issue by moregubbins** [KnuckleCracker/CW4-bug-tracker#12]
Game Version = DEMO 1.1
Unity Version = 2018.4.23f1
OS = Windows 10  (10.0.0) 64bit
Touchpad device: Synaptics SMBus TouchPad (onboard, two touch points)

Default touchpad settings in Windows 10 are to avoid input while alpha-numeric keyboard keys are pressed. Thus, it is impossible to press "R" and move the mouse simultaneously. Touchpad also does not allow "holding down the mouse wheel" (side of touchpad). No obvious work-around in Windows mouse/touchpad settings exists. Hence, demo is unplayable as user cannot rotate the map during the first mission. Suggest replacing "R" with "Shift" or similar.

Otherwise, great progress above CW3! Thanks and keep up the good work!

**Comment by knucracker** [comment]
This can be changed in settings/controls. So 'R' can be changed to 'shift'.  What can be improved is that the first demo mission can point this out.

**Comment by knucracker** [comment]
Also added keybindings to rotate the map right and left (no mouse required).
