### ISSUE TITLE
[bug] no intro to rocket/ac bomber

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#121]
i did not have access to rocket and ac bomber on the map experiment, but i do at the beginning of somewhere in space time. no notice of it was ever given.
![image](https://user-images.githubusercontent.com/54015763/98617084-d906ca00-22c3-11eb-8ee0-3bba4fb5f203.png)

**Comment by grabz-dev** [comment]
This map also gives unexplained access to Beacon and Platform, none of which are useful on it.

**Comment by knucracker** [comment]
Removed units that were not supposed to be there.
