### ISSUE TITLE
ERN portal model colors don't match upgrade colors

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#122]
![image](https://user-images.githubusercontent.com/26010895/98622778-862f1180-22c7-11eb-9d7c-1a3e83913478.png)

Describe the bug 

Make an ERN portal
View its upgrades
Note that the blue correspond with the green and vice versa

I had noticed that I was missing a green upgrade when I quickly glanced over and opened the menu to check that yes, I did have it upgraded. Gave me a scare for a minute.

**Comment by knucracker** [comment]
Changed the ern portal texture to match the colors in the dialog.
