### ISSUE TITLE
[bug] air tab doesn't stop flashing

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#123]
on the map "the compound" when AC bombers are unlocked the air tab never stops blinking. at least it hasn't so far and i have done all that normally stops it

![image](https://user-images.githubusercontent.com/54015763/98623392-305f6700-22d1-11eb-9037-757aece8b005.png)

**Comment by harrymcb** [comment]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5514653/output_log.txt)

log. in case it helps

**Comment by grabz-dev** [comment]
Something's up with this mission, I also have this permanently at the bottom of my screen
![image](https://user-images.githubusercontent.com/51026936/98626396-f5315800-2311-11eb-8fa2-3d762350b1a0.png)

**Comment by chrislove01** [comment]
Can confirm happening to me too

**Comment by knucracker** [comment]
I've fixed the air tab flashing problem. The other issue, with the "rotate" indicator, I am not reproducing.  Maybe it had something to do with the air tab... but I doubt it. If that continues to show up, just open a new issue for it.
