### ISSUE TITLE
Terraform introduction gets only triggered when you use the on screen button, not by keyboard

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#128]
On serious, the terraform button keeps blinking when you start the terraforming with the keyboard and the info text does not get triggered.
Additional info: I've changed the keybind to "G"

**Comment by knucracker** [comment]
Can you reproduce this? It's not reproducing for me. Is the terraform panel actually popping up when you press "G" (your custom mapping)?

**Comment by BilboGCL** [comment]
Not with my current save as the terraform introduction does not get triggered anymore, so, there is no blinking on the terraform button when I enter Serious
