### ISSUE TITLE
[bug] Inability to Progress on 09 Leo, 266 Mission

### ISSUE THREAD

**Issue by Kruthex** [KnuckleCracker/CW4-bug-tracker#13]
### Description
To note, most people probably would not run into this, and I only did because I was playing around with the units. In the mission on _09 Leo, 266_, moving a cannon onto the highlighted area (_see the black square near the center of the screenshot_) where the rift lab should be moved prevents the player from progressing the mission. Because no object can be placed outside highlighted area, the cannon can't be removed, and the rift lab can't be placed where it should be.

### Screenshot
This screenshot shows my attempt to move the cannon off the highlighted area. The red square south of the cannon grouping shows how the cannon can't be placed outside of the area intended for the rift lab and thus, can't be removed in order to place the rift lab where it should be.

![20200829160216_1](https://user-images.githubusercontent.com/70452109/91646324-7f586880-ea13-11ea-8fc3-7cd99abfd086.jpg)

### Current Workaround
The only way I was able to complete the mission after encountering this issue was to restart the mission.

### Steps
1. Follow mission prompts until prompted to move the rift lab to a highlighted area.
2. Don't move the rift lab.
3. Instead, place a cannon in the highlighted area.
4. Try to move the cannon off the area.

### Output Log
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5145987/output_log.txt)

**Comment by Karsten75** [comment]
How is NOT following instructions a bug?

**Comment by Kruthex** [comment]
Whoa, chill. I'm not sure where this hostility is coming from. Not following instructions isn't a bug, but given that one of the things I like about how the Creeper World missions and mechanics so far have allowed people to rectify or at least continue despite their own mistakes mid-playthrough to allow them to finish (from that timer Hail Mary In CW3 to even the final demo mission), I just thought It would be nice touch to have that leniency here in the tutorial. If you don't agree, then no big deal. You don't need to go all caps though.
