### ISSUE TITLE
[minor] The max ammo of porters counts down while charging

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#134]
In the porter introduction map, I found that porters count down their max ammo while (first?) charge:
So this is pic one: 
![image](https://user-images.githubusercontent.com/16858356/98731782-877f3d80-239e-11eb-9a3c-c89a6bcce443.png)
And this is pic two, few seconds later: 
![image](https://user-images.githubusercontent.com/16858356/98731844-99f97700-239e-11eb-8822-9e8185fc079f.png)

**Comment by Karsten75** [comment]
Never spent time observing this, but I suspect this is an issue where the ammo is transferred into the pod. As such, there's probably not an issue

**Comment by knucracker** [comment]
I changed it so the max ammo doesn't count down. This was an issue when wares were selected (not energy).
