### ISSUE TITLE
[minor] the info? button has a larger response field 

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#135]
The info panel gets triggered when I click on the porter 
![image](https://user-images.githubusercontent.com/16858356/98732299-40de1300-239f-11eb-9bc2-ce944f9f8cba.png)

**Comment by Karsten75** [comment]
This refers to the hitbox for the Info button. Might be related to resolution and scaling?

**Comment by BilboGCL** [comment]
Res was 1920x1980 with this ui-slider setting: 
![image](https://user-images.githubusercontent.com/16858356/98733520-ec3b9780-23a0-11eb-8cd0-33554bc458f1.png)
