### ISSUE TITLE
[bug] Valley of Death and Shadow cannot be 100% completed

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#139]
**Describe the bug**
Totem activation is one of the objectives, and they require liftic. There is no liftic on the map.

**Additional context**
Valley of Death and Shadow looks to be a "before time" clone, except it's missing parts(like it's got a slightly different topography on top of slightly different enemy units).
If it is supposed to be the mission for 21 gun salute, the volcano is missing. That achievement may not be completable. Ignore if this is not the same mission.

**Comment by Karsten75** [comment]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5525254/save.zip) 

Here is a save with totems changed to require Arg. :)
