### ISSUE TITLE
[bug] Mission Objective Icons Stretched

### ISSUE THREAD

**Issue by chrislove01** [KnuckleCracker/CW4-bug-tracker#14]
![image](https://user-images.githubusercontent.com/35330243/93240765-6faf8280-f77c-11ea-8fd2-52b3fbd7d648.png)

 Likely due to my ultra wide resolution?

**Comment by Aaron100-prog** [comment]
Same for me on 1280x1024

**Comment by Karsten75** [comment]
I suspect this is more "by intent" than a bug. However, I'll let knucracker make the call.

**Comment by knucracker** [comment]
I forgot about this objective icons. They appear squished because I changed the view angle on worlds and didn't change the view angle on the icons. It's fixed next build (along with them appearing when they should).
