### ISSUE TITLE
[bug] Neuron completion does not unlock map above it

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#140]
**Screenshot**
![image](https://user-images.githubusercontent.com/26010895/98758122-3fa2eb00-238b-11eb-81ed-ad2063248cfe.png)

**Describe the bug**
On completion Neuron should unlock the map above and to the right of it. This only works for the map to the right, and not the one above.

**Comment by grabz-dev** [comment]
Can confirm - finished Neuron, map above is locked.
