### ISSUE TITLE
[bug] Valley of the Shadow of Death and Creeper++ - Units can be placed on top of enemies

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#141]
In Valley of the Shadow of Death and Creeper++ (span), units can be placed on top of all Emitters and Stashes

![image](https://user-images.githubusercontent.com/51026936/98758603-76025980-23cf-11eb-84e2-d63b1b5ed582.png)
![image](https://user-images.githubusercontent.com/51026936/98772630-70b10900-23e7-11eb-8d25-2fa11a1c85ff.png)

**Comment by TacisLexica** [comment]
The same happens in Neuron, with no real effect on gameplay.

**Comment by Karsten75** [comment]
Save file in #139 will fix this as well
