### ISSUE TITLE
{Suggestion] Bomber target indicator improvements

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#143]
**Is your feature request related to a problem? Please describe.**
I find that ordering many bombers around is very difficult. I like to spread them out so they evenly cover a larger area. The way I do this is by selecting several of my bombers all at once, and ordering them somewhere. Then I click on the target marker to select a single bomber, and order it somewhere else in vicinity - repeat until all bombers are ordered. This is difficult for two reasons:
1. The markers disappear quickly. After they disappear, I have to go back to my bombers, and quickly move my mouse across all bomber units to make markers appear, then quickly go back to where I ordered my bombers so I can go back to organizing targets. Repeat until all bombers are ordered.
2. When left clicking, units take precedence over target markers, so if a marker is dead in the center of a unit, it is very hard to select - not impossible, but the user must click pixels on the very edge to hit the marker.

**Describe the solution you'd like**
1. I'd like bomber markers to only show up when a bomber is selected, not hovered over. This avoids "random" markers popping up as user moves their mouse around their screen and touches random bombers in the air. It would also make showing all markers again as easy as clicking a bomber and hitting CTRL+A, which is how I thought it worked originally. I'd also like marker lifetime to be doubled.
2. Markers should take precedence over units when left clicking, because moving a marker back and forth to select a unit is easy, but moving a unit back and forth to select a marker is not.

**Describe alternatives you've considered**
I considered target markers not disappearing, but as K75 said the screen would probably be too cluttered.

**Comment by knucracker** [comment]
We can eval this in beta 2...
I've made these changes:
1: The target indicator has been changed to a model that looks like a plus sign.
2: The target indicators do not fade out.
3: Target indicators are visible for all air bases when they have assigned targets.
4: Arrows no longer appear over aircraft or pads.
5: The pads show an orange plus on their pads when they have an assigned target.
6: All most over actions are removed.
7: When a target indicator overlaps a unit, clicking will select the target indicator.

Not fading out the target indicators is debatable... so we can see how that works out.

**Comment by BilboGCL** [comment]
The new thing gives some problems: 
1. aim with 3 or 4 bombers on one emitter
2. select one of the bombers via target indicator
2a. select another target (not needed!)
3. try to aim on the same emitter again

Expected result: the selected bomber should aim at the emitter

True Result: A second bomber is selected (when you click again, a third)
