### ISSUE TITLE
[bug] You can force completion of a story mission's objectives by beating a new mission in the editor

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#147]
This is kind of a weird one. If you load up a story mission then afterwards load up a new mission in the editor you can force completion of that story mission. Here are the steps to repro:

1. Go to Farsite Expedition and load a mission that you haven't completed yet.
2. Exit to main menu.
3. Go to the mission editor and create a new custom mission.
4. Set the victory conditions to whichever conditions you would like to complete on the Farsite Expedition mission.
5. Complete the victory conditions while still in the mission editor.
6. Rift Jump and return to main menu.
7. Observe that the previously uncompleted mission in Farsite Expedition is now completed.

Output log seemingly shows nothing unusual, but here it is nonetheless:

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5523210/output_log.txt)

**Comment by knucracker** [comment]
Thanks for the very accurate way of reproducing this problem... that helped a lot.  Yeah, turns out a little typo was preventing the mission GUID from being updated when creating a map. So a newly created map would assume the last GUID in use.
