### ISSUE TITLE
[Bug.Minor] AC following Creeper Pathways on Shaka.

### ISSUE THREAD

**Issue by IronChainMan** [KnuckleCracker/CW4-bug-tracker#148]
After nullifying all enemies and letting AC cover map I disabled the nullifiers and the AC followed along the Creeper Pathways into the other landmass.
![20201111100410_1](https://user-images.githubusercontent.com/74311731/98830831-d9f54400-2408-11eb-98d9-88433b618b83.jpg)
![20201111100459_1](https://user-images.githubusercontent.com/74311731/98830833-db267100-2408-11eb-9f14-90d4d4d4af80.jpg)
![20201111100638_1](https://user-images.githubusercontent.com/74311731/98830834-db267100-2408-11eb-9c74-ac9ea6a36604.jpg)
![20201111100404_1](https://user-images.githubusercontent.com/74311731/98830840-dbbf0780-2408-11eb-9819-7aeb51dccd4c.jpg)

**Comment by Karsten75** [comment]
Active Mesh will conduct either Creeper or anti-Creeper. If this is what you are reporting, it's not a bug.
