### ISSUE TITLE
[bug] Unit select keys are not dynamic

### ISSUE THREAD

**Issue by Honnullul** [KnuckleCracker/CW4-bug-tracker#15]
Describe the bug 
   First to be seen in the Home mission, clicking 3 to build a Nullifier from the weapons tab will not work, instead it is mapped to 6, or whatever key is assigned to 'Build Unit 6'. Same in the later missions.

**Additional context**
While there are no missiles or other units to test, this most likely applies to them too. It would be most recognizable in custom maps where some units are removed and the order of units is changed.
**Edit:** Same goes for the beginning of Not my Mars with the Miner, not having the Pylon unlocked it should be built with 2 instead of 3.

**Comment by knucracker** [comment]
Updated the keys to match the unit in their slot. That keeps it consistent with how they are documented in the controls settings menu.
