### ISSUE TITLE
[bug] AC is lined with C lines under Dark Towers

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#150]
**Screenshot**
![image](https://user-images.githubusercontent.com/26010895/98840964-b4fed200-2404-11eb-91e4-17665f0aabc0.png)

**Describe the bug**
With default visibility settings, AC, when under a dark tower's cylinder of influence, will have the lines show up. These lines only respond to the "Hide C lines" option, and are colored for creeper. "Hide AC lines" does not impact their visibility.

**Comment by knucracker** [comment]
The alpha channel for the vertex color is used to specify which contour lines to render. For AC in darkness, I had the wrong alpha value.
