### ISSUE TITLE
Farsite overview - some infoboxes are cut at the edge of the screen

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#153]
When I click i.e. Ruins Repurposed, return to the main menu and get back in Farsite Expedition, I see:
![cw4-overview](https://user-images.githubusercontent.com/16858356/99018169-c0afdd00-2559-11eb-83e0-d2be23f38108.jpg)

This are my display settings:
![image](https://user-images.githubusercontent.com/16858356/99018210-d7563400-2559-11eb-8cd1-972c257eb572.png)
(My native resolution is 3840x2160)

**Comment by Karsten75** [comment]
Some UI and scaling fixes must have been implemented since then, remaining issues are most likely not going to get fixed.
