### ISSUE TITLE
[Beta2] Bomber behaviour

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#154]
As https://github.com/KnuckleCracker/CW4-bug-tracker/issues/143 is closed:

The new thing gives some problems:

1. aim with 3 or 4 bombers on one emitter
2. select one of the bombers via target indicator
2a. select another target (not needed!)
3. try to aim on the same emitter again

Expected result: the selected bomber should aim at the emitter

True Result: A second bomber is selected (when you click again, a third)

**Comment by knucracker** [comment]
I've changed it so that when a target indicator is selected, you can place it on top of other indicators without selecting those indicators.
