### ISSUE TITLE
[bug] Completion of "Highway to helheim" does not unlock planet above it

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#155]
Same as #142

**Comment by Karsten75** [comment]
My suggestion is that by default,  none of the missions get locked

**Comment by knucracker** [comment]
Yeah, there are directions to the connections that is not at all very clear. I'm just going to unlock all worlds. That will solve the problem of some people getting stuck on some worlds as well.
