### ISSUE TITLE
[bug] Beta2 - Completion of Fark York Farm does not unlock the map above it, completion of Sector L does.

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#156]
Completing Sector L unlocks the map above (Highway to Helheim) but completing Far York Farm does not.
https://github.com/KnuckleCracker/CW4-bug-tracker/issues/151
![image](https://user-images.githubusercontent.com/51026936/99021068-22734580-2560-11eb-8c04-636126557cc0.png)

**Comment by Karsten75** [comment]
As per other issue, just consider not locking any mission(s)

**Comment by knucracker** [comment]
Yeah, there are directions to the connections that is not at all very clear. I'm just going to unlock all worlds. That will solve the problem of some people getting stuck on some worlds as well.
