### ISSUE TITLE
[bug] Monolith unit in Parasite can be disabled even before it is taken over by AC

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#157]
The Monoliths in "Parasite" can be disabled from the start, stopping Creeper flow through it.

**Comment by Karsten75** [comment]
Making this a minor issue since Monoliths cannot be built in current missions. Trivial issues like this have no effect on game play

**Comment by knucracker** [comment]
This is an old built in unit, so a simple fix
