### ISSUE TITLE
[bug] Colonies apply filters doesn't work sometimes

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#158]
**Describe the bug**
As title says; title and author searches weren't working.

**Additional context**
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5534985/output_log.txt)

**Comment by knucracker** [comment]
It was actually the sort by 'thumbs' checkbox that was not hooked up properly.  When that was selected it would fail on any other filter that caused it to attempt to refresh.  Tricky
