### ISSUE TITLE
Lore achievement progress popup occurs whenever you press "Rift jump" regardless of actual progress [Bug.Minor]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#159]
![20201113095917_1](https://user-images.githubusercontent.com/40322714/99038849-4605b280-2597-11eb-99cd-369a6beb68d5.jpg)

Anytime you press Rift jump the "25%" popup would occur. That is despite the fact that no actual progress is made.

**Comment by knucracker** [comment]
Changed it so the progress badge only shows when the progress has changed.
