### ISSUE TITLE
[bug] Overseer Audio source at wrong position

### ISSUE THREAD

**Issue by Aaron100-prog** [KnuckleCracker/CW4-bug-tracker#16]
Description:
     The activation sound of the overseer seems to 
      originate from the 0.0 position.
Steps to reproduce this behaviour:
     1. Go into a mission which has the overseer.
     2. Regain enough ground to activate the overseer.
     3. While the activation sound plays look directly at the 
           overseer
     4. Hear that the sound originates from the 0.0 position

**Comment by knucracker** [comment]
I added the position to the sound when playing. Please check it in preBeta 7 to see if it sound correct.
