### ISSUE TITLE
Ern selected when selecting unit [Bug.Minor] 

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#163]
![20201113171403_1](https://user-images.githubusercontent.com/40322714/99081363-bcc0a100-25d3-11eb-9f47-3066cf33e1f0.jpg)

1. 1. Click on an ERNed unit
2. 2. Release ern
3. click the unit
4. Expected: you selected a unit
5. In practice: you selected the ERN

**Comment by Karsten75** [comment]
The hitbox is small, you need to be careful. After a short while the ERN will drift away anyway

**Comment by knucracker** [comment]
I made ern's not selectable while at the same time keeping the collider so the popup appears telling people what it is.
