### ISSUE TITLE
[Bug.Minor] Unable to move camera with keyboard immediately after closing the recorder

### ISSUE THREAD

**Issue by Aaron100-prog** [KnuckleCracker/CW4-bug-tracker#164]
After closing the recorder the player is unable to move the camera with the keyboard. Presumably the game loses focus after pressing the X button inside the recorder view.

Steps to reproduce:
1. Play any mission
2. Open and close the recorder
3. Don't click anything.
4. Try to move the camera with the keyboard
5. See that the camera is not moving

Workaround:
When this happens the player can click somewhere inside the game window to regain focus on the game, fixing the problem

**Comment by Karsten75** [comment]
After the Recorder window has closed, it seems as if focus is somewhere else or not assigned (if that is even possible).
