### ISSUE TITLE
[bug] Founders - A.D.A gives new unit to Dr. Seloi after the ending

### ISSUE THREAD

**Issue by Dawid8plc** [KnuckleCracker/CW4-bug-tracker#166]
Mission: Founders

The mission has 2 main objectives: nullifying the neutron reactor and collecting the info cache. It is possible however to collect the info cache and then nullify the reactor right away, which results in A.D.A telling Dr. Seloi about a new Airship unit, however Dr. Seloi is already dead.

![image](https://user-images.githubusercontent.com/16761816/99097405-e2e84000-25d7-11eb-8270-46f754d136d9.png)

**Comment by knucracker** [comment]
Changed so that is the info cache is collected after destruction of the neutron reactor, the player gets a different and shorter message. Super weapons also do NOT unlock since Danu isn't there to ask for them.
