### ISSUE TITLE
[Bug.Minor] Founders - Objective Stats on the Play Log window are not aligned properly

### ISSUE THREAD

**Issue by Dawid8plc** [KnuckleCracker/CW4-bug-tracker#167]
Mission: Founders

The objective statistics on the play log window are not aligned properly.
UI Scale was set to 0.9, my resolution is 1366x768 and I play in fullscreen

![image](https://user-images.githubusercontent.com/16761816/99098796-ccdb7f00-25d9-11eb-80bd-660b99a4b8dc.png)

**Comment by Regallion** [comment]
Occurred to me too, on the same mission
![image](https://user-images.githubusercontent.com/40322714/99124902-1943b080-2614-11eb-8b37-f41c5b72b8d0.png)
1920x1080, default UI scale

**Comment by knucracker** [comment]
Reworked the layout of the 8 items (6 objectives and 2 header rows). The grid layout wasn't handling the case of two missing items. I changed it to two master columns with a header row and 3 objected in each column.

When playing future missions pay close attention and see if it lays out properly after this fix.
