### ISSUE TITLE
[bug] no range indicator dots on mesh over void

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#17]
last mission. my mortars could clearly hit the mesh yet there was no visual indication. in this specific case it is minor however it would be VERY easy to have a situation that is not minor

![](https://cdn.discordapp.com/attachments/700392764776383126/755539124227801269/unknown.png)

**Comment by knucracker** [comment]
Mesh got a y bump when over void.  I changed it so the yellow squares also get a bump up when over void, so they will show now over mesh.
