### ISSUE TITLE
[bug] Reloading a save and restarting the mission afterwards loads the save, and not the beginning the mission

### ISSUE THREAD

**Issue by GrandTeki** [KnuckleCracker/CW4-bug-tracker#170]
Simplest steps to reproduce:
1. load a save
2. click restart mission from the esc menu

**Comment by knucracker** [comment]
This is harder to fix than it should be. THere are numerous ways a mission can get loaded. Embedded mission, loose file, randomly generated, from main menu, or from the save load dialog in game. I've made a go at having the mission remember its 'specifier'. When the restart button is pressed in mission, if there is a specifier present on the mission it will attempt to load based on that specifier and category.  This seems to work for story, span, chronom, markv, and colonies. For a loose file and for the editor, it does not work. For the editor, I have removed the restart button anyway.  For a loose file... well that file represents the base state.

Keep a lookout for any issues and open a new issue if something is wrong.
