### ISSUE TITLE
Incoherent obelisk naming [Typo]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#171]
![image](https://user-images.githubusercontent.com/40322714/99110996-58fe9e00-25fc-11eb-8b14-ae3ab593615c.png)
![image](https://user-images.githubusercontent.com/40322714/99111022-66b42380-25fc-11eb-9626-2f0f334bc67f.png)

**Comment by knucracker** [comment]
The obelisk has been removed from the Wallis mission. But I'll still tend to this on the final mission.
