### ISSUE TITLE
[bug] Spore path indicator stops randomly

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#172]
**Screenshots**
![image](https://user-images.githubusercontent.com/26010895/99112759-69d2f380-25ab-11eb-95eb-5a35e33aa2f7.png)
![image](https://user-images.githubusercontent.com/26010895/99113526-a7844c00-25ac-11eb-987b-a59577750ea7.png)

**Describe the bug**
Spore path indicator stops randomly. Conditions necessary to duplicate this are unknown(thought it might be bombers getting in  he way of the path... but second time it happened, no bomber was in the way). Spore travels like normal.
Will not happen every spore tower launch(quite a few are between first screenshot and second).

**Comment by Karsten75** [comment]
I seem to recall that this was addressed or at least the cause was identified in the time between when this issue was raided and now, I am unsure if it was ever fully resolved, but regardless, this ship has sailed.
