### ISSUE TITLE
[bug] Play order error in final mission

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#173]
![image](https://user-images.githubusercontent.com/40322714/99115773-ff9a6d00-2603-11eb-8123-becb02c29796.png)

Founders - farsite expedition

It is possible to attempt to start near the reactor. In this case, the response dialogue from Danu is quesitonable, since there would be no reason for her to resolve to kill the reactor at this point.

**Comment by knucracker** [comment]
Added a check to see if it is too early for the normal message. If so, show a different message and response (only once). Then show the normal message later if it is triggered.
