### ISSUE TITLE
[Typo] Incoherent unit naming - Founders

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#174]
Founders - farsite expedition

![image](https://user-images.githubusercontent.com/40322714/99115913-41c3ae80-2604-11eb-9440-d9188dfd9c29.png)
![image](https://user-images.githubusercontent.com/40322714/99115933-48eabc80-2604-11eb-9d78-85bf1971b6d9.png)

**Comment by knucracker** [comment]
Changed internal name of unit
