### ISSUE TITLE
[Bug.Minor] Unreadable unit name for reactor

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#175]
Founders- farsite expedition

![image](https://user-images.githubusercontent.com/40322714/99116011-66b82180-2604-11eb-9b28-a25e829c771a.png)

**Comment by knucracker** [comment]
I made the name consistent with the lore name. The name doesn't fit in the space available, though. But it truncates properly so I'm going to let that stay as is for now.
