### ISSUE TITLE
[bug] Lighting issues

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#176]
**Describe the bug**
Shadows can cover the entire viewed area. When I first saw it, moving objects(possibly bombers? whatever it was was outside the viewing window) of some kind caused the issue, and not placement ghosts. It caused the screen to flash as the shadow covered everything and then nothing. 
I was able to somewhat replicate it by seeing a platform's shadow when in placement form normally until I moused over high terrain that was not close to the camera, where the shadow covered the entire viewing area.
Unfortunately moving the camera made the situation no longer cause the lighting issue, and I don't know how replicatable it is. Logging in case anyone else comes across it.

**Comment by Regallion** [comment]
I believe i experienced the exact issue you described, where there is a bit of a weird flicker you get sometimes.
I have failed to consistently replicate it, but i am not convinced it has anything to do with shadows.
