### ISSUE TITLE
MarkV - after playing a map, previous missions stays empty

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#177]
After playing a MarkV for the 1st time, previous missions stay empty: 
![image](https://user-images.githubusercontent.com/16858356/99126271-1e016800-2606-11eb-9d96-b7bcc1adb598.png)
output_log.txt is here:
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5539548/output_log.txt)

The file markv.txt was not existent in Docs>MyGames>creeperworld4

Putting this file in said folder resolved the problem:
[markv.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5539561/markv.txt)

Playing missions are now shown in previous missions

**Comment by Dawid8plc** [comment]
I had the same thing happen to me, looks like the file just has to exist for this to work, which means that you can simply create an empty text file in the creeperworld4 folder

**Comment by knucracker** [comment]
The code expected a markv.txt file to exist. If not, it would throw a null pointer exception.
