### ISSUE TITLE
[bug] Stopping the nullification on the Neutron Reactor locks your camera

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#178]
During the countdown after nullifying the Neutron Reactor, your camera is locked until the countdown is complete.  If the countdown is cancelled your camera remains locked, and if you lose the nullifier it becomes very hard to play the level.  Save & load does fix the issue.

To recreate this bug: get a nullifier placed on the reactor, once it gets to full and triggers the camera lock disable the nullifier.

**Comment by knucracker** [comment]
When transitioning back out of the countdown, release the camera and reset it. Not ideal since the camera moves to the default position. But better than having a locked camera.
