### ISSUE TITLE
[bug] drag selecting unit move error

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#18]
when you drag select units that can move and some that can't the group includes places for the ones that can't. in this case walls on final mission

**Comment by harrymcb** [comment]
![image](https://user-images.githubusercontent.com/54015763/93271939-0dee1900-f77a-11ea-9480-ab0ec68ea6d4.png)

**Comment by knucracker** [comment]
The ParkUnits call was getting called on all selected units, not just those that are movable.
