### ISSUE TITLE
[bug] The founders - misaligned lasers

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#180]
[Blastingtest.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5540655/Blastingtest.zip)
![image](https://user-images.githubusercontent.com/40322714/99146649-28b21080-268b-11eb-9cc9-aa5bfb2ab8f1.png)

Mission - the founders - farsite expedition

1. Put a unit near the obelisks so that they start firing
2. Save the game while they are firing.
3. Load the game.

Beams now go crazy.
They will re-align once you unpause.

**Comment by Karsten75** [comment]
I think the fact that it's a custom unit and that it fixes itself as soon as the game unpauses makes it minor. Only reason I'm not closing it is that there may perhaps be an issue in saving state. That has happened a few times and is worth checking?

**Comment by knucracker** [comment]
The beams needed one more piece of information to load properly. They were persisting the location of the end of the beam as a local offset from the unit they were attached to. When loading they were using that offset as an absolute position.
