### ISSUE TITLE
[bug] Porters feed back into themselves

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#181]
1. Build a porter
2. Assign it a goal that is in the same network as the porter
3. The freshly-delivered cache immediately filters back into the porter.

Use case: was trying to use porters the same way you could use guppies in CW3, to speed up frontline resupply.
CW3 guppies would not feed their own bases, nor would feed any other bases in the same network as their own base.

**Comment by knucracker** [comment]
Looks like this is only true when the porter is taking energy. I already had a check in place to prevent the feedback of a non-energy ware into a porter.  I've added a similar check for energy.
