### ISSUE TITLE
"Infinite" resource production(Editor) [Bug.Minor]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#183]
1.  Enter editor
2. Place a redon deposit
3. Set the production delay to 0.
4. production rate is now "Infinite"

![image](https://user-images.githubusercontent.com/40322714/99147185-f656e200-268f-11eb-9eaf-3e1ca5815cdc.png)
![image](https://user-images.githubusercontent.com/40322714/99147198-17b7ce00-2690-11eb-8ea3-91770b14806c.png)

**Comment by knucracker** [comment]
Fixed the infinit part.  Also made some small changes to the deposits (redon and bluite). Now, 0 and 1 intervals produce at 30 per second (so they are the same). Also removed the random variation on deposits. Previously a random amount in the +-10 range was added each production interval. This no longer happens. This makes deposits very regular and reliable producers. One things to look out for is a performance dip if there are a ton of redon all producing on the same frame. If you note this, open a new issue for it.
