### ISSUE TITLE
[bug] Bombers can be placed on elevation different from the Runway

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#185]
Don't know for sure if this is a bug or intended, reporting anyways:
![image](https://user-images.githubusercontent.com/51026936/99150391-93b41500-2694-11eb-9af7-7fb4842ffbaf.png)

**Comment by theachevah** [comment]
Hi, I have a pic to add to this report:
![bombers in different elevations](https://user-images.githubusercontent.com/65570143/99150765-3f496f00-266d-11eb-83a8-19b47986c399.jpg)

**Comment by knucracker** [comment]
Pads were not checking the height of the runway and comparing it to themselves.
