### ISSUE TITLE
Porter - target selection 

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#186]
When using a porter, It seems to be random where I'm allowed to place porters:
This is forbidden: 
![image](https://user-images.githubusercontent.com/16858356/99151522-27d5aa80-269c-11eb-940a-dd749495d441.png)
but this is allowed: 
![image](https://user-images.githubusercontent.com/16858356/99151529-3754f380-269c-11eb-843f-53c533b7370c.png)

In a more gameplay relevant context, there is no place on the top left island where I can drop a porter 
![image](https://user-images.githubusercontent.com/16858356/99151565-869b2400-269c-11eb-944f-a026d8ababd8.png)

**Comment by BilboGCL** [comment]
My bad: The pics were taken with mesh not visible and it turns out, porters aren't allowed to land on mesh, even when it's dead
This is a maps save (delete the .txt at the end): [porter problems.cw4.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5541100/porter.problems.cw4.txt)

**Comment by knucracker** [comment]
Removed the restriction that was preventing porters from specifying a target on mesh.
