### ISSUE TITLE
[Bug.Minor] Incremental steam achievement acquisition logging

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#187]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5541408/output_log.txt)

1. Enter the main menu.
The game will acquire and log your steam achievements
**SteamStatsAndAchievements Enabled for AppID: 848480**
**Storing Steam Stats
StoreStats - success**

2. Enter any map.
3. Exit map. 
4. Return to main menu.
The game will acquire and log your steam achievements...twice.
**SteamStatsAndAchievements Enabled for AppID: 848480
Storing Steam Stats
StoreStats - success
StoreStats - success**

5. Repeat steps 2-4 again.
The game will acquire and log your steam achievements...thrice.

**SteamStatsAndAchievements Enabled for AppID: 848480
Storing Steam Stats
StoreStats - success
StoreStats - success
StoreStats - success**

This continues indefinitely and can potentially cause problems for long play sessions.

**Comment by knucracker** [comment]
The achievements panel was set to not destroy on scene load. That in turn lead to a new panel being created every time the main menu scene was loaded. Each of those in turn synced with steam.  I've made it so subsequent instantiations of the achievements panel destroy themselves before they do anything.
