### ISSUE TITLE
[bug] Bugged visuals/audio for Berthas on Chanson

### ISSUE THREAD

**Issue by Decagon95** [KnuckleCracker/CW4-bug-tracker#189]
On the map Chanson, I encountered a visual/audio bug with the Berthas. Their targeting graphic is located way off the map, the projectiles themselves have no trails and no firing sound effect, and when ERN boosted, it doesn't split into three projectiles like I assume they should. The Berthas also do not have a "Clear Target" button.

I have performed a restart and this hasn't fixed the issue. This issue appears to affect all of the Berthas on the map.

![20201115123041_1](https://user-images.githubusercontent.com/74496261/99186174-76d81a00-2746-11eb-9cc5-fa71cec978af.jpg)

Here is the .zip for the save and log files:
[Chanson-Bertha-Bug.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5542409/Chanson-Bertha-Bug.zip)

**Comment by Karsten75** [comment]
there has also been mention (not by this user) issues on Chanson there the nullifier could not be sestroyed for the custom objective, or did not give the custom objective. It might or might not have been after a save.

**Comment by knucracker** [comment]
Updated the Bertha's with the 2020 version (not the 2019 version). Also fixed a compile issue in the inhibitor.
