### ISSUE TITLE
[Bug.Minor] Editor window hover does not block minimap

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#190]
![image](https://user-images.githubusercontent.com/40322714/99190208-50ca6e00-2776-11eb-8681-092c4c925aff.png)

Seen on screenshot: while hovering over editor options it also hover over underlying minimap. This looks odd.

**Comment by BilboGCL** [comment]
Another image:
![image](https://user-images.githubusercontent.com/16858356/99744935-eb111580-2ad8-11eb-9ab1-35361b8908db.png)
The cursor was on the marked area and the minimap descriptions popped up behind the editor pane
