### ISSUE TITLE
[bug] Creeper++ mechanic incorrect emitter values

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#192]
The hover tooltip of an emitter is not correctly affected by creeper++ mechanic, while the on-click menu does. This is not specific to a map.
![image](https://user-images.githubusercontent.com/40322714/99190907-722d5900-277a-11eb-8f17-cfcfb665576f.png)
![image](https://user-images.githubusercontent.com/40322714/99190889-5033d680-277a-11eb-87d0-460d7bc52bb1.png)
![image](https://user-images.githubusercontent.com/40322714/99190895-5fb31f80-277a-11eb-8c3a-da7c1613ad85.png)

(same emitter)

**Comment by knucracker** [comment]
Updated the hover tooltip to show the modified output amount.
