### ISSUE TITLE
[bug] Importing CW3 map, saving and restarting

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#195]
There are several workflow issues around importing a CW3 map. 

Some of these may carry over into other editing workflows. 

Most importantly, the "restart" button on the menu pane yields incorrect results prior to the first save, returning a blank map.  I have not checked if this pertains only to maps imported from CW3, or maps started in a different way and edited, but not saved. 

Once saved, the map will restart from what appears to be the saved copy of the map. 

2nd issue is that importing a map does not preserve map units prior to the first save

3rd issue is that emitters with negative values (anti-creeper emitters)  have incorrect positive  values

**Comment by knucracker** [comment]
Newly created maps weren't being saved after creation properly.  More specifically, they were being saved but being saved too early in the startup process.  For the negative emitters, they weren't being loaded at all. The were persisted with a different name in CW3, so they were not even being loaded.

On the 'restart' issue, it's hard to define what restart should do when in a 'map editor' map. So I've removed the restart button when launching a map from within the editor. Note that the save/load menu is already different when in a map editor map (it has save, load, and finalize options).
