### ISSUE TITLE
[Bug] Map Turtle uses old wares for totems

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#196]
**Screenshots**
![image](https://user-images.githubusercontent.com/26010895/99194988-370e3400-2740-11eb-82b2-ebcda539d256.png)
![image](https://user-images.githubusercontent.com/26010895/99194997-40979c00-2740-11eb-9bd6-4b5743480b3c.png)
![image](https://user-images.githubusercontent.com/26010895/99195007-4db48b00-2740-11eb-889d-08c33742b656.png)

**Describe the bug**
Some of the totems require the old wares, such as resistium and fluxygen. These wares are unobtainable, so the totem objective cannot be achieved.

**Comment by knucracker** [comment]
Fixed by K75
