### ISSUE TITLE
[Bug] Map Turtle has a totem with unidentifiable material requirements

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#197]
**Screenshots**
![image](https://user-images.githubusercontent.com/26010895/99195062-adab3180-2740-11eb-8390-a6aa5a4b5c92.png)
![image](https://user-images.githubusercontent.com/26010895/99195072-b865c680-2740-11eb-8ea5-34833babb8b3.png)

**Describe the bug**
The totem is the southernmost totem, and it looks like it has multiple requirements, but they all stack on top of each other.

**Comment by knucracker** [comment]
Fixed by K75
