### ISSUE TITLE
[Typo] The Complex and Sequence

### ISSUE THREAD

**Issue by GrandTeki** [KnuckleCracker/CW4-bug-tracker#199]
![image](https://user-images.githubusercontent.com/50800712/99196876-42d51700-278f-11eb-923b-1c99be1493c9.png)
Should instead be "preferred"
![image](https://user-images.githubusercontent.com/50800712/99196878-47013480-278f-11eb-8a75-25506ee93d73.png)
Should instead be "Destination"

**Comment by knucracker** [comment]
Changes incorporated
