### ISSUE TITLE
[Bug.Minor] Survive objective scores are sorted ascending with group name

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#202]
Hold objective makes more sense to be sorted descending since you want to survive as long as you can.
![image](https://user-images.githubusercontent.com/51026936/99255467-4363c100-2814-11eb-8499-fee24683238d.png)

**Comment by Karsten75** [comment]
Yes, known to-do. :)

**Comment by knucracker** [comment]
Updated the server script to reverse the sort when there is a group filter and the query is for the hold table. This change is on the server so it is live right now (new build not required).
