### ISSUE TITLE
[Bug] Save/Load resets state of Hold bases

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#203]
[PartHoldem.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5546418/PartHoldem.zip)

Whenever you load a save all red bases will reset to green. This happens even if they are submerged, in which case they will go through green-red animation again.

**Comment by knucracker** [comment]
The bases were not persisting their state properly.
