### ISSUE TITLE
[Bug.Minor] Spore Arc visual 

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#205]
![SporeArc](https://user-images.githubusercontent.com/72889843/99285542-a7cb5400-2805-11eb-989b-a89ffd288179.png)
Describe the bug:
   See image. The arc was finished painting - but did not show the point of impact; ending high in the air instead. This is the closest (and highest) I've seen a spore go, so it may be related to that.

**Comment by knucracker** [comment]
Dup of #172
