### ISSUE TITLE
[Typo] Final Email Response cutscene

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#207]
![FinalEmailResponseCutscene](https://user-images.githubusercontent.com/72889843/99294053-840e0b00-2811-11eb-99ef-51c7ab039f91.png)

That second sentence is a bit of awkward phrasing.
A comma after "not me **,** and Preach" is a bit better, but consider this sentence instead:

"Preach, Hip, and Sarge want 'not me' to join them for an eternal voyage through space and time to make the universe a better place?"

**Comment by knucracker** [comment]
Changed message to

Really ADA, you old girl? I'm cyber-me now? And Preach, Hip, and Sarge want 'me' to join them for an eternal voyage through space and time to make the universe a better place?
--- COUNT ME IN! ---
