### ISSUE TITLE
[Bug.Minor] Reclaim percentage can be illegally obtained 

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#208]
[CursedHoldem.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5549309/CursedHoldem.zip)

In certain cases, when creeper spills into a void and later evaporates, it causes your reclaim objective percentage to go up. In this case, i can get 50% while never doing anything at all. 
Not critical, but kind of odd?

**Comment by Karsten75** [comment]
Note that in the case of Holdem, the actual,. ,full reclaim eligibility cannot be obtianed this way. This shwos that the design of a map is the crucial factor in determining how a reclaim victory can be achieved. In CW3, we did not deny quick wins when map makers failed to protect their Inhibitors. If someone wants to turtle to the extent necessary to achieve a reclaim victory this way it should be permitted. 

Additionally, not that the entire map was flooded.  It might be more on-point to deny a reclaim victory ( or any victory, for that matter) if the Rift Lab is not on terrain at the time the victory becomes eligible.

**Comment by knucracker** [comment]
I suppose the only way to change this would be to not count creeper on void. But that eliminates some legit cases for reclaim missions. It's also one more 'if' check in the core part of the creeper sim to do this (so it would be a small performance hit). For now I will just leave this as is.
