### ISSUE TITLE
Increase difficulty of Founders mission

### ISSUE THREAD

**Issue by knucracker** [KnuckleCracker/CW4-bug-tracker#211]
Airsac island can be taken out too easily. The single air sac also isn't enough to even be noticed by some players. Perhaps a couple air sacs on a slightly increased schedule will do the trick.

Also increase breeder output. People are too easily direct assaulting the Nexi.

**Comment by BilboGCL** [comment]
One way to change that: Right now flying units over the neutron source are not affected. When I sent the porters to air sac island, I expected the porters to be destroyed. So when you also check for in-flight units, that would make things harder. 
You should be so kind to tell the player about that

**Comment by knucracker** [comment]
- Added two air sac cauldrons. One goes off after just a couple minutes. It takes a while to make it to the player's base, though.
- Added a land bridge from the main island to air sac island.
- Increased breeder terrain output.
- Increased Creeper cap from 7 to 16.
- Added random height variation to the creeping terrain.
- Make sure all enemies target structures.
- Increase spores and blobs.
- Increase egg output (2 rather than 1)
- Added extra crimsonator terrain
- Expanded the land a little bit to incentivize taking the southern island.
- Moved some redon from the player island to the southern island (another incentive).
