### ISSUE TITLE
[Suggestion] We Know Nothing Enemy Station and Nullifier interaction 

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#213]
![WeKnowNothingNullifier](https://user-images.githubusercontent.com/72889843/99327725-90618a80-2848-11eb-8c3b-f3735271255d.png)

Nullifiers should destroy themselves (a la CW3) if their target is destroyed. 

Most evident on nullification of 'EnemyStation' units on 'We Know Nothing'

**Comment by Karsten75** [comment]
There is very little actual benefit/difference - this is a quibble. This is not productive to complete the game and release in a short while.

**Comment by Regallion** [comment]
To be fair, instead of it being a general thing, you could simply adjust the 4RPL to also delet the offending nullfier.

**Comment by WithersChat** [comment]
> To be fair, instead of it being a general thing, you could simply adjust the 4RPL to also delet the offending nullfier.

Assuming you can detect it using 4RPL
And assuming it has no other target.

**Comment by Karsten75** [comment]
Nullifier overload was introduces somewhere, sometime.
