### ISSUE TITLE
[Bug.Minor] Factory and ERN Portal are missing from the Info menu

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#214]
![InfoFromFounders](https://user-images.githubusercontent.com/72889843/99328118-6eb4d300-2849-11eb-8763-cf473502c47a.PNG)

Screenshot from 'Founders' level but pretty sure Factory and ERN Portal are missing altogether. Since these are more complex units, they should be included.

Enemies and other (non-buildable) units are missing also; which would be nice but not as needed.

**Comment by Karsten75** [comment]
same as issue #118
