### ISSUE TITLE
[Typo] 09 Leo, 266

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#215]
![09LeoDrSeloi](https://user-images.githubusercontent.com/72889843/99328644-8476c800-284a-11eb-9a93-4719d8dd2d06.png)

"The soylent fields are now activating Dr. Seloi." -> "The soylent fields are now activating, Dr. Seloi." [comma added]

Also, consider: "They were to be part of the exhibition." -> "They were **supposed** to be part of the exhibition"

![InitializedJump](https://user-images.githubusercontent.com/72889843/99328812-dcadca00-284a-11eb-94d6-f67b183db39e.png)

Consider removing the period after initialized.

**Comment by knucracker** [comment]
Changes incorporated
