### ISSUE TITLE
[Typo] Farsite

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#216]
![FarsiteComma](https://user-images.githubusercontent.com/72889843/99329009-3f06ca80-284b-11eb-9272-2a36a622d9d0.png)

"The jump drive has been reinitialized Dr. Seloi." -> "The jump drive has been reinitialized, Dr. Seloi." [comma added]

**Comment by knucracker** [comment]
Comma added
