### ISSUE TITLE
[Bug] Restarting a map that was [EDITED] keeps showing as edited

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#218]
How to reproduce:
1. Open any map, for example in span
2. Hit the Editor key, map is now [EDITED]
3. Restart. Map is still [EDITED]

**Comment by Karsten75** [comment]
Perhaps fixed by #170, or otherwise a consideration before pushing gout the build that contains the fix for #170.

**Comment by knucracker** [comment]
Reset the edited status in the mission on the call to restart. It was previously passing in whatever the current edited state was to LoadMission.
