### ISSUE TITLE
[Bug.Minor] Cluttered range indication for moving multiple non-yellowdot units

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#219]
Here's what moving a single mortar looks like:

![image](https://user-images.githubusercontent.com/40322714/99375843-39ee5d80-28d5-11eb-81ec-1e8f6e360103.png)

9 mortars

![image](https://user-images.githubusercontent.com/40322714/99375879-42469880-28d5-11eb-899b-c504de5cfcb1.png)

No range indication. (which is good)

Moving 72 terps

![image](https://user-images.githubusercontent.com/40322714/99376003-67d3a200-28d5-11eb-8508-fb6e9f58fab5.png)

Moving 8 snipers

![image](https://user-images.githubusercontent.com/40322714/99376033-7326cd80-28d5-11eb-851a-d1e39d5d6620.png)

Moving 22 beacons

![image](https://user-images.githubusercontent.com/40322714/99376273-c7ca4880-28d5-11eb-8b02-29cc6da21535.png)

Moving 34 missiles (MY EYES)

![image](https://user-images.githubusercontent.com/40322714/99376112-8e91d880-28d5-11eb-8e31-5818d6d820c8.png)

Moving a variety of units

![image](https://user-images.githubusercontent.com/40322714/99376221-b5500f00-28d5-11eb-9153-0a47d21d25ad.png)

Perhaps, non-yellowdot ranges should also be hidden when mass-moving?

**Comment by Karsten75** [comment]
s) don't do that.
b) I would concur to turn off range on missiles when moving multiples, since that makes it hard to actually move them (why one would want to move them is of course an issue. All the other units seem OK since it is still possible to move them and their operating ranges are displayed.

**Comment by knucracker** [comment]
Added a handler that hides the range indicators on these units when there is more than one selected for movement.
