### ISSUE TITLE
Build x/yy is sometimes not valid

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#22]
I built two nullifiers and set them to off.
Later I select them both and put both units on
When both nullifiers are selected, they show "Built: 0/50" after they received packets.
Probably best solution: Don't show "Built: x/yy" when more than one unit is selected.

**Comment by knucracker** [comment]
Yeah, it was supposed to not show when more than one unit is selected. Instead, it was just "not updating". So it would show in that field whatever is was last set to. Fixed in next build.
