### ISSUE TITLE
[Bug] Incorrect display of resource income with mining ERN

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#220]
With ERN

![image](https://user-images.githubusercontent.com/40322714/99382920-42976180-28de-11eb-9d1f-5272bd1da95a.png)

Without ERN

![image](https://user-images.githubusercontent.com/40322714/99382963-4f1bba00-28de-11eb-8eb5-71a699ad44a4.png)

However, it is clear that the ERN affects the speed at which the mines produce. (it's unclear by how much due to jitter in this build).

If the ERN is meant to affect the mines, it should affect their rate, the rate display and the resource income on the factory button.
(would it affect the crystals with rates of 1 and 0?)

**Comment by knucracker** [comment]
Updated the displays to factor in the ern efficiency upgrade rate
