### ISSUE TITLE
[Bug] Spores can be negated by a shield 100%

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#221]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5553181/save.zip)

1. Create a spore tower
2. Cover it with a shield
3. All spores will immediately and harmlessly dissipate on launch.

This can be abused to "nullify" spore towers by briefly landing a shield as it launched, then evacuating.

**Comment by knucracker** [comment]
The shield was not setting it's store of arg to 0 when a spore hit it. Fixing that still didn't do a good enough job. So I add a 3 second stun to the shield when hit by a spore. That takes it offline long enough for a subsequent spore(s) to make it through the shield. Note that if the spore launcher only launcher 1 spore, that spore will still be totally neutralized.
