### ISSUE TITLE
[Bug.Minor] "Map already exists" when entering a space as the name

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#223]
![image](https://user-images.githubusercontent.com/40322714/99388230-4e872180-28e6-11eb-95dc-00b84f783ce1.png)

If you enter a space as a map name, the error message is...not correct

**Comment by Karsten75** [comment]
Since spaces are not valid, some error message is appropriate, I'm not going to let this go through just to add a different error message.
