### ISSUE TITLE
[Bug] Terp and Refinery play an explosion sound (but not visual) when manually destroyed

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#226]
Unlike other units, which go away quietly with no sound or visual explosion.

**Comment by Karsten75** [comment]
There is another issue, that one does not mention the Refinery. If I can find it, I'm closing it by pointing to this one

**Comment by knucracker** [comment]
In both cases it was the drone that was making the explosion. The base unit was going away silently, but the drones were blowing up. I changed the pads to destroy the drones rather than waiting for the drone to blow themselves up.
