### ISSUE TITLE
[Bug] Exit confirmation dialog is overlaid by recorder window. 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#231]
Reported by BurningShadow, I recreated it. 

1. play a mission. 
2. In mission, open recorder
3. Press Close Window X in top right of game window. 

Confirmation dialog does not appear until the recorder window is  manually closed.

**Comment by knucracker** [comment]
If the recorder is up, the game will now close the recorder if the game's window close button is clicked. That allows the close confirmation dialog to show.
