### ISSUE TITLE
[Bug.Minor] Bomber indicators are occluded by units or dips in terrain

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#232]
![image](https://user-images.githubusercontent.com/51026936/99434271-df71f300-290e-11eb-8670-7babdbf54353.png)

**Comment by knucracker** [comment]
I've changed the bomber indicators to do an 'always' depth test. So they will appear on top of everything. This solves the problem with being hidden. It introduces the problem of them always being visible (like behind hills, etc). But this is the way they were for a long time before the most recent changes, so best overall to have them always show.
