### ISSUE TITLE
[Bug] Can't click nullifier at certain camera angles

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#233]
I placed this nullifier, but I can't click it:
![image](https://user-images.githubusercontent.com/51026936/99439061-00d5dd80-2915-11eb-8b94-915a9093e59a.png)

If I move the camera to the right such that the nullifier is on the left side of my screen, I can, but it's iffy. If it's on the right side of my screen, it's completely unresponsive to any clicks.

[Grabz - Shaka.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5555824/Grabz.-.Shaka.zip)

**Comment by knucracker** [comment]
Really odd.  The nullifier had some ancient stuff on it. More colliders than it needed and a rigid body. The main collider was also set to trigger. I cleaned all of that up and that fixed the problem. Not sure why, but that brings the nullifier into spec with everything else.
