### ISSUE TITLE
[Bug] Chanson 4RPL units are at height 0 for nullifying purposes

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#236]
**Describe the bug**
Need to terraform all the way down to nullify them, which is definitely not intended.

**Comment by grabz-dev** [comment]
Can confirm, these units are very difficult to nullify, but it is possible to nullify all of them with very specific terping.

**Comment by knucracker** [comment]
The nullifier was using a line of sight calculation based on the terrain height under the center of the unit (plus 2 vertically). That worked for everything except these units. They were manually forced to sit on terrain that was higher than their center cell. As such, the nullifier couldn't get a LOS.

I have updated the nullifier to use LOS to the unit itself, not the terrain the unit sits on. This is a pretty low level change on a very core unit, so keep an eye on the nullifier in the next build.
