### ISSUE TITLE
{Suggestion] Control Panel for disabling production of ammo/build packets

### ISSUE THREAD

**Issue by Aaron100-prog** [KnuckleCracker/CW4-bug-tracker#24]
In some situation I want the energy to only being used for ammo and not for build packets.

I think when the rift lab is selected there should be a menu for toggling packet output. A bit like how it is in CW3:
![20200919001946_1](https://user-images.githubusercontent.com/56323986/93649775-0a25f500-fa0d-11ea-9d16-65bdd0ebbc7b.jpg)

**Comment by knucracker** [comment]
The command base only  dispatches build and ammo packets, so I just added a couple toggles to the command base control panel to regulate if each can be dispatched.
