### ISSUE TITLE
[Bug.Minor] Editor - Message list does not refresh after editing/incorrect handling of message deletion

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#242]
1. Open Editor-Text
2. Edit A.D.A. Messages
3. Add a new message
4. Close editor.
Bug: until you switch tabs, the message will not be valid for starting/ending message.

5. Add another message.
6. Set it as either starting or closing message.
7. Delete that message

Expected: the slot set in step 6 is now NONE
Actual: the slot set in step 6 is now the message from step 3

**Comment by knucracker** [comment]
Changed to update the dropdown when the ada messages change. Also removed the "End Message". It was not hooked up anyway.
