### ISSUE TITLE
[Bug] Blobs and striders do not respect map edges

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#243]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5560186/save.zip)

If blobs or striders are ordered to go to a location outside the map they will gladly do so.
They won't spill creeper there but...that's certainly not intended for -anything- to go past map's edge?
![image](https://user-images.githubusercontent.com/40322714/99535450-f883ae00-29b9-11eb-96b0-3219d34eb32f.png)

**Comment by markdomansky** [comment]
I've not captured a picture of the same, but I have witnessed blobs crawling on the outside edge of the map to bypass all defenses.  These seems like a bug as well.

**Comment by markdomansky** [comment]
![image](https://user-images.githubusercontent.com/4317290/101433156-db167580-38cf-11eb-8b8b-3260ff227e6a.png)
![image](https://user-images.githubusercontent.com/4317290/101433202-ea95be80-38cf-11eb-951e-cb17b1a7f54b.png)
This is definitely a bug, and cheating too!

**Comment by Regallion** [comment]
@markdomansky  if the map shown is "Parasite" then it's not actually map edge, that's just cleverly hidden void.
