### ISSUE TITLE
[Suggestion] De-tile normals the same way you can de-tile textures

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#248]
I'm not sure if this is possible, but I'd like to be able to de-tile normals the same way we can de-tile textures. That way we could de-tile textures and still be able to match them with normals. I'm only posting this suggestion if this is something that just wasn't thought of. If it was thought of and determined to be not possible, you can disregard this one.

**Comment by Karsten75** [comment]
There was a reason this was not done already.
