### ISSUE TITLE
[bug] Enemy units placed from map editor have very old placement icons

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#25]
One screenshot says it all

Spore launcher and placement ghost, side-by-side 

![image](https://user-images.githubusercontent.com/22965021/93670290-01aada00-fa60-11ea-888f-b3f74f4adb9c.png)

**Comment by knucracker** [comment]
I'll be updating all of those old icons once I've finished all of the new models
