### ISSUE TITLE
[Bug] Video length for partical recording displayed wrong

### ISSUE THREAD

**Issue by burningSchadow42** [KnuckleCracker/CW4-bug-tracker#250]
If you create a video of a partial recording via marking start and end the video tool still displays the legnth as if you made a video of the full recording.

![recording_bug](https://user-images.githubusercontent.com/64912782/99570565-6a67f180-29d2-11eb-829d-84155c06dd35.png)
The actually video created here was around 40seconds long

**Comment by knucracker** [comment]
The calculated time wasn't looking at the marks. Changed to factor in the marks.
