### ISSUE TITLE
[Bug] Editor: reclaim status of map cannot be cleared

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#252]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5562475/save.zip)

Once the map achieves the reclamation status, placing a delegate causes it to pop immediately. 
Finalizing it does not remove reclamation either.
Proposal: Have a button that wipes the reclamation status. Also wipe it on finalize.

**Comment by grabz-dev** [comment]
I made a map where I spawned a bunch of creeper then cleared it. Now if I place the delegate down and it starts charging, if I delete it and place it again it picks back up where it was previously. Maybe deleting and placing the delegate again could clear the entire reclaim status of the level.

**Comment by knucracker** [comment]
- Finalize now clears the state on the delegate.
- The delegate now saves/loads its internal state properly.
- I changed the "Reset Time" button on the game tab of the editor to "Reset Map Data". That button now does the same cleanup that finalize does (so it will also clear the delegate state and the peak creeper levels).
