### ISSUE TITLE
[Bug.Minor] Improperly cleared maps can be posted

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#253]
Right now, it is possible to only clear required objectives on a map and port out, then declare a victory.
That means, it is possible to have uncompletable objectives on map.
This is probably not intended.

The tricky issue of course is maps potentially having objectives not mutually achievable in one run. (Especially with optional custom objectives which might be for challenge runs)

Perhaps something to think about post-release.

**Comment by Karsten75** [comment]
This is a design objective. It is intended to allow for more options in a map,. If it gets abused, some action will be taken, the map may be reported and auto-redacted, etc. but the game will not prevent these types of maps to be uploaded.
