### ISSUE TITLE
Project Thor

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#255]
When I try to send multiple thors to one place, as in one elevated pylon, you pick up always one of the target indicators, looks like the same issue like the bomber indicators.

**Comment by Regallion** [comment]
To clarify: thors cannot be multi-selected at all.
You CAN shift-click several, but only one would move to the destination set.

**Comment by Karsten75** [comment]
Some units function as a group, others do not. THis is the same mechanism as for Bertha targeting. While multiples can be selected, they don't "target" or accept move orders as a group.

**Comment by jonerer** [comment]
I would also consider this a bug
