### ISSUE TITLE
When you unpower the last obelisk while it beams a unit, the beam persists

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#256]
I nullified the last power unit while the obelisk tried to delete one of my units:
![Zwischenablage01](https://user-images.githubusercontent.com/16858356/99615791-53e68800-2a1c-11eb-8744-e425b7c581ca.jpg)
![image](https://user-images.githubusercontent.com/16858356/99615838-6f519300-2a1c-11eb-9078-cca0d05ab97e.png)
And it will not vanish anymore: 
![image](https://user-images.githubusercontent.com/16858356/99615980-b0e23e00-2a1c-11eb-9348-fa2b6158eb65.png)

**Comment by knucracker** [comment]
When transitioning back to state 0, the obelisk will now turn off the beam and the beam sound.
