### ISSUE TITLE
[Bug] collect still buried info cache

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#257]
on archon i collected the closest info cache without using a terp
![image](https://user-images.githubusercontent.com/54015763/99622474-d86ee180-29ef-11eb-829a-2fc18666e2e9.png)

[save-1.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5564424/save-1.zip)

**Comment by knucracker** [comment]
LOS checking for paths was not checking the endpoints. So it was assuming the target connection point was not occluded by terrain. This is true for any unit other than a buried one. I changed the algorithm to check the start and end points to see if they are below the terrain height at that location. That, in theory, should not disturb the algorithm other than to perform these extra checks at the start and end of the path. 

Before this change, you could put a tower on the hill near that infocache and see the connection line go through the terrain. After this fix that no longer happens.
