### ISSUE TITLE
[Bug] output log is flooded with "Look rotation viewing vector is zero"

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#258]
**Describe the bug**
Log is flooded with "Look rotation viewing vector is zero". Trying to exit the map caused the game to hang, and for windows to put a "not responding" window up.

**Additional context**
I was working with 4RPL units; issue is very likely related.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5564522/output_log.txt)

**Comment by knucracker** [comment]
That is coming from some call in RocketShot.4rpl, and it's a unity message (something unity decides is a great idea to log on its own).  If you could send me, or put here, the test map with that script I should be able to reproduce it.  It's probably from a 'lookat' function, but hard to tell.

**Comment by Alophox** [comment]
It's entirely possible whatever command I used to get that message is no longer within the script;  but here is the map, as of the time of closing.
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5568446/save.zip)
Github doesn't support .cw4(imagine that) so here's a zip containing it.

Actually, it's possible that it was logged whenever `SetUnitForward(self <-velocity)`(line 47 of RocketShot.4rpl) had a velocity of 0. Which happened a lot, but shouldn't now.

**Comment by knucracker** [comment]
SetUnitForward didn't have checking for a zero vector. Unity pitches a fit you you assign a zero vector to certain things (like the forward vector of a gameobject). It doesn't thow an exception, it just logs a message.
I have added zero checking for SetUnitForward. That should fix this issue... but there are probably 10 other places where it may show up. If you notice any, just log a new issue.
