### ISSUE TITLE
[Suggestion] Pods being able to supply porters

### ISSUE THREAD

**Issue by TacisLexica** [KnuckleCracker/CW4-bug-tracker#260]
Scenario: (Encountered on Far York Farm)
A pre-placed cache of 200 Arg is on the map.
"Aha!", you think. "I can build two micro-rifts to connect the stockpile to the friendly-looking starting plain. I shall place the Rift Lab there to begin."

It turns out that the Arg will not move from the pod to the new porter.
(Building a Factory near the Arg doesn't affect it, tried it "on spec" as a once-suggested fix for #237.)

On the Far York Farm map specifically, it's possible to build remotely or to work around to a redon source, but this may not be the case on all maps.

Proposed possible solutions, in order of desirability:
- Allow pods to be instructed to supply porters, this setting defaulting to "no". Allows exact control.
- Allow pods to deliver to porters that did _not_ just deliver them - the Guppy behaviour from CW3, almost.
- Allow pods to deliver resources to porters - previous behaviour, which was removed for a reason.
- Ignore.
- Allow pods to restock the Factory only - may choke production, the pod will usually be placed where it is for a reason, the factory can only be built in one place.

The changes to porter activity are mentioned here (https://github.com/KnuckleCracker/CW4-bug-tracker/issues/237#issuecomment-729729353), but the Beta4 milestone doesn't seem to have an issue for it.
> This problem was introduced by the change in beta 4 that prevents pods from supplying porters.

**Comment by knucracker** [comment]
I've changed pods the following way:
1: Do not allow pods dropped of by porters to supply their origin porter pad.  
2: Do not let pods supply porter pads that are on the same network as their origin porter pad.

Item 1 prevents the simple case of a pod from supplying it's own pad.  Item 2 makes it so if you have multiple porters supply a front line position (for purposes of increasing the supply to the front line), you won't have energy/wares headed back to the supply porter pads for each other.

For disjoint networks, like remote locations or islands, it allows porters to pickup and bring energy/wares back to the main network.
