### ISSUE TITLE
[Bug.Minor] Misleading ERN portal bonus names

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#261]
Currently
Energy collection increases benefits from towers, energy miners and collector panels
Mine production increases effects of redon and blueite crystals, as well as blueite miners. (effect on liftic unclear)

This is misleading, as a casual read implies that Mine production would affect both modes of miners, while energy collection would not affect it at all.

Proposal: Rename the bonuses to Energy production and Resource (ware?) production.

**Comment by Bob2Chiv** [comment]
A different suggestion was 'Mineral production'
