### ISSUE TITLE
[Bug.Minor] Map size input fields allow for infinite input (visual)

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#267]
![image](https://user-images.githubusercontent.com/40322714/99730699-f448b500-2acd-11eb-92dd-ed9777c6c59f.png)

**Comment by Regallion** [comment]
If you do this and then press a map size, it does this
![image](https://user-images.githubusercontent.com/40322714/99731072-6ae5b280-2ace-11eb-814f-778de3033e86.png)

**Comment by Karsten75** [comment]
Things like these are self-inflicted, and has no impact outside of the local machine the use perpetrates them on. As such, the priority for fixing it is pretty low. 

Additionally, it most likley requires rework at a low functional level to replace the older text controls used in the game with newer versions and is thus a disproportionate effort.

**Comment by knucracker** [comment]
The text fields were TextMeshPro fields so I was able to set a max char limit on them (set to 3)
