### ISSUE TITLE
[Bug.Minor] Undeletable map in editor

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#268]
['m 3.29 minutes in... I'm now te.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5570078/m.3.29.minutes.in.I.m.now.te.zip)

Unpack this as a map folder.

Cannot be deleted from editor: when you try, it just...does nothing.
Relevant line from output_log
`Could not find a part of the path 'C:\Users\USERNAME\Documents\My Games\creeperworld4\editor\'m 3.29 minutes in..'.`

**Comment by Karsten75** [comment]
how did that file name even appear in the list of editable maps? Where is the screenshot showing that map in the editor pane?

You can open the editor folder in File browser and manually delete
