### ISSUE TITLE
You can place a cursor in the coordinates field in editor

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#269]
While looking for a way to change x/z coords of a placed info cache, I double clicked the unit description and got a blinking cursor
![image](https://user-images.githubusercontent.com/16858356/99739487-286fa600-2acd-11eb-9055-1b299fbcdbc2.png)
There was no way to edit or type anything

**Comment by Karsten75** [comment]
![image](https://user-images.githubusercontent.com/22965021/99754127-5ba23d00-2aad-11eb-9cd1-46a3d60e34df.png)

After that, I clicked the type drop-down and the cursor was in that field. 

![image](https://user-images.githubusercontent.com/22965021/99754179-7d032900-2aad-11eb-8331-516d0101e4cb.png)


It is intended that the coordinates and unit id/ GUID are selectable for copy/paste operations.
