### ISSUE TITLE
Editor, misplaced tooltipps

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#270]
When clicking the red marked arrows, the text bit on the left appears:
![image](https://user-images.githubusercontent.com/16858356/99742466-ce261380-2ad3-11eb-84da-193a2332929a.png)
This are my video settings: 
![image](https://user-images.githubusercontent.com/16858356/99742504-e433d400-2ad3-11eb-9b09-0829b32b6505.png)

**Comment by grabz-dev** [comment]
I do not see any tooltips appear, not even in the area indicated in the screenshot.
![image](https://user-images.githubusercontent.com/51026936/99830540-2144a880-2b5e-11eb-927f-9387529497fd.png)

**Comment by knucracker** [comment]
There were a ton of tooltips in the theme editor that were all broken. I replaced them with the common tooltip control that I used elsewhere.
