### ISSUE TITLE
[Bug.Minor] Theme Editor Cliffs Scale input field defaults to 255

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#272]
Just a weird quirk of the input fields, doesn't seem to break or affect anything. Happens right after loading a project:
![image](https://user-images.githubusercontent.com/51026936/99829133-2f91c500-2b5c-11eb-92d9-6ddf586d67cc.png)

**Comment by Karsten75** [comment]
I just opened the editor and the scale was not 255

![image](https://user-images.githubusercontent.com/22965021/99835914-eb3a0100-2b2a-11eb-90c8-3c8939be6c57.png)

Please re-open when 
a) you can specify whey one vlaue is necessrily worse than another
b) have steps to recreate

**Comment by grabz-dev** [comment]
Yeah I can't reproduce this anymore... oh well..
