### ISSUE TITLE
Video Settings - current resolution should be standard in the drop down menu

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#273]
The preset resolution in the video settings is always 1280x72, independent from the set resolution:
![image](https://user-images.githubusercontent.com/16858356/99831724-d035b400-2b5f-11eb-8b17-8d14561bd2a7.png)

When I change to i.e. 1600x900, press apply, go to either any other setting tab or close settings and come back to video settings, I see 
![image](https://user-images.githubusercontent.com/16858356/99831522-7fbe5680-2b5f-11eb-91f2-65a44c826be2.png)
I think it would be nice when the preset value matches the current resolution.

**Comment by Karsten75** [comment]
At issue here is that the list of full-screen preset resolution is not always similar for different users. It is possible that this is the cause of showing the wrong or a different selected resolution  than the actual value. 

If the user interacts with the UI scaling, and press "apply" without also ensuring that the correct full-screen resolution is selected, then the outcome can be unexpected.
