### ISSUE TITLE
[Bug.Minor] Some A.D.A. message and log issues

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#275]
In the final story mission (I have not tested all of them, but I have looked at others) only the initial message is saved in the A.D.A. log.
Additionally, end mission messages for custom maps do not appear (at least when playing after finalization and before uploading)

**Comment by knucracker** [comment]
This won't change any time soon.  The purpose of the ADA log is mainly to get back to any 'initial' data that is shown.  Over time, I ended up adding more messages shown from 4rpl. Those messages aren't ada log messages.  Adding them to the ada log would be a big overhaul at this point.

I still see the log as useful for many custom maps where the author only wants to put information (like unit or mission overview) in the opening ADA message. It can be good to be able to get back to that.
