### ISSUE TITLE
[Bug.Minor] Small graphical glitch in editor

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#277]
In the editor, the settings for Absorber terrain have a small glitch where the "/AC" text is hidden under the "MIN" input box.
![Minorgraphicalglitch](https://user-images.githubusercontent.com/18480264/99856594-6360ff00-2bdd-11eb-8500-180ecd46ae71.PNG)

**Comment by knucracker** [comment]
Fixed
