### ISSUE TITLE
[Bug.Minor] Dark towers starts acting weird on very large ranges

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#278]
This is a 262x250 map
[Bigmap.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5576456/Bigmap.zip)

This is what it looks like when you set dark tower to 200 range
![image](https://user-images.githubusercontent.com/40322714/99857466-5b349f80-2b9c-11eb-8311-4ccf1d698d77.png)
Yes, the weird secondary dark area ALSO blocks units.

Here's what happens if you set it to 250

![image](https://user-images.githubusercontent.com/40322714/99857542-80c1a900-2b9c-11eb-8949-3881a71811e7.png)

And yes, only the dark area blocks units.

**Comment by knucracker** [comment]
Integer overflow believe it or not. I use the square of the distance rather than the distance, and that can result in integer overflow larger cases (because it's an ellipse and two squared distances get multiplied together). I switched to longs.
