### ISSUE TITLE
[bug] Emitter operation does not permit build-up of large amounts of creeper

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#28]
After a change to how emitters work, they will not emit creeper once they are in same or higher-depth creeper. 

This change is detrimental to map makers. 

It means that large masses of creeper cannot be achieved by low-powered emitters, to create massive bulks of creepers, emitter specifications have to be increased to values that would prevent them from being approached and capped.

Emitters should revert to the previous mode of operation, where they  continue to emit creeper, even if their surrounding depth is at or higher than the value they emit. Optionally, they can/should check to not emit when they will cause a conversion. Eg, when at height 2,100 creeper, they should not emit 200 additional creeper. In that instance, they can be  quiesced.

I forgot to add that the more recent introduction of Creeper limits on maps may serve the same purpose as the original implementation of the capping of individual emitters.

**Comment by knucracker** [comment]
I started to make this an option on the emitters (the cap amount)... but then just decided to set the cap to 2147 and call it a day.  So effectively the emitters no longer will stop emitting now.  As you say, the global map limit can be used to better handle the limit anyway.
