### ISSUE TITLE
[Bug] Another crash.

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#280]
Not sure why it crashes: but if you open up the attached map and move the cursor near the upper skimmer spawner the game crashes.
[Crash Folder.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5576817/Crash.Folder.zip)

**Comment by Karsten75** [comment]
#241, fixed in Beta build 5
