### ISSUE TITLE
[Bug] Bombers are using runways of differing height and bombers not able to be built in valid locations

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#281]
![image](https://user-images.githubusercontent.com/68219054/99878956-10844900-2bd7-11eb-94fa-7b55e229e1b7.png)

To get this you need to place two runways at different heights and bombers between them; one runway does not need to be built, just placed to enable the bombers to be placed.  Once everything is placed, one runway can be removed and the bombers will use an incorrect height runway.

![image](https://user-images.githubusercontent.com/68219054/99879455-11b77500-2bdb-11eb-8e0a-46bdd1643139.png)
![image](https://user-images.githubusercontent.com/68219054/99879463-2431ae80-2bdb-11eb-8ef3-33d27830667a.png)
![image](https://user-images.githubusercontent.com/68219054/99879476-37447e80-2bdb-11eb-8879-4381e3fc2eb9.png)

When building these I had issues placing bombers sometimes, it appears that bombers will always try to attach themselves to the runway to the north or west of their location (over south or east respectively).  This causes them to not allow being built at valid locations:
![image](https://user-images.githubusercontent.com/68219054/99879196-2c88ea00-2bd9-11eb-8e28-c8eebeb6bd16.png)

**Comment by TacisLexica** [comment]
It might be easier to declare different-height bomber pads to be valid placement, since bombers sink into the pads rather than moving over the surface to access the runway.

Hopefully it would be simpler to check, anyway.
