### ISSUE TITLE
[Bug.Minor] Height indicators for terraforming to 6 and 9 are a bit too simillar

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#287]
![image](https://user-images.githubusercontent.com/40322714/99908717-3273ed80-2cf5-11eb-911b-cecd2ae841c8.png)
![image](https://user-images.githubusercontent.com/40322714/99908723-3738a180-2cf5-11eb-9cb4-545cc4895208.png)

Short of a small hue change (which might not even be visible if the indicators are under creeper), there is very little way to distinguish between terraforming to 6 and 9

![image](https://user-images.githubusercontent.com/40322714/99908746-4b7c9e80-2cf5-11eb-8065-84e703cf6b19.png)

**Comment by knucracker** [comment]
Added lines under 6 and 9
