### ISSUE TITLE
[Suggestion]  Add unit build limits  to units menu

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#292]
Please consider adding a feature where map makers can  specify build limits to the number of each unit that can be built.  This can be done by not only having a check box, but also a number field on the build menu. 

It would be beneficial  if 4RPL had an API to interact with this so a pick-up could alter the limit.

**Comment by knucracker** [comment]
Added build limits for all built in units. Also dynamically add game menu entries to limit any custom unit that is added the the player build bar.
