### ISSUE TITLE
[Bug] Previously mentioned '0 setting' on skimmers bug now broken differently.

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#293]
The game no longer crashes on hovering over the units with a 0 setting, however as soon as you unpause the game (e.g. to test) it crashes for some reason anyway. Map and log attached: all you should need to do is unpause.
[Crash Folder.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5580431/Crash.Folder.zip)

**Comment by knucracker** [comment]
The doors on the skimmer factory were doing a divide by zero when calculating when to open, when the interval was 0. Fixing this and doing a 5.1 build.
