### ISSUE TITLE
[Bug] Diagonal pieces of disconnected land are rendered differently in a Dark Tower's influence

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#295]
**Screenshots**
![image](https://user-images.githubusercontent.com/26010895/99921040-e456ee00-2ce4-11eb-81eb-d76b2d43517d.png)
![image](https://user-images.githubusercontent.com/26010895/99921074-241dd580-2ce5-11eb-8ca9-2a04f5ebc124.png)

**Describe the bug**
See screenshots above; one set of diagonal lines(from top left to bottom right) works just fine. The other set, however, disconnects the wall effect when entering the dark tower's range. The second image is symmetrically centered on the dark tower.

**Additional Context**
This does not impact creeper flow; just a rendering error.

**Comment by Alophox** [comment]
This should really be labeled as a minor bug, forgot to change it as I was writing it

**Comment by Karsten75** [comment]
Do you have a save file that this is replicated on? Please attach it to this issue.

**Comment by Regallion** [comment]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5583008/save.zip)
![Uploading image.png…]()

**Comment by Alophox** [comment]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5585229/save.zip)
interestingly enough, nullifying or using beacons to clear the influence renders it back to normal
