### ISSUE TITLE
[Bug.Minor] Error message clips out of the box

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#296]
![image](https://user-images.githubusercontent.com/40322714/99934866-4f99d200-2d70-11eb-87ca-fb66e5c08dda.png)

**Comment by Karsten75** [comment]
There seems to be no documented negative consequences to this issue.  The message is legible, it leaves no residue after the pane is closed, etc. I'm tempted to close it or put it in a place where it will only get looked at once that pane has to be worked on.  WIll leave it to knucracker's discretion, though.

**Comment by Karsten75** [comment]
Seems it got fixed, or it is dependent on resolution?

![image](https://user-images.githubusercontent.com/22965021/200390562-69f7fdb1-4254-43b8-8ac2-c1720a50d032.png)
