### ISSUE TITLE
[Bug] Editor window does not handle dots in folder names correctly.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#297]
1. Create a map with a dot in it's name. (example attached). This is allowed.
2. You can edit it normally. Finalize it.
3. Try to play the finalized map. You can't.

Relevant log output:
Load file doesn't exist: C:\Users\USER\Documents/My Games/creeperworld4/finalized/Eggstravaganza 1.1/Eggstravaganza 1.cw4

[Eggstravaganza 1.1.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5581359/Eggstravaganza.1.1.zip)

**Comment by knucracker** [comment]
The game now disallows map names with periods.
