### ISSUE TITLE
[Bug.Minor] Factory is unduly prioritized

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#299]
When the smart prio system was implemented, factory was prioritized below towers but above miners.
However, if you turn off both smart prio checks, it remains prioritized, which can occasionally cause problems.
It should either be it's own checkbox, or be tied to one of the other prios.

**Comment by Karsten75** [comment]
When you say "can occasionally cause problems" please provide the case (and if possible) a saved map that demonstrate this scenario.

**Comment by Regallion** [comment]
The specific scenario was putting a factory as one of the units to build out evenly and getting a surprise when it got prioritized despite the checks being off.
It's not a big deal, but it's a bit odd that unlike the other 2 priorities, this one is hard-enabled.
