### ISSUE TITLE
[Suggestion] Move or point out Factory button better.

### ISSUE THREAD

**Issue by TheDuke1984** [KnuckleCracker/CW4-bug-tracker#3]
Was directed on your discord to make this suggestion/bug report here. 

I initially thought it was a bug, in the mission "ruins repurposed", when the game prompts you to build a factory, I was looking in the build-toolbar going "where's the damn factory, I can't see it!". Only after taking my time to review the UI did I see that the build-factory icon was **next** to the build bar rather than in it, and with everything else going on it didn't "stand out" to me like it probably should have. 

So, suggestion, when the game prompts to build the factory for the first time (since the campaign kind of acts as a tutorial) highlight the factory icon in the same way that the game first highlights "pause" etc? (IE - big yellow line + highlight)

Oh and, I'm loving CW4 so far, keen as beans. After following your development on YT for so long it's nice to be able to play the demo. 

Kind Regards, 
Me

**Comment by knucracker** [comment]
The ERN Portal and factory buttons may get a bit of a re-org.  Adding to "Probably" column for now.

**Comment by grabz-dev** [comment]
I agree, it's very easy to forget about the factory and the game becomes very confusing if you do.
