### ISSUE TITLE
The icon for survive 

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#30]
I think, the Icon for survive should get a thicker outline, right now it looks a bit like inactive
![image](https://user-images.githubusercontent.com/16858356/93671888-fdee7600-faa6-11ea-9dca-1c29e9a4a553.png)
Just my 2ct - I might be the only one with this association!

**Comment by knucracker** [comment]
Fixed previously, but just now getting around to marking it
