### ISSUE TITLE
[Bug] Delegate starts the map in "Ready to charge" state

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#300]
1. Create a map.
2. Place delegate on it.
3. Unpause.
4. Delegate will begin charging and fire.

This can be unfortunate if a map has a long delay before any creeper is produced.

Probably delegate should not fire if no cells were actually reclaimed.

**Comment by knucracker** [comment]
Changed so that the delegate will only start charging if peakCreeper is greater than 0. So on a map that has never seen creeper, the reclaim objective will not fire.
