### ISSUE TITLE
[Bug] Delegate freezes and bugs out if you load during the firing animation

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#301]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5583673/save.zip)
]
1. Make it so the delegate starts firing it's beam
2. Save.
3. Load
4. Delegate is now stuck and will forever play it's charging sound without ever triggering the objective
![image](https://user-images.githubusercontent.com/40322714/99974972-afb16800-2db2-11eb-98a7-96479c7a2106.png)

**Comment by knucracker** [comment]
The beam wasn't being recreated on load of the delegate
