### ISSUE TITLE
[Performance] Very long save time

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#302]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5584395/output_log.txt)
[auto.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5584400/auto.zip)

The save file is unexpectedly big and takes a while to save despite the map having no 4RPL

**Comment by knucracker** [comment]
It looks like it took about 2.5 seconds according the the log file (for each save). The auto.zip file you attached contains the cw4rec file. If you could attach the save.cw4 file, I could probably figure out why the save file is large.

**Comment by Regallion** [comment]
Okay, so the thing is:
[Weirdos.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5584577/Weirdos.zip)
This archive contains the pair of save files.
I believe the saving is so long exactly due to cwrec file being ENORMOUS.

**Comment by Karsten75** [comment]
The size of the save file is governed by the activity (creeper, units and enemy movement). As such, lots of activity over extended periods of time May cause large recorder files that will impact save times as well as potentially disk and memory usage. 

After release, re-evaluate if some options to turn off or limit saving the recorder file (or even creating the recording data) would be beneficial for constrained machines and or users preferring not to have the recordings available. 

Also consider a quic-save that does NOT write out the data during save.

**Comment by Karsten75** [comment]
I am under the impression that the recorder save space usage is to come under revision soon. So I'm just moving this back to eval for you to decide. There may well be another issue on it?

**Comment by Karsten75** [comment]
I believe the is now a cut-off for the Recorder in game. If not, not going to happen anyway.
