### ISSUE TITLE
[Bug.Minor] Info -> Game Interface is cutoff

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#303]
![gameInterface](https://user-images.githubusercontent.com/72889843/99990485-dacf9380-2d81-11eb-987d-9fc1d8ff0438.PNG)

Text is a bit too long to fit here; 'of the same or different type.' is missing from the end of the visible text.

Changing the UI Scale (even to minimum) still results in missing the word 'type.'

Since this might be dependent on resolution, here are my settings:
![resolution](https://user-images.githubusercontent.com/72889843/99991081-95f82c80-2d82-11eb-9e81-19f37b7034c5.PNG)

**Comment by knucracker** [comment]
Fixed
