### ISSUE TITLE
[Suggestion] Free Camera and Esc interaction

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#304]
If you Shift-F to enter 'Free View Camera' (suppose on accident) and you don't know the Shift-F or Shift-R to get out of that mode, you will not have a cursor to be able to recover.

I am thinking it makes sense in all cases to allow Esc to do a 'Shift-R' (or maybe even a Shift-F) for you while opening the menu.

**Comment by knucracker** [comment]
This is a good idea. When people get stuck they reach for the ESC key.
I've made it so that pressing esc  (or whatever the cancel key is bound to) will exit free view if in free view. Other wise, it brings up the game menu.
