### ISSUE TITLE
[Bug] AC bomber can bomb nothing on occasion

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#305]
![image](https://user-images.githubusercontent.com/40322714/99993103-43d9fa00-2dc8-11eb-9d7b-02a4409c7709.png)
[Badbombers.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5584597/Badbombers.zip)

AC bombers are bombing outside the map doing exactly nothing useful

**Comment by Karsten75** [comment]
Seems to be easily corrected user error.

**Comment by Karsten75** [comment]
![image](https://user-images.githubusercontent.com/22965021/99994289-6c3d0680-2d7e-11eb-8da6-d81594d4745a.png)

**Comment by Karsten75** [comment]
Reopening. If the trajectory of the bomb tracks outside map boundaries, then the AC/explosion will happen on map boundary.

**Comment by knucracker** [comment]
I made two changes.
- I make sure AC bombs don't move outside the map bounds. They will clamp to  be within the map. Not realistic, but better for gameplay.
- I made sure that an AC bomb that somehow finds itself outside of the map will clamp the coordinates that it deposits AC on. So the AC will not be lost.
