### ISSUE TITLE
[Bug] Crazonium 'Enable AC Blocking' doesn't allow AC through when disabled and creeper is on the other side

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#306]
[crazytest.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5585190/crazytest.zip)

See attached save file.

Basically, Crazonium's 'Enabled AC Blocking' functionality (when disabled) doesn't work when creeper is on one side of the crazonium.

Deleting the creeper allows the AC to pass through. 

Also, Cannons cannot shoot through Crazonium (which is a difference from walls - but that could be intended(?)).

**Comment by Karsten75** [comment]
this appears to be partially related to what I observed on that map you showed me yesterday. Until I had mortars fire over the wall, the AC building up inside the enclosed space did not seem to flow out. 

Bith the above as well as the fact that cannons' LoS are blocked could be intended. Especially the blocked LoS.

**Comment by cornucanis** [comment]
On the subject of Crazonium, there is a similar and possibly related bug you may experience if you disable it using the standard unit UI options. If the Crazonium is disabled while in contact with creeper, it will become permeable for the creeper. Further, if you re-enable the Crazonium afterwards, it will still remain permeable to the creeper. There seems to be no apparent way to revert it to its impervious state once you've disabled it at least once while in contact with creeper.

**Comment by knucracker** [comment]
- Removed ability to disable/disarm Walls and Crazonium.
- Fixed issue where crazonium was not blocking LOS when AC flow was turned on.
- Made it so crazonium only blocks paths. Weapons can fire through crazonium.
- Added a game option to specify the wall decay rate. Default is 500. Set to 0 makes immortal walls.
- 'Enable AC flow' remains unchanged. AC flow is only allowed when the wall/crazonium is not under attack (in contact with) Creeper.
