### ISSUE TITLE
[Bug] Farsite Colonies does not remember page number

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#307]
Scroll to any but the first page of Farsite Colonies. Select a map, , click to play and exit back to Farsite Colonies.  

Player is now again on page 1.  It is expected that the player will remain on the page where they left off.

**Comment by knucracker** [comment]
I've implemented some logic to remember the map number when you launch a colony mission. Upon return to the  main menu the game will attempt to find what page that map is on and then navigate to that page.
