### ISSUE TITLE
The overseer shouldn't show it's health

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#31]
Pretty much the headline: When you select the overseer, it shows a health of 1.0/1 - imho, there shouldn't be health unless the unit can be damaged

**Comment by Karsten75** [comment]
I checked, and it is correct. The Overseet does in fact have a health of 1. While there are no game-standard units to damage the overseer, it is possible that it can be health-damaged via a 4RPL unit and that the Reclaim victory can become "lost" or unobtainable that way.
