### ISSUE TITLE
[Bug.Minor] No-spore towers have an incorrect minimap tooltip

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#310]
![image](https://user-images.githubusercontent.com/40322714/100112181-fcaf4000-2e7f-11eb-9157-3b9ecf7f459f.png)
![image](https://user-images.githubusercontent.com/40322714/100112063-df7a7180-2e7f-11eb-9cbc-f84e5dd31cf4.png)

**Comment by Karsten75** [comment]
There is no display anywhere on Spore Tower's egg launching activity (or even if they do launch eggs) .

**Comment by knucracker** [comment]
Fixed. This issue of how to show eggs I'll leave for another topic.
