### ISSUE TITLE
[Bug] Terps do not carry on ERN unburying if a terp is destroyed mid-process

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#311]
1. Bury an ERN
2. Place 2 full-ammo terps next to it.
3. Let one terp start digging it up.
4. Delete that terp.
Bug: the second terp will not take over the unburying process.

Save-load fixes it, so no save.

Screenshot:
![image](https://user-images.githubusercontent.com/40322714/100116100-67627a80-2e84-11eb-9836-c8e8466ba2bd.png)

**Comment by Regallion** [comment]
No further terps, newly-built or not would take over the process either by the way, the only way out is save-load.

**Comment by knucracker** [comment]
Looks like the terp drone was not clearing its state on the ern when the drone was destroyed. So other terps thought the ern was still being excavated.
