### ISSUE TITLE
[Suggestion] Player selected creeper colours

### ISSUE THREAD

**Issue by Sorrontis** [KnuckleCracker/CW4-bug-tracker#312]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would love to be able to set the 3 colours of creeper (creeper, anticreeper, reinforced creeper) similar to what was done in CW2 and CW3. I love to have black creeper. Feels .... more ominous. 

**Describe alternatives you've considered**
I did not.

**Additional context**
N/A

**Comment by Karsten75** [comment]
As a result of early design decisions and implementation restrictions, it's regrettably not feasible to implement custom creeper colors in this version of Creeper World.
