### ISSUE TITLE
[Bug.Minor] If a totem objective is ever achieved on a map, the totems laser animation can never play again

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#313]
[Testground.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5592584/Testground.zip)

1. Create a map.
2. Add a totem to it.
3. Achieve totem objective.
4. Reset game data.
5. Unpause - the totem will re-achieve the objective immediately with no laser.
6. Reset game date.
7. Add another totem.
8. When that totem finishes, the purple thingie will pop, but not the lasers.

Finalizing does NOT solve this.

**Comment by knucracker** [comment]
In the Clean Map function the game will now go through totems and reset all of their internal state back to 'brand new'.
