### ISSUE TITLE
[Bug] Rift lab is immune to dark tower effects

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#314]
[Testground.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5592597/Testground.zip)
![image](https://user-images.githubusercontent.com/40322714/100148669-1c5d5d00-2eae-11eb-8127-6e7eba1043cc.png)

Rift lab is completely immune to dark towers. it can land in their effect, it can materialize in their effect, it can even provide packets in their effect.

**Comment by knucracker** [comment]
Removed darkness immunity from the lab.
