### ISSUE TITLE
Bricked

### ISSUE THREAD

**Issue by afallingmoose** [KnuckleCracker/CW4-bug-tracker#317]
Not actually sure if this is a bug or a performance issue but I am on the 4th (or 5th...?) world where you first start producing Bluite and the totems create the drones with AC packets in them. My computer at complete random, will brick up. No keyboard or mouse input can be made. The game still runs seemingly fine on the screen but I can’t do anything with my PC entirely. Ctrl Alt Del doesn’t work. Windows key neither. The mouse will not respond. This is the third forced PC reboot I’ve had to do and only on this level specifically. I don’t really have other info to give unfortunately. Hope this gets looked into. <3

**Comment by afallingmoose** [comment]
Update: changed the settings to max performance and changed from fullscreen to Windowed. The issue still persists.

**Comment by afallingmoose** [comment]
Update/edit: I was able to plow through the 5th mission and upon entering the next one, the reoccurrence that I mentioned in the last update happened. It is not a map specific or performance specific issue.

**Comment by Regallion** [comment]
in your C:\Users\YOURUSERNAMEHERE\AppData\LocalLow\Knuckle Cracker\Creeper World 4 there should be a file known as output_log
Paste it here right after you experience this issue.
Do not re-launch the game before you do, as doing so will wipe the contents.

**Comment by Karsten75** [comment]
The issue seems to be  low-level problem with your computer. If the game crashes, we get a dump file at Unity, because the OS is still around to make and send that to us. If it crashes at a lower level, then it is not something in the game that can be fixed.

If there is an event in the Windows Event Viewer, then  that may lead you (and us) to some clue as to what might have gone wrong. 

if it was a game issue, the symptoms would be different. The game can't lock up the computer in a way that kills the mouse, keyboard or other hardware.   The game is a user-mode application, Only lower level drivers and/or the Operating System can lock up a machine in the manner you describe. 

if your drivers are good and current, then I would suspect that you have perhaps a lataent problem that manifests itself once your machine takes on a significant workload. To validate this hypothesie, use some of the stress test tools from this article and see of your machine handles them well. 

https://techguided.com/best-tools-to-stress-test-p-cpu-ram-gpu/

**Comment by afallingmoose** [comment]
I’m quite confident that my PC is capable of handling this game. I play games like Arma 3 and Minecraft on highest settings (Lol). I have never encountered an issue like this. And I also went into the game files and there is no Crash Dump or anything. I couldn’t locate the “output_log” file either. I guess it never counted as the game crashing...? Either way. I’m currently trying to run the game with task manager on windowed. Im pretty certain it is some kind of hardware conflict. Will post results in a moment.

**Comment by afallingmoose** [comment]
apologies. I found the output log. Here we go.

Initialize engine version: 2018.4.27f1 (4e283b7d3f88)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 960 (ID=0x1401)
    Vendor:   
    VRAM:     4053 MB
    Driver:   26.21.14.4587
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 43.784400 ms
--InitGame.Init--
Game Version = DEMO 2 (PreBeta 11.0)
Unity Version = 2018.4.27f1
Command Line = [C:\Program Files (x86)\Steam\steamapps\common\Creeper World 4 Demo\CW4.exe]
Time Since Game Start = [1.343]
----------------------------------------------------------------------------------------------
OS = Windows 10  (10.0.0) 64bit
System Memory = 16295
MP4 Supported = true
----------------------------------------------------------------------------------------------
Processor Type = AMD Ryzen 7 2700X Eight-Core Processor 
Processor Count = 16
Processor Frequency = 3693
----------------------------------------------------------------------------------------------
Graphic Device Name = NVIDIA GeForce GTX 960
Graphic Device Version = Direct3D 11.0 [level 11.1]
Graphic Memory Size = 4053
Graphic Shader Level = 50
----------------------------------------------------------------------------------------------
Game Dimensions = 1920 x 1080
Resolution = 1920 x 1080 @ 60Hz
Displays = Display (0) Sys=[1920 x 1080] Rend=[1920 x 1080] ACTIVE  
DPI = 96
UI Scale = 1
Target Frame Rate = 30
----------------------------------------------------------------------------------------------
Settings: AA = 1
Settings: FPS = 1
Settings: SHADOWS = False
Settings: BLOOM = False
Settings: TERRAIN = False
----------------------------------------------------------------------------------------------
Device Type = Desktop
Language = English
Supports Audio = True
----------------------------------------------------------------------------------------------
Max Texture Size = 16384
Max Cubemap Texture Size = 16384
Support Shadow = True
NPOT Support = Full
Support Render TargetCount = 8
Support 3D Texture = True
Support Compute Shader = True
Graphics Multithreaded = False
Supported Render Target Count = 8
Supports 2D Array Textures = True
Supports 32 bit Index Buffer = True
Supports Image effects = True
Supports GPU Draw Call Instancing = True
Uses Reversed Z Buffer = True
Supports Sparse Textures = True
Quality Level = 3
Gen = True [Can Confirm: False]

--GameLoad.Awake--
Checking Steam...
Steam is Running.
***SteamManager Awake***
Steam User ID: 76561198038936083
Setting up 8 worker threads for Enlighten.
  Thread -> id: 44e0 -> priority: 1 
  Thread -> id: 5754 -> priority: 1 
  Thread -> id: 3428 -> priority: 1 
  Thread -> id: 5290 -> priority: 1 
  Thread -> id: 37a0 -> priority: 1 
  Thread -> id: 4eb8 -> priority: 1 
  Thread -> id: 2a50 -> priority: 1 
  Thread -> id: 57e4 -> priority: 1 
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 48.629300 ms
--InitGame.Init--
Checking Steam...
Steam is Running.
SteamStatsAndAchievements Enabled for AppID: 1293770
Steam User ID: 76561198038936083

Unloading 11 unused Assets to reduce memory usage. Loaded Objects now: 26376.
Total: 120.319600 ms (FindLiveObjects: 1.290900 ms CreateObjectMapping: 0.476200 ms MarkObjects: 118.479600 ms  DeleteObjects: 0.072300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Received stats and achievements from Steam

SteamAchievement: 1st Nullification Objective = True
SteamAchievement: 1st Totem Objective = True
SteamAchievement: 1st Reclaim Objective = False
SteamAchievement: 1st Hold Objective = False
SteamAchievement: 1st Collect Objective = True
SteamAchievement: Parallel Universe = False
SteamAchievement: Farsite Farside = True
SteamAchievement: 21 Gun Salute = False
STEAM STATS
------------------------------------------------------------
SteamStat: STAT_STORYMISSIONSCOMPLETED = 0
------------------------------------------------------------
Storing Steam Stats

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 26378.
Total: 72.518000 ms (FindLiveObjects: 1.285900 ms CreateObjectMapping: 0.536200 ms MarkObjects: 70.670800 ms  DeleteObjects: 0.024800 ms)

StoreStats - success

**Comment by afallingmoose** [comment]
I have just ensured my drivers were up to date. There was an update earlier this month that didn't auto-install. I'll play in a moment and see if I get another computer crash.

**Comment by afallingmoose** [comment]
The issue happened again. That missing driver update wasn’t the issue...

**Comment by afallingmoose** [comment]
So. I decided to leave the game running even after my PC bricked up to watch my task manager. It appears that my HDD is capped at 100% usage and is not fluctuating at all. Note: it is the same drive that has my OS on it. I am going to reboot and move the game to my secondary Hard Drive and try again.

**Comment by afallingmoose** [comment]
Another red herring... I moved the game to an SSD and it’s the same deal.

**Comment by Karsten75** [comment]
Thank you for the log file (as an aside) you can drag and drop the file here, it makes it easier to download. 

In the log file there is absolutely no indication of an error. 

I suggest you look at Event Viewer  and see if that leads you (and us) closer to a cause. 

If you don't know how to read event viewer, Open it, select "save all events" and drop the resulting .evtx file in here and I'll see if I can figure something out.

**Comment by Karsten75** [comment]
I want to reiterate our position on crashes  or freezes that are "global" and locks up your mouse/keyboard, etc. 

These types of crashes are not related to CW4, they are merely exposed by the game. CW4 is a user mode application and has no ability to lock out your mouse and/or keyboard or cause your computer to freeze. If the game, or a script in a map in the game is in a hard loop, you should be able to use Task manager to cancel the game, or Windows may notify you that the application has become unresponsive and give you an option to cancel.

**Comment by afallingmoose** [comment]
Tonight or tomorrow I will be getting together with a friend of mine that is a computer engineer. He is suspecting an issue with how the game is accessing the RAM. Before then, I’ll try using Event Viewer to get more info.

**Comment by afallingmoose** [comment]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5606433/output_log.txt)

**Comment by afallingmoose** [comment]
Look at this Output Log. This one is massively different than the last. This crash around I replayed all of the previous missions. Taking an extra 15 minutes or so on each level than I needed to. But I couldn't replicate a crash until the same world I first encountered the crash (5th world). I even made massive cobwebs of collectors and weapons on those previous maps to try breaking it. It still only seems to break my PC on the 5th and 6th world. I did also have event running and I did not get any kind of meaningful error messages it looks like... Log Name:      Application
Source:        ESENT
Date:          11/27/2020 2:01:51 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Catalog Database (4920,R,98) Catalog Database: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:51.0152163Z" />
    <EventRecordID>10281</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Catalog Database</Data>
    <Data>4920,R,98</Data>
    <Data>Catalog Database: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 2:01:50 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Catalog Database (4920,R,98) Catalog Database: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:50.5776889Z" />
    <EventRecordID>10280</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Catalog Database</Data>
    <Data>4920,R,98</Data>
    <Data>Catalog Database: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 2:01:50 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Catalog Database (4920,R,98) Catalog Database: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:50.2182907Z" />
    <EventRecordID>10279</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Catalog Database</Data>
    <Data>4920,R,98</Data>
    <Data>Catalog Database: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      System
Source:        Service Control Manager
Date:          11/27/2020 2:01:49 AM
Event ID:      7000
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
The GuvyQuietTe service failed to start due to the following error: 
Access is denied.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:49.5776225Z" />
    <EventRecordID>7576</EventRecordID>
    <Correlation />
    <Execution ProcessID="864" ThreadID="4784" />
    <Channel>System</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">GuvyQuietTe</Data>
    <Data Name="param2">%%5</Data>
    <Binary>470075007600790051007500690065007400540065000000</Binary>
  </EventData>
</Event>

Log Name:      Security
Source:        Microsoft-Windows-Eventlog
Date:          11/27/2020 2:01:39 AM
Event ID:      1101
Task Category: Event processing
Level:         Error
Keywords:      Audit Success
User:          N/A
Computer:      Ingram-PC
Description:
Audit events have been dropped by the transport.  0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Eventlog" Guid="{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}" />
    <EventID>1101</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4020000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:39.2175588Z" />
    <EventRecordID>355321</EventRecordID>
    <Correlation />
    <Execution ProcessID="1084" ThreadID="2788" />
    <Channel>Security</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <UserData>
    <AuditEventsDropped xmlns="http://manifests.microsoft.com/win/2004/08/windows/eventlog">
      <Reason>0</Reason>
    </AuditEventsDropped>
  </UserData>
</Event>

Log Name:      System
Source:        Microsoft-Windows-Kernel-Power
Date:          11/27/2020 2:01:10 AM
Event ID:      41
Task Category: (63)
Level:         Critical
Keywords:      (70368744177664),(2)
User:          SYSTEM
Computer:      Ingram-PC
Description:
The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" />
    <EventID>41</EventID>
    <Version>8</Version>
    <Level>1</Level>
    <Task>63</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000400000000002</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:10.6480514Z" />
    <EventRecordID>7538</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="8" />
    <Channel>System</Channel>
    <Computer>Ingram-PC</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="BugcheckCode">0</Data>
    <Data Name="BugcheckParameter1">0x0</Data>
    <Data Name="BugcheckParameter2">0x0</Data>
    <Data Name="BugcheckParameter3">0x0</Data>
    <Data Name="BugcheckParameter4">0x0</Data>
    <Data Name="SleepInProgress">0</Data>
    <Data Name="PowerButtonTimestamp">0</Data>
    <Data Name="BootAppStatus">0</Data>
    <Data Name="Checkpoint">0</Data>
    <Data Name="ConnectedStandbyInProgress">false</Data>
    <Data Name="SystemSleepTransitionsToOn">0</Data>
    <Data Name="CsEntryScenarioInstanceId">0</Data>
    <Data Name="BugcheckInfoFromEFI">false</Data>
    <Data Name="CheckpointStatus">0</Data>
    <Data Name="CsEntryScenarioInstanceIdV2">0</Data>
    <Data Name="LongPowerButtonPressDetected">false</Data>
  </EventData>
</Event>

Log Name:      System
Source:        EventLog
Date:          11/27/2020 2:01:37 AM
Event ID:      6008
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
The previous system shutdown at 1:29:10 AM on ‎11/‎27/‎2020 was unexpected.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="EventLog" />
    <EventID Qualifiers="32768">6008</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T07:01:37.0299141Z" />
    <EventRecordID>7513</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>System</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1:29:10 AM</Data>
    <Data>‎11/‎27/‎2020</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>2473</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Binary>E4070B0005001B0001001D000A005600E4070B0005001B0006001D000A005600600900003C000000010000006009000001000000B00400000000000000000000</Binary>
  </EventData>
</Event>

Log Name:      System
Source:        Microsoft-Windows-DNS-Client
Date:          11/27/2020 1:34:47 AM
Event ID:      1014
Task Category: (1014)
Level:         Warning
Keywords:      (268435456)
User:          NETWORK SERVICE
Computer:      Ingram-PC
Description:
Name resolution for the name mobile.pipe.aria.microsoft.com timed out after none of the configured DNS servers responded.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DNS-Client" Guid="{1c95126e-7eea-49a9-a3fe-a378b03ddb4d}" />
    <EventID>1014</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1014</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000010000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:34:47.0145522Z" />
    <EventRecordID>7511</EventRecordID>
    <Correlation />
    <Execution ProcessID="3092" ThreadID="3904" />
    <Channel>System</Channel>
    <Computer>Ingram-PC</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="QueryName">mobile.pipe.aria.microsoft.com</Data>
    <Data Name="AddressLength">128</Data>
    <Data Name="Address">1700000000000000260017001B212EE000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 1:24:20 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Video.UI (17704,D,2) {31241EE1-D622-45C6-A089-B92F527A3A4B}: The database format feature version 9080 (0x2378) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:24:20.9904304Z" />
    <EventRecordID>10267</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Video.UI</Data>
    <Data>17704,D,2</Data>
    <Data>{31241EE1-D622-45C6-A089-B92F527A3A4B}: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9080 (0x2378)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 1:24:20 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Video.UI (17704,D,2) {31241EE1-D622-45C6-A089-B92F527A3A4B}: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:24:20.9899295Z" />
    <EventRecordID>10266</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Video.UI</Data>
    <Data>17704,D,2</Data>
    <Data>{31241EE1-D622-45C6-A089-B92F527A3A4B}: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 1:24:20 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Video.UI (17704,D,12) {31241EE1-D622-45C6-A089-B92F527A3A4B}: The database format feature version 9080 (0x2378) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:24:20.9869291Z" />
    <EventRecordID>10264</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Video.UI</Data>
    <Data>17704,D,12</Data>
    <Data>{31241EE1-D622-45C6-A089-B92F527A3A4B}: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9080 (0x2378)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 1:24:20 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Video.UI (17704,D,50) {31241EE1-D622-45C6-A089-B92F527A3A4B}: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:24:20.5871685Z" />
    <EventRecordID>10260</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Video.UI</Data>
    <Data>17704,D,50</Data>
    <Data>{31241EE1-D622-45C6-A089-B92F527A3A4B}: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        ESENT
Date:          11/27/2020 1:24:20 AM
Event ID:      642
Task Category: General
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      Ingram-PC
Description:
Video.UI (17704,R,98) {31241EE1-D622-45C6-A089-B92F527A3A4B}: The database format feature version 9180 (0x23dc) could not be used due to the current database format 1568.20.0, controlled by the parameter 0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat).
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ESENT" />
    <EventID Qualifiers="0">642</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:24:20.4743201Z" />
    <EventRecordID>10255</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Ingram-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Video.UI</Data>
    <Data>17704,R,98</Data>
    <Data>{31241EE1-D622-45C6-A089-B92F527A3A4B}: </Data>
    <Data>0x410022D8 (8920 | JET_efvAllowHigherPersistedFormat)</Data>
    <Data>9180 (0x23dc)</Data>
    <Data>1568.20.0</Data>
  </EventData>
</Event>

Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          11/27/2020 1:06:29 AM
Event ID:      10016
Task Category: None
Level:         Warning
Keywords:      Classic
User:          Ingram-PC\Ingram
Computer:      Ingram-PC
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user Ingram-PC\Ingram SID (S-1-5-21-4290657127-3849306569-4210832976-1000) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2020-11-27T06:06:29.1441749Z" />
    <EventRecordID>7508</EventRecordID>
    <Correlation ActivityID="{92494eae-73d7-41cc-ab94-3b1ed6e7fa9c}" />
    <Execution ProcessID="1348" ThreadID="5352" />
    <Channel>System</Channel>
    <Computer>Ingram-PC</Computer>
    <Security UserID="S-1-5-21-4290657127-3849306569-4210832976-1000" />
  </System>
  <EventData>
    <Data Name="param1">application-specific</Data>
    <Data Name="param2">Local</Data>
    <Data Name="param3">Activation</Data>
    <Data Name="param4">{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}</Data>
    <Data Name="param5">{15C20B67-12E7-4BB6-92BB-7AFF07997402}</Data>
    <Data Name="param6">Ingram-PC</Data>
    <Data Name="param7">Ingram</Data>
    <Data Name="param8">S-1-5-21-4290657127-3849306569-4210832976-1000</Data>
    <Data Name="param9">LocalHost (Using LRPC)</Data>
    <Data Name="param10">Unavailable</Data>
    <Data Name="param11">Unavailable</Data>
  </EventData>
</Event>

**Comment by afallingmoose** [comment]
Look at this Output Log. This one is massively different than the last. This crash around I replayed all of the previous missions. Taking an extra 15 minutes or so on each level than I needed to. But I couldn't replicate a crash until the same world I first encountered the crash (5th world). I even made massive cobwebs of collectors and weapons on those previous maps to try breaking it. It still only seems to break my PC on the 5th and 6th world. I did also have event running and I did not get any kind of meaningful error messages it looks like...

**Comment by afallingmoose** [comment]
[events 2.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5606584/events.2.txt)

**Comment by afallingmoose** [comment]
That above is the event viewer. The forced system shutdown was reported at 2:01:37 AM and in the report, it states the shut down was at 1:29:10 AM.

**Comment by Karsten75** [comment]
I typed up a lot of stuff and then pressed the wrong keys - lost it all :( 

There is nothing amiss in the log file. It should the normal events we expect when people playing the game, including occasional garbage collection. 

For me to process the Event Viewer, you  need to save as and choose a .evtx format. (you will most likly have to put the file in a zipped folder to upload it here. 

We welcome any advice your computer engineer friend can provide. We don't directly access RAM, it's all done through C# that Unity translates into C++ through their IL2CPP compiler. It's pretty standard, and works the same on the literally tens of thousands of computers that have already played the demo. 

We have a number of years of experience with crashes in this and previous games and know that the types of errors you report are usually when the game stresses components of a user's computer and exposes a latent fault - sometimes drivers, sometimes hardware, sometimes cooling/overheating, or any one of a number of other causes -  but it's not the game.

**Comment by afallingmoose** [comment]
[events.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5606665/events.zip)

**Comment by afallingmoose** [comment]
My friend looked at this events. He is thinking the whole OS is having issues with the latest Windows Update. After we solve Error 642 I'll come back and see if the crash persists.

**Comment by afallingmoose** [comment]
I do realize it isn't specifically the game's fault. I have been following the development for a very long time. Big fan of the series and pride myself in playing the first one when it came out back on Flash games. No offense, but I did fully expected to encounter some issues and bugs coming into this beta.  I just wasn't expecting this kind of issue at all lol. I truthfully want this game to do well.
