### ISSUE TITLE
[Bug] Platforms do not check if terrain is created under them. 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#318]
Thanks to Regallion we find that platforms placed legitimately in void will tolerate terrain appearing under them. 

Platforms should perhaps check occasionally if there is terrain under them and self-destruct (taking all the units on the with them into unit-heaven) when they find that terrain has magically appeared under them (as may be possible in some scenarios). 

images courtesy of Regallion 

![image](https://user-images.githubusercontent.com/22965021/100213450-3e69d600-2ed4-11eb-89bb-88e0344ffd07.png)

![image](https://user-images.githubusercontent.com/22965021/100213481-49bd0180-2ed4-11eb-9575-4e0341675113.png)

**Comment by knucracker** [comment]
Fixed
