### ISSUE TITLE
[Bug] Negative 'off' timer

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#320]
Setting Creeper Breeder to -100 (or possibly -ve whatever the 'on' is) off is causes a crash.

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5602496/output_log.txt)

**Comment by Karsten75** [comment]
What were you attempting to do? Put it another way, what do you expect from setting the the value as -ve? is it some missing feature? 

A negative interval is weird.

If it was a mistake of simply entering a value in an incorrect field, that might explain it. Still should not CTD.

**Comment by knucracker** [comment]
Changed to disallow negative numbers for either duty cycle number. The problem was that (on+off)  was being used as the denominator in a fraction, this caused a divide by zero.
