### ISSUE TITLE
[Bug.Minor] Negative resource pods deny resource transport in network

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#321]
[Negpod.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5602737/Negpod.zip)

If a resource pod with a negative amount of resource is within a network and is the closest "source" of that resource to the target, no resource will be able to be dispatched.

While this possibly allows for some clever denial traps, this is likely unintended.

Negative resource pods should either not exist (same as 0), or alternatively act as resource sinks.

**Comment by Karsten75** [comment]
Map makers should take care not to go to extreme lengths to specify absurd values.

**Comment by knucracker** [comment]
Restrict the pod editor to settings a value >= 1.
