### ISSUE TITLE
[Bug.Minor] Invasion map contains a movable delegate

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#322]
Invasion - Experimental span
The delegate unit in this map is movable. This is not normal delegate behavior.

![image](https://user-images.githubusercontent.com/40322714/100351871-30fc3b00-2ffd-11eb-9427-68e87ec3d369.png)

**Comment by knucracker** [comment]
Deleted and replaced with a new delegate.
