### ISSUE TITLE
The messages on farsite change and pop up while paused

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#323]
Start Farsite,
unpause, pause again
"This looks interesting" appears on the info cache
While still paused, it is replaced by "Maybe build towers and connect to it"

Build a cannon when you can do so, even if paused "So this is how I die" pops up - confirm while still paused and a few seconds later "Prayse be the founders" (OK, time to get serious) pops up. Still paused, "Annoying but useful" pops up.

IMHO, the script should not move on while paused at all

**Comment by knucracker** [comment]
For the infocache this is mostly working as designed. The first prompt is just a "this looks interesting" thing to get the players attention. The second prompt is a more specific version of the same thing "build towers". They both do the same thing and players might pause the game while they look around trying to figure out what to do. Switching to the second message, even while paused, helps them figure that out.

For the other case, the text is mostly just banter staged over time to get the player to look at the info cache. I don't think it matters if it happens while paused or while playing. So long as it happens before the info cache is retrieved it should be ok.
