### ISSUE TITLE
No Close Confirmation does not work 

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#328]
Settings>Options>Game Options - No Close Confirmation
Even with marked checkbox, the game still asks "Return to host operation system"

**Comment by knucracker** [comment]
Looks like it was working for closing the game any any way other than pressing the "Close Game" button on the main menu. I've fixed that.

Also while I was at it, I made ESC work to exit any of the sectors. So if you are on the story, span, etc page pressing ESC will go back to the main menu.
