### ISSUE TITLE
Info cache on Hints

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#330]
The Info cache on Hints:
![image](https://user-images.githubusercontent.com/16858356/100486021-9d149700-3102-11eb-896e-0912d2dbca91.png)
"this" should be "thys" and I'm not sure if "identyfyed" should read "ydentyfyed"

**Comment by knucracker** [comment]
There were several other words that were missing the y to i conversion as well.
Words that start with "i" keep the leading "i".
