### ISSUE TITLE
[Bug.Minor] Weird movement indicator behavior when moving rift lab in darkness

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#333]
This map allows easy repro:
[It is dark.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5612733/It.is.dark.zip)

1. Have the rift lab be illuminated by a beacon.
2. Select another beacon-lit destination and liftoff
3. Move the beacon so it stops affecting the rift lab
4. Rift lab movement indicator will become red.
5. If you select the rift lab at this point it will become purple.
![image](https://user-images.githubusercontent.com/40322714/100551908-c8c78680-3294-11eb-82f5-d6eb3081d87f.png)

**Comment by Karsten75** [comment]
How is this even a bug?

**Comment by Regallion** [comment]
I don't see why it would turn red (it still completes the movement just fine AND the turning takes a couple of seconds), but then turning purple is just... no other unit does this in any normal situation. 
This is likely some kind of unintended behavior even if it's really low-priority.
