### ISSUE TITLE
[Editor] Strange dots in void

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#334]
I started with an 160x90 map, imported this pic
![DSC_8013](https://user-images.githubusercontent.com/16858356/100679978-ea963b80-3370-11eb-816d-64e2e76bc148.jpg)
with these settings:
![Zwischenablage01](https://user-images.githubusercontent.com/16858356/100680000-f681fd80-3370-11eb-8460-e1f246ed0502.jpg)
Paint something with specials slot Empty , you see nothing and then paint void over this and get this: 
![image](https://user-images.githubusercontent.com/16858356/100680095-23361500-3371-11eb-8c0e-28e8c0e7088e.png)

These dots don't have any specials, no creeper, no specials - just ugly dots
This is a save file
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5619449/save.zip)

**Comment by BilboGCL** [comment]
Wait - these dots can be removed with "delete specials"

**Comment by knucracker** [comment]
Did you have a map where you had already painted some specials, then you imported the image? If so, maybe the image import and map terrain generation doesn't clear the specials that are set.

**Comment by BilboGCL** [comment]
I tried both, re-importing the image did not clear the specials.

**Comment by Karsten75** [comment]
This is the result of painting with the "Empty" slot in Special Terrain types.  As it cuases no harm and might have interesting applications, there are no plans to make modifications to it.
