### ISSUE TITLE
[Bug.Minor] Map improperly centered in colonies preview

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#335]
![image](https://user-images.githubusercontent.com/40322714/100681724-70bc7d00-3385-11eb-928b-9f06c801298a.png)
In the preview that appears when clicking on the map, the map is improperly centered.

**Comment by e-d-u-r-a-n** [comment]
Small addition: Vertical alignment works, it is only horizontal centering that has an issue.
