### ISSUE TITLE
Theme Editor: Undo Key does not undo last theme change

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#336]
When you use the undo key combination (CTRL+Z), you do not undo the last theme editor change like the undo-button..
So these buttons 
![image](https://user-images.githubusercontent.com/16858356/100685297-63e75b80-337c-11eb-91f5-b63a017c68a3.png)
aren't triggered with the keys.

**Comment by Karsten75** [comment]
It may well be that this is a  conscious decision to allow terrain changes to be backed out/redone on either side of the application of a map theme. Will forward for evaluation, though.
