### ISSUE TITLE
[Bug.Minor] Bomber ghost indicator appears in bottom left of the map until moved

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#338]
Select a bomber and don't move your mouse. A white indicator shaped marker appears at 0,0
![image](https://user-images.githubusercontent.com/51026936/100784790-0270cc80-3410-11eb-8dc7-e133961818b0.png)
Moving the mouse erases the weird marker.

**Comment by Karsten75** [comment]
there does not seem to be an adverse impact on the game or on gameplay. The marker will appear in the correct location the very instant the mouse is moved, which is what one can expect after the unit is selected.

**Comment by knucracker** [comment]
Happened to pass by the code where this is addressed while I was looking at the unit stacking issue. So this is fixed afterall..
