### ISSUE TITLE
[bug] Walls have misleading double indicator of "Health"

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#34]
Via GoodMorning on Discord

![image](https://user-images.githubusercontent.com/22965021/93691448-e4e7c400-faaa-11ea-8709-b480df501d0a.png)
Walls show Health in two places and it is contradictory and confusing. One value is theamount of health before the unit is counted as destroyed, the other is the health of the field it raises. 

The latter should probably be changed to reduce confusion. 

Suggestions for a new mane can be

Power
Field
Force
Strength

Depending on space aailable

**Comment by knucracker** [comment]
Changed to say "Power" rather than "Health"
