### ISSUE TITLE
Skimmer Factory and Spore Towers show "0 in x seconds" if count is zero and a time is set

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#342]
When you set the count to zero for Spores or Skimmer Factory (but you set the time!), you see 
something like ![image](https://user-images.githubusercontent.com/16858356/100802160-4ae8b400-3429-11eb-9b2e-5b994156f00b.png)
Better would be "No Skimmer" or "No Spores", same as you see when the timer is set to zero.

**Comment by Regallion** [comment]
Also true from blob nests and air sac cauldrons tbh... also emitters, but why would you make a 0-creeper emitter.
