### ISSUE TITLE
[Suggestion] Spread out selected bombers' indicators in the same formation they were in previously by holding the formation move key

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#343]
**Is your feature request related to a problem? Please describe.**
Moving these guys one-by-one is very time consuming:
![image](https://user-images.githubusercontent.com/51026936/100815836-28649400-3445-11eb-9142-185e967949ac.png)

If one likes to spread out bombers for efficiency, their only option is to move the indicators one-by-one. When a map lets you have 10 runways, it gets a little daunting. The only alternate way to spread out bombers is to hold G to draw a line formation, but with so many bombers this line is way too wide.
 
**Describe the solution you'd like**
- When double clicking a bomber indicator, shorten the range of other indicators that become selected by half. I believe the game selects way too many for the purpose of this suggestion.
- When multiple bombers are selected, holding formation move (G) spreads out the bomber indicators in the same formation the selected bombers currently have, similar to how formation move does it for units. If a selected bomber doesn't have an existing indicator, put it in the center of the mouse. This also retains the line formation function, as it requires the user to click and hold the mouse and then press G, whereas my suggestion requires the user to press G while the mouse button is not held.
- This is a small side note, but perhaps shift clicking individual indicators should allow the player to select multiple bombers that way (it does not do that currently).

**Comment by Karsten75** [comment]
Bear in mind that "G" (Formation move) already spreads out bombers in a straight line. That is a useful function that I'd not like to see lost. 

Also the proposal to reduce the selection  range for units on double-click seems to focus only on this scenario and not on other, more common scenarios.

**Comment by grabz-dev** [comment]
Yes I've mentioned the line formation. It requires you click and hold the mouse while holding G. My suggestion requires holding G before the mouse is clicked. In theory, these two functions should not clash with each other. I do not wish to lose the line formation either.

> Also the proposal to reduce the selection range for units on double-click seems to focus only on this scenario and not on other, more common scenarios.

My rationale for this is that it's better for the range to be smaller than larger because you can always Shift+double click more units. If you have your bombers spread out in a larger area, it is easier to move them one-by-one than if you got a big cluster of indicators.
