### ISSUE TITLE
[Suggestion]  Allow mass-editing of units

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#344]
Currently, it is impossible to edit more than 1 unit at once.
Due to the related inability of copying a unit, it is tedious to setup multiples of a similar unit (such as blob nests or spore towers).

It would be nice if selecting multiple units in editor allowed you to change their attributes at the same time.
In this case, only the changed attributes would apply.
EX: I select 5 spore towers and edit the payload value to 200. All 5 towers should have a payload of 200, but their count, delay and targeting remain unchanged from what they were previously.

Q: Which values to show for current attributes?
A: Empty field, if it's populated that's the new value to set to.
Q: What if disparate units are selected
A: No mass editing is allowed then
Q: Should it affect custom units
A: Yes

**Comment by Karsten75** [comment]
Tab-key while pointing at a unit is supposed to copy the unit wit all attributes. This simplifies the process "to setup multiples of a similar unit (such as blob nests or spore towers)."

I am not certain that the process is fully implemented for all units and custom units, so passing this on for comment and evaluation.

**Comment by e-d-u-r-a-n** [comment]
Tab works for emitters, but no other enemy unit can be copied.
