### ISSUE TITLE
[Bug] Inconsistent save/load behavior

### ISSUE THREAD

**Issue by JasonGore** [KnuckleCracker/CW4-bug-tracker#346]
**Describe the bug**

1. Start mission from "Farsite Expedition" (I did `story4` Ruins Repurposed)
1. Save game
1. Exit Mission
1. Return to top menu
1. Load File
1. Select `farsite/story4/<save>`
1. Note that when you hit Escape and `Save/Load` that no saves appear
1. Save game again
1. Save is now stored in `misc/story4/<save>`

**Additional context**
Actually as I wrote this up I discovered that when you click on missions, you can resume saves from there. So I guess this is relatively minor bug. I just wasn't aware that I was supposed to click on the mission again to reload the game (as I didn't see any obvious load mechanism other than exiting to the top menu.)

**Comment by Regallion** [comment]
![image](https://user-images.githubusercontent.com/40322714/101090689-17905b80-35c8-11eb-8d28-031e5c2c049c.png)
![image](https://user-images.githubusercontent.com/40322714/101090770-35f65700-35c8-11eb-97db-e9bdc9c38b7f.png)

The Load file functionality is not meant for loading, but rather for playing maps from files shared to you directly.

**Comment by Karsten75** [comment]
I think this is a misunderstanding of how save/load works. I'm not sure we're going to try and document a circumvention or explanation for it.

**Comment by JasonGore** [comment]
Love the game, but I think the only thing I'd say is that it's hard to be a "misunderstanding" when there really isn't any communication or clear demarcation of how it works or how to load campaign saves.
