### ISSUE TITLE
[Bug] Buried ERN's are duplicated when looking at special angles

### ISSUE THREAD

**Issue by GamyGamer** [KnuckleCracker/CW4-bug-tracker#347]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\output_log.txt`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`
3. Screenshots help! 
  Screenshots are here

![image](https://user-images.githubusercontent.com/49346764/101089583-a647ad00-35b5-11eb-838e-9278d28550f9.png)
![image](https://user-images.githubusercontent.com/49346764/101089591-a8117080-35b5-11eb-880d-81e0377ea6cf.png)

'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

4. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 
There is a bug, that shows buried precent where it shouldn't be. To reproduce it go to this map (one of earliest colony map, use freecam, go near where is my camera on sec screenshot and do 180* turn

**Additional context**

**Comment by Regallion** [comment]
Can confirm this behavior.
Here's the same thing from a story map. Pay attention to map rotation.
![image](https://user-images.githubusercontent.com/40322714/101092113-2c6dee80-35ca-11eb-9049-265babe6c5b6.png)
![image](https://user-images.githubusercontent.com/40322714/101092155-40b1eb80-35ca-11eb-91c2-b7e287c1fa6a.png)

**Comment by Sanian-Creations** [comment]
This actually happens for ANY burried ERN. It's not just "special angles", the % text is just drawn twice. The second time it is drawn is on the opposite end of where the camera is in relation to the ERN. Whenever you look at a burried ERN, you can make a 180 turn and see the floating % text behind you. The camera acts as a mirror of sorts. 

It's a really interesting effect, since it's mirrored against the camera you can actually place ERNs all over the map and turn around to see a mirror image of the map in the sky: https://youtu.be/91KHxUG9R78

**Comment by knucracker** [comment]
The code for mapping a unit position to a screen position wasn't checking of the unit was not in the screen view. So it would end up wrapping around and showing the text indicator for an ERN so that it appears to be behind the camera.
