### ISSUE TITLE
[Bug] Placing a unit (Emitter) Outside the map boundary is possible in editor and causes time to freeze.

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#348]
To reproduce: create a custom map, go to units in editor menu and place an emitter. You can easily place the emitter initially outside the boundaries of the map. This will cause time to freeze, but will not stop the map being finalized (however it cannot be uploaded because time freezes).
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5639692/output_log.txt)

**Comment by knucracker** [comment]
The emitter was causing an array access exception when outside of the map
