### ISSUE TITLE
[Performance] Unplayably low framerates and instability when running for first time

### ISSUE THREAD

**Issue by david0mckee** [KnuckleCracker/CW4-bug-tracker#350]
When I first booted the game into full screen, I was getting unplayably low performance of about 10FPS. Alongside this, there seems to be a slight color shift of my monitor whenever when the near constant hitching happens. Occasionally, my entire monitor will black out and reappear but the windowed game will be all white. It will also frequently crash. If I disable HDR for my monitor, it wont crash as often, however, it still has an incredibly slow frame rate.

I suspect it has something to do with either my hardware or monitor, or HDR in windows. Thus, I have included my dxdiag
[DxDiag.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5640214/DxDiag.txt)

**Comment by david0mckee** [comment]
I have also tried to change the settings in game to minimum. It has had no effect

**Comment by david0mckee** [comment]
log output file
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5640272/output_log.txt)

**Comment by david0mckee** [comment]
before reinstall, here is the crash files requested.

[Crashes.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5640304/Crashes.zip)

**Comment by david0mckee** [comment]
output log for working version. It seems a reinstall has fixed low framerate issues.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5640343/output_log.txt)

**Comment by david0mckee** [comment]
output log for admin ran version
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5640353/output_log.txt)

**Comment by david0mckee** [comment]
It seems that a reinstall has fixed the low framerate issue. However, there seems to be an issue with flickering when game is in focus... It can be on screen, but only when in focus. It can be on screen with no obstructions, but not focused, and there will be no flickering. However, when in focus, there is flickering.

For reference, the monitor is a Samsung C32HG70

**Comment by Cwright15** [comment]
Seeing as how you have a 3080 card, I would assume that this is due to drivers and how new of a release it is. Can you try and roll back the driver? Also, if you're using HDMI, try DP or vice verse. Lastly, verify the integrity of game files in Steam.

These are all shots in the dark, but they are where I would start.

**Comment by Karsten75** [comment]
This game does not have driver-specific dependencies like many of the top-tier AAA games. As such we NEVER recommend rolling back drivers (unless you are running a beta-version) driver). 

The developer himself has a Nvidia 20-series card and we had a few 30-series cards in beta. We have had no reports of flickering. 

I looked at the last log file you provided and could see no errors. 

I am at a loss to explain the flickering or what you can investigate for problem determination. I'll boost this up to the developer and see if he perhaps have any suggestions.

**Comment by Karsten75** [comment]
cross-linking this to #354

**Comment by Karsten75** [comment]
We recently had more reports of "stuttering. In that case, there was associated high power use (200W) from the GPU. The user had a large number (<200) chrome tabs. 

They updated their driver and rebooted to clean things out. That resolved their issue and power consumption dropped to approx 40W. 

If you can perhaps take a video (with your phone) that demonstrates the stuttering. 

Also, please try this. Zoom in as close as you can, move the camera as far left as it can go. Using arorw keys, navigate as far left as you can go. Do you see the stuttering then? 

Agggain, if you do, please attempt to take a video and upload that.

**Comment by Karsten75** [comment]
Pending close for lack of supporting material/response
