### ISSUE TITLE
[Bug.Minor] Mouse 4 and Mouse 5 can not be bound to an action

### ISSUE THREAD

**Issue by Nathanielastonge** [KnuckleCracker/CW4-bug-tracker#351]
Mouse 4 and 5 are ignored when trying to bind an action
To reproduce use a mouse with a mouse 4 or 5 or rebind buttons to output mouse 4/5.  Then open rebinding dialog and press mouse 4 or 5

![Capture](https://user-images.githubusercontent.com/35466599/101115209-f6704080-35b0-11eb-8117-5640d9802eb0.PNG)

**Comment by Bob2Chiv** [comment]
@Nathanielastonge 
If you want to hack it you can try this:
Edit this file:
"c:\Users\USER\Documents\My Games\creeperworld4demo\settings\controls.xml" 
In there are all of the keymappings.
<singlestep> is the one for frame advance.
It defaults to 110 for the key (the n key).
You can change that to 326 or 327, etc.

Unity has these mappings for  the mouse buttons. Note mouse0 is the left button, mouse1 the right button, mouse2 the middle button.  Enjoy.  If you break something, just nuke the controls.xml file and the game will recreate it (do so while the game is not running).

mouse0 323
mouse1 324
mouse2 325
mouse3 326
mouse4 327
mouse5 328
mouse6 329

**Comment by Karsten75** [comment]
I believe supporting more mouse buttons is in-plan

**Comment by knucracker** [comment]
Added support for mouse buttons 1-6 (mouse 0 is the left mouse button, and it is 'reserved'). So now folks can click any mouse button, other than left mouse, and it will assign on the key assignment screen.
