### ISSUE TITLE
[Suggestion] Addition to GeForce NOW

### ISSUE THREAD

**Issue by vitallish** [KnuckleCracker/CW4-bug-tracker#352]
The game so far has been excellent. Unfortunately, my laptop isn't quite up to snuff for excellent graphics and I would love to be able to play this game on NVIDIA's GeForce NOW.

Would it be possible to add it to their catalog?

**Comment by Karsten75** [comment]
I believe addition to GeForce now is "by invitation" and not usually extended to smaller indie developers. 

If you know otherwise, or know a way to do so, the developer has indicated an interest in looking into it.

**Comment by vitallish** [comment]
Got it thank you - I just sent them a request to add the game on their feedback form - I will report back once I hear from them.

**Comment by Karsten75** [comment]
Closing in 1 day due to no follow-up
