### ISSUE TITLE
[Bug.Minor] Inexplicable object appears in corner when adding a cpack mesh

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#356]
![image](https://user-images.githubusercontent.com/40322714/101167516-0e949e00-364b-11eb-9e82-85f304cb2f33.png)

Open cpack menu.
Add a new unit.
Add root.
Select any mesh for root.
Close the Cpack menu.
This appears in the corner.
Goes away on reload, hence minor and no savefile.

**Comment by Karsten75** [comment]
Root should not have a smesh

**Comment by knucracker** [comment]
I have this on my notepad so I'll reopen and use this issue to track it. The problem has to do with the preview models getting created and being visible by the main camera.

**Comment by knucracker** [comment]
The game now creates the object preview meshes out of the viewing area.
