### ISSUE TITLE
[Bug.Minor] Incorrect mesh type indicator

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#360]
Open a custom unit.
Open "Objs"
Open an object with a custom mesh
![image](https://user-images.githubusercontent.com/40322714/101182556-4ad1f980-365f-11eb-885e-3139c09e30bf.png)
By default it will show mesh type as "Stock" regardless of whether it's stock or custom.
Furthermore, if you change it to custom, it will display "Custom" on all meshes, even if they are stock.
Basically, it is completely divorced from reality.

**Comment by Karsten75** [comment]
Please wait to submit bugs on parts of the editor that compriose the 4RPL sphere

**Comment by knucracker** [comment]
On load, the button text was not being refreshed properly.
