### ISSUE TITLE
[Bug.Minor] Inconsistent build selection indicator.

### ISSUE THREAD

**Issue by Wyrus** [KnuckleCracker/CW4-bug-tracker#361]
During game play (no specific level), when I use the mouse to select Weapon, then use the mouse to select Cannon, the cannon "button" appears selected (green border).

When I perform the same action with the keyboard (F2 for weapon, 1 for cannon), the weapon tab is shown, and cannon is selected for build. However, the cannon button does not appear selected (no green border).

I would expect that keyboard selection and mouse selection would provide the same feedback.
i.e. Both should cause the Cannon button to appear selected.

I tried various combinations of mouse/keyboard, different tabs and different items. I've only played the first two missions so far. But, I'd suspect that this issue is universal, not tied to a specific tab/item. 

Love the game!

**Comment by Karsten75** [comment]
Yea, this is a thing that never got any love :(
