### ISSUE TITLE
[Bug.Minor]Unit Icons in front of help screen

### ISSUE THREAD

**Issue by Aaron100-prog** [KnuckleCracker/CW4-bug-tracker#362]
![20201203200101_1](https://user-images.githubusercontent.com/56323986/101203814-8d013800-366b-11eb-87a5-b68c0ae19945.jpg)

When playing the game on lower resolutions/higher UI scale the Unit icons get rendered on top of the help screen.

**Comment by Karsten75** [comment]
I'm sure this got fixed?
