### ISSUE TITLE
[Bug] [Video] Absorbers Special turns off when creeper reaches cutoff

### ISSUE THREAD

**Issue by doomdrvk** [KnuckleCracker/CW4-bug-tracker#368]
Absorber terrain simply turns off when creeper reaches it's maximum cutoff point.

[Bug Example Video](https://youtu.be/eKUYrjSU9Pk)

**Comment by harrymcb** [comment]
confirmed

**Comment by knucracker** [comment]
Changed to exclude absorber from the cutoff
