### ISSUE TITLE
{Suggestion] Show spore launch time when selected

### ISSUE THREAD

**Issue by Aaron100-prog** [KnuckleCracker/CW4-bug-tracker#37]
When selecting a spore launcher the player should be able to see when and how many spores are going to be launched. Just like what happens when you hover the mouse over the spore icon in the minimap.

Also same suggestion for the blob nest.

**Comment by Karsten75** [comment]
Right now, there is no easy way to tell when waves of enemies will launch, so a player not familiar with the map may not know how much time they have to prepare. This should be rectified somehow and showing timers, etc. in the unit details field  will go some way to that, It could conceivable even show status like the initial launch time and cycle time, as well as status (nullified, etc.)

![image](https://user-images.githubusercontent.com/22965021/94145827-bb2af600-fe38-11ea-903b-f7c0f628fcfd.png)

**Comment by knucracker** [comment]
Added a hover popup to most enemy units
