### ISSUE TITLE
[4RPL] "Update unit instances" triggers :Destroyed

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#370]
When you press "Update unit instances" it triggers the :Destroyed function. 
This is not...obvious behavior as there is no destruction going on visually. 
While it should probably trigger :Once and :Awake, i'm not sure that :Destroyed makes a lot of sense in that context (of resetting a unit to 0).

**Comment by Regallion** [comment]
I consider this a minor bug, but this is more 4RPL than bug.

**Comment by Karsten75** [comment]
I don't recall observing this in recent build, must have gotten fixed?
