### ISSUE TITLE
[Suggestion] Squad mechanic can be way better and more intuitive

### ISSUE THREAD

**Issue by mrvice** [KnuckleCracker/CW4-bug-tracker#372]
Please make sure you have read, understood and agreed to the [policy](https://github.com/KnuckleCracker/CW4-bug-tracker/blob/master/Suggestion%20policy.md) regarding submitting material to Knuckle Cracker

**Is your feature request related to a problem? Please describe.**
The current squad mechanic is horrible and very unintuitive

**Describe the solution you'd like**
Like every other RTS has done it.
Select Units u want in squad
press "shift+numberkey" example "shift+1" "shift+2" and so on
pressing 1 should selec your squad
pressing 1 two times in a row should move camera to selected squad.

**Describe alternatives you've considered**

**Additional context**

**Comment by jcheung9941** [comment]
but currently 1-8 or however high it goes is used to quick-select items for building. me personally, i rarely ever actually use an actual squad or formation moves, but i use those number keys often to build with... so where would those go?
i might agree with numpad doing what you're saying though

**Comment by mrvice** [comment]
Hmm... then maybe just implement the option with the modifier key "shift" and we will assign stuff to our liking.
but youre right with the nubmer keys... numpad tho is way to far away.
But as long as its costum bindable every player can work that out for themselves.
for exmaple using QWERT and so on would also be an option.
