### ISSUE TITLE
[Bug.Minor] Cannons aiming down sometimes lie about their range.

### ISSUE THREAD

**Issue by ChthonicOne** [KnuckleCracker/CW4-bug-tracker#373]
Cannons when placed on a Z-level well above the ground might have a single pip of area that shows in range. Frequently, even if the creeper is on this pip and they have ammo, the cannon will still not fire on the creeper.

Steps to recreate: Build a wall several levels above the ground.
When placing a cannon, check the range. If it shows more, raise it up another level. If it shows none lower it a level.
If it shows one single dot of range on the ground in front, it likely won't be able to hit that dot even when they have ammo and there is creeper all over the ground.

It feels that there is a minor rounding issue with cannon range. It might also exist with sprayers as well, as they too use a similar mechanism for aiming up/down.

**Comment by Karsten75** [comment]
Please provide a screenshot?

**Comment by ChthonicOne** [comment]
I will be happy to once I see it again. Last time I had it happen it was on the map with the 2 structures that transported creeper over to the creeper emitter that created a sort of creeper wind. The east part of the north wall at the start had some positions where a cannon showed a single pip of range, but would not fire on the creep. Once I have had breakfast, I will go back in there and grab a screenshot of it.

**Comment by ChthonicOne** [comment]
![Cannon Range error](https://user-images.githubusercontent.com/22509283/101261218-9342f300-3703-11eb-9d04-6bb18833e659.png)
![Cannon wont fire](https://user-images.githubusercontent.com/22509283/101261219-93db8980-3703-11eb-8aea-82911407b27b.png)
Here, we have in the first image the cannon's range. It shows a single pixel where it should be able to fire on. There is creeper already there, but it doesn't have ammo yet. In the second image it has ammo but it refuses to fire.

**Comment by Karsten75** [comment]
Thank you. Also, PLEASE, the save file!

**Comment by Karsten75** [comment]
I also have to ask you this: What platform are you running on?  See this box in the lower left of your image - part of the game UI? It should have numbers in it, numbers for the brown terrain height, and numbers for the UPS, at the very least...

**Comment by ChthonicOne** [comment]
Strange, those numbers weren't captured with screen capture, they're there when I play.

You can see what platform I play on by the task bar actually, Windows 10. Not sure why that captured with the screen capture either. Something is wonky. Alt+print screen should only get the game window. Instead it cut off the bottom of the game window and got my task bar as well.

As for the save file, I can reproduce it every time just by loading up the level, as I just did. If you want the save, you'll have to tell me where the game hides them from me.

**Comment by knucracker** [comment]
Tricky little thing. The issue was caused by the move/build ghost being 0.025 higher than the unit. That smidge was making the LOS difference in some cases. The ghosts are higher up so they render on top of some terrain features, and they were using their Y position as the starting point for their LOS preview calculations.
