### ISSUE TITLE
[Suggestion] Additional targeting options for Sprayers and other weapons

### ISSUE THREAD

**Issue by ChthonicOne** [KnuckleCracker/CW4-bug-tracker#374]
Hardened creeper is supposed to be countered by anti-creeper, and on of our main mechanisms for dealing with it is the sprayer. However, we have no real way to guide our weapons to focus on the right kind of creeper like we did in CW3, where we could tell weapons to focus on creeper, digitalis, or crawlers.

My suggestion is to add some targeting options to the Sprayer and other weapons:
Sprayer:
Can choose whether it will choose to focus fire on normal creeper, hardened creeper, or closest.

Cannon:
Can choose between Creeper or Mesh (already an option)
Can further choose between focus fire on normal creeper, hardened creeper, or closest.

Mortar:
Can choose between focus fire on normal creeper, hardened creeper, or closest.
Can be manually aimed for a single shot similar to a Bertha. Next shot fired will fire at mark. One shot only. Mark is either a single target, or a box drawn over the terrain. If a box is drawn, normal targeting rules are used within that box.
Can set above to repeat.
Any manual targeting is undone when the mortar is told to move.

**Comment by jcheung9941** [comment]
to add to this, i'd personally like to see an option to _ignore_ mesh for cannons and mortars if possible
