### ISSUE TITLE
[Suggestion] Sprayer unit toggles are misleading

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#375]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/51026936/101244316-0ea5a400-3706-11eb-91e4-9d348b79b0d3.png)
I thought "AC Collection" was what made the sprayer actually collect AC based on name, instead "Dispatch Ore" is the setting that makes the sprayer collect nearby creeper and dispatch it.

From naming alone, I thought "AC Collection" is required to make the sprayer collect AC, and "Dispatch Ore" governed whether the unit would send back excess Bluite or not.

**Describe the solution you'd like**
Name the functions something that describes the functions better, e.g.
"AC Collection" -> "Pull nearby AC"
"Dispatch Ore" -> "Collect as Ore"

**Comment by ProfFancyPants** [comment]
I agree. I made the same interpretation.

**Comment by knucracker** [comment]
Changed the sprayer controls text to:
![image](https://user-images.githubusercontent.com/6733225/111320723-a7b95480-863d-11eb-8c75-dbf4c54801b6.png)
