### ISSUE TITLE
[Bug] Final objective on founders failed to trigger

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#376]
[Founders.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5647288/Founders.zip)

Reported by WendyWOT#3086

The reactor was destroyed and according to user, the normal sequence of blackout+final messages triggered. The messages were said to be closed normally. The objective is not achieved.

Placing another reactor and re-triggering the sequence works as expected, so it's a really weird glitch.

**Comment by Regallion** [comment]
Found a way to replciate the issue: if at the time of neutron burst another message is on-screen, it will cause the sequence to fail.

**Comment by knucracker** [comment]
On screen messages are supposed to pause the game, so I'm having a hard time getting a message on screen at the time of the neutron burst. Perhaps it is a certain message, or I'm missing a step...

**Comment by Regallion** [comment]
@knucracker 

[Cheese.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5663941/Cheese.zip)

Here's a zip with an artificially replicated situation, where you collect an info cache at the same time as you nullify a reactor.
(Replicating the issue in normal gameplay would take an unduly long time, but it's still possible by timing a thor or an orbital to it)

You need to time it so the message pop after the blackout starts which is a very, very tight timing.

**Comment by knucracker** [comment]
Updated the mission so that it closes any open dialog when trying to show the final dialog sequence.
