### ISSUE TITLE
{Suggestion] Units with multiple targeting modes should have a method to display current mode

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#38]
Here are 3 cannons in CW3 that has, from left to right, targeting modes forCreeper, Digitalis, and Runners 
![image](https://user-images.githubusercontent.com/22965021/94363771-44853700-008a-11eb-9b39-0d3e16aa2ca7.png)

Here are two CW4 cannons that have, from left to right, targeting modes for Creeper and for Mesh

![image](https://user-images.githubusercontent.com/22965021/94363828-8f06b380-008a-11eb-9052-c1d99c021ad1.png)

**Comment by WithersChat** [comment]
Yeah, this makes targeting insanely hard to manage, compared to what it is.
