### ISSUE TITLE
[Bug.Minor] Cannot bind controls to the same key, despite default controls doing just that

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#380]
It appears that the rebinding a control to a key that is already used by another control will automatically unbind the other control. Because of this, you cannot bind the same key to multiple controls. This seems reasonable, until you realize that the game's default controls actually do this for MultiSelect and Slow Zoom Mouse. If you bind any of those to another key, you can never both bind them back to Shift. The only way to do so is completely resetting back to default controls, which kinda sucks when you already have 10 or more other controls rebound.

Here's two images of me trying to rebind MultiSelect to Shift when it is already set to Shift. Doing so will unbind Slow Zoom Mouse, even though nothing should change.

![rebinding multiselect 1](https://user-images.githubusercontent.com/74179010/101265972-63b7d900-374b-11eb-83bc-2885c892d4e0.png)
![rebinding multiselect 2](https://user-images.githubusercontent.com/74179010/101265974-64e90600-374b-11eb-9136-5d44cf605efc.png)

**Comment by knucracker** [comment]
I've removed the restriction on duplicating controls. The panel will still warn the key is in use, but the player can double up if they want.
