### ISSUE TITLE
[Bug.Minor] Unit Landed on Destroyed Platform

### ISSUE THREAD

**Issue by MetBoy** [KnuckleCracker/CW4-bug-tracker#381]
![20201205141434_1](https://user-images.githubusercontent.com/75547925/101266616-50821a80-3705-11eb-9ab4-012354ecc11d.jpg)
Allow me to draw your attention to the Cannon near the center of the screen. Yes, the one sitting on nothing, still firing.

What happened is that there was a platform there, the cannon had been ordered to move there, and the platform was then destroyed. I don't think this is how this should work... either have such units self-destruct when they land, or have their health drain.

**Comment by Karsten75** [comment]
In tests that we performed, these units should in fact self-destruct.  Would appreciate if you have a save file that can be used to recreate the situation or a more detailed  description of the steps needed to reproduce this. 

For instance, at what stage of the cannon's flight to that platform did the platform get destroyed?

Did you have to take any steps after the platform was destroyed?

**Comment by MetBoy** [comment]
I'm not 100% sure what stage it was in, either the transfer or descent stage. I don't have the 'before' game save, but once I noticed something going on, I did save just after.
I have no idea where the save files are stored.

**Comment by Honnullul** [comment]
Just tested this. Only units landing self-destruct, units in-flight and taking off proceed to fly and land on void.

**Comment by knucracker** [comment]
The bug requires a planetary background. When the planet background is present, the units don't go down as far (all the way to 0 on the y axis). There was a redundant check in place that was looking for that before it would check to see if the unit was on the void without a platform present.
