### ISSUE TITLE
[Performance] Story mission 19 has unusually poor framerate

### ISSUE THREAD

**Issue by ManaFriendsmith** [KnuckleCracker/CW4-bug-tracker#382]
Please describe the issue and add compressed (zip) file with the saved map.
[bounce.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5647953/bounce.zip)

`warning! when I tried to download this file, I received virus alerts` k75

Unpause the game from the provided save (or just start mission 19 and power one of the ball cannon things). UPS drops to ~15, and remains low if paused again. This happens whenever there are more than a handful of ball projectiles.

Running the game on Linux w/ Proton 5.9-GE-5-ST. Everything in performance settings is disabled, mist and screen shake are disabled. These settings were able to play the first 18 levels at 29-30 UPS on default speed and 85-120 UPS depending on the map at 4x speed.

**Comment by Karsten75** [comment]
I will pass this on, but proton is not officially supported. We also do need a log file. Since we don't support Linux/proton, I unfortunately can't tell you where it is located, I can only tell you where Windows 10 keeps it: 

`%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4\output_log.txt`

**Comment by ManaFriendsmith** [comment]
Understood, here is the log from a session loading only the affected save
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5648050/output_log.txt)

**Comment by Karsten75** [comment]
I am really sorry to inform you that my viris scanners indicate that the bounce.zip file is infected with a virus. I will not be able to download it or open it. 
![image](https://user-images.githubusercontent.com/22965021/101268830-7cb19180-372d-11eb-9f89-63b0ed55802b.png)

**Comment by ManaFriendsmith** [comment]
OK, second try, here is the original save, not zipped. I changed the extension to txt because it would not let me upload as cw4, but I have not changed anything else about it.
I scanned the entire steamapps/compatdata/848480 directory for viruses - nothing. If the game is generating save files that look like viruses to your software there's little I can do.
[bounce.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5648479/bounce.txt)

**Comment by Karsten75** [comment]
It's kust a little strange, sicne in all other file exchanges, this was the very first virus alert, and I've been exchanging saves and zipped folders for almost 4 years now. :)

**Comment by Karsten75** [comment]
Both knucracker and I evaluated this save file on our machines and we get consistent frame rats. 

on knucracker's machine, it runs at 120ups at 4x . There must be some proton related issue. Not sure what it might be, though.

you have a somewhat older graphics card with the minimum amount of VRAM, so that may factor in as well.

**Comment by Karsten75** [comment]
Pending close if no response in 24 hours

**Comment by ManaFriendsmith** [comment]
Unfortunate that there's no fix, but it's ultimately minor - the mission seems completable without using that unit. Thank you for taking the time to check.

**Comment by Karsten75** [comment]
We are continuing to investigate to the best  of our abilities. Several of these issues have been reported by users who resolved them by closing various overlays, software like iCue, and a diverse number of other applications.
