### ISSUE TITLE
Changes to Mark V and Chronom map generators

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#384]
Mark V. 

Invert terrain selectors. so that #4444 represents most challenging and not #1444

Chronom

Add a check to algorithm to ensure minimum terrain is in the map. Avoid another map such as Dec 5th, 2020. 

For reference, the Chronom for Dec 5th had 

terrain % 0.140
void % 0.859

**Comment by grabz-dev** [comment]
Personally I like the thrill of the player never knowing when Chronom may spit out a challenging map, makes it at least that bit more interesting - but that's just my $0.02

**Comment by Bob2Chiv** [comment]
DEC 5 had a lot of (mostly positive?) response - that being said, it's probably on the lower limit of the acceptable range.
