### ISSUE TITLE
[Bug] Imported magica voxel units will not always have the correct texture

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#387]
**Describe the bug**
Importing the exported magica voxel units won't always have the correct colors.
Take this unit:
![image](https://user-images.githubusercontent.com/26010895/101270141-78887280-3733-11eb-8b53-81c57df1f681.png)
when imported directly, it looks like this:
![image](https://user-images.githubusercontent.com/26010895/101270146-85a56180-3733-11eb-90be-56de6151021e.png)
each object is using their respective texture(first object is using first object's texture)

Now this can *mostly* be fixed by using the palette itself(saved, so not exported with the unit)
![image](https://user-images.githubusercontent.com/26010895/101270227-5511f780-3734-11eb-8e3a-31477ae832ba.png)
i say mostly because the pole did *not* change colors using either texture(this is why the live unit does not use the pole visibly)

This zip includes:
1: the (vox) model
2: the palette used
3: a c-pack with everything imported and seen
[import bug.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5648207/import.bug.zip)

if you would like to duplicate steps taken in importing, do this:
export the model with the palette as it active palette, as an object.
import those objects into cw4(0 is base, 1 is turret, 2 is pole, 3 is rocket for when i export)
make unit, see that the colors are wrong
import saved texture, and use that instead
see that it fixes most of the problems

**Additional Information**
Not all units imported this way have this issue(and I don't know why)
magicavoxel version 0.99.2 is what's used for the cpack(can be replicated in 0.99.6.2)
imports using this are scaled by 10 and facing the wrong way, but thats on the software, not the game
using version 99.6.2 fixes scaling and rotation, but moves it's position; colors are *not* changed, which is why i suspect the game is doing something

**Comment by Alophox** [comment]
An added observation: it appears that if the object is mono-colored, it will use the first slot in the palette, rather than the correct slot. For my palette, it is that blue seen. A workaround is simply not applying the texture, and manually changing the color of the object.

**Comment by knucracker** [comment]
This might end up being a problem in magicavoxel. When the model imports it will have uv coordinates for some offsets in the texture map. I don't do a lot (if any) processing on those when importing a vox file.  If it is a magicavoxel issue, then  in theory the same problem should present when importing into other model viewing tools. I've not had a chance to look at this yet, but that will be the first thing I try. If it isn't a problem with the vox file, then it will be some issue with the vox importer I'm using. I don't recall if magicavoxel has a way to export to obj or not. If so that might be another workaround.

**Comment by Alophox** [comment]
Alright, there's a lot to unpack here.
1: I've been exporting to .obj this entire time(and guess what, exporting to .vox fixes the color issues)
2: The .obj views just fine with the default win 10 3d viewer, right colors and all.
3: The .vox files can use the textures they import with just fine, so must be something weird with the .obj exported or imported. As .vox works fine, I'm going to use that instead.

**Comment by knucracker** [comment]
If you  have the obj you exported attach it here and I'll take a look

**Comment by Alophox** [comment]
[object.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5681099/object.zip)

objects with Ring or Glowy are the mono-colored ones; the rest needed the separate palette(ARCColors) to be viewed with the right colors
