### ISSUE TITLE
[Bug] AC at very tall heights turns into anticreeper

### ISSUE THREAD

**Issue by minicheatbook** [KnuckleCracker/CW4-bug-tracker#389]
When collecting massive amounts of AC in one area to make an AC wave, at approximate 2100 height, the AC spontaneously turns into creeper. Screenshot shows slightly after this happened when my sprayers targeted the creeper that transformed from my AC on top of the pylon. No, this was not a mortar despite having one in the map, the issue is completely able to be replicated and you can see in the first screenshot this happened slightly before the mortar strike, and the last screenshot is the same issue again, later in the mission. Mouse in the first and last screenshot is over the pylon in the center of the max AC height area.
It does come to mind that this might not be a bug, but a deliberate cap on AC height, but that would also be a bit sad as i would like to make ridiculous waves of AC to fight back against the creeper and this limits that greatly. If it is not a bug, then this is my suggestion to allow higher AC for more fun.
![damaged pylon](https://user-images.githubusercontent.com/75557668/101272718-ab3a6700-3743-11eb-9cce-42eda4ef50b0.png)
![image](https://user-images.githubusercontent.com/75557668/101272762-23a12800-3744-11eb-8fc5-52abfa4b1fe2.png)
![damaged pylon 2](https://user-images.githubusercontent.com/75557668/101272793-67942d00-3744-11eb-9524-d98bc7d71568.png)

**Comment by grabz-dev** [comment]
This is an intended game mechanic that has been with us since CW2 - creeper is stored as a 32bit signed int, and flips to the opposite value after max int.
https://en.wikipedia.org/wiki/2,147,483,647#In_computing

**Comment by minicheatbook** [comment]
Hm, understood, but some way to... compress? AC or creeper in a location to release a massive wave of it all at once could be cool, hard to do with the traditional units. and since waves weren't really a thing in previous games this could be something interesting to implement, obviously too late for the campaign as an official unit at least. Guess I'm stuck trying to make a custom unit that will do that. Either way, I understand the value flipping but was just hoping in my heart it was different in this new game because of the new wave mechanics.
As you said, not a bug, so I'm closing this out.
