### ISSUE TITLE
[bug] intro video stops closing game

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#39]
in the intro video to the first mission if you try to close the game by any normal means it won't show the "exit to operating system" message till the whole intro is over.

**Comment by knucracker** [comment]
Detect if the intro sequence is running when attempting to close the game (and close confirmation is on). In that case, just skip the intro sequence so the confirmation dialog can show. That isn't perfect, but it at least lets a person who intends to exit to actually do so without having to wait (or click the skip button).
