### ISSUE TITLE
[Bug] The wrong unit is selected when clicking while zoomed in.

### ISSUE THREAD

**Issue by EmoryM** [KnuckleCracker/CW4-bug-tracker#390]
I attempted to take screenshots to illustrate this but the cursor is not displayed (attaching them anyway.)

To reproduce: build two miners as in the screenshot, zoom in, click on the center of the green diamond on the upper miner.
Expect: The upper miner to be selected.
Result: The lower miner is selected.

You can move the mouse up until the bottom of the cursor is on the upper miner and the lower miner still gets selected.  I'd guess you're tracing a ray against simplified geometry and the miner is a cuboid as far as collisions are concerned but no real idea, just know I'm frequently selecting the wrong things.

![20201205211655_1](https://user-images.githubusercontent.com/44074520/101273787-56035300-374d-11eb-9ed0-eca50829adb9.jpg)
![20201205211659_1](https://user-images.githubusercontent.com/44074520/101273788-57348000-374d-11eb-9b9f-15ecd623af6d.jpg)

**Comment by Regallion** [comment]
As a side-note, this has much direr consequences when using shift+x in editing mode, often resulting in unwanted deletions.

**Comment by knucracker** [comment]
The collider for the miner was way oversized and too tall. I've reduced it to a rectangular solid the size of the base
