### ISSUE TITLE
[Bug.Minor] Platforms can clip under terrain

### ISSUE THREAD

**Issue by cinnamennen** [KnuckleCracker/CW4-bug-tracker#395]
On the Dec 5 map:
![Screenshot 2020-12-06 142116](https://user-images.githubusercontent.com/2693113/101290174-8dfeaa80-37ce-11eb-9271-718ecc54c8a0.png)

**Comment by knucracker** [comment]
Yeah, I reduced the footprint so they could be stacked next to each other and that comes with terrain overlap by a bit. It makes them more versatile and I don't want to change them at this point. So I'll live with the terrain overlap
