### ISSUE TITLE
[Suggestion] AoE indicator for shields before building

### ISSUE THREAD

**Issue by wejengin2** [KnuckleCracker/CW4-bug-tracker#396]
**Is your feature request related to a problem? Please describe.**
When placing a shield template to be built, there is no aoe indicator to how big it is

**Describe the solution you'd like**
An AoE indicator for shield before building it, basically a ghost of the flattened shield would do the trick

**Describe alternatives you've considered**
Pretty sure the above is the best way, as it was done in CW3

**Additional context**
No size indicator : 
![CW4_0otBSLwwRR](https://user-images.githubusercontent.com/48154165/101295026-494d3080-381b-11eb-922a-9e5dc282bb37.png)

How it could look,(imagine it's not built yet):
![CW4_zFePJgoDg5](https://user-images.githubusercontent.com/48154165/101295034-5a963d00-381b-11eb-906a-c0e6af609515.png)

**Comment by knucracker** [comment]
Added a ring range indicator on the build and move ghosts
