### ISSUE TITLE
[Bug.Minor] Player can switch to free cam from terraform cam

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#397]
1. Switch to top down using the top view toggle.
2. Try going into free cam - game doesn't allow it.
3. Switch back to regular view.
4. Hit Terraform - game is forced in top down camera.
5. Try going into free cam - game allows it. Rotating in this mode causes weird graphical glitches:
![Screenshot_20201207_010108](https://user-images.githubusercontent.com/51026936/101297177-eada7f00-3827-11eb-8dc5-ee69dffdae79.png)

**Comment by knucracker** [comment]
I new prevent entering free view when terraforming mode is active
