### ISSUE TITLE
[Bug] When trying to launch the game, loading screen freezes, unity crash handler boots up and game crashes.

### ISSUE THREAD

**Issue by Magickan** [KnuckleCracker/CW4-bug-tracker#398]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5651120/output_log.txt)
![Crash screen](https://user-images.githubusercontent.com/75606020/101322686-bc7c9400-3867-11eb-9daa-181c4af739b6.png)

**Comment by Karsten75** [comment]
From the crash output your video card (NVIDIA GeForce 840M) shows to sun at DirectX 11.0 level. Your card is compatible with DirectX 12, and the gmae requires DirectX  11.1.

I suggest you look at updating your grpahics drivers. That may resolve the issue.

**Comment by knucracker** [comment]
The log indicates a directx error.  Let's try this;  Attached is a config file (an xml file inside a zip that you will need to extract) that will make the game start in a window at a lower resolution.  Place the attached GameSettings.xml file at the following location:
"c:\Users\YOUR_USER\Documents\My Games\creeperworld4\settings\GameSettings.xml" 
[GameSettings.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5653725/GameSettings.zip)
