### ISSUE TITLE
[Bug] Carry egg probability does not get saved

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#399]
1. Enter map editor.
2. Place a blob nest.
3. Set Egg carry prob to any number other than 20. Apply.
4. Save
5. Load.

Expected: Egg carry prob is what you set in step 3
Reality: Egg carry prob is 20.

I would not be surprised if that's not the only semi-hidden parameter that doesn't actually save correctly.

**Comment by knucracker** [comment]
Fixed. It appears that everything is is serialized. Just missed that one it seems.
