### ISSUE TITLE
[Minor Bug] Terrain reduced to 0 can be re-created if it was marked beforehand

### ISSUE THREAD

**Issue by Tharifaz** [KnuckleCracker/CW4-bug-tracker#400]
What I believe happened (I only noticed it when the ground was reduced to 0 already) is - the ground was marked for terps, but there weren't any nearby. Then, when I tried to cancel, it only cancelled the areas that weren't reduced to 0 by that point. After that I moved some terps in and they lifted the ground up from 0/void which should be possible I believe? The screenshot pieces are in chronological order. The scenario is Cheap Construction.

![CW4](https://user-images.githubusercontent.com/75622515/101357609-bb208b00-38aa-11eb-9b46-c581f3697bab.png)

**Comment by knucracker** [comment]
The game now removes terraform target indicators when the land decays to level 0.
