### ISSUE TITLE
[Bug.Minor] Final mission dialogue oversight

### ISSUE THREAD

**Issue by Tharifaz** [KnuckleCracker/CW4-bug-tracker#401]
In the last mission, if you first disable the reactor, then the cache message is changed accordingly.

I've had an obelisk turn on again by accident when messing around the last mission after clearing everything and disabling the reactor, and the message still had Danu speaking.

**Comment by Karsten75** [comment]
NoFix?

**Comment by Tharifaz** [comment]
Sorry?

**Comment by knucracker** [comment]
I've changed it so that the obelisk kill dialog does not show if the reactor is already destroyed.
