### ISSUE TITLE
Building and power packets stopped traveling across the network

### ISSUE THREAD

**Issue by u2mad** [KnuckleCracker/CW4-bug-tracker#402]
I was playing on Span - Cheap Construction when suddenly the game slowed way down. Building and power packets stopped traveling along the network as well and bombs from the mortars and cannons didn't seem to be falling anymore.
The save is from saves\span\knucracker8. I renamed the .cw4 extention on the file to .txt so I could upload it.

[save-1.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5653067/save-1.txt)
[save-1_rec.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5653068/save-1_rec.txt)
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5653041/output_log.txt)

![2020-12-07 05_59_21-Creeper World 4](https://user-images.githubusercontent.com/54191831/101359770-9946ea00-3851-11eb-91ef-d0c888292d60.png)

**Comment by knucracker** [comment]
After some time, the blobs started routing around areas where they were killed. This caused one to route to the top edge of the map and that in turn exposed a problem where the blob was looking outside its legal data structure bounds. I've added checking to prevent this out of bounds check.
