### ISSUE TITLE
[Suggestion] Relax 'Ever After' Life objective requirement

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#405]
**Is your feature request related to a problem? Please describe.**
Multiple users have reported confusion on how to 100% this objective, because units present in the level prevent trees underneath from growing, and have to be deleted to finish the objective.

**Describe the solution you'd like**
Relax the tree requirement a bit to allow for more trees to be dead before completion, to account for units used to fight back creeper.

**Comment by Karsten75** [comment]
everything has to be scaled back?

**Comment by grabz-dev** [comment]
> everything has to be scaled back?

Well that or have a better tutorial? Unless you like complaints/questions about it for years to come...

**Comment by BilboGCL** [comment]
One solution could be an info cache Hippie complains about weapons/industry stealing space for trees...

**Comment by grabz-dev** [comment]
Closing this as suggesting this seems to have struck a nerve and I don't want this coming back to me.

**Comment by grabz-dev** [comment]
Reopening this issue because there's been at least 10 people so far for whom I've had to explain why their Life achievement is stuck at 98-99%. Maybe now the sentiment will have changed.
