### ISSUE TITLE
[Typo] Mark V sample in Span welcome message

### ISSUE THREAD

**Issue by Tharifaz** [KnuckleCracker/CW4-bug-tracker#406]
Probably doesn't require the "missions will continue in full game" message anymore, as well as missile launcher etc. tutorials.

![20201207234757_1](https://user-images.githubusercontent.com/75622515/101403781-c42f4d80-38e6-11eb-88ef-afb7670c0187.jpg)

**Comment by Karsten75** [comment]
we're keeping it in this form for archival purposes.
