### ISSUE TITLE
Achievements do not award when completing optional objectives in a second play

### ISSUE THREAD

**Issue by egerke28** [KnuckleCracker/CW4-bug-tracker#407]
I first cleared the Archon story mission without nullifying all enemies. Then when I went back later and got that (along with all other objectives) in a second play, the achievement for completing the mission and the whole campaign did not award, neither within in the game nor on Steam.

**Comment by knucracker** [comment]
If you enter edit mode during play, the achievements won't award. Maybe you entered edit mode (even by accident)? Shift-E enters edit mode. In the 1.0.1 release  there will be a confirmation dialog for edit mode.

**Comment by Karsten75** [comment]
If the above is not the case, please provide the save file of the mission in question.

**Comment by egerke28** [comment]
I don't think I ever entered edit mode, save attached.
[story15.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5659948/story15.zip)
