### ISSUE TITLE
[Bug] Another stacking issue

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#408]
By Pilihp64 on Discord:
> Hey, I found another gameplay unit stacking method. As far as I can tell it has nothing to do with the previous shift-preview method so I thought you might want to know it as well. The mechanics are a little harder to describe but I did make a quick video to show the easiest replication. This is showing two grouped units.
[stack3.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5656417/stack3.zip)

**Comment by knucracker** [comment]
This one involved squad selection. I changed it so that when selecting a squad, a layout is preformed. That repositions the ghosts like they should be.
