### ISSUE TITLE
[Bug] Wave Cap setting does not persist after save load

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#414]
1. Change wave cap value to anything e.g. 2
2. Save and load
3. Value is back to 35
![image](https://user-images.githubusercontent.com/51026936/101551747-d7f3b600-39b1-11eb-8b39-e247d834ca0d.png)

Possibly related to https://github.com/KnuckleCracker/CW4-bug-tracker/issues/399

**Comment by knucracker** [comment]
Yeah, looks like I missed serializing the cap. The transfer rate was there but not the transfer cap. Thanks for the catch
