### ISSUE TITLE
[Bug] Eggs fall off and despawn on the north and east border of the map, but not the south and west border.

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#416]
I was messing around with small map and lots of eggs, and noticed my eggs being stopped by south and west border, but falling off the map and despawning off the north and east border.
[save.cw4.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5662988/save.cw4.zip)
![image](https://user-images.githubusercontent.com/51026936/101562164-23fd2580-39c7-11eb-8e37-f668716fb4a6.png)

**Comment by knucracker** [comment]
Pulled in the edge collision by 1 on the right and top. Looks like it was allowing the eggs to go 1 too far on those edges.
