### ISSUE TITLE
[Bug] Weapons phantom are able to absorb ern

### ISSUE THREAD

**Issue by manuco** [KnuckleCracker/CW4-bug-tracker#421]
When building a weapon near an Ern, if we select the weapon-to-be-built, and even if it is not being built, if we click on "Ern: want" option, the Ern is absorbed.

For me it's a bug since the blueprint of a weapon shouldn't interract with the world (except for being destroyed by the creeper).

![cw4ss_1](https://user-images.githubusercontent.com/243316/101674045-45f2b880-3a58-11eb-92db-ad52670a170a.jpg)

**Comment by knucracker** [comment]
I did it this way so the ern could pre-load and the user could specify that they wanted an ern on the unit right after placement. The ern should be released if the ghost is destroyed or the player tells it to release.

Internally, the ERN moves to the unit and then waits for it to complete, then it docs with the unit. Visually, it shows the glow ring so the player can know the ern is waiting to dock.
