### ISSUE TITLE
Sniper "custom" selection not working

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#422]
The "[do not fire at] custom" option on a sniper does not save correctly. Checking it, then deselecting and reselecting the sniper shows "eggs" checked instead; deselecting and reselecting the sniper again then shows no options checked. This last state seems to be correct, based on the sniper's behavior. This occurs on at least Chanson and Far York Farm in the span, and Tower of Darkness in the expedition, so is presumably consistent across levels.

**Comment by knucracker** [comment]
Yep, I didn't have the toggle control for specials hooked up to the right method. It was calling the eggs callback.
