### ISSUE TITLE
Platfrom breaking just as mortor/other weapons lands on it results in mortor landing on space/empty space (could be intentional idk)

### ISSUE THREAD

**Issue by SnakeMister** [KnuckleCracker/CW4-bug-tracker#424]
Platfrom breaking just as mortor/other weapons lands on it results in mortor landing on space/empty space (could be intentional idk) 
![creeperworldbugreport](https://user-images.githubusercontent.com/75764143/101707774-b8579e80-3a40-11eb-8391-e78aad15f934.JPG)
![creeperworldbugreport](https://user-images.githubusercontent.com/75764143/101707782-be4d7f80-3a40-11eb-86e7-51e983f37225.JPG)

**Comment by grabz-dev** [comment]
Duplicate of https://github.com/KnuckleCracker/CW4-bug-tracker/issues/381

**Comment by Karsten75** [comment]
This is a known issue and it will be fixed in the first update for the game. Thank you for bringing it to our attention.

**Comment by SnakeMister** [comment]
Great! :)
