### ISSUE TITLE
[Bug] CW4 zooms in and out on scroll when the mouse is not in the window

### ISSUE THREAD

**Issue by jyn514** [KnuckleCracker/CW4-bug-tracker#425]
1. [x] I have rebooted without the issue going away.

2.  [x] [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5669588/output_log.txt) (this is on Windows 10)

3. I am not sure how to take video of both monitors at once (I saw suggestions about OBS but I'd rather not install it if I don't have to, this is a shared computer).

4. Describe the bug 

When CW4 is in focus, it will zoom in and out on scroll, even if it is not currently highlighted with the mouse. This means you can have two different windows zooming at once, which is pretty disconcerting.

Steps to replicate (with one monitor, this is trivial with two):

1. Open CW4
2. Switch from Full Screen to Window mode
3. Open a new window, such as Chrome
4. Click back on CW4, making sure it doesn't take up the whole screen
5. Scroll while the mouse is hovered over Chrome. Both windows will scroll up and down.

**Additional context**
The problem occurs in both full-screen and windowed mode, but not sure how to replicate that with only one monitor.

**Comment by jyn514** [comment]
This is mostly just an annoyance since I can always workaround it by bringing another window into focus.

**Comment by Karsten75** [comment]
We are aware of this. I am not sure if there is a way for the game to sense when the mouse is not over the game window. As it is, once you click outside the game window and the game loses focus, then this behavior stops.

**Comment by knucracker** [comment]
I added a special check for the scroll wheel event. It will check if the mouse cursor is within the window/screen bounds now. This should make the zoom not happen when the mouse is out of the game but the game still has focus.
