### ISSUE TITLE
[Bug] Game Freeze

### ISSUE THREAD

**Issue by Biostar-Ten** [KnuckleCracker/CW4-bug-tracker#426]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\output_log.txt`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`
3. Screenshots help! 
  Screenshots are here
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

4. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

**Additional context**

**Comment by Biostar-Ten** [comment]
Pretty weird, I downloaded it again and tested myself, no problem so far. Might be a random rare event maybe just try it again?
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5670290/output_log.txt)

**Comment by Karsten75** [comment]
There is no indication in the log files that the game suffered any issues. 

Cause: These types of crashes are not related to CW4, it was merely exposed by the game. CW4 is a user mode application and has no ability to lock out your mouse and/or keyboard or cause your computer to freeze. If the game, or a script in a map in the game is in a hard loop, you should be able to use Task manager to cancel the game, or Windows may notify you that the application has become unresponsive and give you an option to cancel. 

Recommended: It is most likely that you have latent issues with your hardware or software. Start investigating by making sure all your drivers are up-to-date.  If that does not resolve your issue(s), then you may have to find someone that has the ability to investigate the Windows Crash Dumps, or consider using these benchmarking/stress tools to see if you can narrow the problem down more.

**Comment by Karsten75** [comment]
closing due to no feedback/no documentation.
