### ISSUE TITLE
[Bug] Graphic glitch - Energy map overlay

### ISSUE THREAD

**Issue by skarss** [KnuckleCracker/CW4-bug-tracker#427]
As a macOS user I have to start CW4 in a VM. I am using:

* Parallels Desktop 15 - Version 15.1.2 (47123)) 
* VM Microsoft Windows 10 Home N (10.0.19042)

Also I have tried several graphic settings, CPU, RAM, ... but unfortunately there is always a graphic glitch in the rendering of the energy levels on the map (flickering green areas, most of the time not shown) as you can see in attached image. 

If you need some more information please let me know.

![3ddbb32f842e](https://user-images.githubusercontent.com/13269401/101741129-f9e05c00-3ac9-11eb-9712-c02b39bdac74.png)

**Comment by skarss** [comment]
[settings.xml.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5671353/settings.xml.txt)

**Comment by Karsten75** [comment]
We suspect that Parallels has issues with mapping the DirectX graphics to OpenGL. Players have reported that Crossover works for them. 

Unfortunately, since MacOS (nor Virtual machines are supported at this time, there is no further assistance that can be offered.
