### ISSUE TITLE
Emitter Text too big for text box

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#428]
When an creeper emitter's text becomes relatively huge (20K amt and 10 seconds delay in my case) the S falls below the text box that shows up when you hold the cursor on top of the emitter. Visual minor bug.

**Comment by knucracker** [comment]
Changed emitter, spore launcher, blob nest, skimmer factor, and air sac cauldron popups to have a variable font size in their second row of information.
