### ISSUE TITLE
Switching from 2D to 3D camera and back moves the camera forwards

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#429]
When you switch from 2D (top view) to 3D the camera moves forward a bit. I didn't test if there is any difference depending on the "height" of the camera, but I usually play with the camera pretty close to the terrain.

When I switch 2D and 3D often I have to manually scroll down which is a little bit annoying.

**Comment by Karsten75** [comment]
Does this happen even if you make absolutely no changes in posotion on the map? Ie. you just flip between "normal" camera and top view? It  is my experience that the forward movement of the camera is the result of a change in position of the ceter of the camera's view. 

Some changes in camera might be coming in a planned version (not sure if 1.01 or 1.1), so maybe re-open this after that has rolled out?
