### ISSUE TITLE
[Bug] Message Pod Softlocks The Game

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#430]
When a message pod has both checkable options checked (click to remove message and pause game) and the message type is not ADA the game stops when you collect the info cache, since there is no way to remove the message/text.

The game keeps working, it's just permanently paused. Pressing the pause button also does nothing n this situation.

**Comment by grabz-dev** [comment]
I took a look at this and it seems to me like just setting the type from ADA to GameMessage makes the cache freeze the game after being collected, regardless of which of the two options mentioned are checked.

**Comment by knucracker** [comment]
It looks like the infocache was always pausing the game when it showed an message (non ada). Note that pauses are exclusive, meaning they are not controlled by the pause button state. Even with this fix, if a user configures the infocache to popup, to pause, and then doesn't give a button to dismiss it, and/or doesn't close on click, then the game will remained paused until something else (presumably 4rpl) closes the message.  

If there is another case I didn't catch, or this one still seems to be a problem, just open a new issue after 1.0.1 and I'll take another look.
