### ISSUE TITLE
Edit specials button changes special terrain that was already placed.

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#431]
Resource terrain turned into breeder with power 10 after I set special terrain type breeder to power 10 (edit special button). This happened to resource terrain already placed down hours ago. I don't really know what caused it but I feel like the "edit special" button somehow changes everything that once belonged to a certain terrain slot (1-10)

If someone encounters this issue as well and can be more specific or correct than me, please add a comment.

**Comment by knucracker** [comment]
That sounds correct.  When you are editing a special, you are editing a "slot".  When you paint you are also painting a "slot" onto the map.  You can change the slots from one type to another and that slot will change on the map. Typically, you will define your slots before you make a map (deciding what you want on a map). For instance, you might want 4 types of breeder terrain so you might choose 4 slots and set them to breeder with different values. Then, you will paint them on the map.

**Comment by grabz-dev** [comment]
Yeah, this is a little confusing, but not bugged - I originally assumed you just get one of each when it comes to special terrain, and didn't understand that these are slots that can be set to any special, and simply happen to be pre-filled with one of each.
