### ISSUE TITLE
"Copy build unit" behavior inconsistent between terp/greenar refinery and bombers

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#432]
Attempting to use the "copy build unit" keyboard shortcut to select a terp or a greenar refinery fails if the associated drone is docked or otherwise between the cursor and the unit. This is inconsistent with bombers and AC bombers, which (presumably correctly) select the appropriate pad for building when attempting to copy the bomber itself.

**Comment by HurkWurk** [comment]
second issue, copy terp does not copy the "nearist first" setting
