### ISSUE TITLE
[Bug.Minor] Incorrect rounding of ERN portal benefits

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#441]
![image](https://user-images.githubusercontent.com/40322714/101913302-de617800-3bd3-11eb-820a-589fd74c77fb.png)
Expected: base lab production is 1, ern gives +50% thus total is 1.5, the + is 0.5

In reality - the + shows as 0.4

**Comment by knucracker** [comment]
This is interestingly a difference between mono and il2cpp. The old method of ((int)(x * 10)) / 10f works and shows 0.5 when running under mono but 0.4 under il2cpp.  I've changed to a mechanism that does rounding (x.ToString("F1")) for showing the value.
