### ISSUE TITLE
Cannons do not appear to target "mesh" (digitalis?) or creeper any differently when priority is set.

### ISSUE THREAD

**Issue by xxJ6xx** [KnuckleCracker/CW4-bug-tracker#442]
During gameplay, cannons within range of both creeper and mesh do not visibly seem to change targeting priority when set either to just creeper or just mesh. I've seen this behaviour on multiple maps. Also, would be nice to have the old CW3 color change on cannons to indicate what targeting priority the cannons have.

**Comment by Karsten75** [comment]
To the best of our knowledge, based on testing and experience, targeting priority does make a difference. If you feel otherwise, please include screenshots and/or a save file that show the specific situation where you observe the aberrant behavior.

**Comment by Karsten75** [comment]
Closing due to no further feedback/lack of documentation
