### ISSUE TITLE
[Bug] Egg pathfinding getting stuck on Totem shields. Eggs also disappear into thin air.

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#446]
So this may actually be multiple bugs, I'm not sure.

I recorded the following (2min long) clip of my game: https://www.youtube.com/watch?v=-xFdR402Gn4 
In the clip, I have just powered up a totem whilst 4 eggs are within the shield range. I'll explain what happens in the clip and why it could be a bug.

First of all, when a totem shield activates any eggs that are within range of the shield will kind of "float" up on top of the shield. I assume this is a feature, though it looks a bit strange. Since eggs normally explode when they are not covered in creeper, I find it odd that they don't so so when on top of a shield.

Second, throughout the entire clip one of the 4 eggs is trying to pathfind its way to the center of the totem, but is unable to do so because the shield blocks it from getting closer. It seems to get stuck in a perpetual state of trying to reach the center. I wasn't able to record or find out how exactly it got stuck in this state, the game's recorder feature isn't of much use for tracking eggs whilst they are moving fast. I'm guessing it targeted the totem whilst it wasn't activated yet but the totem got activated before the egg was able to reach its destination.
![image](https://user-images.githubusercontent.com/74179010/101965675-cd395b00-3c15-11eb-9fa0-a6a4a72397be.png)

Lastly, the clip starts off with 4 eggs within the shield range. One of the eggs is stuck in pathfinding as mentioned above but the other three kind of slide off. Of those three eggs, the middle one slides off first and explodes into creeper at around [0:27](https://www.youtube.com/watch?v=-xFdR402Gn4&t=27s), as expected. The other two however, appear to not explode at all and simply disappear into thin air. This first happens around [0:53](https://www.youtube.com/watch?v=-xFdR402Gn4&t=53s), the egg doesn't disappear when it is still in creeper, but once a mortar blows up the last remaining bit, it vanishes. The recorder feature does show a skull symbol when this happens, but there is no explosion of creeper. My guess is that the edge of the shield somehow interferes with the spawning of the creeper deposit. It happens again with the third egg at around [1:47](https://www.youtube.com/watch?v=-xFdR402Gn4&t=107s), when a mortar blows up the creeper around it and the egg is on the very edge of the shield. No creeper is deposited, whilst the recorder does register the egg dying.

I don't think a log is necessary for this type of bug but I'll attach it anyways:
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5682156/output_log.txt)

**Comment by knucracker** [comment]
I've made it so that eggs will deposit their creeper when the detonate over a shield. Orbs will not (no change on them). That's why the egg was disappearing with no creeper. It was popping but not depositing any creeper.

The other case of a blob trying to drag an egg into a shield is working 'correctly'.  And the last case of an egg trying to get to a totem is also 'correct'.

**Comment by knucracker** [comment]
Upon further reflection I have changed eggs back so they do not deposit their creeper when over shields. To deal with the issue of 'disappearing', I have eggs emit a puff of yellow smoke when they attempt to deposit over a shield. Note that eggs emit over a 3x3 area. Each cell is evaluated independently for depositing creeper, or not. Each cell get's 1/9th of the egg payload and may or map not deposit creeper depending on if the cell in inside a shield or not. Each cell also independently produces a puff of yellow smoke. So you can get a situation where an egg releases some of its payload and some that is does not.
