### ISSUE TITLE
[4RPL] When enabling units from 0, there is no default tab

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#447]
[CriticalMass.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5682841/CriticalMass.zip)
 
In this map, the units are only enabled at 1:30 game time.

If you do that, then when the units are enabled, no tab is selected, resulting in an empty-looking menu. The player has to manually select a tab for any units to appear.
![image](https://user-images.githubusercontent.com/40322714/101980985-75810b00-3c7a-11eb-880e-cb0c4f8e1b85.png)

**Comment by knucracker** [comment]
This seemed like a special case where there were no tabs available and then 1 or more became available. So I check for that case.
