### ISSUE TITLE
[4RPL] C++ overlay goes on top of GameMessages

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#449]
![image](https://user-images.githubusercontent.com/40322714/101983350-a453ad00-3c8b-11eb-873a-9c5bb41ec0da.png)
![image](https://user-images.githubusercontent.com/40322714/101983358-addd1500-3c8b-11eb-8206-dc0b2777e168.png)

**Comment by knucracker** [comment]
I moved the c++ and hold base panels to be behind the in game message
