### ISSUE TITLE
[Bug.Minor] It is possible to remove contaminant even if decontamination is disabled

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#450]
Partially correlated with #298 

If a terp is used to change the height of contaminant-affected terrain the contaminant is removed. This is true, even if decon is turned off in game settings, rendering the decon toggle functionally non-functional.

**Comment by knucracker** [comment]
Changed it so that when decon is disabled in the game settings, a terp will not remove contaminant when terraforming. If decon is left enabled, then it will remove contaminant when terraforming.
