### ISSUE TITLE
[Bug.Minor] Texture of Shields causes z-fighting with bomber pads

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#451]
As the title says, whenever the visibility setting for "Hide Shields" is on, placing bombers within the shield range will cover them in a bright cyan texture, but the texture is placed at the same height as the surface of the bomber so the game doesn't know which texture to render on top of the other. This causes a flickering effect known as [z-fighting](https://en.wikipedia.org/wiki/Z-fighting). 

The cyan texture might itself be a bug, because it doesn't appear on any other units, though I'm not sure about that.

Here's a short clip showing the bug: https://youtu.be/cOeoyUpnnTI

**Comment by knucracker** [comment]
Budged the flattened shield a tad lower
