### ISSUE TITLE
[4RPL] Shift+Insert does not work if SetUnitsSelectable (false) was called.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#452]
1. Call SetUnitsSelectable (false) in a script.
2. Units cannot be force-selected.

[CriticalMass.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5683736/CriticalMass.zip)

**Comment by knucracker** [comment]
The UnitsSelectable state was 'global' and meant to lock everything out. I have relaxed it so that when pressing shift-insert it is temporarily suspended, if set.
