### ISSUE TITLE
[4RPL] Global scripts do not restart when recompile/update unit instances is hit.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#453]
1. Make a script that calls SetUnitsSelectable(false) in :once
2. Make it a global script.
3. Let the game run for 1 frame.
4. Units are now not selectable.
5. Edit the script, changing "false" to true.
6. Compile scripts/update unit instances/reset map data
7. let game run for 1 frame.

Expected: Units are now selectable as per amended script.
Reality: Units still not selectable.

Removing and re-adding script to list of global scripts fixes this.

**Comment by knucracker** [comment]
When compile is called, the game will new null out the global scripts. Upon next execution, they will regenerate with the newly altered scripts.
