### ISSUE TITLE
[Bug] Blob coming from outside scenario

### ISSUE THREAD

**Issue by fryguy1492** [KnuckleCracker/CW4-bug-tracker#456]
Parasite level.

Can't kill some blobs cause sometimes they get out from scenario end then come in again. My snipers can't "see" them when it happens.

![Sin título](https://user-images.githubusercontent.com/19964455/101998801-3fad4800-3cb5-11eb-9200-1fe5da37feb5.png)

**Comment by Regallion** [comment]
@fryguy1492  on this map, the area you are seeing is actually void, not outside of the map. It shows up as a black border on the minimap.
Somewhat mean of the mapmaker, but not actually a bug.

**Comment by knucracker** [comment]
Yeah, this map was made a long time ago and imported from a CW3 map. At the time CW4 only supported maps of certain sizes. So when it was imported from CW4 a void border was added to the map to make it the correct size. I've left most of the maps in the Span as untouched as I could get away with reasonably. That is supposed to be part of their flavor... that they were maps used during development and contain eccentricities.

**Comment by fryguy1492** [comment]
"it's not a bug, it's a feature"!!! hahha, got it!
Congrats on the game, my favourite since CW1 was published en kongregate
