### ISSUE TITLE
Total energy failure.

### ISSUE THREAD

**Issue by SAnzivino** [KnuckleCracker/CW4-bug-tracker#457]
Help us help you. 

Mission: Cheap Construction.
A lot of things went wrong, so ill start with a picture.

![CW4Error](https://user-images.githubusercontent.com/52632773/102000820-39b96600-3cb9-11eb-8137-105a67f335e2.PNG)

Point 1, Top left: Energy collection, storage and related graphs are all 0.
Point 2, Top left: Factory is at 0.
Point 3, Bottom Left: Graphs are all zero. (Note, height map works, but I didn't have my cursor on anything in the screenshot.)
Point 4, Middle: Eggs falling through map.

Problems that are not directly visible from screenshot. Packets are not flowing. All packets seem to be frozen in place. Towers that are being used are out of energy / not receiving resupply.
Towers that were hit by a skimmer stun are not being un-stunned. This is a group of mortars on the top right.
Also most of the small projectiles (bombers bombs, mortar shots) that were in air when this occurred are frozen in space.

So, I want to be helpful but I have almost no idea what caused this. My best guess is that it is related to a skimmer hitting the units I have on the top left. I have a micro-rift there (I don't think it was hit) and I don't know if that caused a problem.

Unfortunately I do not know how this bug could be re-created. If I knew where the saves were stored I will provide the save of the mission.

Thanks!
[output_log - Copy.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5684064/output_log.-.Copy.txt)

**Comment by Karsten75** [comment]
There is enough data in the output log you provided. Hopefully. 

Save files are in your `documents folder/my games/creeperworld4\saves\span\knucracker8\`  and then the name of the save

**Comment by knucracker** [comment]
Same cause as issue #420, which will be fixed in 1.0.1
