### ISSUE TITLE
[4RPL] ADA text editor slightly broke

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#458]
I was copy-pasting some stuff when this happened.

![image](https://user-images.githubusercontent.com/40322714/102015456-ca04b300-3d6c-11eb-9ba6-275f4f728cce.png)

The text in question is "Alarm2".
Map file: 
[CriticalMass.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5684769/CriticalMass.zip)

**Comment by knucracker** [comment]
That's a bug in the textmeshpro text editor control included with unity... I've seen it myself. My hope is they will eventually fix it. The only workaround I have is to copy all of the text out, delete the contents and then paste it back. Sometime I have to do it in batches (break up what I paste back).

If I  move to unity 2019 (a large 'if') there's some chance this might be affected (a small 'some').

**Comment by knucracker** [comment]
I've updated to unity 2019 and also updated TextMeshPro to the latest version (2.1.3). On the test map it does not make a difference in the editor when loading the mission save. However, there's some chance it might not occur again from scratch (when typing in a new text editor). Not sure, just a chance. Either way I can't do too much more about it at this time.
