### ISSUE TITLE
[Bug.Minor] M-RIFT placement on platform restriction, intentional?

### ISSUE THREAD

**Issue by MutexMorgan** [KnuckleCracker/CW4-bug-tracker#459]
M-RIFT can't be placed on platforms, while shields, refinery and a nullifier can.

No need for any screenshots logs or save-files, it can be re-created in editor almost instantly as well as being confirmed by few community members.

It would have use, for maps such as [these](https://cdn.discordapp.com/attachments/787697783791681556/787698403194306560/DEC_5_2020.cw4rec)

**Comment by knucracker** [comment]
There was really no reason to not allow microrifts on platforms. I've updated them to be allowed. I also made it so beacons can land  on platforms.

**Comment by MutexMorgan** [comment]
What about porters?
It would be nice to have them allowed to be placed on corners of 4 platforms close to each other as well

**Comment by knucracker** [comment]
Yeah, they were added yesterday when I was looking at this. I've not added their issue to github yet, though.  So they will also work on  platforms if you build 4 platforms and make a 6x6 area between them

**Comment by MutexMorgan** [comment]
Alright, thank you for your great work on this great game.
