### ISSUE TITLE
[Bug] Negative emitters are not affected by C++, but their tooltip is

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#461]
1. Create a map.
2. Add an AC emitter to it
3. enable C++

Expected: As C++ level increases, emitter emission increase, the change is reflected in the tooltip.
Reality: As C++ level increases, AC emissions do not change, however the tooltip does change.

Of note, it's a bit unclear, but does C++ affect payloads of spores/sacs/blobs/skimmers? What about negative payloads on those? This is unclear since you can't see their stats in-game.

**Comment by knucracker** [comment]
C++ Doesn't affect the payload of the other units. It affects emitters output and it lowers the void overflow threshold.
Fixed the tooltip for the emitter when it emits an negative amount.
