### ISSUE TITLE
[Suggestion] Make build menu shortcut keys consistent across all maps

### ISSUE THREAD

**Issue by wobblycogs** [KnuckleCracker/CW4-bug-tracker#463]
The menu shortcut keys for buildable items change depending on what you can build in a mission. For example the mortar is normally "F2" followed by "2" unless the cannon isn't allowed in that mission in which case it's "F2" followed by "1" (contrived example, I think the cannon is always present). This is frustrating as it breaks muscle memory of shortcuts.

**Describe the solution you'd like**
Just leave blanks in the menu for items you can't use in that mission or otherwise keep the the shortcuts the same all the time. I want an AC bomber to be "F3-3" on every map.

**Comment by marmilicious** [comment]
Yes please.  This would be very nice for keyboard selection consistency.
