### ISSUE TITLE
Minor bug with the missile launchers texture

### ISSUE THREAD

**Issue by MiaMesa** [KnuckleCracker/CW4-bug-tracker#465]
Missiles from the missile launchers turned blue, and with an incorrect texture.

It seems disabling the missile launchers and re-enabling them does this, the missile launchers do work as intended, but their missiles remain that way.

**Additional context**
This glitch happened on a custom map, "Among the ruins" ID#6. Don't know if it has a link with the map or not.
![image_2020-12-14_163410](https://user-images.githubusercontent.com/74882806/102100852-32659a00-3e2a-11eb-9331-0abd6656eeab.png)
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5689769/output_log.txt)

**Comment by knucracker** [comment]
I removed the missiles from the unit texture so they ignore the unit disabled state. This will prevent the missiles from getting reset to the wrong texture after the unit is enabled.
