### ISSUE TITLE
[Bug] Game dialog button becomes unresponsive after a save

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#466]
Two save files attached for the issue:

Most likely scenario is that the game is saved immediately after the message pops up

[quick.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5692128/quick.zip)
[sage Plot.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5692131/sage.Plot.zip)

**Comment by knucracker** [comment]
The InGameMessage was not loading it's persisted data correctly (was off by 1 letter). So it was not loading its autoclose state. Also, when that was fixed it was not using the correct constructor to pass in the autoclose state.
