### ISSUE TITLE
[Bug] Cannot create mission-saves with special characters like ?>:< but "Saved" dialogue shows anyways

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#471]
Title explains the bug pretty well. 

Since the name you put as the name of a save is used in the actual filename, symbols like /:*\?<>"| are not supported. Attempting to save a mission-save with such characters in it doesn't show any error or message of any kind, in fact, it even shows the green "Saved" dialogue at the top of the screen, despite no save file actually being created.

Creating a custom map with these characters will show a message "Name contains invalid characters" and stops you from continuing, a similar check should be put in for saving missions mid-game.

Here's a short clip of the bug: https://youtu.be/aISXh8xjCNU

**Comment by knucracker** [comment]
Added a check for legal file name characters when attempting to save file.
