### ISSUE TITLE
[Suggestion]  Unit copy for all units are not implemented

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#473]
By default Tab key copies a unit and allows placement of a similar unit with similar attributes copied from the origninal. 

In the editor this is a handy tool, but not all structures permit this. 

Please extend Tab-copy to all units?

Reference: 
https://steamcommunity.com/app/848480/discussions/0/2990917484147198475/

**Comment by Regallion** [comment]
#182 #385
