### ISSUE TITLE
[Bug.Minor] Exiting top-down view whilst zooming in or out places the camera way higher or lower than it should

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#479]
I noticed I sometimes get zoomed in way too far to the ground when I'm using my hotkey to switch between top-down view and 3D view.

How to reproduce:

1. Enter top-down view
2. Zoom all the way out
3. Begin scrolling forward to zoom in
4. Immediately use the hotkey to switch to 3D view
5. The camera ends up much lower than it should, even zoomed all the way in if you do it quick enough

This works with both zooming in and out, though zooming out seems to only bring you half as far, whilst zooming in can bring you from all the way zoomed out to all the way zoomed in instantly.

Clip: https://youtu.be/f3wHM-cS9n0

**Comment by knucracker** [comment]
This was caused by the zoom tween/animation still playing after the orthographic mode  was toggled. I changed it to cancel the camera zoom movement when the ortho mode is changed.
