### ISSUE TITLE
[Bug.Minor] Centering the camera whilst holding right click makes the camera freak out

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#480]
Centering the camera whilst holding right click will cause the camera to jitter back and forth, it seems the game is fighting between which action it should listen to, moving towards the center or staying in place because Move Map is held down.

How to reproduce:

1. Hold right click (or whatever Move Map is set to) anywhere on the map whilst being not completely centered
2. Press the hotkey for centering the map, I think it's C by default
3. Watch how the camera flickers until the centering animation is done.

Clip: https://youtu.be/iB3VsW3jMGY (Make sure to watch it in 60fps, you don't really see the flicker at 30fps)

**Comment by knucracker** [comment]
It's caused by the tween trying to center the camera. The alternative is to not do the tween, but then the center would not happen if it was pressed just before the user let go of the right mouse button.  I can live with it the way it is
