### ISSUE TITLE
Make ERNs not avoid creeper

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#483]
On some wild maps when your ERNd weapons are in the frontline and die in creeper, it is very unpleasant that the ERN, even if wanted from a unit two cells away, goes to the top of the creeper like a bubble in the sea instead of diving through the creeper. Depending on the situation it can last a minute or so to get the ERN out of the surf.
Otoh, when ERNs swim lore-wise, then this is of course the way it has to be...

**Comment by knucracker** [comment]
With the minimap now available and showing the location of ERNS, plus the ERN Portal build button showing the counts... yeah, why not.  I've changed it so that ERN's don't really care about creeper, they still respect the terrain, but will plow through creeper.
