### ISSUE TITLE
[Bug] Steam Sync don't work

### ISSUE THREAD

**Issue by Cassetete** [KnuckleCracker/CW4-bug-tracker#485]
To reproduce, install CW4 on another PC and start the game. The game start with tutorial.

On my "main" computer, I finished 19/20. And do some another map. So, It's not normal. No?

**Comment by Cassetete** [comment]
Ho, and ya, the sync is activate for the game and on both PC.

**Comment by knucracker** [comment]
Steam sync is under the control of steam. Make sure you have it enabled in the properties for the game. Steam is configured to sync data under your Documents/My Games/CreeperWorld4 directory. So long as you are on the same account, have it enabled for the game, the steam client should sync

**Comment by Cassetete** [comment]
However, I enabled on both PC.
I noticed weird information, in properties for the game, just ebelow the checkbox for sync, I see "2.20 KB / 95.37 MB". 
2.2 KB it's weird when I compare the real size of "Documents/My Games/CreeperWorld4" is 227 MB. May be steam not sync when over the limit.
When I check the C:\Program Files (x86)\Steam\logs\cloud_log.txt, only two files is sync : 
[2020-12-17 23:31:12] [AppID 848480] File is in sync My Games/creeperworld4/data/achievements.dat
[2020-12-17 23:31:12] [AppID 848480] File is in sync My Games/creeperworld4/data/mcs.dat

![image](https://user-images.githubusercontent.com/18293669/102657975-acf12b00-4144-11eb-84b1-760cbfaa9a68.png)
![image](https://user-images.githubusercontent.com/18293669/102658343-651ed380-4145-11eb-83de-ce7d81b4c826.png)

Note : All others games in my steam account with sync, work.

**Comment by knucracker** [comment]
That's correct. Only *.dat files sync. The file, mcs.dat contains all of your mission progress (which missions are unlocked).

**Comment by Cassetete** [comment]
Ho, I founded, I just retest on new PC, the menu is always show "start here" and other menus is disabled. But, I view that the "chronom" has one complete and span experiments show "1/26"... 
So I click on "Farsite expedition", then click "return"... and voilà, the game menu is now "unlocked". Yé!  :-)

Probably you saved the state of "tutorial" in another file that the .dat  :-)
