### ISSUE TITLE
[Suggestion] Make decay status of walls easier to see visually

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#49]
**Is your feature request related to a problem? Please describe.**
It is difficult to visually see blue walls' decay status.

**Describe the solution you'd like**
Place a black square border on the top face of each wall that has less than 100% health, which should make it easier to spot wall health relative to their neighbors.

I also want to say that the checkered pattern on the walls might be making it harder to see, I feel like earlier wall designs were easier on the eyes:
![image](https://user-images.githubusercontent.com/51026936/94994080-aadfed00-0595-11eb-9993-63b1efd5b211.png)

**Comment by knucracker** [comment]
Made walls change to red when they aren't at 100%
