### ISSUE TITLE
Game music volume inconsistent

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#491]
The game music volume varies between tracks, such that it's difficult to balance one's settings so that it's neither too quiet nor uncomfortably loud.

**Comment by knucracker** [comment]
I've not noticed this. The soundtracks were all volume normalized by the composer. Now naturally they vary within tracks (the intense moments vs the less intense moments). Are you using any volume altering software (audio effects, surround sound emulators, noise canceling headphones), etc?

**Comment by Squornshellous-Beta** [comment]
I am not; just ordinary headphones. I do have a hearing impairment that I suppose might be affecting my perception of it, though.
