### ISSUE TITLE
[Bug] Porter Landing Pad images [1.0.1 Beta]

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#493]
In 1.0.1 Beta I get this:

![porterPads1](https://user-images.githubusercontent.com/72889843/102575391-fef06d00-40c0-11eb-9174-6be206c6a899.png)

Going back to the regular version results in this:
![porterPads2](https://user-images.githubusercontent.com/72889843/102575514-3ced9100-40c1-11eb-9727-14c1fb098bf9.png)

**Comment by knucracker** [comment]
Apparently unity thought it wise to change the vertex order on the built in quad primitive. Had to reshuffle the uv assignment order.
