### ISSUE TITLE
[Bug.Minor] Opening 'Enter Lab' button [1.0.1 Beta]

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#494]
In 1.0.1 Beta I see this button:
![openButton1](https://user-images.githubusercontent.com/72889843/102575879-3a3f6b80-40c2-11eb-9816-e6be6c9af1e0.png)

In live version I see:
![openButton2](https://user-images.githubusercontent.com/72889843/102575890-41667980-40c2-11eb-97d7-a26e74f1a51a.png)

Text is exceeding the button a bit

**Comment by knucracker** [comment]
Another small font issue. Fixed in 1.0.2
