### ISSUE TITLE
[Bug] When Anti-Creeper passes ~2145 depth it becomes Creeper.

### ISSUE THREAD

**Issue by Exie610** [KnuckleCracker/CW4-bug-tracker#495]
5. Describe the bug 
   As per the title, any time a point of Anti-Creeper passes ~2145, it becomes ~2145 Creeper. 

   This bug is easiest to recreate by having AC Bombers target a small (smaller is better, for speed reasons) island. It can also easily be accomplished by having a swarm of Sprayers use their AC Collection field while in close proximity to one another in relatively deep anti-creeper. When using the Sprayer method, you will witness them shooting while taking damage.

   Attached are two screenshots. The first has a small island (Under the targeting cross) with 2141 AC. Game time is 1:48:51.7 - there is NO creeper on the map at all, and all enemies are neutralized. The second screenshot is taken at 1:48:51.9 - you can clearly see the island now has 2145 creeper.

   This bug may be reproduced on any map regardless of type.
![AC 1](https://user-images.githubusercontent.com/76196350/102578350-8f2db280-40bf-11eb-9368-4d4e2b034dcb.png)

![Creeper 2](https://user-images.githubusercontent.com/76196350/102578363-948afd00-40bf-11eb-856f-827a04556a60.png)

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5713842/output_log.txt)

**Comment by Exie610** [comment]
If I were to guess, this happens at exactly 2,147 depth and that AC is calculated out 6 decimals. If this is the case then this issue is the maximum value of a signed 32-bit integer.

**Comment by Regallion** [comment]
yes, this is known as Creeper Overflow and while it was a bug back in CW2, it has been accepted as a deliberate feature in later titles.
Some maps even use it as a gimmick. 
Not a bug, intended gameplay for advanced cases.

**Comment by Karsten75** [comment]
This is an established game mechanic since CW2. The overflow is used to flip between Creeper and anti-creeper.
