### ISSUE TITLE
[Bug] Undismissable InfoCache message [1.0.1 Beta]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#497]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5715623/save.zip)

collect the info cache.
try to dismiss message.
You can't.

![image](https://user-images.githubusercontent.com/40322714/102614832-fa21cc80-4145-11eb-91da-01bdac7567c0.png)

**Comment by knucracker** [comment]
For infocaches, I have made autoclose always be on if there is a message. It used to be an option, and then in 1.0.1 it was tied to the pause state. Now it is on all of the time.
