### ISSUE TITLE
[Bug.Minor] Editor field labels are wonky with long inputs [1.0.1 Beta]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#498]
![image](https://user-images.githubusercontent.com/40322714/102615081-5f75bd80-4146-11eb-93e2-850afba4dd64.png)

The input is AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbB

**Comment by knucracker** [comment]
I set a min size on the label so it can't get squeezed to super small
