### ISSUE TITLE
The right half of the 'Filter Group' input box clicks the 'Filter' button

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#5]
Clicking anywhere in the red box hits the 'Filter' button instead of the 'Filter Group' input box.
![image](https://user-images.githubusercontent.com/51026936/86034291-99d58c00-ba3a-11ea-903f-521ffb102a09.png)

**Comment by knucracker** [comment]
Why does Unity default ui text fields to raycastable?  A mystery forevermore.  As usual, there was a text element that was too big for the container and it was set to raycastable, so it was catching the mouse clicks.
