### ISSUE TITLE
[bug] Creeper spawned inside a wall is stuck without eroding the wall

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#50]
In the last mission, a spore hit exactly here:
![image](https://user-images.githubusercontent.com/51026936/94998772-a7a82980-05b4-11eb-9c94-71dce41f11b9.png)

A single adjacent wall has eroded, and the creeper is stuck inside the wall:
![gif](https://user-images.githubusercontent.com/51026936/94998869-63695900-05b5-11eb-865c-42a90a337d42.gif)

Confirmed by K75 that this happens when creeper is spawned inside a wall.

**Comment by knucracker** [comment]
Changed it so that the wall 'containing' the creeper will decay. Adjacent walls will not decay while it is contained in a wall. The creeper also will not flow out until the wall decays.
