### ISSUE TITLE
[Bug] Very long InfoCache messages cannot be dismissed [1.0.1 Beta]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#500]
[11.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5715691/11.zip)

![image](https://user-images.githubusercontent.com/40322714/102615998-e4150b80-4147-11eb-881c-f6bd3bda872d.png)

**Comment by knucracker** [comment]
I've added the text messages and the buttons to a scrollview. That limits the max width and height. For, I think, most all messages and buttons found in the story there will be no impact. For tall messages, or wide buttons, or window sizes that clip messages, a vertical scrollbar should appear.
