### ISSUE TITLE
[Bug] When info caches are collected simultaneously, conflict occurs.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#503]
[11.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5717791/11.zip)

Run the mission.

Instead of allowing you to see all 3 messages (of different types and pause controls) only one message is shown.

**Comment by knucracker** [comment]
I put a queue in place for  in game messages. If an in game message is called when there is already an in game message showing, it gets queue and will be shown when the previous message is closed. This queue is also persisted to the save game if the game is saved while a message is showing. 

I've done this sort of thing before so you can rest assured there won't be any issues.  No sirree, not a chance of a problem in a story mission. I'm confident in that. You can bank on it.
