### ISSUE TITLE
[Suggestion] Please add a "Mute" button to the menus 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#505]
often-times one needs to mute music when on the main menu or other menus. It is not possible except by navigating to options, selecting audio (sound) and moving the volume slider. Then, when one wants sound again,  one has to do this dance over agian. Many times, 

A small mute button on the main menu would do wonders to alleviate frustration.

**Comment by knucracker** [comment]
- Linked the mute (found in the top right of the game) to the main menu music as well as the in game music. 
- Added a mute toggle to the main menu
![image](https://user-images.githubusercontent.com/6733225/102676428-7c70b780-416b-11eb-8b8f-cf23cbe002c9.png)
