### ISSUE TITLE
[Bug] Farsite displays wrong objective in expedition screen (DEMO ONLY)

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#507]
In the demo version, this objective can never be green because it's supposed to be Totems:
![image](https://user-images.githubusercontent.com/51026936/102680610-1e1ef580-41ba-11eb-9d3d-1d1a87ed0df0.png)

**Comment by knucracker** [comment]
Fixed in the 1.1.1 version of the demo. The steam demo and a non-steam version of the demo are being updated and released soon.
