### ISSUE TITLE
[4RPL] Global control tab does not properly refresh.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#510]
1. Start a mission with 2 CPACKs
2. Add a global control in CPACK 1
![image](https://user-images.githubusercontent.com/40322714/102692723-53f9c380-4226-11eb-8227-41c661b97df4.png)
3. Switch to CPACK2
4. Expected: Global control tab contains only scripts from CPACK 2 but not CPACK 1. If you refresh it manually, it will be so.
5. Reality: Tab still shows script from CPACK 1

**Comment by knucracker** [comment]
Added a call to refresh the global list when the cpack is changed.
