### ISSUE TITLE
[4RPL] GetKeyDown does nothing, GetKeyUp doesn't compile

### ISSUE THREAD

**Issue by SanderWassenberg** [KnuckleCracker/CW4-bug-tracker#512]
The GetKey function works as expected, but the GetKeyUp and GetKeyDown functions don't. It's possible that they shouldn't work at all, but at least GetKeyDown is compiled normally, calling it just does nothing. GetKeyUp doesn't even compile.

The following code compiles but does nothing, the values aren't consumed from the stack

```
GetKeyDown("C" 0) TraceStack
```
The following code doesn't even compile

```
GetKeyUp("C" 0) TraceStack
```

This code on the other hand works as expected:

```
GetKey("C" 0) TraceStack
```

The reason I'm confused about this is because GetMouseButton and its respective GetMouseButtonUp/Down functions do work normally

**Comment by knucracker** [comment]
GetKeyDown was commented out, but I had it implemented. I didn't use it for the story, so I left it out. I've added it back in. We'll see how it works.  GetKeyUp is not implemented and won't be unless there is some really compelling need.  

The game, by default, updates at 60fps with the game logic updating every other frame. This creates an issue for implementing the up and down handlers. For the down handler, I can work off of the GetKey call and then remember state (and some other complicated logic). For the up handler, I can't use the same technique. The only way to do it would be to remember  every key that is down, check all keys, or require registering which keys to monitor.  None of those things are appealing.  I also think it is possible to handle this from within specific 4rpl code on a case by case basis.
