### ISSUE TITLE
[1.0.1] Fullscreen exclusive mode - Mouse pointer gets big 

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#515]
When you choose a resolution lower than your native resolution and switch to the fullscreen exclusive mode, the mouse pointer gets bigger (the lower the fullscreen resolution, the bigger the mousepointer)

**Comment by knucracker** [comment]
What resolution are you switching to?  That sounds 'correct'. Exclusive mode is the same thing as changing your desktop resolution. If you change to 640x480 and use exclusive mode, that's the same as switching your windows resolution to 640x480 and then running the game. If you do that in windows, I expect your windows mouse pointer will be large.

**Comment by BilboGCL** [comment]
I switch from 3840x2160 (native) to 1920x1080.
Probably it is correct, but as everything else scales pretty great with the UI-slider, the mouse pointer sticks out.

**Comment by knucracker** [comment]
I'll research it, but it's a hardware cursor and I don't know that I have any control over the size (other than making a smaller image to assign to it).
