### ISSUE TITLE
[1.0.1] Icons in recorder output are a bit strange

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#516]
This is a video with the 1.0.1. beta:

https://user-images.githubusercontent.com/16858356/102703172-c8a32100-426b-11eb-8d74-e592270efb04.mp4

**Comment by knucracker** [comment]
More quad shenanigans from unity. The changed the vertex order on the the quad primitive between 2018 and 2019 apparently.
