### ISSUE TITLE
[4RPL] Default settings for scripts attached to units are ignored

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#517]
When you attach a script to a unit, the CPACK manager has an option to set initial parameters for the script:
![grafik](https://user-images.githubusercontent.com/75800362/102713741-a55b8e80-42ca-11eb-853b-03bc9f362fac.png)
![grafik](https://user-images.githubusercontent.com/75800362/102713777-d63bc380-42ca-11eb-80fb-3444ebdf5106.png)

After placing the unit and selecting it, the editor displays the default values correctly:
![grafik](https://user-images.githubusercontent.com/75800362/102713791-e489df80-42ca-11eb-8059-3465f7c3db1b.png)

But when the script executes, the entered values are ignored and replaced by the default values defined in the script.

My code:
```
$myName:"defaultName"
$var1:"defaultValue"

:once
	"value_2" ->var2
	PrintAll(<-myName ": running once block")
	PrintAll("var1 = " <-var1 ", var2 = " <-var2)
```

Output in RPL.txt:
```
onceTest.4rpl: defaultName: running once block 
onceTest.4rpl: var1 = defaultValue, var2 = value_2
```

**Comment by e-d-u-r-a-n** [comment]
Additional remark: The same does NOT happen for global scripts. They work as expected. Units also work fine if values are assigned in the mission editor for each individual unit.

**Comment by knucracker** [comment]
The cmod settings were being crammed into the input settings on the scripts, as far as the UI was concerned. They were not actually being applied to the cores that hold the scripts. I had to add a setCModInutVars map to go along with the setInputVars map held by each core. Each are setup when a cmod is created and each applied in the Compile now.
