### ISSUE TITLE
[Bug] Flipping target_frame_rate

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#523]
I was browsing through some CW4 files and found the analytics stored in the appdata directory. I noticed that for some logs the target_frame_rate keeps flipping between 30/60. Is this intended for performance reasons or might this be a bug?

I have included an ArchivedEvents analytics folder and the output_log.txt. <- These do not belong to the same session I don't think!

Will keep an eye on the logs if this might indeed be due to a bug and logs from one session would help.

[Analytics 160829914100004.52171f5c.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5724193/160829914100004.52171f5c.zip)
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5724194/output_log.txt)

**Comment by Regallion** [comment]
Yes, if your UPS is sufficiently low, the game will lower the FPS to 30 to increase performance, then bring it back once UPS increases.
This can result in a Yo-Yo effect, but is naturally intentional ^_^

**Comment by PRG-YouTube** [comment]
Indeed, checked the GPU load during gameplay and it does seem to be fully loaded lots of the time.
