### ISSUE TITLE
[Suggestion] Stop weapons attacking targets within a Dark Tower's area of influence

### ISSUE THREAD

**Issue by Storm315** [KnuckleCracker/CW4-bug-tracker#524]
All weapons should not attack targets with a Dark Tower's area of influence since it is futile. Their behavior should be limited to only viable targets within their range, outside a Dark Tower's influence. This should be part of their default behavior. If no viable target exists then the weapon should hold its fire in order to not waste resources attacking a target they can not damage.

**Comment by Regallion** [comment]
N-no? What? Creeper in the range of dark tower is not immune, as any quick check with a map editor would verify.

**Comment by Storm315** [comment]
Thank you for the quick clarification of what is normal behavior.
