### ISSUE TITLE
[Suggestion] Add "Disable minimap warn" to more default units

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#528]
Since the introduction of a new "Location" type of unit targeting, it is now possible to use blobs, spores, airsacs and skimmers as remote creeper delivery systems to dedicated locations. In case of blobs it's also a way to create streams of blobs to deny certain map areas.
However, only blobs allow you to suppress minimap warnings. Allowing that functionality for other units could reduce the clutter on the minimap warn when rapid-fire enemies are present.

**Comment by knucracker** [comment]
Added to all 4 main nest types, not just the blob nest.
