### ISSUE TITLE
[Suggestion] Suppress spores visual option.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#530]
![image](https://user-images.githubusercontent.com/40322714/102819440-85b88900-43e4-11eb-8d41-e92cadab066b.png)

Currently, spore visuals are a little too flashy, when used en-masse.

The attractiveness and shine are pretty good when you have 3-8 spores at a time, but when you launch them like candy, it becomes a bit much.
Being able to at least turn off the glow and maybe even hide the lines could probably be helpful towards uncluttering it.

**Comment by Karsten75** [comment]
this did get implemented in a fashion, spore lines can be suppressed, not the actual spores.
