### ISSUE TITLE
Certain areas of the map not accessible

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#533]
In this screenshot, the upper cannon is selectable (x positon: 61), the lower one not (x position: 60). This is true for all Z=>65
In the same area, you can't build new units.
![image](https://user-images.githubusercontent.com/16858356/102832012-7d188080-43ed-11eb-8296-bcf02b2a3bd6.png)

These are my settings (native 3840x2160):
![image](https://user-images.githubusercontent.com/16858356/102832227-0fb91f80-43ee-11eb-852d-0adb5292bba0.png)

**Comment by e-d-u-r-a-n** [comment]
Had the same problem. I think the issue stems from the hidden factory / ERN portal UIs.

![grafik](https://user-images.githubusercontent.com/75800362/102932257-3afc4700-44a0-11eb-8528-267f6bbe8a85.png)
![grafik](https://user-images.githubusercontent.com/75800362/102932266-3e8fce00-44a0-11eb-82be-eddcf7749c4f.png)

The Pylon in the screenshot above is selectable if I click on its lower half, consistent with where the UI would be.

**Comment by knucracker** [comment]
Yeah,  it is the hidden factory and ern portal buttons that were blocking it (actually, it was a transparent image behind them). I've removed that image and am not entirely sure why I had it there. Could have been as a UI blocker one upon a time and it no longer necessary.
