### ISSUE TITLE
[Suggestion] save backlog for daily content

### ISSUE THREAD

**Issue by DeadlyKitten37** [KnuckleCracker/CW4-bug-tracker#534]
**Is your feature request related to a problem? Please describe.**

to me the draw of daily missions/content is 2 primary types
a) a (often large) backlog of content once i have completed the main campain/content
b) new content available when I want to look at it

the current setup (only saving the past 5 days) fails part A entirely due to old missions being deleted and fails the 2nd part of part B due to it being deleted after less then a week

**Describe the solution you'd like**

save all previous daily missions and allow people to go back at their leisure 

**Describe alternatives you've considered**

a) just make the rolling buffer larger (like 2 years or half the current lifetime of the game)
this would allow a large buffer (~700 missions) but still allow old missions that you want forgotten to eventually leave

b) ignore problem
community content and mark V already do a fairly good job of both attractions (i think the daily missions might just be mark V entries anyway)

**Comment by Karsten75** [comment]
*The wise leave the past where it belongs.
They do not carry around old quarrels or grudges,
Nor do they unearth that which lies peacefully at rest
In efforts to undo what has already been done.
The wise learn a great deal from passing moments,
Then bid them goodbye forever
Like water under the bridge.*

**Comment by DeadlyKitten37** [comment]
It is your game, If this is your choice I will leave after this last comment.
I would request you extend to either 8, 15, or 29 days, this would allow those who only play one a week to not feel that they are missing out by not coming mid week, 15 and 29 would allow the same (or cherry picking the best) for 2 or 4 week intervals respectivly
