### ISSUE TITLE
[Bug] roll over if there is too much creeper / AC in one place

### ISSUE THREAD

**Issue by DeadlyKitten37** [KnuckleCracker/CW4-bug-tracker#535]
image 1 AC at a spike in creeper caused by 3 singularities in one place. note white tip and lack of AC lines
![image](https://user-images.githubusercontent.com/53106272/102844507-d3bf9380-43c8-11eb-8b97-af680f3772f8.png)

image 2 level of creeper before and after the prosses above was done several times, flat section is before (200) wavy section is after
![image](https://user-images.githubusercontent.com/53106272/102844317-6dd30c00-43c8-11eb-9b6f-3910208f2b7f.png)

Image 3 AC sprayers in collect mode turning AC into creeper (A) with guns near by shooting at it (B)
![image](https://user-images.githubusercontent.com/53106272/102845354-9e1baa00-43ca-11eb-999f-84d1fc297606.png)

image 4 AC lever before (50) and after i reset both sides ac to 50, create 6 ac sprayers (2 groups of 3) all set to ac collection wait for things to settle down (about 10 mins at x4 speed) then turn them off and wait to settle down again
![image](https://user-images.githubusercontent.com/53106272/102846233-ac6ac580-43cc-11eb-9edb-d8dcca64bcf1.png)

Describe the bug 
if too much C/AC is in 1 tile it will spontaneously turn into the other. I assume (but do not know for certain) this is due to a roll over error turning positive numbers into negative numbers
this is common when using multiple (3 or more) ac sprayers or singularities

**Comment by Karsten75** [comment]
Creeper and anti-creeper is like yin and yang - one complements the other. By design, too much of one becomes the other. It has been this way since Creeper World 2, when anti-creeper was invented by Aliana Abraxis. 

The issue with the Sprayer. That is in the fix list for 1.1 - after that the Sprayer will not be so enthusiastic about collecting massive amounts of AC around itself to the point where it falls into the trap of "too much of a good thing is a bad thing".

**Comment by DeadlyKitten37** [comment]
2 requests
The first is for information, how much c/ac is required before rollover?
The 2nd about enthusiastic about ac collectors, please make sure it still works, a - with a single collector cleaning up an area (make sure it still mops up the area), and b - with 30 all next to each other all pulling ac toward them in a deep area (make sure it does not delete stuff). basically testing the extremes to make sure it still works as expected
