### ISSUE TITLE
[Bug] Deleting custom units from a CPACK does not delete them from the map, but they do disappear upon saving and re-entering the map.

### ISSUE THREAD

**Issue by Sanian-Creations** [KnuckleCracker/CW4-bug-tracker#536]
Applies to v1.1.0

(1) Removing a custom unit from from its CPACK does not remove any instances of that unit from the actual map. If the map is _saved_ and then opened again, the units are suddenly gone. Since they don't persist over saves, they should probably just get removed from the map entirely the moment they are deleted from the CPACK.

(2) Deleting the units from the CPACK also doesn't update the _Mods_ tab in in the Mission editor properly, if the Mods tab was opened when the unit got deleted then its name will remain in the list until the _Mods_ tab is closed and opened again. For the duration that it is still in the list it can even be placed normally.

Here's a <1m clip of me explaining/demonstrating the bug: https://youtu.be/f-GYAX3ZehM

**Comment by e-d-u-r-a-n** [comment]
(3) Removing an entire CPACK does not remove any units defined in the CPACK from the map. As with (1) and (2), they vanish on save/reload.
