### ISSUE TITLE
[Typo] Branch CPACK message cut off

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#538]
The message on the screen that comes up when you branch a CPACK ends mid-sentence:
![grafik](https://user-images.githubusercontent.com/75800362/102910838-7d5f5d00-447b-11eb-8eb3-47824386485d.png)

Screen resolution is 1920x1080 with default UI scale.

**Comment by knucracker** [comment]
One more font thing broken by the 2019 switch
