### ISSUE TITLE
[4RPL] Forbidding selection of a moving unit causes weirdness

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#539]
[TestOfScriptFail.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5731488/TestOfScriptFail.zip)

Open the map.
Before unpausing, ask Rift lab to move elsewhere.
Unpause.
Pick up the movement marker of the lab.
Lab will now follow your mouse.
If it ever catches up, it settles and becomes properly unselectable.

I don't think this is an intended behavior at any point.

**Comment by Karsten75** [comment]
some Rift Lab movement did get altered over time, not sure if this was ever resolved.
