### ISSUE TITLE
[Bug] UI option to turn off or disarm enemy crystals

### ISSUE THREAD

**Issue by vonflare** [KnuckleCracker/CW4-bug-tracker#540]
![crystalbug](https://user-images.githubusercontent.com/76500044/102941373-8dc60680-4480-11eb-910d-73df5e29a0b0.png)

1. Select an enemy crystal
2. The option to turn off or disarm the crystal appears

Unsure if this is just a UI bug or if it actually disables the crystal

**Comment by knucracker** [comment]
Removed the enable and arm buttons from the crystals
