### ISSUE TITLE
[4RPL] Global scripts are not reset when importing a CPACK

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#541]
If a CPACK is imported into a map, global scripts retain their internal state. That means they do not run through the _once_ block again and the state of all variables is the same as during the frame the script was exported.

This happens on 1.1.0 with the fix for #453 already in effect.

**Comment by knucracker** [comment]
Changed so that the globalscripts  within a cpack get reset after import of the cpack
