### ISSUE TITLE
Creeper flows into void too early

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#547]
Can you already notice what's wrong on this image?
![Schermopname (12)](https://user-images.githubusercontent.com/75793635/103064423-3923a800-45b4-11eb-9f69-c4b59c375f85.png)
The creeper on the island is around 300 height at most, and I didn't alter space height. Yet, there's creeper flowing off the island.
Blobs also seem to push creeper into space/void but that might be a feature?

The creeper consistently keeps flowing off the island afterwards, too. On a different map space can reliably stop a flood up to the creeper limit, so  I don't know what causes this to happen. Maybe the big amount of wave action?

**Comment by Karsten75** [comment]
Blobs have a tendency to drag Creeper with them. Also, it is requested that you provide a save file of the game if you wish to report bugs like this.

**Comment by TrickyCorp** [comment]
Not sure how to find an exact save file and provide it here. How do I find it? It's one of the saves of a finalized level.
It's gonna be hard for me to provide something I don't know of how to identify it.

**Comment by knucracker** [comment]
It looks like you are either making a map or playing one from the colonies. Your editor maps are stored here:
"c:\Users\YOUR_USER\Documents\My Games\creeperworld4\editor" 
Finalized maps are here:
"c:\Users\YOUR_USER\Documents\My Games\creeperworld4\finalized" 
Just zip up the appropriate folder for your project under to send us a project.

For saves (say you want to save the map in the state it is in during your screenshot), they are located here:
"c:\Users\YOUR_USER\Documents\My Games\creeperworld4\saves" 
Under that folder will be a location for each place in the game where you are playing. (colonies, finalized, etc). If in the colonies, there will be another directory based on the map number.

I can't see the top of the creeper in your screenshot, but the most likely explanation is wave action in the corner. Waves can reach really high when they come together in a corner.  As for the blobs, that they do intentionally drag creeper.

**Comment by TrickyCorp** [comment]
Since these save files all have names that aren't the ones I set in game, I won't be able to recognize them unless I specifically look at the date of each. I don't really want to put much effort in all this, I'm the type of person that only reports things and doesn't want to spend extra time giving extra information.

A request for another screenshot is easy though, here is it.
![Schermopname (13)](https://user-images.githubusercontent.com/75793635/103102075-b08c2280-461a-11eb-9469-4d50d72d2e34.png)

You can see in the bottom left corner how much creeper is at the emitter.
That's all the information you're gonna get from me, sorry.

By the way, the save files have names like "1ab9000a52ef6ac9f3bb29d842ea6c63" so it's gonna be hard for me to find the right one like that (too much effort for someone like me, maybe I shouldn't report things like this then)

**Comment by TrickyCorp** [comment]
It kinda annoys me it's still here, so here's some more info. Level name was "Crystal Caverns 1" and the creeper would always flow into space like that after a minute or 2 of creeper++.

Also, I finally got myself to try to zip up the save file again, and apparently the file is 30MB with all the save files, and there's no way to remove save files right now. Github doesn't like files with a size over 10MB, so I'll have to be able to remove save files first before being able to help more.

**Comment by Regallion** [comment]
Not a bug - creeper ++ lowers effective void height as it goes up.

[CrystalOof.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5796938/CrystalOof.zip)
(This is edited to hasten C++, no other edits were made)

However, what IS odd is that using a GetVoidHeight call still returns 2146, despite it being effectively lowered.
