### ISSUE TITLE
Wave cap doesn't save.

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#548]
When I edit a level and change the wave cap, it stays the way I set it... until I save the game.
As soon as I load the game, the wave cap gets reset to 35... or maybe it doesn't get saved/loaded properly?

Therefore, changing the wave cap does nothing since it doesn't get saved.

**Comment by Karsten75** [comment]
duplicate of #414. Are you running on current beta  build?

**Comment by TrickyCorp** [comment]
I'm running on the initial release, I never updated CW4 after getting it. Might as well close this then.
