### ISSUE TITLE
[Bug.Minor] Hotkeys trigger when typing in some editor fields

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#549]
1. Launch map editor on any map.
2. Go to Theme
3. Select any planet
4. Input 1 in RED
5. If you still have "1" bound to "Build first unit" this will trigger it.
6. Same for the other color fields, as well as the Color intensity field.
7. Does not apply to most other editable fields i tried.

**Comment by knucracker** [comment]
Fixed for the theme planet text fields
