### ISSUE TITLE
[Bug] Ordering a unit to move makes it immune to mesh even if it's still in contact with it

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#550]
Reported by Mutex Morgan#3748
Save with scenario in place: 
[meshsave.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5741966/meshsave.zip)

Steps:
1. Place a unit on live mesh. It will start taking damage
2. Stun the unit
3. Unit continues to take damage from mesh
3. Order the unit to move
4. Unit no longer takes damage from mesh despite not moving an inch on account of being stunned.

**Comment by knucracker** [comment]
Added an additional check for stunned that prevents the unit from entering the takeoff state.
