### ISSUE TITLE
[Bug] Pressing Escape on Info screen behaves unexpected

### ISSUE THREAD

**Issue by RobinBastiaan** [KnuckleCracker/CW4-bug-tracker#554]
When you press on "Info" on the top left side of the game a helpful information/tutorial UI appears on the screen. However, this screen is not closeable by pressing the escape key (or the space bar for the matter), as one would expect from using some other UI elements. I would like and expect the pop-up to close to the escape button (and maybe the space bar too?).

I notice that pressing the escape key while the info screen is active, the "Resume/Save/Load/Settings/..." UI is behaving unhindered. I would expect for getting to the menu you would have to press escape twice; once to close the information UI and once to bring up the "Resume/Save/load/Settings UI".

![image](https://user-images.githubusercontent.com/38226878/103143133-3d190c80-4711-11eb-8d2e-700e4c832e12.png)

**Comment by RobinBastiaan** [comment]
This should have been marked as a minor bug, since it doesn't break anything and is just a minor inconvenience. Sorry!

**Comment by RobinBastiaan** [comment]
Care to share why this is closed due to not planned? Thanks :)

**Comment by Karsten75** [comment]
Not sure how I can be more explicit. There is no plan  to do any  work on this issue.

I'm simply going through old issues and closing them out, since development work has moved on to the next game.

**Comment by RobinBastiaan** [comment]
I understand.

Excited for the next game!
