### ISSUE TITLE
[Bug] Screen tearing

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#556]
Starting with 1.1.0, I get a lot of screen tearing. It is always caused by moving the camera. Movement on the screen while the camera is static does not cause tearing (even things like large creeper waves that involve large parts of the screen). The UI is unaffected. The empty space void background is also not affected, but planetary backgrounds are.

Game speed and UPS are not relevant. UPS was always white and at 30/60 on 1x/2x speed and mostly at 119 at 4x speed. The tearing happens both on empty and very crowded maps.

Turning off the "High FPS" performance setting seems to solve the issue. But maybe it is just hard to see the tearing given how stuttery the map movement is at 30 FPS. The other settings have no influence on the tearing.

Tearing happens both in normal and exclusive fullscreen mode, but not in windowed mode. I tried to "trick" the game by setting it to windowed mode and using [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming), but that reintroduced the tearing.

I tried forcing Vsync through the Radeon software and it did not help. But activating another setting, "Radeon Enhanced Sync", does eliminate tearing entirely.
![grafik](https://user-images.githubusercontent.com/75800362/103153528-6d07f480-4791-11eb-8f20-188d825b2075.png)

Funny fact (at least for a layman): When I try to record the tearing with https://www.screentogif.com/, the tearing stops. For that effect to happen it is enough to put a small recorder window anywhere on the screen, without actually recording.

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5743142/output_log.txt)
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5743221/Player.log)
Copy of the info displayed in the options menu:
```
Game Version = 1.1.0
Unity Version = 2019.4.16f1
Command Line = ["D:\Games\Steam\steamapps\common\Creeper World 4\CW4.exe"]
Time Since Game Start = [197.9409]
----------------------------------------------------------------------------------------------
OS = Windows 10  (10.0.0) 64bit
System Memory = 16334
MP4 Supported = true
----------------------------------------------------------------------------------------------
Processor Type = AMD Ryzen 5 3600 6-Core Processor 
Processor Count = 12
Processor Frequency = 3600
----------------------------------------------------------------------------------------------
Graphic Device Name = AMD Radeon RX 5700
Graphic Device Version = Direct3D 11.0 [level 11.1]
Graphic Memory Size = 8152
Graphic Shader Level = 50
----------------------------------------------------------------------------------------------
Game Dimensions = 1920 x 1080
Resolution = 1920 x 1080 @ 59Hz
Displays = Display (0) Sys=[1920 x 1080] Rend=[1920 x 1080] ACTIVE  Display (1) Sys=[1680 x 1050] Rend=[1680 x 1050] INACTIVE  
DPI = 96
UI Scale = 1.1
Target Frame Rate = 60
----------------------------------------------------------------------------------------------
Settings: AA = 1
Settings: FPS = 1
Settings: SHADOWS = True
Settings: BLOOM = True
Settings: TERRAIN = True
----------------------------------------------------------------------------------------------
Device Type = Desktop
Language = German
Supports Audio = True
----------------------------------------------------------------------------------------------
Max Texture Size = 16384
Max Cubemap Texture Size = 16384
Support Shadow = True
NPOT Support = Full
Support Render TargetCount = 8
Support 3D Texture = True
Support Compute Shader = True
Graphics Multithreaded = False
Supported Render Target Count = 8
Supports 2D Array Textures = True
Supports 32 bit Index Buffer = True
Supports Image effects = True
Supports GPU Draw Call Instancing = True
Uses Reversed Z Buffer = True
Supports Sparse Textures = True
Quality Level = 3
Gen = True [Can Confirm: False]
```
My monitor is a generic 60Hz, 1920x1080 TN panel. One thing I noticed is the log says `Resolution = 1920 x 1080 @ 59Hz`. Which I find odd, because my monitor OSD tells me it is running at 60Hz.

Let me know if there is any additional info you need. I am also available on discord.

**Comment by e-d-u-r-a-n** [comment]
After some additional testing, I noticed that my FPS is a constant 59 instead of 60 while running CW4 in fullscreen mode.

**Comment by knucracker** [comment]
Unity introduced this in 2019.1.
https://issuetracker.unity3d.com/issues/screen-tearing-occurs-when-running-standalone-build-in-fullscreen-mode

I've disabled the newer flip model and that seems to resolve the problem. That puts the game back to the model it was using in the initial 1.0.0 release which used unity 2018.4
