### ISSUE TITLE
Freezing for several seconds every mission, sometimes twice a mission.

### ISSUE THREAD

**Issue by ParadoxSong** [KnuckleCracker/CW4-bug-tracker#557]
It does not coincide with any particular event, but does tend to happen 5 or 6 minutes into missions. I can not confirm the behaviour for any missions before mission 6, because I played them in the demo. This did not happen in the demo, nor in the bonus missions, it originally contained. It does not happen in other games, not even other unity games.
here is the ENTIRETY of the 5kb output_log.

Initialize engine version: 2018.4.28f1 (a2d4f71491a4)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon HD 7900 Series (ID=0x679a)
    Vendor:   
    VRAM:     3051 MB
    Driver:   27.20.12031.1000
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.365200 ms
--InitGame.Init--
Game Version = DEMO 1.0.0
Unity Version = 2018.4.28f1
Command Line = ["H:\SteamLibrary\steamapps\common\Creeper World 4 Demo\CW4.exe"]
Time Since Game Start = [0.1726351]
----------------------------------------------------------------------------------------------
OS = Windows 10  (10.0.0) 64bit
System Memory = 16314
MP4 Supported = true
----------------------------------------------------------------------------------------------
Processor Type = Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
Processor Count = 4
Processor Frequency = 3400
----------------------------------------------------------------------------------------------
Graphic Device Name = AMD Radeon HD 7900 Series
Graphic Device Version = Direct3D 11.0 [level 11.1]
Graphic Memory Size = 3051
Graphic Shader Level = 50
----------------------------------------------------------------------------------------------
Game Dimensions = 1920 x 1080
Resolution = 1920 x 1080 @ 60Hz
Displays = Display (0) Sys=[1920 x 1080] Rend=[1920 x 1080] ACTIVE  
DPI = 96
UI Scale = 1.1
Target Frame Rate = 30
----------------------------------------------------------------------------------------------
Settings: AA = 1
Settings: FPS = 1
Settings: SHADOWS = True
Settings: BLOOM = True
Settings: TERRAIN = True
----------------------------------------------------------------------------------------------
Device Type = Desktop
Language = English
Supports Audio = True
----------------------------------------------------------------------------------------------
Max Texture Size = 16384
Max Cubemap Texture Size = 16384
Support Shadow = True
NPOT Support = Full
Support Render TargetCount = 8
Support 3D Texture = True
Support Compute Shader = True
Graphics Multithreaded = False
Supported Render Target Count = 8
Supports 2D Array Textures = True
Supports 32 bit Index Buffer = True
Supports Image effects = True
Supports GPU Draw Call Instancing = True
Uses Reversed Z Buffer = True
Supports Sparse Textures = True
Quality Level = 3
Gen = True [Can Confirm: False]

--GameLoad.Awake--
Checking Steam...
Steam is Running.
***SteamManager Awake***
Steam User ID: 76561198040020629
Setting up 2 worker threads for Enlighten.
  Thread -> id: 15d4 -> priority: 1 
  Thread -> id: 1280 -> priority: 1 
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.342100 ms
--InitGame.Init--
Requested value 'ACH_7' was not found.
  at System.EntryPointNotFoundException..ctor (System.String message) [0x00000] in <00000000000000000000000000000000>:0 

  at System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) [0x00000] in <00000000000000000000000000000000>:0 

  at System.Enum.Parse (System.Type enumType, System.String value) [0x00000] in <00000000000000000000000000000000>:0 

  at Achievements.ReadData (NBT.Tags.Tag tag) [0x00000] in <00000000000000000000000000000000>:0 

  at SaveGameManager.LoadAchievementsAndStats () [0x00000] in <00000000000000000000000000000000>:0 
Checking Steam...
Steam is Running.
SteamStatsAndAchievements Enabled for AppID: 1293770
Steam User ID: 76561198040020629

Unloading 11 unused Assets to reduce memory usage. Loaded Objects now: 26850.
Total: 76.929500 ms (FindLiveObjects: 1.635700 ms CreateObjectMapping: 0.652200 ms MarkObjects: 74.456900 ms  DeleteObjects: 0.184300 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 0)
Received stats and achievements from Steam

STEAM STATS
------------------------------------------------------------
SteamStat: STAT_STORYMISSIONSCOMPLETED = 0
------------------------------------------------------------
Storing Steam Stats

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 26852.
Total: 82.658700 ms (FindLiveObjects: 1.735600 ms CreateObjectMapping: 0.602900 ms MarkObjects: 80.283300 ms  DeleteObjects: 0.036500 ms)

StoreStats - success
HTTPManager.OnQuit

**Comment by Karsten75** [comment]
> here is the ENTIRETY of the 5kb output_log.

You can simply drag and drop the FILE, you do not need to copy and paste. That way we get a file we can look at or downlaod.

**Comment by ParadoxSong** [comment]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5743859/output_log.txt)
