### ISSUE TITLE
[Bug] 100% Reclaim on Ever After does not charge the delegate

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#560]
All we have on this one at the moment is this video:
https://www.youtube.com/watch?v=S-pxRhZM_3g

Exact timestamp in the video where all creeper is destroyed and reclaim should've started charging:
https://youtu.be/S-pxRhZM_3g?t=2660

**Comment by Karsten75** [comment]
I am curious. Many, many have completed this. With what evidence provided  in this issue should this problem be identified and fixed?

**Comment by grabz-dev** [comment]
Save showcasing the problem from Strategic Sage on Discord
[Reclaim.cw4.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5743663/Reclaim.cw4.zip)

**Comment by grabz-dev** [comment]
The previous save is not quite it - the creeper evaporates after 4 seconds.
The below scenario is hand crafted (e.g. I placed the creeper there myself), but 0.002 creeper is properly stuck against the top left most shield. UI shows 0.00 creeper.
[save-1.cw4.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5743730/save-1.cw4.zip)

**Comment by Roger44477** [comment]
I encountered this issue when playing the level, and discovered the issue was that it's based on tree growth, and structures takes up the space trees can grow in. By deleting all my structures in areas trees could grow and rebuilding all my towers in the most efficient pattern, I was able to complete the level with room to spare.

**Comment by grabz-dev** [comment]
> I encountered this issue when playing the level, and discovered the problem was that it's based on tree growth, and structures taking up the space trees can grow in. By deleting all my structures in areas trees could grow and rebuilding all my towers in the most efficient pattern, I was able to complete the level with room to spare.

You're thinking of the Life objective, which isn't the subject of this ticket
