### ISSUE TITLE
[Bug.Minor] Selecting multiple rockets removes rocket specific UI toggles

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#561]
Selecting more than one rocket gets rid of the "Auto Launch" and "Launch ASAP" toggles, contrary to other units with unit-specific toggles.
![image](https://user-images.githubusercontent.com/51026936/103160223-72d1fa00-47d2-11eb-994b-9ece63d5fe7f.png)

**Comment by PRG-YouTube** [comment]
Still present in the current version 1.6.4
