### ISSUE TITLE
[Bug.Minor] when a creeper missile hits the out of bounds, the creeper spreads onto terrain from the void

### ISSUE THREAD

**Issue by dudeallmighty** [KnuckleCracker/CW4-bug-tracker#563]
it spreads on the void faster then on land. and if i have any buildings next to the lands edge it gets onto them.
don't know if its intended or not, but its kind of annoying :P

**Comment by Karsten75** [comment]
It's not possible to tell if this is a bug or working as designed without a screenshot and/or a save. It sounds lik eit is working as designed, but feel free to submit a screenshot or perhaps even a save file of the game with which we can recreate the issue to investigate.

**Comment by grabz-dev** [comment]
Assuming this is unchanged in the editor, creeper coming from void will crawl onto any terrain, so if that is what you are observing, it is working as intended.
