### ISSUE TITLE
[Suggestion] allow the airship after the final mission

### ISSUE THREAD

**Issue by dudeallmighty** [KnuckleCracker/CW4-bug-tracker#564]
i LOVED the airship. made me feel powerful, and i wanted to at least get to use it on "mark V" but its not in the AIR options.

i get that its "too powerful" so i was thinking of making it into a type of "superweapon" 
like... limit it too 1 or 2, or make it extremely hard to obtain, or even add a resource like the power orbs that each 1 allows for 1 airship. 
and add an option for the mark V missions to allow airships freely like in the final mission so that power hungry people like me, who enjoy overpowered stuff can bring down doom on the creeper.

**Comment by Regallion** [comment]
Should probably be closed, as it's covered by #659

**Comment by Karsten75** [comment]
Implemented in #659
