### ISSUE TITLE
Editor suggestion compilation

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#565]
After using the editor for some time, there are a number of improvements I can think of. Some of those are duplicates of existing suggestions. I will still list them here with a link to the relevant issue.

### New features:
- **"compile all scripts" button on the MODS tab:** Compiling scripts is something I do a lot during debugging and fine tuning. At the moment that means going to the MODS tab, opening the Package manager, selecting the correct CPACK, selecting the scripts tab, clicking compile, and finally closing the Package Manager again.
- A way to **resize the map without having to start from scratch** ( #96).
- This one is most likely not feasible, but asking does not hurt: **make the 4rpl console and the package manager open in separate windows**.
- **Make enter and tab keys work on input fields**. Tab to cycle through input fields (#558), enter to apply. Using the cancel button already works.

### Improvement of existing features:
- **Persist time unit selection (frames vs seconds)**: at the moment they default back to frames every time you open a new settings window. Also, I would actually prefer it if they were all synced up (i.e. switching any one of the inputs to seconds switches all of them). That would also make them easier to persist.
- **Add missing options for a proper map reset**: delete spores(#464)/blobs/skimmers, reset mesh, reset totems, delete all player units. All of this can be done in some way or other already, but it often involves deleting and replacing (totems, mesh) or waiting for stuff to die (spores, etc.).
- **Enable copying of all enemy units using the Tab key** (#182, #385, #473).
- **Allow selection, editing and deletion of multiple enemy units** instead of having to work on each one individually (#344).

In case you prefer individual issues for each of these suggestions, let me know and I will split them up.

**Comment by knucracker** [comment]
It's fine having many of the closely related issues pulled together in this one entry. Very helpful actually.

On the multi-window thing... yeah that would be very nice. It's a bridge too far given unity's lack of support, though. There are ways to do it with some native integration (hooking into the render thread and using a native windows dll), but that sounds like a hill to die on.  What I could maybe think on is a keyboard shortcut to quickly bring up either the console or the package manager (and to dismiss them).  

The other things are varying degrees of difficulty and utility. They will likely get attention over time. In the case an issue has some other issues, I'll close those other issues as they are addressed. I'll leave this issue open until everything is addressed (which can mean done, or won't/can't do)
