### ISSUE TITLE
[Bug][4RPL] Creating a bomber pad from 4RPL doesn't work.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#566]
I'm toying around with 4RPL and reworking the unit build system. So, I made bomber and AC bomber kits in order to deploy bomber pads and AC bomber pads. That's when I realized that my AC bomber kit worked (Creating an AC bomber pad on its position when a button is clicked and destroy itself), but the Bomber kit didn't work, and it was a copy of the AC bomber kit script.
Then, I ran tests on the console:
1. Using the command _GetUnitsByType_ to ensure that "bomberpad" was the right unit UID
2. Trying to create a bomber pad and an AC bomber pad in the console, using the exact same line, and tracing the UID.
    -The AC bomber pad was created and I got the right UID as a result.
    -The Bomber pad was NOT created and I got -1 as a result.
    -I tried later with an invalid unit name ("creeperworldforever"), no unit was created and I had -1 as result.
Here are the scripts I'm using in the console:
    _"acbomberpad" V3(160 1 40) 0 CreateUnit Trace_ (returns the AC pad UID)
    _"bomberpad" V3(160 1 40) 0 CreateUnit Trace_ (returns -1)
    _"bomberpad" 0 GetUnitsByType Trace_ (returns the expected list)
    _"acbomberpad" 0 GetUnitsByType Trace_ (returns the expected list)
Here are the scripts I'm using in my deployment kits:
    _:_UICALLBACK
	Self GetUnitPosition ->Pos
	<-Pos.x <-Pos.z GetTerrain <-Pos.y eq if
		"bomberpad" Self GetUnitPosition 0 CreateUnit pop
		Self 1 1 1 DestroyUnit
	endif_ (Just destroys itself)
    _:_UICALLBACK
	Self GetUnitPosition ->Pos
	<-Pos.x <-Pos.z GetTerrain <-Pos.y eq if
		"acbomberpad" Self GetUnitPosition 0 CreateUnit pop
		Self 1 1 1 DestroyUnit
	endif_ (Creates pad and destroys itself)

Note that I understand that the 4RPL docs were not released to prevent bug reports like this one too early, so I'm not expecting any reaction before the docs are out. (I won't report minor 4RPL bugs before the docs are out so the dev can focus on other issues)
However, I reported this one now because it's not a minor bug, but I'm saying again that I'm not expecting any reaction before the docs are out, and even then it can take some time.

**Comment by knucracker** [comment]
Try "bomberPad" with an upper case P.  I just took a quick look at it seems that I had that as a typo. I have just changed it for future builds to "bomberpad".  But let me know of "bomberPad" works in the current build.

**Comment by knucracker** [comment]
Actually, that won't work. I see that the code turns whatever you present into lower case. So it won't work till a new build is done (now that I have fixed the upper case P problem).
