### ISSUE TITLE
[Bug] describe

### ISSUE THREAD

**Issue by elelliott1** [KnuckleCracker/CW4-bug-tracker#569]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\Player.log`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`

3. If the error persists over a save and reload of the game, please provide the save file as well (You may have to zip it up, as the .cw4 file type is not supported as a direct upload in GitHub)
  Each part of the game (Farsite, Chronom, Mark V, etc.( has a folder underneath the game's home directory.
         `%HOMEPATH%\Documents\My Games\creeperworld4\saves\`
   If you were saving in the Map Editor, then the save is in the folder for the map in 
         `%HOMEPATH%\Documents\My Games\creeperworld4\editor\`

4. Screenshots help us to **see**the problem. 
  Screenshots are here
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

5. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

**Additional context**

**Comment by elelliott1** [comment]
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5745382/Player.log)

Whenever I launch the game, the loading screen is frozen. I have tried reinstalling the game and restarting the computer. I have no idea why it started freezing whenever I load into the game. I played the game one time yesterday, and when I loaded it today, it either went into a black screen or the screen freezes. There is always audio looping in the background, however.

**Comment by Karsten75** [comment]
At the very end of your log file, this appears

![image](https://user-images.githubusercontent.com/22965021/103185392-d9fab780-4881-11eb-900a-d8f30af75582.png)

```
D3D shader create error for vertex shader [0x887a0005]
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed. 
```
that would indicate an issue with your GPU or GPU driver that we do not have information to resolve.

You can try to turn off the Steam overlay and/or any other GPU monitors and or frame rate monitors or game overlays you may have active. 

You can also look at updating your GPU drivers or  running a GPU diagnostic program or benchmark that is specific to DirectX 11.1 to see if any of those can assist you in determining the root cause of your problem.
