### ISSUE TITLE
[Bug.Minor] Tall colony maps are not centered in preview window

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#571]
Super minor nitpick: If a custom map is taller than it is wide, the map preview is not centered. Only affects the small info box that shows up when you select a map, not the preview in the list of maps.

![grafik](https://user-images.githubusercontent.com/75800362/103200172-f4b64600-48ec-11eb-9677-9a1e5980a03c.png)
![grafik](https://user-images.githubusercontent.com/75800362/103200183-fda71780-48ec-11eb-859b-49539bd73630.png)

**Comment by Regallion** [comment]
335

**Comment by e-d-u-r-a-n** [comment]
Missed that in my search, thanks for pointing it out. I'll close this issues.
