### ISSUE TITLE
[Bug] Porter enters bad state if player changes options during construction

### ISSUE THREAD

**Issue by tncc** [KnuckleCracker/CW4-bug-tracker#574]
If you construct a Porter, and change the resource during construction, then upon completion it will request BOTH energy and the specified resource.  This is 100% reproduceable.
Expected: It should only request one thing at a time, and it should apply that setting fully when the building completes.
Workaround: This state can be rectified by changing the resource at any time after construction is completed.

Related, minor display issue: When switching resources, the capacity briefly changes to 10 before being reset to the desired capacity.

Related maybe-bug: The maximum "ammo" for the Energy resource is always 50, regardless of capacity.  However, for other resources, changing the capacity also changes the maximum "ammo".  This doesn't affect the size of the resource box it sends.

**Comment by Durikkan** [comment]
Changing the type before construction finishes also leaves the ammo count permanently displaying the excess energy, instead of the excess resource.

**Comment by PRG-YouTube** [comment]
A little extra visuals: https://youtu.be/EZ-quXGivb8

**Comment by knucracker** [comment]
I've made a change that addresses the original problem. Or at least I think it does. If there remains an issue, just open a new bug and I'll take a look.
