### ISSUE TITLE
[Bug] Buildings buildable between platforms

### ISSUE THREAD

**Issue by DarekStar** [KnuckleCracker/CW4-bug-tracker#576]
![cw4ss_1](https://user-images.githubusercontent.com/76796503/103387233-3fd88080-4ac8-11eb-9f45-280e03d21766.jpg)
![cw4ss_2](https://user-images.githubusercontent.com/76796503/103387236-423ada80-4ac8-11eb-98bc-9dd78a1428f5.jpg)
![cw4ss_3](https://user-images.githubusercontent.com/76796503/103387237-42d37100-4ac8-11eb-9487-51dd07eb6729.jpg)
I could not recreate it but I managed to build a missile turret between 2 platforms in the mission Founders. Or is this normal? I cant tell.

**Comment by Regallion** [comment]
This is normal - notice that each platform has a 1-cell wide crossbrace in the middle of it.
If you place the platforms side-by-side there is no divider between them.
This creates a slightly wider than usual space.

Note that it allows you to place some of the more unorthodox units in there, such as refineries or certain custom units.

**Comment by DarekStar** [comment]
Ah I tried when I first got them and could not do it maybe it was messing up then but it made me think I couldn’t do that. Thanks for letting me know.
