### ISSUE TITLE
[4RPL] CPACK editor global control doesn't show entire file name if a space is in the name

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#584]
**Description**
4RPL files with spaces in the name will only show characters until the space when selecting in the global control. This is only an issue when selecting files to add, with lots of files with similar names; the file hows up just fine once added.

**Image**
![image](https://user-images.githubusercontent.com/26010895/103709252-633f7780-4f6f-11eb-926c-a89dd89ddb48.png)

**Additional context**
It's a minor bug(on the map maker's side, easily solvable by file names or knowing which file it is by the order displayed), but it can be very annoying, especially when multiple files share the same set of characters before a space(like the above).

**Comment by knucracker** [comment]
The problem was actually that when the string didn't fit, it would disappear.  I switched to a textmeshpro dropdown and changed it so that when the string doesn't show, it adds '...'. Also made the combo box a tad bigger.
