### ISSUE TITLE
[Suggestion] Sound in Main Menu should not turn off Sound for the entire game 

### ISSUE THREAD

**Issue by grimya** [KnuckleCracker/CW4-bug-tracker#585]
**Is your feature request related to a problem? Please describe.**
When I first started playing the game I clicked the sound icon in the main menu at some point and forgot about it shortly after. I noticed my sound was no longer on despite checking that my in-game sound settings were at normal levels, and assumed that due to a bug my game's audio was broken. I didn't mind too much and I was too lazy to put any effort into fixing it, but more than a few times I wished I could try out the game with sound. The issue persisted between sessions of opening and closing the game since it apparently remembers the setting. After 26 hours and beating all of Farsite I finally noticed the button and switched it on. In my opinion it's a severe UI oversight for this tiny button to mute the entire game with no other way to reenable the sound or understand why it's gone.

**Describe the solution you'd like** / **Describe alternatives you've considered**
- Make it mute only the main menu music 
- A button, anything in the sound settings that lets you know it's muted and lets you unmute it.
- A label for the button showing what it does (Mute everything)
- Remove the button/move it to settings

It's a little frustrating that what I thought was a audio glitch was a weird UI thing all along, so I don't want others to lose audio without understanding why.

**Comment by Karsten75** [comment]
There is a sound on/off button in the game's UI. This button acts in concert with the button on the main menu. Either one will turn sound on/off.

![image](https://user-images.githubusercontent.com/22965021/103797741-79504500-500e-11eb-8868-805d41341b50.png)

**Comment by Karsten75** [comment]
reopening this as a placeholder to document the 3rd overall mute button in the sound settings page.

**Comment by knucracker** [comment]
Split the mute settings between game and main menu. Also added mute controls to the sound settings page.
