### ISSUE TITLE
[Suggestion] Increase thumbnail size in map details panel in Colonies

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#589]
**Is your feature request related to a problem? Please describe.**
The thumbnail size of the map details panel is very small, smaller than the thumbnail of the map browser itself.
![image](https://user-images.githubusercontent.com/51026936/103841596-3b95ff80-5094-11eb-99f4-c58f71af49e7.png)

**Describe the solution you'd like**
Some way to make it bigger on appropriately sized resolutions.

**Comment by EvilMathematician** [comment]
👍
