### ISSUE TITLE
{Suggestion] Allow canceling of lab rematerialization on the same frame as the order was given, similar to CW3

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#59]
**Is your feature request related to a problem? Please describe.**
Not a problem for the general populace, but speedrunners may appreciate the ability to place the lab down to see connections, and then retract that order to place the lab somewhere else. In CW3 that is possible to do with CN's on the same frame.

**Describe the solution you'd like**
Allow the Destroy button to exist on the lab on the same game frame as it was placed.

**Comment by knucracker** [comment]
I've implemented a change that addresses this for the first rematerialization (at frame == 0).  You can place the lab like normal, then you can click it and attempt to move it.  That move will happen instantly (live basically) even while paused, but only at the beginning of the game.  That allows a player to change their mind to to move the lab before it rematerializes at the beginning of a mission.
