### ISSUE TITLE
Map descriptions scroll very slowly

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#591]
When a map description in the Colonies is long enough to have a scrollbar, attempting to scroll it via the mouse wheel is very slow, to the extent of needing to be scrolled several times to move by a single line.

**Comment by Karsten75** [comment]
Ah!. The Unity default needs to be changed on *every* scrollbar.

**Comment by knucracker** [comment]
Fixed in 1.1.2b
