### ISSUE TITLE
[Bug.Minor] [BETA] Menu mute button is not correctly synced with the sound settings

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#593]
Open main menu.
There is a mute button on the right.

- Turn it ON
- go to settings, turn menu music OFF.
- go back to main menu. Button is on.
- Press it. It's now off. Music is still off.

Curiously, the reverse (operating the main menu button then looking at settings) works correctly, with the settings changing to muted.

**Comment by knucracker** [comment]
Fixed in 1.1.2b
