### ISSUE TITLE
[Porter] There are states of the porter, that hides "Cancel Route"

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#594]
After destroying a lifitc pod with a hoovering done above I've sent the drone to another place and 
![image](https://user-images.githubusercontent.com/16858356/104061430-dc9dcb00-51f8-11eb-9fc4-8690cd0313c7.png) I had no way to cancel route, even after changing the landing locations

**Comment by knucracker** [comment]
I'm not able to reproduce this in the various ways I have tried.  So long as the drone has a specified delivery target, the cancel button is supposed to show.  If you press the cancel button, the delivery target is cleared and the cancel button is hidden. It won't reappear until you set a new delivery target for the drone

**Comment by BilboGCL** [comment]
I have tried to reproduce it and wasn't able to do so, too - let's call it a temporary hiccup, either of my mind or of the program...
