### ISSUE TITLE
[Bug] Hold objective can enter an illegal state

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#595]
1. Create a map.
2. Fail the hold objective
3. Reset map data

Hold objective will enter an illegal, "Cyan" state. In that state it cannot be completed and that state cannot ever be reset, breaking the objective for that map permanently.

**Comment by Regallion** [comment]
public void SetState(bool complete, bool failed) {
        if (complete) {
            if (failed) {
                image.color = Color.red;
                text2.color = Color.red;
            } else {
                image.color = Color.green;
                text2.color = Color.green;
            }
        } else {
            if (failed) {
                //This state should never happen (failed but not complete)
                image.color = Color.cyan;
                text2.color = Color.cyan;
            } else {
                image.color = Color.yellow;
                text2.color = Color.white;
            }
        }
    }

**Comment by knucracker** [comment]
Fixed in 1.1.2b. Made the reset map data routine clear out the extra and the failed stated on the objectives.
