### ISSUE TITLE
[Bug.Minor] Finalization popup goes under scratch slots

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#597]
![image](https://user-images.githubusercontent.com/40322714/104072075-7bd3ba00-521b-11eb-8d80-1ca8068bfccf.png)

Best seen in motion, but the finalization "Map saved" popup that goes under the finalize button, actually gets covered by scratch slots.

**Comment by knucracker** [comment]
Fixed in 1.1.2b
