### ISSUE TITLE
Nexus not connectingto tower's when it should and stays connected when it shouldn't

### ISSUE THREAD

**Issue by Thalzamar** [KnuckleCracker/CW4-bug-tracker#6]
found by Fire on Discord since he has no Github account i did this Ticket for him
https://discordapp.com/channels/192420539204239361/376817338990985246/727906802846531595

Quote from him:
Near as I can tell the lab only is rechecking connections when moving horizontally, not vertically; I got that screenshot by getting the lab up around height 20 (out of connection range) and then dropping it between the towers.
![cw4 bug](https://user-images.githubusercontent.com/48890032/86262740-8f44ff00-bbc0-11ea-8129-652363301af0.png)

when checking the other way around tower's stay connected even when they shouldn't they do this
Quote from him:
The second image is 1 frame after I told the lab to move sideways.
Note that the towers disconnect and the totem connects; I was moving away from the totem.
![cw bug2](https://user-images.githubusercontent.com/48890032/86263696-dd0e3700-bbc1-11ea-99ff-b0af6c024b02.png)
![cw4 bug3](https://user-images.githubusercontent.com/48890032/86263732-e5ff0880-bbc1-11ea-8959-1e3c9c6d212b.png)

**Comment by knucracker** [comment]
Yep, unit's were not checking for connection alterations while in the landing state. Added logic to evaluate connections while landing. Happens whenever integer Y coordinate changes.
