### ISSUE TITLE
[bug] Totem and Pod tooltip obscures placement indicator

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#60]
Referencing fixed issue https://github.com/KnuckleCracker/CW4-bug-tracker/issues/46

The fix should be applied to Totems and Pods as well.
![image](https://user-images.githubusercontent.com/51026936/95521197-4673c200-09c9-11eb-8181-4f410d501577.png)
![image](https://user-images.githubusercontent.com/51026936/95522977-cc920780-09cd-11eb-8c89-6c70377af726.png)

**Comment by knucracker** [comment]
I changed the popups to use the now standard popup that only shows when items aren't selected.
