### ISSUE TITLE
[4RPL] Create getters and setters for factory wares.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#600]
At the moment there is no way for 4RPL to interact with the factory at all, both getting and setting goods.
This means that you cannot know how much of any given good a player has at their disposal, or directly add good to factory.

There are cases where you might want to know about the stocks/alter them:
1. You want to make a unit that converts one good to another. Currently that would require spawning a resource pod as output.
2. You want to give player some resources (without spawning a resource pod which can be problematic for reasons)
3. You want to trigger something when player's stock is at a certain value. For example, give them a care package if their arg is too low for a certain amount of time. Or perhaps the goal of the level might be to stockpile 300 liftic. (which might only be available in scattered pods)
4. You want to make a "Trader" unit that instantly trades one resource for another. (Otherwise this would require the unit to first eat packets at a top rate of 30/s, then spawn a pod which filters back). 
5. You are Sorrontis and want to punish the player for ever capping out on stock.

**Comment by Regallion** [comment]
In general, any case where you would get or set a unit's ammo also applies to the factory, except it has 3 types of ammo at once.

**Comment by Regallion** [comment]
Also as a side-note, it's possible to 4RPL multiple factories and have them work correctly. This may or may not affect how the getters/setters would work.

**Comment by knucracker** [comment]
Added Get/SetFactoryWares
