### ISSUE TITLE
[4RPL] AddAsWareHolder has unexpected behavior

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#601]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5791297/save.zip)

The custom unit is supposed to dispatch anticreeper as according to https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:addaswareholder that's what 1 means.
However, there are unexplained caveats to this, which cause it to not dispatch in this scenario.

1. The unit needs to be connected either to a rift lab OR to a factory... OR a porter set to ANY resource. Otherwise it will not dispatch. The weirdest part is that for a factory, a ghost is sufficient, it doesn't have to be built. This is...odd to say the least. 
2. The dispatch is infinite, if there are 200 units connected to such a dispatcher, all of them will get free packets, which means that it's impossible to properly control the amount emitted.  This behavior is not shared by, say, redon deposits, as when faced with multiple factories/porters it will only dispatch 1 packet per dispatch period.

If possible, the following alterations are requested:

1. Add a boolean. If true, the dispatch only happens if a unit is connected to rift lab/BUILT factory/ porter of a proper resource type. Otherwise it will dispatch to anything in range, regardless.
2. Add an ability to know when a unit dispatched a packet. This would allow not only for per-frame limitations of emissions, but also limiting total emissions.

**Comment by WithersChat** [comment]
3. Add a way to know when a packet has been sent so we can remove the flag "in time". Additionally, it would allow to re-send the flag on next frame if the packet hasn't been sent, which would make sense.

**Comment by Regallion** [comment]
4. Add "Energy" as a valid ware to allow replication of resource pod functionality.

**Comment by Regallion** [comment]
Amended to request an ability to know when a unit dispatched a packet, as it would also allow for counting how many packets the unit dispatched. This can be used to limit not only how fast the packets are dispatched, but also limit total dispatch, similar to limits on resource pods/factory.

**Comment by knucracker** [comment]
I've added https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:func_warepacketsent. This will allow a custom unit to know when a ware packet is sent.  Note that the way the game is setup, it isn't possible to support energy.  For that, if desired, you may have to create an energy pod and hide it inside a unit.

For wares, AddAsWareHolder and :_WarePacketSent should allow a viable solution.  If not, or it doesn't work, just let me know on this topic.
