### ISSUE TITLE
Platforms can't be build on dead mesh in void

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#602]
When you have killed the mesh on void, you are not allowed to build platforms there:
![image](https://user-images.githubusercontent.com/16858356/104105413-31e7e400-52ae-11eb-8e9b-9d110478e5c7.png)
I think it is a bug, ymmv

**Comment by knucracker** [comment]
This is by design (I think, it was a late decision) and lets a map author create areas that platforms can't be built
