### ISSUE TITLE
[4RPL] Add/SetCreeper do not render when game is paused

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#603]
1. Create a map
2. Pause
3. Run the following script in console:
4. `15 15 15  AddCreeper`
5. At 15 15 there will be 15 creeper added per frame. You can see it on mouseover, but it will not render.
6. It will render when you unpause.

Same goes for SetCreeper.

This behavior persists on save-load.

[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5791649/save.zip)

**Comment by knucracker** [comment]
Adding a note to self:  Add a 4rpl call that syncs up the smooth rendered creeper value with the actual value. Same as when c to ac conversion takes place.

**Comment by knucracker** [comment]
Added an option to disable creeper smoothing #621.  Re-evaluate after this option is in place. I'm not sure what might be 'real' vs perception based on the creeper smoothing algorithm
