### ISSUE TITLE
[4RPL] SetCreeper can result in incorrect rendering of creeper.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#604]
1. Create a map.
2. Put the following script on it:
3. `  183 2 do
        93 0 do
            J I GetCreeper ->T
            J 1 sub I <-T 0 SetCreeper
        loop
    loop
`
4. Make it global.
5. Put some creeper on map, unpause
6. Creeper will get rapidly dragged to the left
7. However, mousing over the right edge will show that the creeper there is fake (it has a 1-frame lag)
8. Saving causes creeper to right itself.

**Comment by Regallion** [comment]
![image](https://user-images.githubusercontent.com/40322714/104106584-21dcfe00-52c8-11eb-8d26-f068479fac08.png)

Another rendering issue this can cause in screenshot form, though i believe it has the same underlying source.

**Comment by knucracker** [comment]
Added an option to disable creeper smoothing #621.  Re-evaluate after this option is in place. I'm not sure what might be 'real' vs perception based on the creeper smoothing algorithm
