### ISSUE TITLE
[4RPL] Custom unit UI looks odd even with short values

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#605]
![image](https://user-images.githubusercontent.com/40322714/104108000-12fb4900-52d2-11eb-98ed-86253ca7d54c.png)

Even a short name for an option with a one-word variant still causes display to look slightly off.

**Comment by knucracker** [comment]
These controls are one line and the font can't go much smaller. Not sure that there are any options other than to pick smaller text. In this case just using "Burn" rather than "Burn Ware" might make the value fit?  Not sure how it resizes.

**Comment by Regallion** [comment]
![image](https://user-images.githubusercontent.com/40322714/104340095-673c3e00-5509-11eb-9bce-b50271e7af5f.png)
Nope

**Comment by knucracker** [comment]
I've changed it so the label, the colon, and the value are controlled by a horizontal layout element. Each is also set to float from 12 to 10 point fonts. This will allow a smaller label to give more space to larger values. It gets a few more characters for both the label and the value.

Changed in 1.1.2c
