### ISSUE TITLE
[4RPL] Neglecting to set a unit's PopupText1 causes it to have a value of "t"

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#606]
Create a unit.
Give it a following script:
`SetUnitPopupEnabled(self true)
SetUnitPopupText0(self "neat")`

Observe.
![image](https://user-images.githubusercontent.com/40322714/104108481-037dff00-52d6-11eb-86c2-8408796311f0.png)

**Comment by Regallion** [comment]
Addendum: This is also true for Text0, but you are unlikely to enable popup without actually putting any text.

**Comment by knucracker** [comment]
Fixed in 1.1.2c
