### ISSUE TITLE
[Bug] Reset map data can cause ERN portal to behave incorrectly

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#607]
1. Create a map
2. Add a built ERN portal and some ERNs to it
3. Unpause, wait a literal minute and let the ERNs dock to the portal
4. Reset map data.
5. The ERNs will not gain any efficiency until the time when they first docked comes around again. This can be "fixed" by undocking them and re-docking, but it's still incorrect behavior.

Example map(select ERN portal and unpause):
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5791917/save.zip)

**Comment by knucracker** [comment]
Fixed in 1.1.2c
