### ISSUE TITLE
[4RPL]  SetUnitMaxAmmo does not reduce Ammo if lowered

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#610]
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:setunitmaxammo

`If ammo is higher than max ammo, then the ammo will be lowered to the value max ammo is set to. `

That is incorrect. If a unit has ammo and then gets it's max ammo lowered, the ammo will remain as-is.
![image](https://user-images.githubusercontent.com/40322714/104119559-314c5d80-5341-11eb-8b34-0d9e421579a6.png)

**Comment by Regallion** [comment]
However a unit in this case will still request 1 more ammo packet, which IF it arrives, will set it to correct 15/15. If the packet is prevented from arriving, by, say, the unit moving out for a bit, it will remain that way until the ammo is disturbed.

**Comment by knucracker** [comment]
Fixed in 1.1.2c
