### ISSUE TITLE
[4RPL] SetObjText cannot be properly cleared

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#612]
Script for unit:
`once
			Self "Text" "Thanks for rescuing me from the evil creeps!" SetObjText 
			Self "Text" 50.0 255.0 div 220.0 255.0 div 50.0 255.0 div 255.0 255.0 div V4 SetObjTextColor 
			self "Text" 15 SetObjTextFontSize
			150 SetTimer1
endonce
			GetTimer0 eq0  if 
		        Self "Text" "" SetObjText 
	                endif`

Expected: After 5 seconds text changes to nothing
Reality: After 5 seconds text remains.

Save-load causes text to disappear, which indicates a rendering issue.

**Comment by knucracker** [comment]
(There's a small typo in the example script. It sets Timer1 but checks Timer0 in the 'if').
Fixed in 1.1.2c.  I had a classic Unity 'typo' where I was destroying a component not the component's gameobject when an empty string was passed in.
