### ISSUE TITLE
[4RPL] Save/Load causes popup text to be lost

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#613]
Script 
`once
SetUnitPopupText0(self "neat")
endonce
:Awake
SetUnitPopupEnabled(self true)
`
Run this unit for a frame. It will have a popup text of "Neat"
Save and load
Popup text is now empty.

**Comment by knucracker** [comment]
Changed in 1.1.2c.  These APIs override the values set in the cmod unit settings (the UI). The UI settings are persistent and previously the 4rpl set values were not persistent.  I have changed them to persist.  
Note: If SetPopupText is called with an empty string, they will now default back to whatever values are specified in the UI settings for the cmod.  If you want to show 'nothing', but also want to have a default value in the UI settings for the Cmod, then pass in " " (an empty space).
