### ISSUE TITLE
[Bug] .cw4rec files take up large amounts of disk space

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#614]
Refer: https://knucklecracker.com/forums/index.php?topic=36488.0

Perhaps consider a method of housekeeping that will allow deleting these as well as old save files 

refer to #502 as possible circumvention

**Comment by knucracker** [comment]
Added an option in the settings/options page to limit recordings. Off by default. When on, there is a text field, defaulted to 100, that specifies how many recording files to keep in the recordings directory. When the count of files exceed that number, the oldest file(s) are deleted.

Added in 1.1.2c
