### ISSUE TITLE
[4RPL Addition] Add a setter for unit construction data

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#615]
Add a SetContructionData method for setting construction data of a unit. The method should allow

1. Setting current build progress
2. Setting build goal
3. Setting build ware

If on execution of method build progress is equal to build goal the unit should become built.

Use cases
1. Actually creating units. Right now any unit without a prebuilt flag (which includes ALL player units) cannot be properly created because it will only spawn a build ghost. I have considered adding a "Createbuilt" flag to CreateUnit, but i'd prefer a more versatile approach.
2. Allow building of units which don't accept packets (and are instead progressed based on some other condition)
3. Allow creating of "Builder" units that can build units independently.

**Comment by WithersChat** [comment]
Maybe just a SetUnitConstructing may be cool.
