### ISSUE TITLE
[wiki] 4RPL syntax highlighter needs work on dark mode. 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#617]
Example on  `break` command page : https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:break

![image](https://user-images.githubusercontent.com/22965021/104205190-ba23d180-53f3-11eb-8026-2f1bc59105e9.png)

![image](https://user-images.githubusercontent.com/22965021/104205231-c6a82a00-53f3-11eb-9d1d-27b85b90a937.png)

**Comment by knucracker** [comment]
Fixed and live
