### ISSUE TITLE
[4RPL] ClearTraceLog doesn't do anything

### ISSUE THREAD

**Issue by Sanian-Creations** [KnuckleCracker/CW4-bug-tracker#619]
**Applies to version: 1.1.2b**

Try running (not Run Once) this script from the console:

```4rpl
ClearTraceLog
GetPointerTerrainCoords Trace2
```

The console output only continues to fill up, ClearTraceLog simply doesn't do anything.

**Comment by knucracker** [comment]
Fixed in 1.1.2c.  The call was stubbed in but never implemented.
