### ISSUE TITLE
[bug] Towers have an efficiency when soylent is disabled

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#62]
![image](https://user-images.githubusercontent.com/51026936/95523932-4d520300-09d0-11eb-866b-16969cc48756.png)
When soylent is disabled, Towers left pane still shows an efficiency. 

I was on the fence about whether this was of any importance to report, but I thought this could be a good spot to also mention that soylent is disabled, in the offchance that players miss the ADA log and the on screen indicator, they might see it there.

**Comment by Karsten75** [comment]
Bear in mind that the player might still want to know the projected efficiency for a tower once soylent is activated. The fact that it does not currently generate energy does not mean that the efficiency of it's location is altered.

**Comment by knucracker** [comment]
Yeah, I think I will leave it. It doesn't hurt and it could come in handy in maps where the soylent is turned on and off at different times via script.
