### ISSUE TITLE
[Suggestion] Limit the types of orbitals that player can use.

### ISSUE THREAD

**Issue by Sorrontis** [KnuckleCracker/CW4-bug-tracker#622]
Please make sure you have read, understood and agreed to the [policy](https://github.com/KnuckleCracker/CW4-bug-tracker/blob/master/Suggestion%20policy.md) regarding submitting material to Knuckle Cracker

**Is your feature request related to a problem? Please describe.**
No problems here. 
I would like to be able to limit the types of orbitals accessible, rather than just having Rockets allowed/disallowed. 

Example. Allow for Damper/Singularity, but disallow rain/conversion.

**Describe the solution you'd like**
Either by Editor UI switches  and/or 4RPL

**Comment by Regallion** [comment]
As a rider, would be nice if you could also add to that menu.
