### ISSUE TITLE
[4RPL Addition] Add a way to change alpha (opacity) of objects with 4RPL

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#628]
There is currently no way to change alpha of models in unit editor, and there is no way to change it in 4RPL either.
So, maybe it could be good to implement SetObjectAlpha, which takes one float between 0 and 1 and sets the alpha to it (And GetObjectAlpha to have the value back), 0 being invisible and 1 being normal.
The weirdest part about this is that you CAN set an alpha in the color on object editor. But it's not applied on the mesh. Maybe "fixing" this could also be an option.

**Comment by knucracker** [comment]
This is a shader request... and not something I could likely do for CW4. Not with true transparency anyway. There are already multiple layers of transparency (the creeper, shields, etc) and z sorting transparent objects is a ginormous pain.  Here's one unity topic about it: https://forum.unity.com/threads/approximated-order-independent-transparency.327299/

Long story short, this is a bridge too far for CW4.  The best I could possibly do is support dithered transparency. That is currently used on the walls (the cyan walls that turn run and decay when touched by creeper). Those are opaque, but their shader dithers them so they can appear sort of transparent.  I could maybe allow something like that for custom units... but it likely would not be what you want, and isn't the simplest thing to do, so even this is also probably just a jump too far for CW4.
