### ISSUE TITLE
{Suggestion] Clean up unnecessary settings for units on the left pane (Analysis inside)

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#63]
From Discord:
> Yeah, units that don't need 'armed' can have it removed. Every 'unit' needs a review between now and release to clean up the left pane. It's been easy to overlook extra stuff, or harmless stuff, but if it doesn't need to be there it should be removed.

NOTE: Under many units I wrote that they don't need [Health], that is because in the demo there's no way to damage them. However if there is consideration that 4RPL can damage some of these units therefore health should be displayed, please ignore the portions where it says [Health] isn't needed. I wrote how much health the units display they have in case this information aids whether or not health should be displayed.

Miscellaneous:
- CollectorPanel (Both large and small) in 09 Leo and Mark V Sample: Doesn't need [Armed]
- UltraC in Not my Mars: Doesn't need [Armed] and [Supply]. Disabling [Armed] doesn't stop the unit from storing and providing energy.
- Delegate: Shows 1.0/1 health. Doesn't need [Health].
- Wall: Shows 1.0/1 health. Doesn't need [Health].
- Supply Pod: Shows 0.1/0.01 health (bug?). Doesn't need [Health], [Armed] and [Supply] (Far as I can tell, Liftic caches just dispatch Liftic, so they are not supplied in any way)
- InfoCache: Shows 1.0/1 health. Doesn't need [Health], [Unit] and [Armed]. This unit turns red when disabled, but it doesn't do anything. Perhaps [Unit] could stay, if turning off the cache meant it wouldn't get picked up (there could be some strategy to this)
- Totem: Shows 1.0/1 health. Doesn't need [Health]. I thought about this one but all other options all have a use. [Unit] disables both shield and supply. [Armed] disables shield. [Supply] kills supply.
- Redon: Shows 0.0/0 health. Doesn't need [Health] and [Armed]. Should have a visual indicator when disabled, which it currently doesn't have. I assume this also applies to Bluite in crystal form.

Structures:
- Tower: Doesn't need [Armed]
- Pylon: Doesn't need [Armed]
- Miner: Doesn't need [Armed]

(Probably applies to other structures in the full game)

**Comment by BilboGCL** [comment]
crystals on level "Hints" shows units on/off and armed on/off

**Comment by Alophox** [comment]
Greenar Mother: Shows health 0.0/0. Doesn't need [Health], [Unit], [Armed]

**Comment by Karsten75** [comment]
Crystal tower unit
