### ISSUE TITLE
[4RPL Addition] Properly expose the "Weapons" Tab to 4RPL

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#630]
![image](https://user-images.githubusercontent.com/40322714/104644061-55e86280-56be-11eb-8f83-5eb61271b649.png)

Let's go by line items:
1. Range - exposed by GetRange and SetRange
2. Boost range with height - not exposed. Unclear how it works - apparently values 1-5 cause a difference but higher values give lower results?
3. Max ammo -exposed by GetUnitMaxAmmo and SetUnitMaxAmmo
4. Ammo ware - not exposed, requested in #608 
5. Can request ammo - not exposed.
6. Weapon fire pos - GetUnitFireOffset
7. Ern range boost - not exposed. Appears to be a multiplier, but that's not explicitly mentioned anywhere.
8. Upgraded range boost - not exposed. Appears to be how much ERN portal affects a unit, seems to be a multiplier.
9. Line of sight enabled - GetUnitLOSEnabled, however appears to be partially misleading as it's ALSO a setting to make unit's LoS visibly via yellow dots.
10. LoS always visible - not exposed.
11. LoS ignore terrain - not exposed.
12. Indirect LoS - not exposed
13. Indirect LoS height pad - not exposed, function unclear.
14. LoS target height - not exposed, function unclear.

There also exists a call GetUnitRangeWithMods which is useful, but currently unclear if it considers indirect LoS values/ height modification when returning. In fact it appears to not do that, which means it has limited use when dealing with ranges such as the one on screenshot below.

Can we get all the not exposed items actually exposed (especially stuff relating to indirect fire) with explanations of what those settings actually do to affect the unit's range calculation? Thanks in advance.

Why those need to be exposed - for units that can have different targeting modes, it would be nice to be able to set the stuff from script. It is also currently impossible to know if a cell can be seen by a given unit, especially for units with indirect fire - see the attached screenshot - how am i supposed to calculate in 4RPL that the tiles next to the cliff are not actually reachable? The game does that, but it can't be using the ballistic arc methods since i'm not inputting gravity/projectile speed anywhere.

Here's a screenshot of  ranges that i'm super unclear on how to calculate in 4RPL (and which might not even be correct, woo!):
![image](https://user-images.githubusercontent.com/40322714/104646151-1e2eea00-56c1-11eb-9b33-6773ee80d0c0.png)
![image](https://user-images.githubusercontent.com/40322714/104646223-356dd780-56c1-11eb-9bcc-93723999dbdf.png)

**Comment by RealArgonwolf** [comment]
I'd like to second this and add the possibility of setting built-in units' "UI" settings from script. Things like activating sprayer gravity fields, setting porter destinations and resource type, and setting units to request ERNs (including the ERN portal itself).
