### ISSUE TITLE
If submitting fails, there is no obvious way to retry

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#631]
Every now and then if I try to submit my results the game tells me Error:
![image](https://user-images.githubusercontent.com/16858356/104662736-bdf17580-56cb-11eb-9f14-32407371f951.png)

Two things: 
First, there is a message "Error:" and the colon gives me the impression, that something is missing.
And second: I'd expect a retry button. Right now I have to keep playing the mission and press Rift Jump again - depending on the playstyle, it happens pretty easy that one forgets to pause and as the Rift Lab is not connected, all nullifiers will fail pretty soon. This, in combination with the fact that by this time no auto save has been initiated, leads to a totally lost game.

**Comment by BilboGCL** [comment]
Same, if it is obviously (or at least very probably) a different error:
![image](https://user-images.githubusercontent.com/16858356/105393777-086b7880-5c1d-11eb-8c11-027ee5c667a8.png)

**Comment by knucracker** [comment]
Are you on the beta?  Does the error repeat with that map?

**Comment by BilboGCL** [comment]
Yep, I'm on Beta
I was able to submit on the next try, had to "Keep playing" and rift jump again.

**Comment by BilboGCL** [comment]
Just to make sure: That was Colonies!

**Comment by Regallion** [comment]
An easy way to replicate this issue is to cut off your internet before trying to submit. It will cause an error.
Seeing as that specific case can be a surprise to the user, some sort of a retry would really make sense.
