### ISSUE TITLE
Specific Mark V map allows no submitting

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#632]
[save-1.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5817683/save-1.zip)

I (and Regallion) were not allowed to submit scores on this specific map while submitting to other maps worked
Every time I try, the game throws an unspecified error
Here's a log file:
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5817688/Player.log)

Edit: Map's name is "Dead man's Hand#1333" - with a special character...

**Comment by knucracker** [comment]
I think this was resolved back in January, 2021.  Not sure, and it may already be in the current built.  I have marked it as closed for 1.9 and later. https://discord.com/channels/192420539204239361/368747848046739456/799454227033227266
