### ISSUE TITLE
[Bug.Minor] Wiki opening while saving with a unit selected

### ISSUE THREAD

**Issue by Fanquar** [KnuckleCracker/CW4-bug-tracker#634]
If a user tries to save a map while having a unit pending placement, if they type H into the name of the save, their browser will open the wiki tab for the unit they're placing.

example: 
![image](https://user-images.githubusercontent.com/49006425/104819040-4fc3c480-582b-11eb-8f44-c627689bd699.png)
opened up the https://knucklecracker.com/wiki/doku.php?id=cw4:info:nullifier page on my default browser.

**Comment by knucracker** [comment]
Added checks so that pressing H won't bring up the wiki when entering a file name.
