### ISSUE TITLE
[Bug] Blueite Miner show up as unusual decal in recorder mp4

### ISSUE THREAD

**Issue by Sorrontis** [KnuckleCracker/CW4-bug-tracker#635]
Help us help you. 

5. Describe the bug 
   As described in title. Can be seen in the video (https://youtu.be/MGYwHdkaH8o?t=85) at the center-bottom of the center island. 
The map was played on my Win7 Desktop (can provide details if necessary - Logfile already overwritten) and the video was encoded on my win10 laptop. 

Laptop Log file, Save File and Recorder File attached here (Video.mp4 file available upon request, its 71mb): 

[ErrorInRecorder.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5831101/ErrorInRecorder.zip)

**Comment by Alophox** [comment]
I have seen this bug as well; it only affects the blueite versions of the miner, not the energy versions.

**Comment by knucracker** [comment]
This was a left over unity 2019 induced issue. Unity 2019 changed the vertex order for the quad and setting an "override image" in the recorder was a bit of code I had not updated.
