### ISSUE TITLE
[Creeper World 3] Convert score tables to play log tables for Arc Eternal maps

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#636]
**Is your feature request related to a problem? Please describe.**
It is commonly known that score tables in CW3 can be pretty useless due to cheaters. However, many Colonial Space maps don't get much traction and score tables have more value there. However, in Arc Eternal story maps, the score tables have almost zero meaning.

**Describe the solution you'd like**
Convert score tables to play log tables for Arc Eternal maps. 

**Additional context**
This suggestion may break the CW3 achievement 'Born Leader' where a player has to place in top ten on the leaderboard.

**Comment by BilboGCL** [comment]
I'd include Prospector Zone and Tormented Space, too.
Born leader can either be gifted (that's probably what would happen when changing the system) or it has to be achieved at DMD or Colonial Space maps (that is more or less obligatory now, too)
