### ISSUE TITLE
[4RPL Addition] GetTerrainSurfaceNormal command

### ISSUE THREAD

**Issue by Sanian-Creations** [KnuckleCracker/CW4-bug-tracker#637]
I would like a command that returns a vector pointing exactly away from the terrain at those coords (a.k.a. the [surface normal](https://en.wikipedia.org/wiki/Normal_(geometry))).

The command would have signature `float float - vector`, where the 2 floats are the exact X and Z terrain coords, and the vecor is a directional vector (like what RotateTowards uses).

A possible use case for this would be placing units on an angled surface (like the side of a high wall), in such a way so that the unit appears to be anchored to the wall. Or, a unit passing over uneven terrain could rotate along with the surface so that it appears to be sliding over it.

I believe a similar calculation already has to be done within the `BounceTerrainCollision` command, so a command returning the angle of the surface without the bounce-calculations around it should be possible.

**Comment by knucracker** [comment]
Added a GetExactTerrainAndNormal api.
