### ISSUE TITLE
[Bug] Game loop breaking due to 4rpl exceptions

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#638]
Filling this out for someone else, EidolonWyrm on the discord.  For further information contact them.

So, this map apparently repeatedly triggers a series of exceptions that bog down gameplay.  It looks like the initial cause is probably 4prl related, but it eventually has exceptions in the main game loop, the result is the the game effectively pauses, because each frame throws an exception before it finishes.  

Here's the discord link to a message showing the video.  https://discord.com/channels/192420539204239361/371084855569809409/800925407620235324

Here's the player log which contains the exceptions.

[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5833528/Player.log)

Here's the map as the errors occur, the map will play for a couple seconds before locking at a time of 10:16.7

[error.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5833531/error.zip)

In case it's needed, here's the finalized map, the errors usually occur at around 10 minutes.
[finalized.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5833532/finalized.zip)

Unsure if this happens every time, but it has happened to them multiple times in an attempt to finalize the map.  

Also worth noting that if you delete all of the mortars that does stop the exceptions.

**Comment by knucracker** [comment]
The problem came from calling GetUnitAmmo (in 4rpl) on a unit that requires a ware, but the unit had no ammo.  Fixed in 1.2.beta and should be in the 1.3.0 release.
