### ISSUE TITLE
[Suggestion] Make Greenar Crystal spawn RNG seed not change after full map restart

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#639]
**Is your feature request related to a problem? Please describe.**
Greenar is often a key element to speedrunning maps in CW4 as it is usually required to power Totems. An issue is that every time a map is restarted fully, a new seed is generated for Greenar crystal spawns. This means players who are trying for a good time frequently have to spend a lot of time continuously restarting a level to find a good spawn pattern:

Start over -> Save -> Play on 4X to see spawn pattern -> If pattern is good, load save. If not, start over.

While some randomness is not inherently bad in speedrunning, in this case it's just not very fun.

**Describe the solution you'd like**
It would be much nicer if the seed for Greenar crystal spawns was predetermined with the map, so that the same thing would happen every time with Greenar spawns, at least early on in the level while no refineries are placed to harvest it and change the pattern.

**Comment by knucracker** [comment]
So the greenar mother uses the same repeatable RNG as everything else. It's  based on a seed determined the first time the map is loaded (which is when the map is first created in the editor). The seed for the RNG is persisted in the map save.  So if you make a map with only a greenar mother on it, then save the map, then let the map run... you will get the same crystal pattern each time you load the map back.

That said, anything else that uses the RNG will change the pattern of the crystals. On a real world map there at tons of things asking for random numbers. Many of them are conditional, so in practice you likely see a different output pattern from a greenar mother.

I have changed each mother to have it's own RNG and hence sequence. This decouples each from the the master RNG. Now terraforming and other things that affect crystal placement can still cause the pattern to change. For instance, if a crystal tries to spawn but it can't, then a new location is chosen. That changes the sequence of random numbers and you will find yourself with a bone fide Kelvin timeline on your hands for that greenar mother.

**Comment by Karsten75** [comment]
re-opened wrong 'un
