### ISSUE TITLE
[bug] Corrupted icons in Recorder

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#64]
The Icon for the ERN Portal appears corrupted

![image](https://user-images.githubusercontent.com/22965021/95652316-b8293a00-0ab5-11eb-8b63-3af6f90db16d.png)

Uploaded recorder file that above image was taken from as a .zip. 

[victory_361.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5358776/victory_361.zip)

There is also an observation made that some of the recorder files in the Discord Competition channel appears to not show the factory being built.

**Comment by knucracker** [comment]
- Updated Factory image.
- Updated ERN Portal image.
- Updated AirSac Cauldron image.
- Updated Greenar Refinery image.
- Updated Ultrac image.
- Updated Bomber/ACBomber image.
- Updated Sprayer image.
- Updated ERN Portal image.

Fixed bug that was causing some custom unit images to overwrite some built in images. I had reserved only 64 slots for built in images in the texture array. There were 66 used. So things like the obelisk could overwrite the last built in unit images (like the hold base image).  I changed it to reserve the lower 70 texture array slots for built in images and reserved the upper 48 for custom units.
