### ISSUE TITLE
[4RPL Addition] Add get/set pseudo terrain unrelated to units

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#641]
Add an API call that allows setting and getting pseudo terrain per cell.
Use case discussed in discord, it's similar use cases to units but without needing to be tied to the square shape.

**Comment by Regallion** [comment]
Incidentally, a setting to allow such terrain to persist on save-load could be useful.

**Comment by WithersChat** [comment]
If it's possible to get this work with negative pseudoterrain too, it would be perfect!

**Comment by knucracker** [comment]
Get/SetTerrainOverride has been added.
