### ISSUE TITLE
[4RPL] Basegame messages are unknown

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#642]
It's been mentioned that certain in-built events send a message one can subscribe to.
Can we have a list of those events for reference?

**Comment by knucracker** [comment]
The "Built in function callbacks"  on https://knucklecracker.com/wiki/doku.php?id=4rpl:start document the function calls. If additional ones are added they will show up there. If any are discovered to be missing, they should be added there.
