### ISSUE TITLE
[4RPL Addition] A tracelog window for units with scripts attached

### ISSUE THREAD

**Issue by Sanian-Creations** [KnuckleCracker/CW4-bug-tracker#643]
**Problem**
Currently, if you write any code that doesn't work properly you can run it in the console to find if it has any issues, runtime warnings such as "treating a non-list like a list" and "taking items from an empty stack" will show up there.

With scripts for _units_ this is impossible. If a runtime warning happens you simply cannot tell. For manually displaying info there's `SetUnitDebugText`, but I personally find it rather unfit for actually displaying debug info due to how large the font is and how the content automatically gets wrapped if it is too wide, which is particularly annoying when trying to display vectors (which will sometimes fit in one line, but wrap to the next if the values have too many decimal places).

**Solution**
In CW3 cores had a feature where they could each open up their own little output window, which could be used to display debug info through the Trace command, runtime warnings would also show up in there. I would very much like it if units with scripts in CW4 could also display their trace log in one way or another.
![image](https://user-images.githubusercontent.com/76259603/105168463-754a1a00-5b1a-11eb-96c1-8f4fdea9fe76.png)

**Possible implementations**
1. One way to implement it would be in the same way as CW3 where there is a `ShowTraceLog` and `HideTraceLog` command, no need to reinvent the wheel. The trace log will show up in the game at the location of the unit just as in the previous game.

2. Another way to do it could be to use the Mission Editor overlay. Selecting a unit already allows us to modify the Script Settings, another button could be added to **"Open unit TraceLog"** which would open a screen very similar to the current 4rpl console, just linked to that particular unit. This would also assure that the window could never be displayed whilst playing the map and is only used for actual debug purposes. Here's what that could look like:
![Untitled](https://user-images.githubusercontent.com/76259603/105167261-c8bb6880-5b18-11eb-9f16-829933f3e8a2.png) ![unit console concept](https://user-images.githubusercontent.com/76259603/105170175-d70b8380-5b1c-11eb-8e46-5867fac43641.png)
One problem with this approach is that it makes it kind of difficult to modify scripts efficiently, since it forces players to constantly navigate between windows through **Close tracelog > close unit settings > open CPACK manager > Compile all scripts > close cpack manager > click unit > open tracelog**. Some additional buttons could be added to the unit console to aid this.

**Comment by Karsten75** [comment]
#917 resolved this, I believe, feel free to re-open if the solution is not sufficient.
