### ISSUE TITLE
[4RPL Addition] Add a method to inflict stun

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#644]
Right now, there is no way to replicate skimmer's EMP functionality.
Allow us to inflict stun on units.
Desired methods - 
1. SetUnitStunned - takes a unit and duration, sets a stun counter on unit to that many frames. 
2. GetUnitCanStun - gets the value of the "Can stun" setting on the unit, needed to avoid stunning unstunnables. SetUnitStunned  should not check for this setting, as you might want to bypass immunity.
3. SetUnitCanStun  - sets the value of "Can stun" setting.
4. GetUnitStunned - returns the amount of frames of stun remaining. 0 means "Not stunned".

**Comment by knucracker** [comment]
Added: Get/SetUnitCanStun, StunUnit, StunUnitsInRange, GetUnitStunCount, ClearUnitStun apis.
