### ISSUE TITLE
[4RPL Addition] Add ability to interact with crimson

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#645]
Basically add a pair of GetCrimson and SetCrimson methods.

Can't say much about the specifics, as crimson mechanics are kind of opaque (especially how it chooses to flow and how long it lasts)

Use cases: allowing units to create crimson creeper like forbs do, without messing with terrain.

**Comment by knucracker** [comment]
Added Get/SetCrimson apis.
