### ISSUE TITLE
[4RPL] GetUnitByType doesn't get all units by type

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#647]
`"Stash,Emitter,SporeLauncher,BlobNest,SkimmerFactory,AirSacCauldron,DarkTower" "," split ->UnitsList
<-UnitsList Trace
<-UnitsList GetListCount 0 do
	<-UnitsList[I] 0 GetUnitsByType ->TempList
	<-TempList Trace
loop`

Will result in an output of:
`[Stash, Emitter, SporeLauncher, BlobNest, SkimmerFactory, AirSacCauldron, DarkTower]
[]
[788]
[786]
[785]
[920]
[]
[]
`

if used on a map below:
![image](https://user-images.githubusercontent.com/40322714/105257594-28f1ef00-5b99-11eb-8568-076b48c859b4.png)
Specifically 

- Stash
- AirSacCauldron
- DarkTower

appear to not be valid types.

Ideally a recheck of all units being correct is in order.

**Comment by knucracker** [comment]
Reviewed and update all unit names in the unit name table. Fixes this problem (and a bunch others).
