### ISSUE TITLE
[4RPL] [Bug] return does not break nested loops correctly

### ISSUE THREAD

**Issue by Uzguz** [KnuckleCracker/CW4-bug-tracker#648]
If a `return` statement is encountered from within a loop at least 2 levels deep, it will exit the function, but will only clear the innermost loop's jump point. If a `loop` statement is subsequently encountered outside the function, execution will jump back into the function's outer loop.

Code:
```
"Outside" Trace
5 0 do
	"LoopA" I TraceAllSp
	@Function
loop

:Function
	"Function" Trace
	false ->shouldHaveReturned
	5 0 do
		"LoopB" J I TraceAllSp
		5 0 do
			"LoopC" K J I TraceAllSp
			<-shouldHaveReturned if
				"Whoops..." Trace
			endif
			I 2 eq if
				"Return!" Trace
				true ->shouldHaveReturned
				return
			endif
		loop
	loop
```

Output:
```
Outside
LoopA 0 
Function
LoopB 0 0 
LoopC 0 0 0 
LoopC 0 0 1 
LoopC 0 0 2 
Return!
LoopB 0 1 
LoopC 0 1 0 
Whoops...
LoopC 0 1 1 
Whoops...
LoopC 0 1 2 
Whoops...
Return!
```

As for why it terminates early: best guess, although execution jumps back into the function, the call stack still thinks it's outside the function, so the second hit on the `return` statement returns from the outside.

**Comment by knucracker** [comment]
The 'return' was basically doing the same thing as 'break' and then returning from the function. This wasn't correct if there were nested loops in the function, as you noted. I changed 'return' to pop off everything (everything pushed in the function) of the while and the do loop stack. This solves this problem.
