### ISSUE TITLE
[bug] New Menu does nto dismiss with Esc key

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#65]
![image](https://user-images.githubusercontent.com/22965021/95652596-e60f7e00-0ab7-11eb-8414-5a3ed284fade.png)

This menu can be called into existence by pressing the Esc key. It should thus also dismiss when open and the Esc key is pressed.

**Comment by knucracker** [comment]
It is dismissing for me when I press ESC. Do you have a special case where it isn't?  I tried selecting a unit, etc. But it still seemed to dismiss when I pressed ESC.

**Comment by Karsten75** [comment]
I swore It didn't work ... sorry!
