### ISSUE TITLE
[4RPL Bug] GetUnitsInRange uses hitboxes instead of position when isSquare is true

### ISSUE THREAD

**Issue by Sanian-Creations** [KnuckleCracker/CW4-bug-tracker#650]
### Reproduce

- Create a new unit which is far wider that it is long (adding a cube object for visualizing might help)
![image](https://user-images.githubusercontent.com/76259603/105356609-e8738f00-5bf3-11eb-8133-53def636aac2.png)
![image](https://user-images.githubusercontent.com/76259603/105356453-b6fac380-5bf3-11eb-8fff-870b9c751f78.png) ![image](https://user-images.githubusercontent.com/76259603/105356400-a2b6c680-5bf3-11eb-9079-3175cdf45c1b.png)
- Place the unit somewhere and run the following script from the console:
```
GetPointerTerrainCoords GetTerrainvector #startPos
1     #range
false #isSquare
true  #is3D
false #requireLOS
0     #enemyState
0     #builtState
0     #imperviousState
GetUnitsInRange
ClearTraceLog
TraceAllSp
```
- Any uid of a unit within 1 tile of the cursor will be printed to the console, Notice how we have to point at the very center of the unit for it to show up, because the exact position of the unit is what decides if the unit is in range.
- Now switch **isSquare** to true and re-run the script. Notice how we can now point anywhere around the edge of where the unit is and it will still show up in the console, the exact position of the unit is no longer used to decide if the unit is in range.

This means the **isSquare** boolean doesn't only change the shape of the search area, is also changes the way in which the search itself works, which isn't what the name suggests.

I'm honestly fine with this being how it works, it just isn't very intuitive. I wanted to bring attention to it because i didn't know if this was an intentional choice or something to do with a built in Unity method being used.

**Comment by knucracker** [comment]
Not really intentional. I see that the "isSquare" short circuits the range check. The way the routine is written this causes it to fall back to accepting the unit as in range. And the units selected as candidates are ones that have some part of their footprint in 'square' range.

I could fix it, but I might break some existing maps if I do. It might cause some units to be missed that are currently being picked up.

**Comment by Sanian-Creations** [comment]
I'll just update the wiki then, I understand changing commands after the fact may impact existing scripts.

**Comment by Sanian-Creations** [comment]
> I see that the "isSquare" short circuits the range check.

@knucracker I assume this means the returned list is also not sorted anymore, correct?

**Comment by knucracker** [comment]
Interestingly, they should still be sorted... unless isSquare is true and is 3D is set to true. So they will be sorted when doing a 2d search but not a 3d search (when isSquare is set).  The reason for this has to do with how the isSquare 'short circuit' was implemented (how the range check was skipped).

**Comment by knucracker** [comment]
I added another API called GetUnits. Same as this one except it takes a new first argument (a unit type string). GetUnits will search across all units (of the type) on the map regardless of the footprints. I also made the isSquare setting work 'correctly' on this API.
