### ISSUE TITLE
[4RPL] GetUnitSettings returns millions for emitter payload.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#651]
When asked to return emitter payload, GetUnitSettings will return payload in millions, inconsistent with all other payloads, which are measured in creeper units.
Get/Set of emitter payload should be consistent with other payloads.

**Comment by knucracker** [comment]
This will apply to the "payload" setting on all of the units that deal in creeper. I'll change them all to floats and normalized 'creeper' units.

**Comment by knucracker** [comment]
Changed the "Payload" settings to return creeper normalized values (floats)
