### ISSUE TITLE
[Bug] SetObjTextBillboard does not compile

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#654]
Help us help you. 

5. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

SetObjTextBillboard does not compile on version 1.2. I tried copying and pasting the example from the wiki, and that doesn't work either. All that is needed to do to recreate it is to type it into a script and try to compile.

[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5853683/Player.log)

**Comment by knucracker** [comment]
There was a typo in the command name. It  was "SetObjTextBilloard" (the B was missing in BillBoard). I have fixed this in the current beta branch so it will be in the 1.3 release. I have also kept the erroneous SetObjTextBilloard command in the event anyone was actually using it. You can use  the typo'd command  in the 1.2 release and it will continue to work in future releases.
