### ISSUE TITLE
[bug]  Factory and ERN portal  icons are shown as inactive in Recorder

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#66]
Leaving aside the already-reported issue that the ERN portal icon is corrupted in the Recorder, these icons are also showing as their inactive versions and not the colored versions that depict their active status. 

![image](https://user-images.githubusercontent.com/22965021/95652817-8619d700-0ab9-11eb-9bf4-4123eb7aef28.png)

Active factory icon 
![image](https://user-images.githubusercontent.com/22965021/95652843-afd2fe00-0ab9-11eb-91e5-8b33960a827b.png)

Active ERN portal icon
![image](https://user-images.githubusercontent.com/22965021/95652849-bcefed00-0ab9-11eb-9f6d-fbe16723c1e9.png)

**Comment by knucracker** [comment]
Same as #64
