### ISSUE TITLE
[Bug.Minor]

### ISSUE THREAD

**Issue by kemiller** [KnuckleCracker/CW4-bug-tracker#661]
Hi, I think this is a bug; it is a least a very strange behavior, and it's quite reliable if you set it up right.  After I win I like to try to max out the AC production and create a sort of aquarium effect.  Don't judge me.  I'm talking about > 200 level AC coverage across the entire board.  I also like to play around and make waves.  So I was doing that today by setting one of my sprayers to AC Collection and watching a giant spike develop.  But here's where it gets weird.  It *looks* like when it goes over a certain level, it converts the center column to regular creeper!  Now, there is no creeper left on the board — everything is nullified and mopped up.  But there's a tiny blue spike at the top of the column.  And then it kills the sprayer!  It explodes, a ghost floats up, and nearby sprayers start attacking the spot where it was for a few seconds.  Is this intentional?  Is there a hardcoded limit for AC height?  Anyway, doesn't affect gameplay really, but I thought it was odd.

**Comment by Regallion** [comment]
There is a limit of 2147 creeper height in either direction (C or AC), at which point it flips. This is normal and expected behavior even if it's not very documented.
