### ISSUE TITLE
[4RPL Addition] Add minimap hookups

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#662]
Desired actions:
1. Put icon on minimap
2. Remove icon from minimap
3. Change icon color (to signify status)
3. Issue a map warn (with timer). Map warn can (must?) be associated with an icon causing it to flash.

Right now custom units cannot show up on the minimap OR cause warns, which is somewhat limiting for custom spore launcher and such. I remember this being talked about at some point, but, oh well.

**Comment by knucracker** [comment]
I'll see what I can do... it may not be super straight forward.

**Comment by Alophox** [comment]
I came here to find one of the two problems already made. +1 for this.
If all else fails, a system similar to the Raster currently in place may be viable... though the minimap does rotate, so maybe not.

**Comment by knucracker** [comment]
Added Get/SetUnitMiniMapImage, Get/SetUnitMiniMapImageColor, Get/SetUnitMiniMapText, Get/SetUnitMiniMapTimeToEvent
