### ISSUE TITLE
[4RPL Addition] Add a real-time timer function

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#663]
**Is your feature request related to a problem? Please describe.**
Optimizing 4RPL scripts is currently a bit of a pain. The best way to measure a script's impact on performance is GetLastInvocationCount, which only roughly corresponds to execution time. (As an extreme example, "Add" and "UpdateUnitLOSCache" both count the same, despite only one of them being taxing.) Barring that, the most you can do is put the speed up to 4x and see how much the framerate drops.

**Describe the solution you'd like**
CRPL had an ElapsedTime function that was useful for performance optimization, both in the editor and potentially by the script in real time. Some kind of special timer function that worked like the already existing timer functions would work the same.

**Describe alternatives you've considered**
Running scripts in the console currently shows the invocation count, so adding execution time there could be an alternative that wouldn't affect things outside of edit mode.

**Comment by knucracker** [comment]
Added ElapsedTime 4rpl command.
