### ISSUE TITLE
[4RPL Addition]  Allow interaction with terraform markers

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#668]
Desired operations:
1. Set terraform marker. Sets a terraform marker at X/Z with specified height. Can be set on void or TO void.
2. Get  terraform marker. Gets a target height of a terraform marker at X/Z. Returns -1 if none present.

Useful for custom terraforming units, to both allow terraforming to/from void, and to allow such units to interact with the normal TERP framework, without needing an entire new custom UI.

**Comment by knucracker** [comment]
Added GetSetTerraformMarker 4rpl api.
