### ISSUE TITLE
[4RPL Addition] Allow 4RPL to interact with ERN states

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#669]
This will be a little long, apologies in advance.

As of right now, it is impossible for 4RPL to do much about ERNs, except getting the ERN state of units. (In fact, destroying an ERN while it's assigned to a unit actually causes buggy behavior i am only not reporting because it would be covered by this request)
It is desirable to have control over the ERN state of units, especially forcing the "On" state even if an ERN is not present, for example to simulate CW3 power zones.
To that end i propose the following adjustment to the ERN system and methods.

Status model:
A unit may have the following states regarding ERN state
1. None
2. Want
3. Held
4. Active  - when a unit is in this state it acts as ERNed for all intents and purposes, but has no ERN attached. If a unit has an attached (or assigned and in-flight) ERN, it is de-assigned when this state is entered. Visually indistinct from Held.

Status transitions:

Via UI:

1. None-Want
2. Want-None
3. Held-None

If the state is Active, no user action affects it.

Via 4RPL

1. None-want - behaves like the current UI interaction
2. None-Active - shifts from None to Active
3. Want-None - behaves like the current UI interaction
4. Want-Active - shifts from Want to active. Any ERN movement is canceled as if Want-None transition was performed.
5. Held-Active - shifts from held to active. The ERN is released in the process.
6. Held-None - behaves like the current UI interaction
7. Held-Want - Added for completeness sake, little practical use. The ERN is released when the transition occurs and can theoretically be snatched by another wanting unit.
8. Active-Want - Shifts from Active to Want. The effect is similar to None-Want interaction in terms of requesting an ERN. Simply disables the ERNed effect, no ERN is released.
9. Active-None - shifts from Active to None. Simply disables the ERNed effect, no ERN is released.

You cannot transition into a "Held" State via 4RPL, as that is a prerogative of an arriving ERN to do so. 

Desired methods:

GetUnitERNState - instead of 0 or 1, return 0-3 depending on states outlined above. Can be a separate method for backwards compatibility, in which case the current method would need to recognize "Active" as a case to return "1".
SetUnitERNState - accepts a unit and a state. Acts according to state transition list above.
GetUnitAssignedErn -  accepts a unit. Returns the UID of an ERN assigned to a unit, -1 otherwise. Should count an in-flight ERN if a unit is in a "Want" state.
SetErnPortalState - Accepts a slot number and state number. Portal states are functionally equivalent to unit states - it still has None/Want/Held even if it's not labeled as such. State transitions act in the same way as for units. If a slot is Active it simply has no ERN on the unit but is visually still a green square with no "Release" option.
GetErnPortalState - Accepts a slot number, returns 0-3 for current slot state.
SetErnPortalEfficiency -Accepts a slot number and a float 0-1. Sets the efficiency of that slot to that number. 
GetPortalAssignedErn - Accepts a slot number, returns the UID of the ERN assigned to that slot. -1 if no ERN is assigned.

Modification to GetUnitSettings - if asking the ERN about his settings, return the UID of a unit the ERN is assigned (or in-flight) to. -1 if not assigned.

**Comment by knucracker** [comment]
Most of these are bit tough (as in time consuming to implement). I added one concept, though.  SetUnitERNSimulated.  Set that to true and a unit should act like it has an ern even thought it does not. This sets a state that is independent of an actual ERN. So the unit can still request an ern or release one. This state is also invisible (unless the script author shows something), and does not show the glowing ERN indicator.
