### ISSUE TITLE
[4RPL Addition] Enhance interactions with energy generation.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#670]
GenerateEnergy is a really nice call, but it leaves one specific niche unfilled - enhancers for energy generation. If i want to make my little replica of a ERN portal "Energy collection" effect, i have no way to perform that, especially since calculating the energy gain from towers is nigh-impossible.  It is also impossible to know how much energy a player is generating, which could be used to scale enemies/effects/drains based on that.

The following calls are desired:
1. GetEnergyGeneration - returns the "Gen" number
![image](https://user-images.githubusercontent.com/40322714/106014497-99839900-60ce-11eb-9a78-eeed8642cdff.png)
2. GetEcoEnergy - returns the green + number
![image](https://user-images.githubusercontent.com/40322714/106014592-abfdd280-60ce-11eb-8213-96de3b156b14.png)
3. GetBonusEnergy - returns the yellow-ish + number
![image](https://user-images.githubusercontent.com/40322714/106014669-bf10a280-60ce-11eb-8bae-98598bf8b91c.png)
4. GetRawSoylentEnergy - returns the raw amount of energy generated by towers. Does not count the effects of ERN portal. Not required, would be nice.
5. GetSoylentEnergy - returns modified amount of energy generated by towers. As i understand the ERN portal is not a flat 50% increase for them, hence this method.
6. GetRawMinerEnergy - returns the raw amount of energy generated by miners. Does not count the effects of ERN portal.
7. GetEnergyUse - returns the current value of the "Use" number
![image](https://user-images.githubusercontent.com/40322714/106017037-1a439480-60d1-11eb-8004-c02c1c2d768b.png)
8. GetEnergyStore - returns the value of the "Store". If it's "Deficit" the value is negative.
![image](https://user-images.githubusercontent.com/40322714/106017127-347d7280-60d1-11eb-8800-7a1309b25fe5.png)

Energy from other sources can be calculated by subtracting SoylentEnergy, EcoEnergy and MinerEnergy from EnergyGeneration, meaning that customs/panels do not require an additional method to get their production total.

Enhance GetUnitsSettings - when asking a miner about his properties, return his % efficiency and mode. 

This also allows me to trigger things based on player's energy generation, such as enabling a custom objective to generate a certain amount of energy, or checking his energy generation composition.

**Comment by knucracker** [comment]
I can get you some of these APIs. GetEnergyGenerations, GetEnergyUse, GetEnergyStore, GetEnergyEco, and GetEnergyBonus have been added. I also made the game persist these values across a save/load so when the game comes up after a save the values don't have to wait to repopulate. The EnergyUse, for instance is a rolling average over a time window.
