### ISSUE TITLE
[Bug.Minor] Sprayer behaviour inconsistent with CW3 wrt Armed/Disarmed status

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#671]
In general, units that are Disarmed ` Armed: Off` should still permit ammo requests. The intent of this setting  that the unit will have a full inventory of ammo, but not fire at targets. 

Sprayers can obtain ammo in two ways. One via requests from the Factory, and also by enabling the Ore Dispatch setting. 

In the latter case, a sprayer also do not collect/dispatch the anti-creeper on the terrain. This is incorrect and probably should be changed to have parity with  how a sprayer operated in CW3.  

It is not anticipated that this will have an impact on existing maps in any sector of the game.

**Comment by knucracker** [comment]
Made the sprayer armed status not be coupled to collect and dispatch
