### ISSUE TITLE
[4RPL Addition] Enable totem interactions

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#672]
Currently, all totems have a "None" setting that was meant to be used with 4RPL as per discord discussions.

Can the planned API for that be implemented? Presumably you could enable totems, disable totems, set ware, set quantity, although the last 2 could probably be handled by MaxAmmo and the ware setter whenever that becomes implemented.

**Comment by knucracker** [comment]
Added Get/SetTotemActivated. Note that Get/SetUnitSettings already has a way to manage the totem ammo type. I've also added a Get/SetUnitAmmoWare and Get/SetUnitBuildWare apis that work on all units.
