### ISSUE TITLE
[Bug] If a unit's object is disabled on save-load, the object winks out of existance

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#675]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5896765/save.zip)

You can see 2 floating black cubes - URNs. The cube object is labeled as "Body"

One of them is assigned to a  Dummy tower, you can see it by a color-changing frame around it.  This is the "Frame" object of the URN unit.
1. Select any other tower, change URN to "Want"
2. As URN arrives, it disables it's own "Body" objects and enables "Frame". This does not properly happen.
3. Go to the already URNed tower, change URN to "NONE". The frame will disappear, the "Body" will not appear.
4. Go to URN_PAC Cpack in cpack manager. Recompile scripts and Update instances.
5. Let game run for a few seconds to spawn new URNs.
6. Choose any tower, change URN to "Want"
7. When URN arrives, the "Body" object will disable and "Frame" will enable correctly. This behavior will break on save-load.

**Comment by knucracker** [comment]
Disabled objects weren't getting recognized. Had to add "include disabled children" to the children crawling routine.
