### ISSUE TITLE
[4RPL] A unit's UI will not be recognized as similar even if it's the same.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#676]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5896792/save.zip)

1. Let run for a few seconds.
2. Select 2 URN dummy's (look like carbon towers)
3. They will all have a custom UI element that has options of "NONE" and "WANT"
4. Select "Want"
5. Wait for URNs to arrive
6. Their custom options will change to "HELD" and "NONE"
7. Select an URNed tower and a non-URNed tower. The game will recognize their elements as disparate and show a ---. This is correct.
8. Select the URNed towers. The UI will be correctly considered to be the same. Select "NONE" for both of them.
9. The options will be set to "NONE" and "WANT"
10. Select a previously URNed tower AND a never-URNed tower.
11. Despite the fact that their UIs are equivalent, they are not considered to be the same and show a ---. This is an error.

**Comment by knucracker** [comment]
UISettings get set to override values when they are set by 4rpl. The GUI code didn't factor this in, so changes values and default values were treated as different.
