### ISSUE TITLE
[Bug] Unit limit can apply incorrectly when using click&drag

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#677]
![image](https://user-images.githubusercontent.com/40322714/106336966-0fd7f500-62a1-11eb-9a33-73f7540ac6ac.png)
As you can see i can build 3 more "HAHA" units.
However, once i start click and drag, all invalid units will also expend my allotment of units, even though they are invalid and should not count, meaning that even though i should be placing 1 unit at start and 2 after the wall ends, i can only place 1 at start.

**Comment by knucracker** [comment]
Fixed the issue when dragging units and some not being legal. Also made it so the unit limit popup does not show up on every build ghost when dragging. The popup will show up on the "first" unit when you are at or beyond the limit.
