### ISSUE TITLE
[Bug.Minor] Overloading nullifier has an ammo cap of 999

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#678]
Since it blows up on 750, why not set max ammo to that instead?

**Comment by knucracker** [comment]
That's so it keeps asking and gets what it needs (750 internally). If I set it to 750 it would never fill up in some cases since I have the consumption rate set fairly high while overloading. To compensate,  you can mouse over the nullifier when it is not selected to see the percent complete.

**Comment by Regallion** [comment]
Ah, okay, makes sense then.
