### ISSUE TITLE
[4RPL Addition] Add a third state to SetUnitERNSimulated

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#680]
This call already fulfills a bunch of my ERN-related use cases, but i would like it to have a third state that is the inverse of it. When active, a unit acts as unerned even if it's ERNed. Meant for a unit like the Archon's suppression tower, where the ERN effects are suppressed in the area/mission/unit type while the opposing unit stands.

**Comment by knucracker** [comment]
Changed to take an int rather than a bool( -1,0,1).  -1 means to suppress an ERN. 1 means to simulate an ERN, and 0 does nothing.  Since booleans are really just ints in 4rpl, this change is backwards compatible with any code that passed in false and true.
