### ISSUE TITLE
[Bug] OVERLOAD button on nullifiers is there regardless of map setting

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#681]
![image](https://user-images.githubusercontent.com/40322714/106339892-08b4e500-62a9-11eb-9fe9-1c58f70cb34e.png)
Here's an example on a farsite mission. The button does not work, but still, that's very confusing.

**Comment by knucracker** [comment]
Had an error in the logic that showed the button.
