### ISSUE TITLE
 [Bug] Enemy ghosts are incorrect

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#683]
![image](https://user-images.githubusercontent.com/40322714/106340277-48300100-62aa-11eb-8297-12a0356d1379.png)
![image](https://user-images.githubusercontent.com/40322714/106340303-5da52b00-62aa-11eb-953f-365b0c0ece18.png)

Not only don't all normal units have ghosts, but those that do use old models (same as the use for placement)

Also, you can change to color of ghosts? How?

**Comment by Regallion** [comment]
I don't think the emitter ghost is quite correct either tbh

**Comment by knucracker** [comment]
Removed destruction ghosts for the enemy unit structures.
