### ISSUE TITLE
[Bug] All TERPed land inexplicably becomes slot 7 terrain in beta 1.2.5a

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#684]
![image](https://user-images.githubusercontent.com/40322714/106341224-8844b300-62ad-11eb-9a44-be263f35e00b.png)
![image](https://user-images.githubusercontent.com/40322714/106341269-add1bc80-62ad-11eb-9a16-16ea86d60ce3.png)

Normally slot7 is shattered land, but, well.

**Comment by knucracker** [comment]
Typo caused this (introduced when I added the SetTerrainMarker 4rpl api).
