### ISSUE TITLE
[4RPL] Setting terraform marker on void causes terps to become stuck

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#685]
`SetTerraformMarker(0 0 1)
SetTerraformMarker(0 1 2)
SetTerraformMarker(0 2 3)
SetTerraformMarker(1 0 4)
SetTerraformMarker(1 1 5)
SetTerraformMarker(1 2 6)
SetTerraformMarker(2 0 7)
SetTerraformMarker(2 1 8)
SetTerraformMarker(2 2 9)`

Make sure the bottom-left corner is void.
If done that way, the ERN will dutifully pick a cell and terp it to assigned height, then become stuck terping it and wasting ammo indefinitely. On save-load, the markers will be deleted and the terp will become unstuck.

Expected behavior: terraform markers on void behave no different from markers on land, except they are on void.

**Comment by Regallion** [comment]
The markers also don't properly show up which is...inconvenient.

**Comment by knucracker** [comment]
Markers aren't supposed to exist on void. The problem was the API was allowing them (sort of). 4rpl can of course modify the terrain (including void) but setting terraform markers for Terps to use is not allowed on void now.
