### ISSUE TITLE
[Bug.Minor] In-built cpacks are reloaded when the map is reloaded

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#686]
1. Create a new map
2. Enable airships.
3. Change the script setting for airships - say, make the default unit speed 0.3 instead
4. Build an airship - settings work.
5. Save and load
6. Build an airship. Find out settings were reset to default.
7. Whoops.

**Comment by Regallion** [comment]
This also applies to all normal settings, so if i want the airships on my map to cost 600, whoops can't do that.

**Comment by knucracker** [comment]
Previously, I was not persisting the 3 special embedded cpacks. They were not in the save and also not loaded if they were. The idea was they weren't needed.  I have removed this, so now they persist. Upon load, any changes made to them should show up. If you go to the game settings menu and disable them, that removes their cpack (and hence changes). Basically, the checkbox in the game menu does an import and remove (as it is toggled). So keep that in mind.
