### ISSUE TITLE
[Suggestion] Alternate default thor script

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#687]
[Thor.TXT](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5898268/Thor.TXT)

A modification to a thor script with following changes:
1. Added new defaults maintainHeight (bool) and minHeight(int). If bool is true, then instead of hovering at 30, the thor will hover minHeight from terrain. This allows for far easier resupply.
2. reworked the LoS cache check to actually work (was using incorrect assignment)

The only downside of this mode is that it allows there to potentially be a wall between a thor and it's target thus causing it to fire rockets fruitlessly, but that can already be replicated even with current mode so i don't see it as much of an issue.

**Comment by Regallion** [comment]
You could probably even make it a UI toggle for the player, but that might also be a little too OP?

**Comment by knucracker** [comment]
Incorporated
