### ISSUE TITLE
Airship, Bertha and Sweeper aren't fully capitalized in build menu[Typo]

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#689]
The three units added in the beta build only capitalize the first letter in contrast to other units which are all fully capitalized.

![image](https://user-images.githubusercontent.com/68219054/106367614-e7d4aa00-6311-11eb-9978-25bd007cf375.png)

![image](https://user-images.githubusercontent.com/68219054/106367616-ed31f480-6311-11eb-92ee-6d5de872fbfd.png)

**Comment by Bob2Chiv** [comment]
related to : https://github.com/KnuckleCracker/CW4-bug-tracker/issues/659

**Comment by knucracker** [comment]
Changed to upper case. Also fixed a few other issues (whether they were all logging destroy, removed popups, and made sure they took damage from creeper and could not build on contaminant)
