### ISSUE TITLE
[bug] Absorber terrain uses wrong terrain texture

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#69]
https://youtu.be/KY2pyFlpzA0?t=4698
The bug popped up in the latest video. Didn't see the issue posted, figured I'd post it so it is not forgotten.

https://youtu.be/KY2pyFlpzA0?t=4819
"All textures are off by one"

**Comment by knucracker** [comment]
I was off by 1 on all of the textures. They are stored in a textureArray and marshalled via UV coordinates into the shader. After a recent upgrade of Amplify Shader editor, some connections to triplanar shading got cut. When I fixed them I hooked them up wrong. So all of the resource terrain textures were off by 1.
