### ISSUE TITLE
[4RPL] Changing a unit's ammo ware does not work correctly

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#690]
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5898885/save.zip)

See the yellow "Burner" units.
Each of them only works with one of three settings. if switched, the burner will request a different ware but it's ammo will be stuck at 0 and will not be recognized by scripts (even though it will stop after requesting 15 packets, meaning it DID get filled)
The reason why the 3 burners all work... but with a different ware is that apparently the unit works with the first ware it was ever assigned and not any other one.

**Comment by knucracker** [comment]
The contains wares in the wares dictionary was not being cleared. So leftover ammo from a different type of ware was causing the unit confusion.
