### ISSUE TITLE
[4RPL] SetUnitERNSimulated does not correctly interact with custom units

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#691]
Now, for normal units it works 100% fine, tested it, no issues.

However, for custom units it does not quite work. The reason for it, is that custom units check for the ERN presence by using GetUnitERNState, which does NOT change when you add a simulated state change. You could set a variable in every unit where you set the simulated state, but that's a little dirty and not very cross-compatible since different simulation setters could set a  different variable.
Would it be possible to either add GetUnitERNSimulated (so i can just check for both ern state/sim state with a ||) or make GetUnitERNState return the final state?

**Comment by knucracker** [comment]
Added GetUnitERNSimulated
