### ISSUE TITLE
[Bug.Minor] Blob nest has inconsistent 0 interval interaction

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#695]
On every enemy unit except emitter, setting an interval to 0 means "Do not do this" This is true for spores, eggs, forbs, skimmers and airsacs. Blob nests however, if given an interval of 0, will force-set it to 1. This is inconsistent with other units.
I consider emitters a special case in that regard even though they share that behavior.

**Comment by knucracker** [comment]
Changed
