### ISSUE TITLE
[bug] [linux] Crash when exporting video with default name

### ISSUE THREAD

**Issue by LordFarin** [KnuckleCracker/CW4-bug-tracker#7]
2. Output log: [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/4897232/output_log.txt)

3. Screenshot of situation: [20200709_screenshot_CW4.pdf](https://github.com/KnuckleCracker/CW4-bug-tracker/files/4897283/20200709_screenshot_CW4.pdf)

4. Describe the bug:
**Context:** Saving a video from the Recorder.
When I would click the path suggestion, there would be something like an automatic suggestion like "<Map_name>_<date>.mp4" but when I use that, the game freezes and has to be manually killed.
I've retested with different names and _as long as I give a different name all works well_; this can also be seen in the output_log.txt where a succesful recorder message is included.
I would guess that the issue is with the "all blanks" name that is automatically suggested as can be seen in the screenshot.
The game freezes as soon as "Save" is clicked.
**So to reproduce:** Play a game long enough for a simple video to be created, then hit "Create Video", then hit "Save" without changing the name of the recording.

**Additional context**
This issue was found with Steam Proton v5.0-9, running Fedora 32. If you need more details, please let me know.
The output_log.txt is from a representative situation which I have recreated multiple times.

**Comment by knucracker** [comment]
Is the suggested name that comes up all spaces?  Or, is it some name that has a bunch of spaces at the beginning or the end.  The game basically takes the map name and sets that as the name that should appear.  I imagine the bug is with the 'native' file browser that pops up. Something in proton is likely goofing something up before the string value is shown.

**Comment by Karsten75** [comment]
A small change was made to replace blanks in file names with underscores

![image](https://user-images.githubusercontent.com/22965021/92930157-4f439900-f407-11ea-944a-4133c24a93ac.png)

Not evaluated on Linux as Linux is (not yet) a supported platform.

Will be rolled out as part of the October Demo
