### ISSUE TITLE
[Bug] [4RPL] Weird unit behaviour when being moved by 4RPL

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#701]
First, about towers and soylent:
 1) Soylent deployment is messed up if the tower is being moved while deployment occurs (Note that deployed cells move with the tower fine).
 2) When towers check for tiles that are not "soylented", they do it the same way the minimap does. For the minimap, soylent is not moving, which means that new towers without soylent in range may never deploy any cell, because their range used to contain soylent. This part is fixed on save/load, however. 

This screenshot has been taken on towers that moved once every 10 seconds, one cell left from their positions.
![image](https://user-images.githubusercontent.com/76114055/107073643-e6aaed80-67e7-11eb-863f-16484ab46314.png)

Second, weapon range seems to behave weirdly when being moved by 4RPL, like their range calculation doesn't move with the unit. This is fixed by moving the unit as a player.

I'm making a "scrolling" map where everything (Terrain, Creeper and units) moves one tile west every 10 seconds, and I encountered these issues while playtesting. Here is the save for testing.
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5934605/save.zip)

**Comment by knucracker** [comment]
I fixed the issue with towers sometimes not invalidating their soylent areas when moved. It was a frame race condition.
For unit movement I have added SetUnitMovementCell.  Take a look at that and see if you can use it.  If not, open a new issue and we will tackle the problem with the firing LOS cache for moved units separately.

**Comment by knucracker** [comment]
Also, I have added SetSoylentDelay and SetSoylentCount 4rpl apis.  These settings are also available in the game menu and can be used to allow towers to instan-deploy soylent.
