### ISSUE TITLE
[Bug.Minor] Map description sometime4s truncated incorrectly

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#702]
![image](https://user-images.githubusercontent.com/22965021/107089508-5909d680-67c4-11eb-9ddc-431757f33c93.png)

**Comment by Regallion** [comment]
bruh
![image](https://user-images.githubusercontent.com/40322714/107093035-9f3b5600-6815-11eb-8f16-c06eeb10fa33.png)
