### ISSUE TITLE
Sweeper has extremely high request rate when building

### ISSUE THREAD

**Issue by Kaidenalex** [KnuckleCracker/CW4-bug-tracker#703]
This bug occurs on 1.2.7b and likely earlier. When sweeper is enabled, and placed by the player, the unbuilt sweeper will request packets extremely fast to the point where 10-100 packets are sent at once to the sweeper. This can drain the factory liftic inventory within seconds, even when it's full.

**Comment by knucracker** [comment]
Changed in 1.2.8 to build at the normal request rate.
