### ISSUE TITLE
Sweeper built by the player cannot be destroyed

### ISSUE THREAD

**Issue by Kaidenalex** [KnuckleCracker/CW4-bug-tracker#704]
In the 1.7.2b and likely earlier, when the sweeper is enabled, and is built by the player, it is impossible to destroy the sweeper without using the editor. In the screenshot below, you can see there is no destroy button. This means if you mess up the sweeper placement, it's gonna be stuck there forever.
![Annotation 2020-08-18 175425-DESKTOP-V4NIDLN](https://user-images.githubusercontent.com/78657819/107125776-c0359280-6879-11eb-9eeb-31bb33007709.png)

**Comment by knucracker** [comment]
Change in 1.2.8 to allow the sweeper to be destroyed by the player
