### ISSUE TITLE
[4RPL] Choice-type unit UI can get stuck on a building unit.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#705]
![image](https://user-images.githubusercontent.com/40322714/107128052-bccaf700-68cb-11eb-9742-26c51b630fc0.png)
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5937507/save.zip)

Select the building unit.
Select different burn wares.
If it doesn't work, unpause for a second.

**Comment by knucracker** [comment]
There was a null pointer exception that could happen when changing the ware type. Caused by trying to update the build progress bar.
