### ISSUE TITLE
[Bug.Minor] Units moved by 4RPL don't update their LOS cache correctly.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#708]
Moving weapons with the call SetUnitposition makes the range calculation a little bit broken, as explained in issue #701. The SetUnitMoveCell is a very nice addition, and I already see countless possibilities with it, but it doesn't fix the cases when we need SetUnitPosistion, for instant moving, for example.
(The context is the same as #701)

**Comment by knucracker** [comment]
There is a RefreshUnitLOSCache call that can be called on a unit after it is moved. I forgot this call was already in place.  Normally, units refresh their LOS cached when the land, or when the terrain around them changes. If you manually move a unit, then call RefreshUnitLOSCache after the unit reaches its destination (or along the way if that is necessary).  Note that the call has some performance overhead so don't call it more than necessary.
