### ISSUE TITLE
[bug] editor placement icon for units outdated

### ISSUE THREAD

**Issue by harrymcb** [KnuckleCracker/CW4-bug-tracker#71]
![image](https://user-images.githubusercontent.com/54015763/95665867-d163d200-0b19-11eb-8cad-2b35b3e4ad5c.png)
as you can see in this image of the recent stream the emitter model is wrong. i believe others have simmilar problems. i got 1 frame of a clue another one was wrong. not in demo though so :)

**Comment by Karsten75** [comment]
Duplicate of issue #25
