### ISSUE TITLE
[Bug] If creeper cutoff is set to 100 or more, it is no longer visible in the interface.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#711]
![image](https://user-images.githubusercontent.com/40322714/107158869-d0df2900-699d-11eb-9751-ee824bdaeac0.png)

**Comment by Regallion** [comment]
(It still works, but having it invisible is kind of a big oof)

**Comment by knucracker** [comment]
Note sure why, but the game was hiding it if the value was greater than 100. Could be that 100 was supposed to be the limit and I didn't enforce that in the game menu. Either way, I have removed the check that hides the meter if the cutoff is greater than 100. Note that for larger values the number is too wide for the meter, but so be it.
