### ISSUE TITLE
[Bug.minor] 1-cell-wide diagonals don't behave well

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#714]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5955933/Player.log)

3. Screenshots help! 
![DiagonalBug](https://user-images.githubusercontent.com/77822959/107466876-a74b0c80-6b19-11eb-91b9-743b0561b4e5.png)

4. Describe the bug 
Sometimes 1-cell-wide diagonals behave inconsistently, especially when terrain specials are involved. It doesn't matter what the special is, or the terrain height of the diagonal or surrounding terrain. It **does** matter which direction the diagonal is going in, and whether the diagonal is above or below the surrounding terrain.

GetTerrainLOS also appears to ignore 1-cell diagonal walls, which may be related to them sometimes rendering as unconnected spikes.

**Comment by knucracker** [comment]
Made a change too how the terrain triangle slicing is done. Gave priority to terrain height differences. Previously, the special terrain types had priority.
