### ISSUE TITLE
[Bug.Minor] Changing custom objective text requires applying twice

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#715]
Help us help you. 

4. Describe the bug 
If the custom objective is already enabled, changing the "name" field in the editor menu then hitting apply does not update the text. You need to disable the custom objective, apply, reenable the custom objective with the changed text, then apply again.

**Comment by knucracker** [comment]
The game will now refresh the objectives pane when the game settings page is applied.
