### ISSUE TITLE
[4RPL] Changing objectives in a :GameLoaded function in a global control script doesn't work

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#716]
**Is your feature request related to a problem? Please describe.**
This is very minor, but the title pretty much says it. SetMissionObjectiveEnabled does not do anything when used in a GameLoaded function in a global control script. 

A couple things I have tested:
  * It does not behave this way when the script is attached to a unit.
  * The function still gets called. It's specifically setting a mission objective that doesn't work.

**Comment by knucracker** [comment]
From what I could tell, GameLoaded was never being called for global scripts. I have added code so that upon game load, global scripts with GameLoaded will get called.  Pre scripts will get called, then the unit gameloaded scripts will get called, then the post global scripts will get called.
