### ISSUE TITLE
[Suggestion] Add a visibility option for non-enemy outlines.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#718]
You can freely disable enemy outlines, but you can't disable the one around totems, infocaches, resource crystals and all that. These can be useful sometimes, but they can be annoying too, when taking screenshots, for example. Would it be possible to add non-enemy outline enabling/disabling to the visibility tab?

**Comment by knucracker** [comment]
Added a "Others Outline" option to the visibility menu.
