### ISSUE TITLE
Add "want" option to ERN Portal

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#719]
Currently, upon placing an ERN Portal, it is possible to assign as many ERNs as are currently uncovered on the map, but no more. It would be convenient if the player could assign them to further slots such that they are automatically filled when an ERN is uncovered or otherwise becomes available, as is possible for units.

**Comment by Mirco1502** [comment]
Would be a small Life of Quality Improvement, so I would like this, too. Question is how hard this would be to code.

**Comment by StrategicSage** [comment]
I would like this as well
