### ISSUE TITLE
{Suggestion] Highlight pylon paths when Pylon unit is selected for build

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#72]
**Is your feature request related to a problem? Please describe.**
It is difficult to see existing pylon networks when placing additional pylons, as the yellow color is not that distinguishable from white, and pylon paths are not always highlighted with Paths Off.
![Screenshot_20201011_033936](https://user-images.githubusercontent.com/51026936/95668376-6e068e00-0b73-11eb-8578-c910b5971f29.png)

**Describe the solution you'd like**
Make the Pylon paths a clearer color when Pylon is selected for placement.

**Describe alternatives you've considered**
Make pylon paths always visible with Paths Off, and perhaps see if a blue color (similar to CW3) is better than yellow for distinguishing.

**Comment by Karsten75** [comment]
Implemented with #1061 ?
