### ISSUE TITLE
[4RPL] DamageMesh radius and damage do nothing

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#721]
```
DamageMesh(133 84 1 0.000001)
```
The last 2 arguments (radius and damage) don't appear to modify how the function behaves.
This code yields the following result at 133,84:
![image](https://user-images.githubusercontent.com/51026936/107645590-2a36a900-6c79-11eb-954b-335ac5d11d9d.png)

**Comment by grabz-dev** [comment]
Correction - damage works. I did not realize that any amount of constant damage will keep mesh from spreading.

**Comment by knucracker** [comment]
A typo was preventing the radius from applying.
