### ISSUE TITLE
[4RPL] SetTerrainOverride cannot set higher than 10

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#724]
**Is your feature request related to a problem? Please describe.**
Whenever SetTerrainOverride is called, it sets the override to no more than 10, no matter what the final argument is. GetTerrainOverride probably isn't the issue, since creeper flow reflects this as well.

**Comment by knucracker** [comment]
Not sure why it was limited to 10. The code had a check that wasn't allowing it to be larger than 10.  I removed this check.
