### ISSUE TITLE
[4RPL Addition] Allow 4RPL to replicate free view-style camera

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#725]
**Is your feature request related to a problem? Please describe.**
There is currently no way for 4RPL to directly move the camera from mouse movement. This is worked around in the FPS levels with free view mode, but because of the game's 30/60 hz system, it means high FPS must be turned off. Replacing the default camera movement with script-based movement reduces the jitter, but doesn't completely remove it. Replacing the default camera rotation as well would. 

Turning off high FPS isn't the worst thing in the world, but switching game settings between levels can get cumbersome, and I want to reduce that if possible, especially since at some point someone will probably make a hybrid first person-traditional level. The increased creeper render rate is also nice when you're so close to it.

**Describe the solution you'd like**
A GetMouseMoveDelta function would work. A way to hide the cursor as well would allow the use of rpl cam, which would reduce potential conflicts on maps that switch between first and third person.

**Describe alternatives you've considered**
The exact option that is needed is a 30 hz camera rotation from mouse movement when high FPS is on, preferably occurring before or during script execution, so almost anything that accomplishes that would work.

**Comment by WithersChat** [comment]
Actually GetMousePosition, SetMousePosition (with a way to prevent soft lock so you can leave game), ShowMouse (Same as SetMousePosition, these would work.

**Comment by knucracker** [comment]
I've added a number of new RPLCam apis and some input apis, including GetMouseDelta. See the example on GetMouseDelta for a complete example of a flying camera control using the RPLCam with the new apis.  Note the addition of a way to run a script every frame of the game, so that the rpl cam can be updated at 60 fps.
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getmousedelta
