### ISSUE TITLE
[Suggestion]  Add an ability to alter creeper color.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#729]
Has been requested by multiple people over time, logging for posterity.
Desired:
Change creeper and AC color in settings.
Change creeper and AC color via 4RPL.

**Comment by Bob2Chiv** [comment]
strongly related to #312

**Comment by Regallion** [comment]
oh boy, i even searched for "color", why didn't that show up? that's a duplicate then.
