### ISSUE TITLE
{Suggestion] Make enemy unit outline a different color when the enemy is nullified

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#73]
**Is your feature request related to a problem? Please describe.**
It would be much easier at cursory glance to tell between enemies that have been nullified vs. enemies that haven't been nullified if their outline changed colors, similar to how on the minimap enemies are a different color based on whether they are nullified or not.

**Describe the solution you'd like**
To match the minimap, nullified units would have a brown outline, but then the outline of things like Totems would have to change to something else.

NOTE: I notice a little discrepancy where the Stash unit is not shown on the minimap, but has a red outline. I think this should be standardized, perhaps show Stash on minimap but make it always brown color (minimap icon and outline) to indicate that it is a unit that does not have to be nullified.

**Comment by knucracker** [comment]
Made the outline gray for nullified enemy units.
