### ISSUE TITLE
Allow custom units to be targetable by missile weapon[Suggestion]

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#733]
Allow a special target setting in the CMOD settings allowing a custom unit to be targetable by default missile units.

**Comment by knucracker** [comment]
In the unit settings, you can specify a "2" for the SPECIAL TARGET setting. Previously you could only set this value to 0 or 1 (1 being a sniper target).  2 means a missile launcher target.  I have changed the label for this setting to show that 1 or 2 can be specified.

You can also use 3 and 4, and those are for use as custom targets that can be used with the GetNearestSpecialUnit 4rpl api.
