### ISSUE TITLE
[4RPL Addition] Add a way to get script vars from global scripts

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#734]
**Is your feature request related to a problem? Please describe.**
Global scripts have no unit ID, since their whole point is they aren't attached to a unit. However, that makes some APIs like GetScriptVar and GetUnitSettings not work on them.

**Describe the solution you'd like**
Some way to get their script vars, either through giving them IDs or a separate system.

**Comment by knucracker** [comment]
Added RegisterScript, DeregisterScript, GetRegisteredScriptVar, SetRegisteredScriptVar.  
RegisterScript allows a global script (or a console or a unit script) to register itself with a name.  Get/SetRegisteredScriptVar can then be used with that name to read/write values on it.  Note that RegisterScript does not persist in a save game, so it should always be set (in Awake for instance) on a script that wants to be registered.
