### ISSUE TITLE
[4RPL] do ... loop should not execute once when start equals limit

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#736]
`do...loop` is frequently used to iterate over lists. It's not uncommon to see this (do loops even let you plug in a List rather than list length as limit)
```
<-list 0 do
    <-list I GetListElement Trace
loop
```
Issues may arise when the list happens to be empty, resulting in a call such as `0 0 do`, which still runs the loop once. In CRPL the loop would not run. Without additional checks, `I` will be 0, thus the code will assume the list has one element and retrieve nothing.

Naturally this can be worked around but is a bit of a transitional shock from CRPL where do loops were safe to use with lists.

**Comment by knucracker** [comment]
4rpl added (or was it prpl) the ability for do loops to count down.  This went a little too far and threw out the check to see if the start and limit were equal, and if to, not iterate the loop.  I've added back a check for ==.
