### ISSUE TITLE
[Bug.Minor] Totems show a second ammo number

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#738]
2.  **It is very important that you NOT restart the game before you save the output log**
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5986098/Player.log)

3. Screenshots help! 
![Screenshot 2021-02-15 203736](https://user-images.githubusercontent.com/77822959/108018863-bde7dc80-6fcd-11eb-8e27-6e92d9c4c4e1.jpg)

4. Describe the bug 
When totems have a non-integer ammo value, they show a second number for the liftic required. The number first appears when they need less than 10, and generally increases the closer they are to full. As a smaller point, there's also a bit of clipping of the number behind the liftic symbol.

**Comment by knucracker** [comment]
The second number was caused by the long decimal number 'wrapping around'. I have changed the number to be limited to one digit past the decimal.
