### ISSUE TITLE
[4RPL] [Bug] "TERRAFORM" button availability

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#739]
When you create a TERP by 4RPL, the terraform button doesn't show up. It seems that it only shows when you place a TERP as a player.

**Comment by Regallion** [comment]
Specifically it's tied to availability of building terps as a player. Seeing as we now have APIs to interact with terraform markers without terps AND a separate "Show terraform button" toggle, there is no real use for such a coupling.

**Comment by knucracker** [comment]
I'm not quite following (or have totally forgotten something :) ).  The Terraform button (the one on the left under the cancel button) should always be visible unless terraforming has been disabled in the game setting menu.  Are you observing something different?  I recall I used to dynamically show and hide the button, but I thought that was something dropped a long time ago. In a quick test I see a chronom mission begins with the terraform button visible.

**Comment by Regallion** [comment]
1. Open editor
2. Go to Game
3. Disable terps
4. Oops where did my terraform button go?

**Comment by knucracker** [comment]
Ah, so turn off terp building.  That removes the terraform button (which is done for things like the story missions, since the player should not have a terraform button if they can't make terps).  

But the bug is that when a terp is created via script (while terp building is still disabled), or a terp exists on the map at mission start, the terraform button remains absent.

**Comment by Regallion** [comment]
Well i would argue that disabling terps is not a valid reason to hide the button, since, as mentioned, we can now use 4RPL to interact with markers. Granted, the early campaign is a concern, but tying the button to a presence of a terp is very much obsolete.

**Comment by knucracker** [comment]
Made it so that the terraform button is not tied to the ability to build terps. It it tied only the the terraform ability in the game settings.
