### ISSUE TITLE
[bug] there is no more video at 15 minutes in the 5th mission

### ISSUE THREAD

**Issue by Blob2802** [KnuckleCracker/CW4-bug-tracker#74]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\output_log.txt`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`
3. Screenshots help! 
  Screenshots are here
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

4. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

**Additional context**

**Comment by Blob2802** [comment]
If I quit the game and I relaunch it, the big is still there

**Comment by Blob2802** [comment]
It also make my screen crash...

**Comment by Blob2802** [comment]
If I delete the game and reinstall it, the bug goes away, but the mission is still bugged

**Comment by harrymcb** [comment]
by "no more video" i assume you mean the game window is a black screen? i am certain more info about your computer is needed to find a cause

**Comment by 5KyJ8Me0bG8j** [comment]
Game window crashes/minimized where you see your desktop.
Sounds continue to take place in background and is not repeating, like only the display crashed.
Unity crash handler process starts.

Crash file full of:
d3d11: failed to create buffer (target 0x1 mode 0 size 144) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 4320) [0x887A0005]

Crash log file attached.
[Crash_2020-10-12_042920058.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5362931/Crash_2020-10-12_042920058.zip)

**Comment by knucracker** [comment]
That log file shows an nvidia driver from July 2019 (Driver: 26.21.14.3200).  It looks like a ton of driver issues related to buffer allocation.  I'd first try a full system reboot.  If that doesn't address it, I'd then take a look at the driver. This isn't a general purpose problem on your hardware (there are tons of other 1080 cards and similar systems that run without issue). I'm going to close this bug (since I don't want to use git for problem shooting a specific problem). But feel free to follow up on discord or the forum with your specific problem,

**Comment by jayrlsw** [comment]
I am also having this problem
