### ISSUE TITLE
Twitch missing game (category) cover art

### ISSUE THREAD

**Issue by perdignus** [KnuckleCracker/CW4-bug-tracker#741]
## Context
Twitch streamers can show the game they are playing. This game will be displayed with an image and the name beneath every video. The image for Creeper World 4 is missing.

## Process

The issue can be reproduced by going either searching for the game, or going to the game on twitch directly:
[Creeper World 4 - Twitch](https://www.twitch.tv/directory/game/Creeper%20World%204)

## Expected result

That a cover art is shown for the Creeper World 4 game on Twitch

## Possible Fix

This can be solved only by a representative of the development/game team, because it requires verification.
The (short) Twitch documentation can be found here:
[Adding a Game or Game Cover Art](https://help.twitch.tv/s/article/adding-a-game-and-box-art-to-the-directory?language=en_US)

## `Twitch missing cover art` screenshot

![afbeelding](https://user-images.githubusercontent.com/16068001/108249737-b5baa900-7155-11eb-9042-da3ca6e83de9.png)

**Comment by knucracker** [comment]
This requires twitch verifying my organization which will take a week or more.  I'll swing back to this issue if/when they do.

**Comment by knucracker** [comment]
Twitch granted ownership to my account and I have submitted boxart for all of the games. They should start to show up now...

**Comment by perdignus** [comment]
Thanks for the quick response and fix👌🏻
