### ISSUE TITLE
[Bug] Porter Unit limit ignored

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#745]
Somewhat minor bug, but still gameplay affecting.  If you set the porter limit to 1 on a map in the beta, you can still build infinite porters, it keeps track, but doesn't stop you from placing or building more.  So after you place a few it will say you have -3 porters available to place, etc.  This is the only main unit that's affected, all other units properly respect the build limit.

**Comment by knucracker** [comment]
Fixed. There were also similar problems with a couple other units.
