### ISSUE TITLE
[Bug.Minor] "Press O to rotate" can get stuck

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#747]
![image](https://user-images.githubusercontent.com/40322714/108610906-8a9cb780-73ea-11eb-812f-632aa0b46b3d.png)

1. mouse over a rotateable unit like a refinery.
2. Quickly press tab twice
3. the "Press O to rotate" info will get stuck.

Visual only, goes away if you try to enter a build mode for any rotatable unit.

**Comment by knucracker** [comment]
Fixed.  The tween needed canceling when it was told to play again
