### ISSUE TITLE
[Bug.Minor] Eco remains after shattered land decayed

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#749]
Once shattered land with eco on top decays the eco remains as 'floating?' dots in space.

Suggest to remove the eco on the event of the shattered land being fully decayed.

![image](https://user-images.githubusercontent.com/68601223/108623053-15a69d80-743d-11eb-95ad-c6d001598ea8.png)

**Comment by knucracker** [comment]
Changed to removed the eco when decayed land hits 0
