### ISSUE TITLE
{Suggestion] Better camera controls

### ISSUE THREAD

**Issue by thgross** [KnuckleCracker/CW4-bug-tracker#75]
I really love the CW4 demo so far.

However, the controls really get in the way to enjoying the experience.

In my opinion, these three things should be changed:
1. camera rotation (middle mouse button or "r") should not be limited to left and right rotation - rotation should be able to all directions.
 I know there is a second control scheme (shift "f"), but it has sone anoying features, like having to release the mouse cusor and "wasd" not moving us across the map, but instead along where the camera is looking at.
1. The mouse wheel should not move up and down the z-axis, but use the direction the camera is pointing at.
1. We need to be able to change the mouse rotation modifier from middle mouse button to an different mouse button, for example buttons 4 or 5 on the mouse, because many times the middle mouse button is difficult to press, and also does not allow to use the scrool wheel at the same time.

With these changes, mouse controls would really become intuitive, not only because many other games use the mouse linke this (for example, Cities Skylines), but also because we wouldn't need a second control scheme (shift "f"). Having to switch between two flawed schemes should not be the solution.

Thank you for your fantatic games!

**Comment by Karsten75** [comment]
a 3rd camera scheme was implemented, not sure if it met this requirement, anyway, no more work on this will be done.
