### ISSUE TITLE
[4RPL] Trail problem

### ISSUE THREAD

**Issue by 321k9** [KnuckleCracker/CW4-bug-tracker#750]
_:Once
  CreateTrail(self "trail" 0 8)
  SetUnitOutlineEnabled(self true)
  SetUnitOutlineMode(self true) #  trail sometimes  not working when true
  SetUnitOutlineColor(self V4(1 0. 0.7 1))
  SetUnitOutlineWidth(self 1)_

Now we let fly the unit using frame-by-frame commands like SetUnitionPosition. The "true" in SetUnitOutlineMode will cause the trail to forget to draw for short times under special circumstances (not only when unit below terrain 0). When it starts again to draw, it interpolates the missing part by a straight line, which makes the trail ugly.

Using SetUnitOutlineMode(self false) there is no problem. 

It's a minor bug that does not disturb me. I just noticed that behaviour and post it here for documentation.

**Comment by WithersChat** [comment]
I noticed the same kind of bug with mist. I had rockets (4RPL ones) that were flying upwards, creating mist behind, and it seemed that they "forgot" some mist when I launched more than one at a time.

**Comment by knucracker** [comment]
What you were probably seeing was the creation of a new segment in the trail. A lot of the time, those are hidden inside objects so you don't see them.  I have ticked a box on the trail renderer that causes it to create one more leading segment that stretches to match the objects position. That should close this gap.
