### ISSUE TITLE
[4RPL Addition] IsCreeperInRange

### ISSUE THREAD

**Issue by Dawid8plc** [KnuckleCracker/CW4-bug-tracker#752]
I noticed that Creeper World 3 has a IsCreeperInRange method, and I was wondering whether something similar could be added to Creeper World 4. Some time ago I wanted to create an unit that would detect creeper around itself, "absorb it" (delete it) and increase its internal variable, essentially, it would be a movable stash that would collect creeper and deposit anti creeper when the player clicks the appropriate button on the unit's panel. Currently (if I havent missed anything) you have to write a for loop to achieve something like this, and I was also pretty confused at first when I realized that the "height" axis seems to be the Z one instead of the Y one. Apologies if I missed anything.

**Comment by knucracker** [comment]
There is FindUnitEnemy that might work.  Let me know if it works for what you want...

**Comment by Dawid8plc** [comment]
Thanks, it looks like it is what I needed. "FindUnitEnemy" does sound like it refers to actual units though, like emitters for example. Anyhow, I'm going to close this issue now.
