### ISSUE TITLE
Bomber crosshair becomes very bright when a cannon's bullet goes through it

### ISSUE THREAD

**Issue by Kaidenalex** [KnuckleCracker/CW4-bug-tracker#753]
https://user-images.githubusercontent.com/78657819/108636720-26fba400-7455-11eb-8585-abdd44bcb2dd.mp4

I am not sure if the anticreeper has anything to do with the bug.

Edit: The anticreeper most likely doesn't have anything to do with the bug, and also the bug happens only when the cannon bullet gets near it. Also I found this glitch on v1.2.0

**Comment by knucracker** [comment]
I can't create a scenario that reproduces this.  Could be a very rare alignment or something. The brightness is caused by the shot's light reflecting off of the crosshair and the bloom visual effect making it larger. In every scenario I try, it never gets very bright, though.

**Comment by qople** [comment]
I've been able to recreate the bug by having many bombers targeting the same cell. It "flashes" when the shell lands on top of the crosshair, no other units required. 
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6018856/save.zip) in case it's helpful.

**Comment by knucracker** [comment]
Yep, it happened when there are a lot of the target indicators that are stacked.  I have changed the shader to not be 'lit'. That will fix this.
