### ISSUE TITLE
[Suggestion] Show legal placement indicators when attempting to designate illegal placement for porter destination

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#754]
(Suggestion passed on by request of Hypnotic22 in the discord) When attempting to place a unit in an illegal position (on mixed terrain, over void, etc) the game will show white squares on nearby legal placement spots to help guide you to where the unit can be placed. Having the same feature implemented when designating a landing zone for the porter would make it much easier to find a good spot to land your supply pod in "busy" scenarios with a lot of stuff crowding the landing zone. Here are some example images to illustrate the difference:

![image](https://user-images.githubusercontent.com/32053682/108698283-93b08600-74c9-11eb-8ef0-3a5b934f8816.png)

This first example image shows attempt to build a unit in the middle of a crowded area, where the white cells helpfully point out the legal placement spots.

![image](https://user-images.githubusercontent.com/32053682/108698390-b3e04500-74c9-11eb-9bc0-5a16799867a4.png)

In this second example image I try to land a porter in the same spot and it's much more difficult to pinpoint where all the legal placements are.

**Comment by knucracker** [comment]
Yeah, good idea.  Added.
