### ISSUE TITLE
[Bug] When towers move, they only clear the soylent map in their new range.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#757]
I built rift lab and 3 towers, moved everything 3 times one cell left, and then built the 4th, and that's the result. (Fixed after save-load and any tower getting disarmed and rearmed).  It seems that soylent map isn't cleared correctly when towers are moved.
![image](https://user-images.githubusercontent.com/76114055/108890098-6ec52b80-760d-11eb-8a2e-2546318b4f55.png)
Soylent is on instant deployment.

**Comment by knucracker** [comment]
How are you moving the towers? Is it with setunitcell?  I'm not reproducing it, so I must be doing something a bit different.

**Comment by Alophox** [comment]
it might have something to do with elevation?

**Comment by WithersChat** [comment]
[Scroll.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6036488/Scroll.zip)
Here is the save.

**Comment by knucracker** [comment]
Had to do with updating terrain after a tower movement, in the same frame
