### ISSUE TITLE
Terps don't work every now and then

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#758]
Terps don't terp w/o any reason - I've added a save file
[save-1.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6036036/save-1.zip)

I think it started with 1.2

**Comment by knucracker** [comment]
The unit fire range was upgraded at the ern portal so the terps were showing an upgraded range, however they were not actually using the upgraded range so your terraform squares were out of range.  This problem was introduced a few builds back. Fixed now.
