### ISSUE TITLE
[4RPL Addition] GetMappedKeyString to retrieve name of mapped key to a keybind

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#761]
**Is your feature request related to a problem? Please describe.**
1. Mapped keys are sensitive to modifier keys. If the keybinds are WASD, they wouldn't work if you were holding shift or control.
2. No way to display which key to press if they are bound, or to tell player to bind the key if it is not bound

**Describe the solution you'd like**
`GetMappedKeyString` would take keybind name as an argument and return the mapped key strings. If no key is mapped, return an empty string. If a combo is bound, return what the game displays e.g. "SHIFT-A" and if we want to support it we can split the delimiter.

```
"MoveMapUp" GetMappedKeyString ->keySecondary ->keyPrimary #"W" ""
<-keyPrimary FALSE GetKey if
   #code goes here
endif
```

**Comment by knucracker** [comment]
Implemented the requested API. Note that I called it GetMappedKeyStrings (with an s on the end).
