### ISSUE TITLE
[Bug] Overload Nullifier seems not to work out of editor

### ISSUE THREAD

**Issue by Mirco1502** [KnuckleCracker/CW4-bug-tracker#763]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 

2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\Player.log`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`

3. If the error persists over a save and reload of the game, please provide the save file as well (You may have to zip it up, as the .cw4 file type is not supported as a direct upload in GitHub)
  Each part of the game (Farsite, Chronom, Mark V, etc.( has a folder underneath the game's home directory.
         `%HOMEPATH%\Documents\My Games\creeperworld4\saves\`
   If you were saving in the Map Editor, then the save is in the folder for the map in 
         `%HOMEPATH%\Documents\My Games\creeperworld4\editor\`

4. Screenshots help us to **see**the problem. 
  Screenshots are here
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

5. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

**Additional context**

1. Done.

2. Log file:

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6047427/output_log.txt)

3. Save file:

[knucracker13.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6047436/knucracker13.zip)

4. Screenshots:

![cw4ss_1](https://user-images.githubusercontent.com/35544343/109256611-99bea380-77f6-11eb-94cd-6e9a8e2ea0db.jpg)
![cw4ss_2](https://user-images.githubusercontent.com/35544343/109256618-9d522a80-77f6-11eb-9f2b-d3401493c1d6.jpg)
![cw4ss_3](https://user-images.githubusercontent.com/35544343/109256623-a0e5b180-77f6-11eb-82bc-167a802fee50.jpg)

5. Description:

After starting the map and toggle the "Nullifier overload" option in midgame in the Editor menue, it seems to not work. When I build a Nullifier then, nothing happens (it works like always, just stunning the target). When I asked for help on Steam discussions someone testedt it too and told me it works for him, but only in the editor. During an active mission it's also not working for him.

Regards

**Comment by knucracker** [comment]
I'm not reproducing the problem and the attached save shows that the overload nullifier option is not on.  This might be a case of forgetting to press the "Apply" button at the bottom of the game settings.  When l load the save, go to settings and toggle the Overload Nullifiers option, then press Apply, nullifiers then have the Overload option when selected.

**Comment by Mirco1502** [comment]
Hello knucracker,

I did like you said. Still not working. I'm also pretty sure I did hit the "apply" button before. But like you said, I load the game (Nullifier overload option was still checked, like in first Screenshot) and hit apply. No Overload option for me. I then unchecked the option, hit appaly, checked the option, hit applay again. Still nothing.

Any chance this has something to do with some sort of permission or rights? Like said, someone else also got this problem and wasn't able to make it run.

Do I have to start the game in Administrator mode or something like this?

regards

**Comment by knucracker** [comment]
Oh... I see.  I finally paid attention to the map title in your screenshot.  It is a span mission.  Yeah, I coded it so that nullifier overloading is disabled in the story and span missions. I didn't want to disturb them, so the game doesn't allow overloading on those missions.  Chronom, Mark V, and custom maps should all support overloading.  If you really want to play that map (or any other) you can save it at the beginning, then load it from the "Load File" button on the main menu.  That will load it as a loose mission and the game will let you turn on overloading.

**Comment by Mirco1502** [comment]
Ah, that explains it, thank you! And ty for the workaround, too.

Still, any chance to make this available in the campaign? Fully optional of course and even hidden if you prefer it. But I would really like to play the Campaign in good 'ol CW3 style =)

And thank you for the fast response, have a nice evening!

**Comment by knucracker** [comment]
Yeah,  I'm making a change that will allow it to work in the story/span sectors (if you bring up the editor)

**Comment by Mirco1502** [comment]
Awesome! Thank you so much! :-)
