### ISSUE TITLE
[Suggestion] Prevent formation bombing out of map bounds

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#765]
When using a large enough group of bombers and performing a formation bombing, some/lots of bombers are flying next to the map, being useless.

Suggest to limit the formation bombing to the bounds of the map and squeeze the pattern or double up on the event of bombers having a path that is fully outside of the map bounds.

![image](https://user-images.githubusercontent.com/68601223/109354011-712dbc80-787d-11eb-802e-c73f49ff714d.png)

**Comment by knucracker** [comment]
I've improved it by recycling valid positions once a placement marker (either the start or the end) go out of bounds. This keeps bombers from attempting to bomb off map when using the formation movement.
