### ISSUE TITLE
[Bug] Desync UPS - Speed Multiplier + Non functioning Speed Multiplier hotkey

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#766]
The UPS may become out of sync from the speed multiplier and the speed multiplier hotkeys become unresponsive by:

1) Disable UI with hotkey
2) Increase/Decrease speed with hotkeys

At this point two things fault:
1) Only the 1st increment/decrement of speed is performed after which the hotkeys do not have any effect anymore.
2) While the UPS shows that that one inc/dec of speed is performed, enabling the UI again shows a different value.

See: https://youtu.be/DcmR2mmKZ6w

**Comment by knucracker** [comment]
The speed change was tied to the UI. I decoupled it to fix it.
