### ISSUE TITLE
[Suggestion] Discord and Steam Rich Presence integration

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#767]
Some games implement Discord and Steam rich presence, it would be kinda neat if CW4 had it as well, so people could see what maps others are playing, or if they're in editor etc.
![image](https://user-images.githubusercontent.com/51026936/109389209-d29c6c80-790b-11eb-9fdb-0cb816c79d8d.png)
![image](https://user-images.githubusercontent.com/51026936/109389227-f495ef00-790b-11eb-86d2-f65f4ce25196.png)

**Comment by knucracker** [comment]
Probably closer to the work on the 2.0 release, so I will delay this till then.
