### ISSUE TITLE
[minor] Berthas become invisible when not buildable

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#770]
I create levels with unbuilt or built units that are not available to build by the player, so they have limited amounts.
I put a bertha in a level and then disabled building berthas, and to my surprise it turned invisible. Even when pre-built this happens, so I had to make berthas buildable and set the limit to 0. Probably has something to do with the Bertha scripts not being in the level when bertha building is disabled. This probably also applies to the other newly added buildings in the editor that use 4RPL.

My suggestion: keep the 4RPL stuff needed for the units in in level if an unit of that type is part of the level.
The non-4RPL part of the editor should be reasonably simple to use.

I'm not in a beta build (in case this info is needed)

**Comment by Regallion** [comment]
P sure they also erase themselves from existence on reload.
Anyway just my 2 cents: You can solve the base issue yourself by going to the cpack settings and removing the Player Menu Name for Bertha. This will achieve the desired effect.

**Comment by knucracker** [comment]
I changed it so that the cpacks don't unload if there are instances on the map (they do unload if there are no instances).
