### ISSUE TITLE
[Bug.Minor] Nullifier overload ammo unrelated to percentage overload

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#771]
The ammo during overload just displays x/999, which does not seem to be equal to the percentage of overload at which the nullifier is currently. It would be expected that the overload takes 999 packets or the ammo displayed is equal to the point at which the nullifier is overloaded

**Comment by Regallion** [comment]
@PRG-YouTube  #678 
The actualy % counter should be correct.

**Comment by PRG-YouTube** [comment]
But the actual % is not equal to the fraction x/999. eg. a nullifier with 202/999 (=20%) ammo displays 24% overloading.

**Comment by Regallion** [comment]
Yes because it's at 202/750 = 0,269... it actually should be showing 26% charged, interesting. But regardless, the explosions happens at 750 and the reason it has 999 ammo requested is to avoid edge cases with insufficient packet requests.

**Comment by PRG-YouTube** [comment]
If you exclude the ~25 packets the nullifier has as default (202-25)/750=23,6%, which is roughly 24%. Requesting extra packages for edge cases? Building units don't request extra packets either, do they?

Anyhow, lots of magic numbers floating in this issue.

**Comment by PRG-YouTube** [comment]
#678 seems like a workaround rather than a fix.

**Comment by PRG-YouTube** [comment]
If you exclude the ~25 packets the nullifier has as default (202-25)/750=23,6%, which is roughly 24%. Requesting extra packages for edge cases? Building units don't request extra packets either, do they?

Anyhow, lots of magic numbers floating in this issue.

#678 seems like a workaround rather than a fix. As from #678 it might be assumed is that the nullifier consumes the ammo of the overload, which seems odd to me as it starts charging at 0 ammo for overloading. Better fix would be to decouple the default and overload ammo and prioritize the default ammo for incoming packets I would say.

**Comment by knucracker** [comment]
I've changed how overloading is accounted. There is now a separate internal "tank" that has to fill to 750.  I leave the MAX_AMMO along and only pull from the ammo store to fill the tank over time. This fixes all of the reported issues (or it should).
