### ISSUE TITLE
When entering a new page in Colonies, the selected map does not get updated

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#772]
In colonies, select a map, it get's highlighted and you see the details below. 
When you change the page, either with the ">" button or any filter action, the page gets updated but a) no map is highlighted and b) the detail page stays on the first selected map.

**Comment by knucracker** [comment]
That's all on purpose, basically.  The selected map stays the one that you have selected unless you click on a new map.  It allows you to page away and back without losing your map. It also allows a filter to be applied and still have your map selected.  And importantly, it allows the last played map to be shown after you complete a mission even if there is a filter applied that only shows unplayed maps. This all relates to this item in the 1.3 release notes: "Enhanced Colonies to remember the last selected map even if it is filtered out. Also remembers across game instances."

If there is something inconsistent with this, just let me know.
