### ISSUE TITLE
[Bug] Extended nullifier ammo can be retained

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#773]
1. Add "Nullifier overload" as available on map
2. Create a nullifier. Fill it to, say 200/999
3. Disable supply, let all remaining packets arrive.
4. Cancel overload.

Expected: ammo reverts to 25/25
Reality: ammo remains at 200/25 or so.

The trick is disabling supply  - if no packets arrive the unit never updates current ammo.

**Comment by knucracker** [comment]
Fixed. See comment on #771 for more info
