### ISSUE TITLE
[Bug] Nullifier Over-Overload

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#774]
A nullifier will not overload at 750 ammo but 999 ammo instead by doing the following:

1) build nullifier
2) turn on overload
3) turn off supply once overload starts charging
4) let the ammo drop to 0 so the nullifier turns off
5) enable supply
6) ammo charges to 999 and nullifiers explodes

![image](https://user-images.githubusercontent.com/68601223/109500787-fb9d3880-7a96-11eb-92d2-89159f9caa07.png)

**Comment by knucracker** [comment]
Fixed. See comment on #771 for more info
