### ISSUE TITLE
[Suggestion+Bug] Enable nullifier beam when overloading from 0 ammo

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#775]
An overloading nullifier will not enable its nullifier beam when ammo reaches 25+.

So when you build a nullifier, enable overloading, disable supply, let it drop to 0 ammo and cause it to deactivate its nullifier beam, it would be nice if the beam is enabled again once the overloading ammo reaches 25+. Currently it remains inactive until the nullifier overloads, which can take a while.

**Comment by PRG-YouTube** [comment]
This bug causes an edge case in which the nullify enemies objective cannot be achieved.

2 emitters.
Build a nullifier on emitter 1, start overload, disable supply and let is disable its beam at 0 ammo.
Build a nullifier on emitter 2, make it overload.
Enable supply on nullifier 1, make it overload.

You're stuck with an objective of Nullify enemies 0/0

![image](https://user-images.githubusercontent.com/68601223/109502620-82ebab80-7a99-11eb-8f25-feeac2bf3312.png)

**Comment by knucracker** [comment]
Fixed. See comment on #771 for more info
