### ISSUE TITLE
[Bug] GetUnits throws an exception when it has no valid targets

### ISSUE THREAD

**Issue by Collin-B3** [KnuckleCracker/CW4-bug-tracker#780]
GetUnits (externally) works the same as GetUnitsInRange, but a specific unit type is given to search for. When no units of this type exist, the command gives an exception of "NullReferenceException: Object reference not set to an instance of an object."
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6071614/Player.log)
In this case, the function should return an empty list.

**Comment by knucracker** [comment]
Code wasn't checking for a null being returned from GetUnitsByType
