### ISSUE TITLE
[Bug] Nullifier Line of Sight may be broken

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#781]
Once a nullifier has been built, the Line of Sight may be broken without the nullifier deactivating. Would be fixed by performing a re-check on every event of terraforming within the action radius of the nullifier or something like that.

![image](https://user-images.githubusercontent.com/68601223/109719854-8a9a7580-7ba9-11eb-8566-f40285da5d1e.png)

**Comment by knucracker** [comment]
This was intended behavior, but placement ghosts weren't playing along.  See comment on #779 for more info
