### ISSUE TITLE
[Suggestion] Increase Runway Health

### ISSUE THREAD

**Issue by VasVadum** [KnuckleCracker/CW4-bug-tracker#783]
**Is your feature request related to a problem? Please describe.**
The runways often get destroyed before anything around them due to their surface area making them remain in contact with creep longer.

**Describe the solution you'd like**
Increase the runway health by 2, maybe even 4 points bringing it to around 4 or 6 hitpoints. Considering that this structure costs 4 times as much as the bombers, and is heavily required by those bombers, it should in fact be more resilient.

**Describe alternatives you've considered**
The more difficult method, would be to make the runway receive reduced damage to creep. So I presume the above will do just fine.

**Comment by StrategicSage** [comment]
I think the Runway health is good as is.  I think it's on the player to protect their more valuable structures more, and a runway is not a building that needs to be in regular contact with the enemy.
