### ISSUE TITLE
[4RPL]SetFieldRect crashes game

### ISSUE THREAD

**Issue by 321k9** [KnuckleCracker/CW4-bug-tracker#784]
I noticed that
SetFieldRect(100 100 ListN(v2(1 1) v2( -1 -1) 2) 10 100. 0 0 1)
crashes the game. Problem is here, that the Width-Parameter is higher than the list count.

A more meaningless, but syntactically correct command like 
SetFieldRect(0 0 CreateList 0 0 0 0)
crashes the game, too. So probably it's enough just to check that list length modulo width results in 0.

**Comment by knucracker** [comment]
Fixed
