### ISSUE TITLE
Add A "Compile" Hotkey 

### ISSUE THREAD

**Issue by 321k9** [KnuckleCracker/CW4-bug-tracker#785]
Please add a hotkey for "Compile All Scripts". Even when Editor Panel is not open. That saves us tons of clicks when debugging scripts. and often make changes in Editor and then recompile. Thanks!

**Comment by grabz-dev** [comment]
Side note, you may find it easier to load the autosave (F5 -> F6) rather than navigate to the recompile button, as scripts are recompiled whenever the save is loaded. Just be sure to save first if you made any non-script related changes to the CPACK.

**Comment by knucracker** [comment]
Added a compile key binding "CTRL-B" by default. You must be in edit mode for it to work. If in edit mode you will compile all scripts in all cpacks in the mission. A dialog will appear (you don't have to be in the cpack editor) with the compile results. Cancel or ESC will dismiss the dialog.
