### ISSUE TITLE
[4RPL Addition] Add a GetBuildUnitSelected comamnd

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#789]
Since there is no way to add actual UI to screen in CW4, I wanted to use a mechanic like this:
1) I create a unit in the CPack editor that actually does nothing.
2) In a script that runs while paused, detect when the player is building one, trigger a cancel and do something.
However, it seems that only IsBuildUnitSelected exists.
So, a command that would need no argument and return a GUID (like GetUnitType) would allow to make this kind of things, or better tutorials in maps.

**Comment by knucracker** [comment]
Added GetBuildUnit command
