### ISSUE TITLE
[Suggestion] Allow formation bombing when route is over map instead of only when end and start are on the map

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#793]
The formation bombing would feel nicer if it would allow the formation to stretch over any potential route that has a start OR end marker on the map instead of the current start AND end marker. This is mainly an issue when trying to work the creeper back in a corner where the current system would squeeze the formation into a few lines and forget about the large part around it as seen in the image below.

Even nicer than checking the start/end only would be to check if any point on the route is on the map and just clamp the route to these points only (this would be another improvement on top of the previous)

Note: Running v1.4.3

![image](https://user-images.githubusercontent.com/68601223/110470516-3af10800-80db-11eb-94de-dfa56654063f.png)

**Comment by knucracker** [comment]
Changed
