### ISSUE TITLE
[Bug] Trying to build units in a line to the horizon can freeze the game

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#797]
Click-and-drag placement will try to place units outside of map bounds. If the player goes into free view, starts the build on the map, then drags to the horizon, the game tries to build a line of thousands of units, which can sometimes freeze the game for several seconds or longer.

Limiting the placement ghosts to only be created within map bounds should fix that with no impacts on gameplay. 
Capping the build line to something finite but outside of what can be placed on any map (700 long or something) would also stop this.

**Comment by knucracker** [comment]
Changed to limit secondary build ghosts to only being allowed within the map bounds
