### ISSUE TITLE
[Suggestion] Line building map clamp feels off

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#799]
The solution to prevent the line building to the horizon in #797 has a similar issues with the map clam feeling off as in the former formation bombing map clamp #794. Currently the line of buildings may not be pointing towards the actual pointer, which is strange.

![image](https://user-images.githubusercontent.com/68601223/110687500-d9b35c80-81e0-11eb-8d79-8345a2d02c27.png)

**Comment by knucracker** [comment]
Changed to clamp the secondary builds ghosts in a different way (the pointed at location is preserved, so the line draws correctly, but the loop aborts when it goes out of bounds).
