### ISSUE TITLE
[bug] Select build tab keybinds while a unit is selected causes multiple build tabs to be open at once

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#8]
![image](https://user-images.githubusercontent.com/68219054/87284647-96bfae80-c4c4-11ea-94b9-9c4d8f79e1f0.png)
This bug makes it either difficult or impossible to build new units and the only way to fix the bug I was able to find was to click the build tabs (keybinds do not work).  Game still appears to work as normal outside of the build menu.

To reproduce: When any unit is selected (so the build menu is obscured by unit controls), use the keybinds for switching build tabs; bug is not map specific and is still reproduce-able after full restart.

Other details: The "Build Unit X" hotkeys default to the 'highest' tab (struct>weapon>air>special), while click selecting defaults to the 'lowest'.

Edit: Apparently others are unable to replicate this bug; tested renaming the controls.xml file to reset custom keybinds, still able to recreate the bug.  Also tested reinstalling the game; still able to recreate the bug.

Output log file: [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/4913118/output_log.txt)
Renamed control file: [test.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/4913153/test.zip)

**Comment by knucracker** [comment]
Looks like I fixed this a few days after that last demo build (so it has been fixed in the main branch for 19 days as of this writing). I'll mark as closed and when the next demo drops it should be corrected. If you notice it is not corrected, or notice a different problem, just open a new issue.
