### ISSUE TITLE
[bug] Mesh is generating after nullyfiing

### ISSUE THREAD

**Issue by GamyGamer** [KnuckleCracker/CW4-bug-tracker#80]
Help us help you. 

1. 

2.  Logfile: [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5361481/output_log.txt)

3. Screenshots 
![image](https://user-images.githubusercontent.com/49346764/95684996-6be51380-0bf5-11eb-8ea3-b1a22d9b9fa5.png)

4. Describe the bug 
   It happened when I finished map. I decided to flood map with AC as much as possible, then I decided to disable nullyfier to create mesh and reenabled it. I noticed that it was still growing when one of my tower was destroyed

**Additional context**

**Comment by knucracker** [comment]
Looks like the "connected" status that the mesh was looking at was not factoring in whether it was connected to a nullified emitter.
