### ISSUE TITLE
[Bug.Minor] Finalizing shows "script compilation error" for no apparent reason.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#802]
I'm on beta 1.4, and each time I finalize a map, it shows this:
![image](https://user-images.githubusercontent.com/76114055/110823484-7124b800-8292-11eb-8edc-e68202d0257c.png)
However, there are no compiling issues (checked all CPacks) and the map is STILL finalized. This happened on 2 maps with no script in common.

**Comment by knucracker** [comment]
I accidentally not'ed the condition that shows that error.  THe compilation happens successfully, but that message shows the opposite result. So if you see the message, it was a success. If you don't, then it failed. I'll fix this in the next build but in the mean time it is 'harmless' so you can just ignore it.

**Comment by WithersChat** [comment]
I found something else: It seems that re-finalizing the map after finalizing it the first time updates the terrain and unit lyout, but not the scripts.

**Comment by knucracker** [comment]
Fixed now
