### ISSUE TITLE
[Bug] Multiple sprayers with collection field enabled make it so none actually collect

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#804]
Sprayers placed against each other with the collection field enabled end up creating a massive spike at the exact cell in-between them, thus none end up collecting AC:
![image](https://user-images.githubusercontent.com/51026936/111022207-a84db300-83d1-11eb-875f-66c53a6abea4.png)

With 4 sprayers in a box shape, the combined field is able to hold 489 AC in the center, and 214 AC on each side, creating a diamond shape of AC. The rest of the AC gets collected.

I was hesitant to call this a bug since it technically works as intended, just potentially not obvious to players. If the answer to this one is "turn off the collection field", please reconsider #375

Save file: [save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6134309/save.zip)

**Comment by knucracker** [comment]
Yeah, I'm not sure how to make it so this situation doesn't happen.  I have addressed #375, though.
