### ISSUE TITLE
[Suggestion][Performance] Disable unit placement when hovering over UI

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#805]
I noticed that having a group of units selected and hovering over an UI element keeps the unit placement active in the background. This is quite a common move as to set options on a group of units. You could just as well disable that (group) unit placement while hovering over the UI as one cannot place the group anyway while over an UI because the UI catches the click inputs and the UI obscures the view anyway.

Save some cycles, save the planet, save our CPUs.

**Comment by knucracker** [comment]
Added an extra check when updating the unit ghosts. When over UI, it stops updating. That causes the ghosts to freeze in their last position,  until the mouse leaves the UI, but that seems fine.
