### ISSUE TITLE
[Bug.Minor] Soylent counter overdrawn

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#806]
The soylent counter is overdrawn by terrain and stuff. (as it is drawn relative to the camera view and overdrawn by terrain)

![image](https://user-images.githubusercontent.com/68601223/111028816-76504700-83f9-11eb-9b41-edf71cdb4e44.png)

**Comment by knucracker** [comment]
I swapped the shader for that textmeshpro instance to use one the draws on top of everything.
