### ISSUE TITLE
[Suggestion] Ada log, and other messages, key binding text swap-in

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#807]
Currently more maps are appearing with custom keybindings. These maps use key bindings like custom0 and have these mentioned in the descriptions like 'press "custom0" to activate xx and press "custom1" to activate yy', this isn't particularly user friendly. It would be nice to have some option to swap-in the keybindings textual representations in the text (which could be done at load time, and thus has 0 runtime overhead). For this purpose I propose keywords like ```<<keybinding>>``` which are replaced at load time with the actual textual repr of the keybinding <- which can be equal to the repr shown in the settings.

eg.
Ada log entry at map start "This is an FPS mod, press custom0 (```<<custom0>>```) to jump into play mode"
which gets replaced with a simple search and replace to "This is an FPS mod, press custom0 (L) to jump into play mode" <- where L is the mapped key to custom0 (as would also be shown exactly the same in the settings).

This might be useful for ADA log as well as info caches and those notifications, don't know if there are more message types.

Also a default "Key not set in settings" or so would be required

**Comment by Regallion** [comment]
You have failed to consider that i might re-bind mid-map (or even mid-message) so load time is not appropriate.
Also we already have the ability to get what's bound to a keybind, to dynamically alter the text ourselves. Is that not sufficient? 
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getmappedkeystrings - the command to get the key string to do the message replace by the mapmaker himself.

**Comment by PRG-YouTube** [comment]
That is relatively complicated to do for something that is easy to implement in the game itself. As for the mid-map rebind, this swap-in could also be executed at the showtime moment as it shouldn't be heavy. Also I heard that 4rpl cannot modify ADA messages?

**Comment by knucracker** [comment]
I've implemented <<KEY_NAME>> syntax.  It uses this regex on the text:
`(\<{2}[^\<]+?\>{2})`

If KEY_NAME does not match a valid key name, then no replacement to the text happens.  The replacements happen at render time for a message. I already was replacing some text, so I just extended that.  The same  message renderer code is used in all places where the ada-like messages are shown (the ada text editor, ada log, and popup messages)
