### ISSUE TITLE
[Suggestion] Custom0-9 default keys

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#808]
Since more maps using custom0-9 bindings are being released it would be nice to have at least some defaults set there.

Suggestion to set the default bindings for custom0-9 to Keypad0-9.

As K75 mentioned this might be somewhat inconvenient during playing as the left hand is on wasd and the right on the mouse. However, any defaults is better than none I'd say.

**Comment by knucracker** [comment]
I've made Keypad0 - Keypad9 the defaults. Not everyone has a keypad, but they can remap if they don't (same as if there was no default mapping).  To make this work for existing players who already have a controls.xml file in their settings, I check for a 'ver' tag. If not found or not set to '2', then I  default the keys for any Custom# that is not already set.  Ver=2 is written out to the Controls.xml file moving forward, so the default's aren't changed repeatedly.
