### ISSUE TITLE
[4RPL Addition] Custom ADA Messages

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#809]
**Is your feature request related to a problem? Please describe.**
There is no way to generate an ADA message with 4RPL, and game messages can only be modified, meaning a message channel must already be defined. This is the one place where CPACKs can't be fully self-contained, and require some additional action beyond importing to work properly.

**Describe the solution you'd like**
CreateMessageChannel, AddMessageBlock, SetMessageText, and SetMessageBackground would let you do most things you can do in the message editor with scripting. Support for image blocks isn't needed because they would have to be imported outside of scripting, which would defeat the purpose.

**Describe alternatives you've considered**
In CW3 there was a reserved CRPL message channel that all scripts shared.

**Comment by knucracker** [comment]
This one I will leave for the next major update (the 2.0 release time frame).
