### ISSUE TITLE
[Bug.Minor] Airship move target is cleared upon completion

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#810]
See title..

Reproduce:
- Build Airship
- While building set the move target to go somewhere
- Wait for completion
- Move target is reset to the construction location.

It is expected that the move target is not reset after construction finishes, that would also be better.

**Comment by Karsten75** [comment]
Can you clarify if this was observed on a custom map with a custom unit or if it was on a map with the Titan class units?

**Comment by PRG-YouTube** [comment]
I first encountered this on a colonial map, though after I verified this in the editor on a plain map where I just enabled the built-in airship in the unit menu.

**Comment by PRG-YouTube** [comment]
See https://youtu.be/Fk91FBhD3Tg

**Comment by Regallion** [comment]
This is actually a fault of my redesign of the thor script. 
[Thor.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6148442/Thor.txt)
This amended version fixes the issue

**Comment by knucracker** [comment]
Nice... I put the same fix in last night.  Here was my version... it's good to see convergence on the same fix :)

	GetUnitSpecifiedTarget(self) ->st
	if (<-st.x -1 ==)
		Self V3(<-cellX 0 <-cellZ) SetUnitSpecifiedTarget
	endif
