### ISSUE TITLE
[Bug.Minor] (Map) Screenshot confusion

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#813]
The names in the settings for the keybindings for (Map) screenshots seem the wrong way round. It looks like F10 is binded to a 'Map topshot' or so while (shift+)F11 are binded to 'screenshot (no UI)'. Or is that just me?

![image](https://user-images.githubusercontent.com/68601223/111333022-92125200-8672-11eb-9d14-a466cb48b856.png)

Output:
Screenshot F10
![cw4ss_1](https://user-images.githubusercontent.com/68601223/111333187-bcfca600-8672-11eb-92c8-b49d997b11e0.jpg)

Map screenshot F11
![cw4ss_2](https://user-images.githubusercontent.com/68601223/111333229-c980fe80-8672-11eb-9d59-20709edfd3f0.jpg)

Map screenshot No UI Shift+F11
![cw4ss_3](https://user-images.githubusercontent.com/68601223/111333277-d43b9380-8672-11eb-83a8-c57fa89924c1.jpg)

**Comment by knucracker** [comment]
Yeah, they could be named Map Screenshot, Screenshot, Screenshot No UI.  I could change the titles in the ui no problem, but the constants match the current title names. So swapping the titles would make them read opposite to the constants, which could cause its own problems in other areas.

They seem to work as they are supposed to, the titles could just be clearer.

**Comment by PRG-YouTube** [comment]
With constants you mean the under the hood identifiers? I don't know what impact changing those will have (apart from the recently added keybinding swap-in feature probably).

As for now changing the UI titles as you propose would suffice as that is the cause of the issue. Though that would desync the constants with the settings UI titles, but that might be another minor issue with even lower priority.

**Comment by knucracker** [comment]
I've renamed them to Top-Down Screenshot, Screenshot and , Screenshot No UI.  I've also changed the internal constant names to match.  A conversion is done on any controls.xml file that is version 2 or earlier (version 3 is not the current version).
