### ISSUE TITLE
[Suggestion] Negative strength on shattered land

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#814]
**Is your feature request related to a problem? Please describe.**
Shattered land's strength can't go below 0. I think it could be interesting to have terrain growing under the creeper as it flows, perhaps to block line of sight or make an area easier to capture over time. The "min height" variable should probably be renamed if implemented, either all of the time or only when the strength is negative. 

**Describe the solution you'd like**
Inputting a negative strength for shattered land would be the same as positive strength, but instead of terrain decaying it would rise up. The min height setting would then become the max height. 0 strength already means there is no terrain change, so that case can be ignored.

**Comment by knucracker** [comment]
I'll revisit this in the 2.0 release time frame. I'm basically settling the game down so I can work on 'some big things' (for CW4), and will revisit additional features in the 2.0 timeframe.
