### ISSUE TITLE
[Suggestion] Build menu unit hover descriptions

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#827]
While the default set of weapons are introduced in the campaign, this does not hold for custom units, which are usually explained briefly in the ADA. For these custom units it would be nice to have some 'tooltips' descriptions available when hovering over these units in the build menu for lets say 2 seconds. This would allow creators to include some (short!) description with custom units for hover over tooltips.

**Comment by Karsten75** [comment]
when a unit is selected in the Build menu (all units are treated equally) an indicator is activated to show that "H"elp is available.  This appears in the bottom of the build menu. From here on all units are treated equally in that the Info pages of the wiki will open. 

There is also a Tooltip activation that will link to the wiki for units already on-terrain. 

I believe that is sufficient. The complexity of getting another description somewhere in the CPACK creation  menus seem not worth the effort.
