### ISSUE TITLE
Progress Lock in 09 Leo, 266

### ISSUE THREAD

**Issue by SpyderZT** [KnuckleCracker/CW4-bug-tracker#83]
During the first mission, once you have the objective / ability to move the Rift Lab, if you attempt to move any of the four Cannons (From the Top Left of the Base) anywhere, they will default to "Landing" in the square where the Rift Lab is supposed to land (As that is the only available landing space at that point). Due to the fact that you _can't_ choose anywhere else to move them at this point in the level, they are now stuck there meaning that you can't move the Rift Lab there, locking progress at this objective.

**Comment by knucracker** [comment]
Made cannons not selectable until after the lab has moved to the landing location.
Note: Previously it was possible to destroy a cannon that was mistakenly placed in the way. This won't be necessary anymore, though.

**Comment by SpyderZT** [comment]
Huh, I hadn't considered destroying them. This is a better solution, but I was shamefully wrong about it being a "Progress Lock"... -.-
