### ISSUE TITLE
[Bug] Save files lost and progress lost if disk space full

### ISSUE THREAD

**Issue by anthoneyrimmer** [KnuckleCracker/CW4-bug-tracker#834]
This bug occured due to disk space filling up due to another program (zoom in my case) taking up the remaining disk space. It is still a bug though that all progress is lost due to disk space problems, the expected behaviour is that game progress is retained but not updated. 

Steps to reproduce
- Progress through complete game and save progress so that it syncs to steam cloud
- open cw4 and start playing 
- through some method, fill up the remaining space on the disk drive so ther is none left
- close cw4. Note that save will fail (silently I believe) and remove save files, in turn this erased progress is synced to steam cloud
- open cw4 again, note that it will load without any progress and restart you at the first level.

I have not tried to subsequently reproduce this so cannot provide videos. 
This occured in early March 2021.

**Comment by Karsten75** [comment]
Backup of files on your hard drive is supposed to prevent loss of data. I'm assuming you had no backup systems in place or otherwise you could have simply restored the relevant files/folders?

It would be incredibly complex to test a scenario as you describe and the actions to take are also not clearly obvious. I do not expect that the game at any time will be altered to be reactive to this scenario.

**Comment by anthoneyrimmer** [comment]
Hi @Karsten75 , Thank you for taking the time to review my bug report. I raise it in the hope that this can be resolved for future players of CW4. It is worthwhile noting that it is only that I investigated this issue that I realised what happened, most users would not realise what happened, only that the game seemed to have malfunctioned because it reset back to the start with no error message or similar feedback. The need to 'backup' these days seems a bit dated, I don't have anything stored on my computer that I would be concerned about losing including game progress, as it syncs to Steam cloud. I certainly would never consider backing up game progress, and I doubt a large percentage of the players of this game would either. I play on four different devices and rely on the steam cloud to sync progress between them.

I hope a solution can be found.

**Comment by PRG-YouTube** [comment]
While I don't think that there is a solution to a full disk, <speculations> maybe KC has some 'protection' of some sorts in place that removes corrupted game files. In that case the full disk might lead to corruption and the protection to removal. </speculations> In that case a confirmation window with a link to a help thread or so something would maybe be nice.
