### ISSUE TITLE
[4RPL] [Minor Bug] SetTimerObeyPause commands don't seem to work.  

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#839]
As best as I can tell the SetTimerObeyPause commands don't seem to work, unless there's some advanced way they're supposed to be used.   Setting them before and after seems to have no effect.

Reproduction - Use the code below, attach to pre or post, set the script to run while paused and compile, and the sound will always happen, even while paused, 
```
if (gettimer0 eq0)
  true settimerobeypause0
  20 settimer0 
  true settimerobeypause0
  playsound("Notify" 1)
endif
```

This can be worked around fairly easily (like adding 1 to the timer every frame it's paused), so it's not an urgent concern, but it does seem like something that should be fixed.

**Comment by knucracker** [comment]
Fixed. The timerobjeypause vars were being set, but the boolean that checked for them was wrong. It relied on the script being in the 'paused' state, and that changed from CW3 to CW4 for global scripts set to run when paused,
