### ISSUE TITLE
{Suggestion] Add compass N W S E markings to the minimap

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#84]
**Is your feature request related to a problem? Please describe.**
It can be confusing to provide context to strategy performed in a level using directional cues because players have freedom of camera rotation. Though I know players can always reset camera to see what "west" or "east" relates to, I think it would be nice and wouldn't clutter too much UI to add a compass to the minimap.

**Describe the solution you'd like**
![compass](https://user-images.githubusercontent.com/51026936/95812455-bbbafc00-0d15-11eb-9603-11cd03ae5ef0.png)

**Comment by knucracker** [comment]
![image](https://user-images.githubusercontent.com/6733225/95875664-40bb0b00-0d40-11eb-8853-45148dbbab81.png)
