### ISSUE TITLE
[4RPL] CreateUnit unexpected behavior with "pod" (v1.4.8)

### ISSUE THREAD

**Issue by UberWaffe** [KnuckleCracker/CW4-bug-tracker#842]
**Is your feature request related to a problem? Please describe.**
A resource pod "pod" created via 4rpl "CreateUnit" behaves very differently, and seemingly broken, than a resource pod placed via the editor.
The resource pod does not appear to have collision / selection, does not occupy land, and does not connect to the network even when constructed via 4RPL "ConstructUnit".

**Describe the solution you'd like**
It is expected that
`CreateUnit("pod" <-selfPos <-initParams) ->podUID
ConstructUnit(<-podUID 9999)`
creates a pod that is complete (constructed), will connect to the network to output its cargo, and is selectable as per normal (similar to how a resource pod placed via editor does).

Or a note on the "CreateUnit" entry for what special scripting needs to be additionally done when creating a resource pod.

**Describe alternatives you've considered**
The following test was done via 4RPL console:
`V3(5 1 5) ->selfPos
CreateTable ->initParams
0 ->initParams{"Resource"}
50 ->initParams{"Size"}
1 ->initParams{"CreeperDamages"}
0 ->initParams{"Impervious"}
1 ->initParams{"PlayerCanDestroy"}
CreateUnit("pod" <-selfPos <-initParams) ->podUID
SetUnitSelectable(<-podUID true)
SetUnitSelected(<-podUID true)
SetUnitConnectable(<-podUID true)
ConstructUnit(<-podUID 9999)`
Explicitly setting "SetUnitConnectable" resolves the connection problem. But "SetUnitSelectable" can only indirectly select the pod (either via script, or by selecting another pod and then pressing ctrl+a).

I could not attempt changing unit object properties since the objects / parts of built-in units is not viewable via the editor.

**Additional context**
4RPL code posted above for running via console should produce the scenario in question.

**Comment by knucracker** [comment]
I have changed the SetUnitSelectable call to enable the collider on a unit.  The pod was constructed with its box collider disabled.  That collider will automatically enable when you call SetUnitSelectable now.

The remaining problem is taking up space on the map.  For that, you can use the existing API SetUnitOccupiesLand.

So, after build 1.9, the following works:
`V3(5 1 5) ->selfPos 

CreateTable ->initParams 
0 ->initParams{"Resource"} 
50 ->initParams{"Size"} 
1 ->initParams{"CreeperDamages"} 
0 ->initParams{"Impervious"} 
1 ->initParams{"PlayerCanDestroy"} 
CreateUnit("pod" <-selfPos <-initParams) ->podUID 

SetUnitSelectable(<-podUID true) 
SetUnitSelected(<-podUID true) 
SetUnitConnectable(<-podUID true) 
SetUnitOccupiesLand(<-podUID true)

ConstructUnit(<-podUID 9999)`
