### ISSUE TITLE
[Bug.Minor] Pod health 0.1/0.01 by default

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#844]
A pod has a default health of 0.1 with a max of 0.01. Seems illogical to have the default health set higher than the maximum health.

**Comment by knucracker** [comment]
This was a display issue. The internal health was actually 0.01. But, the display would not show any value less than that as anything other than 0.1.  I have changed it to show 0.0 instead of 0.1 (it only shows 1 decimal digit for the health)
