### ISSUE TITLE
[Bug] Registered Messages Increment Timers

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#845]
Help us help you. 

When registered for one of the built-in messages (MSG_PreUpdate and such), the built-in timer functions are also incremented when the message is called. For instance, a unit with a script registered to run while paused has its timers increment at double speed, and still increment at normal speed while paused. This probably also applies to messages called by a script. I haven't checked if this affects invocation count.

**Comment by knucracker** [comment]
I made a change so that all message callbacks do not increment timers.
