### ISSUE TITLE
[Bug] CW4 fails to close.

### ISSUE THREAD

**Issue by rollerce** [KnuckleCracker/CW4-bug-tracker#846]
Steam fails to notice that CW4 has closed. All I need to do to reproduce this bug is to open CW4, then close it.

Although CW4 does not show in task manager, there is a phantom drain on CPU, RAM and battery until I force close steam. This does not happen with any other game on steam, so the bug is CW4's issue. It also started after one of the most recent updates, so you need to fix whatever you broke with the last update.

**Comment by qople** [comment]
If you open another app through CW4 (e.g. click a wiki button and open the browser), steam counts it as part of the game, and won't count steam as closed until it is closed too.

**Comment by rollerce** [comment]
I'm a buttface. Closing issue.
