### ISSUE TITLE
[Bug] SetRplCamCursorLock works outside of RPL cam

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#849]
The SetRplCamCursorLock API hides the cursor, even when the RPL cam is disabled. When the cursor is locked outside of RPL cam, bringing up the menu doesn't free the cursor. The only way to fix it is to force quit the game through task manager.

At one point, I found an instance where the cursor was hidden, but not locked. I was not able to reproduce it.

**Comment by Karsten75** [comment]
This is the source of significant issues within some of the custom game modes. If it can be resolved, I'm sure many will appreciate it. 

@qople , do you have an easy method to replicate?

**Comment by qople** [comment]
You can run this in the console. Custom0 toggles RPL Cam, and Custom1 toggles the cursor lock.

```
if(GetMappedKeyDown("Custom0" 1))
	<-rplCam ! ->rplCam
	<-rplCam SetRplCam
endif

if(GetMappedKeyDown("Custom1" 1))
	<-lock ! ->lock
	<-lock SetRplCamCursorLock
endif
```

**Comment by knucracker** [comment]
Changed it so the lock state only engages when in rplcam mode and when the menu is not up. The state is remembered and refreshes automatically when the menu is dismissed.
