### ISSUE TITLE
{Suggestion] / [Feedback] Missile coverage display colour makes it indiscernable.

### ISSUE THREAD

**Issue by arkhne** [KnuckleCracker/CW4-bug-tracker#85]
I'm still fairly inexperienced at GitHub, so apologies if this is already covered (my quick search however did not turn anything up).

# Situation
When trying to build my Anti-spore defenses today, I was finding it difficult to plan where they needed to go because, unlike CW1 with SAMs, there was no indicator of where coverage did and did not exist. After mentioning it on the Discord, I learnt that it does show, but only if you select a pre-built Missile. However, this display is in a very faint/dark set of lines that is completely and utterly illegible to me (and maybe to others?).

# Current Behaviour / Issue
Right now, the only Missile coverage display is not readily available during the building/planning process, nor is it noticable enough to make out actual coverage.

# Changes
For this to be of any use to me, it would at least need to be a different colour and/or brightness. Ideally, it would also show when placing missiles, just like with SAMs in CW1.

I have no real input on how to do this, or what colour/brightness it should be, other than not-HDR, since colours and graphics is not really my area of expertise.

**Comment by knucracker** [comment]
I've removed showing the range indicators for missile launcher on the map (other than the single one being built, or moved). New range indicators now appear on the minimap that show the effective ranges of the launchers.
