### ISSUE TITLE
[Bug.Minor] Valid build locations not updated after unit destroyed

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#850]
When hovering over a unit when it gets destroyed, the valid build locations are not updated until the cursor is moved at least one cell.

![image](https://user-images.githubusercontent.com/68601223/115003466-1d674900-9ea6-11eb-9459-f27f1530c409.png)

Unit got destroyed but build locations arent updated
![image](https://user-images.githubusercontent.com/68601223/115003521-2d7f2880-9ea6-11eb-91d2-5fb873492630.png)

**Comment by Karsten75** [comment]
Valid build locations are not calculated on a per-frame basis, but based on the cursor movement. As such, the effect you noticed is  in line with how it is supposed to work.
