### ISSUE TITLE
[Bug] Nullifier overload draws infinite energy while disarmed

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#854]
Nullifiers overload energy draw is broken when disarmed.

Reproduce:
1 Build nullifier, enable overload, and let beam activate
2 Disarm nullifier
3 Overload charge does not increase, but energy keeps being supplied at high rate.

**Comment by knucracker** [comment]
Disabling the unit will stop the ammo flow, as well turning off the unit supply with the supply button.  The disarm button doesn't affect supply but does turn off the nullifiers operations (it disables the  beam for instance). As currently implemented it also stops the overload charge.  I don't think I see a use case that the player can't accomplish using disable and de-supply buttons.  Changing the internals to have disarm turn off the beam but continue the overload charge would be a bit of a work I'll defer for now.  If there is some use case I am not thinking about, just let me know.
