### ISSUE TITLE
[Bug] Clicking on the UI will cause custom keybinds to be ignored until the world is clicked on again.

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#856]
If you click on almost any part of the UI, such as clicking on the build menu, then pressing the custom0-9 keys will have no effect until you click on the game itself (i.e. any non-ui thing).  

So for example, if you start a fps level, and you click on the tab where the build options would normally be, then pressing custom1 to enter fps mode has no effect, or any of the other custom hoykeys, like the one to quick select the weapon display.  You have to click on the main part of the screen to return to the intended functionality.  In that state, all of the normal hotkeys still work, like unpausing and next frame, etc, it seems to just be the custom keys that are affected.

**Comment by qople** [comment]
That might be a result of the "ignore over UI" setting with the various GetKey functions. In the FPS maps, I set most (all?) of them to true.

**Comment by Durikkan** [comment]
Ah, somehow I'd failed to realize that was a thing, and it does explain the behavior, though I thought I had it happen even with the mouse off the ui when I thought it was based on the last click location, but I can't replicate that, so I'll just close it.
