### ISSUE TITLE
Custom unit drop-downs scroll very slowly

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#860]
Presumably due to the same thing as issue #591, when a custom unit has a drop-down menu which is long enough to have a scrollbar using the mouse wheel scrolls it very slowly.

Edit: This also applies to the custom unit options pane itself, if there is enough text for a scrollbar to appear.

**Comment by knucracker** [comment]
Changed scrollrect from sensitivity 1 to 20.
