### ISSUE TITLE
[4RPL] Flood fill terrain min and max might both be off by one?

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#861]
If you use the flood fill terrain 4rpl command, it treats the min height as 1 less than the value you give it, so if you set the minimum to 3, it will also accept 2 when it's gathering terrain cells.  The max height is exclusive, which is slightly odd, and may or may not be intentional.  I.e. a max height of 20 accepts 19 and less.  
So if you set the Minimum to 3 and the max to 6, it accepts terrain of 2,3,4,5.  
With these two issues combined, it made me wonder if there's an off by one issue somewhere in there.  

I understand this isn't really that fixable, since changing it might break the scripts on some maps, but I figured I'd throw it out there to be considered.  I already updated the wiki to account for this, as well.

**Comment by Karsten75** [comment]
Extensive discussion, documented in 4RPL wiki.
