### ISSUE TITLE
Enable nullifier overload when all objectives are complete

### ISSUE THREAD

**Issue by knucracker** [KnuckleCracker/CW4-bug-tracker#862]
If all objectives are complete, enable nullifier overload automatically. Add an extra option (that is permissive by default) that can be used to disable this in case some special custom map doesn't want it.

**Comment by PRG-YouTube** [comment]
Take into account that Hold+ objectives might become trivial with this option enabled (on a map that is supposed to be unbeatable with creeper++ and nullifier fail or so). Might want to pop-up a question whether to enable/disable the auto nullifier overload enable when having both the Hold+ objective and this setting on or so.
