### ISSUE TITLE
[Suggestion] Double click on mission should start mission from beginning

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#863]
Context from (lengthy) thread here: http://knucklecracker.com/forums/index.php?topic=37997.0

When selecting a mission from Colonies or from level selection, a 'double click' should automatically start the mission from the beginning.

In the current situation, a click to select a mission, then move the mouse, then click 'Play' - and if you've played the mission before, you then need to select 'restart mission'

**Comment by PRG-YouTube** [comment]
Some people double click everything though. They might then miss the loading menu options.
