### ISSUE TITLE
[Suggestion] Creeper breeder and mesh look very similar

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#864]
Context from (lengthy) thread here: http://knucklecracker.com/forums/index.php?topic=37997.0

Creeper breeder and mesh look very similar (especially to newer users), should find some way to further differentiate these.

**Comment by cornucanis** [comment]
It should be noted that in addition to active mesh resembling creeper breeder, inactive mesh also resembles AC breeder.
