### ISSUE TITLE
[Bug.Minor] ERN maker wiki page only opens from H on mouseover not when selected (and mouseover-ed)

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#865]
To recreate:
1. Go to a map with an ERN maker (Campaign map The Experiment).
2. Mouse over the ERN maker
3. Press H
4. Wiki page opens
5. Click it
6. Press H
7. Regardless of the location if you mouse the wiki page will not open.

**Comment by Karsten75** [comment]
If anyone comes across these pages, please add the necessary info.
