### ISSUE TITLE
[Bug.Minor] ERN maker (And Obelisk Reactor) wiki page is linked from game but does not exist

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#866]
To recreate:
1. Mouse over ERN maker.
2. Press H (See #865 for a related bug)
3. Be linked to this URL: (https://knucklecracker.com/wiki/doku.php?id=cw4:cmod:docs:e180bc1f-f245-4026-8c91-ac959bfe518c)
4. See the "This topic does not exist yet" page

**Comment by Karsten75** [comment]
Should anyone come across these pages, please update the wiki with the necessary info.
