### ISSUE TITLE
[Suggestion] Ignore map move input when mouse is over (some) UI elements

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#867]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use my mouse to check the location of a recently-died unit in the death log, and the map scrolls away.

**Describe the solution you'd like**
I would like the game to ignore map-move-input from the mouse hitting the edge of the screen when it is also over the death log. (And if wanted also for the inline options, and possibly other UI elements,)

**Describe alternatives you've considered**
I could remove map-move-inputs completely. Yet I do not do this since the input method is useful sometimes.

**Comment by matjojo** [comment]
After playing a little more I also found this really annoying for the TERP interface, as well as the ERN Building and the Factory.

**Comment by PRG-YouTube** [comment]
This would make the edge scrolling super annoying as there would be (semi randomish) dead spots on the edge scrolling border.
