### ISSUE TITLE
[Suggestion] Allow the user to look 90* to the map

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#868]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to look 90* to the map (straight forwards) and the game does not allow this.

**Describe the solution you'd like**
I'd like the game to allow me to look straight ahead. (Maybe even up?)

**Describe alternatives you've considered**
Not wanting to look straight ahead: whilst technically a solution not one I'd like to take.

Please see the attached video for a small demonstration of the issue.
https://i.imgur.com/FLPo4j3.mp4

https://user-images.githubusercontent.com/8158314/117133929-2f515300-ada5-11eb-85a9-2be7c9254517.mp4

**Comment by PRG-YouTube** [comment]
This seems intended and is more intuitive than allowing shallower angles I'd say. For the occasional time you might want to aim your camera in another way you can use the Shift + F to enable the free cam mode.

**Comment by matjojo** [comment]
I can see your point. But the free cam is not a usable alternative, as the movement speed for this camera when it's pointed in an angle that the normal "not auto" camera does not support is significantly stunted.

I do not get how disallowing certain angles from being used makes the camera "more intuitive". Can you provide an example that may make this more clear?

**Comment by PRG-YouTube** [comment]
The game is in 3D. Looking at shallow angles only allows one to see the things which are in the front but you lose all aspects of depth in the game.

Lets say you have multiple mountains one after the other and the first mountain is the highest. Looking parallel to the ground would allow you to see just the 1st mountain with slight difficulty to see details in terrain before that mountain, but nothing behind that single mountain. Thus you are not seeing most of the area and you can not manage what you cannot see.

In an RTS game where the whole picture is most important most of the time it makes sense to limit the user to non-shallow angles to prevent losing the whole picture too often. Still there is the option for those who want those shallow angles anyway.

What would your use case be for these shallow angles? And for those, how often do these use cases occur, and wouldn't Shift+F & Shift+R suffice for these cases?

**Comment by matjojo** [comment]
My use case for those angles is to check creeper height and weapon visibility.
Oftentimes I want to check whether a certain natural wall is high enough. Hard to do from top-down, hard to do with the allowed angles. I tend to need to zoom out very far to be able to get a good perspective.

The use case occurs quite often.

And no, Shift F and R are not a replacement, since they have their own weird limitations that make them hard to play with. Like the earlier lined out "slow when panning" and "slow when moving" issues.

They are also not a replacement since they break the flow of the game. I don't want to have to go in and out of different modes when looking around the area, especially since the reason for this is entirely artificial.

Also I don't *really* buy the idea that we have to *protect* the generic userbase from themselves. Do we really have to protect other users from placing their camera behind a mountain or hill and then forgetting the whole rest of the map?
