### ISSUE TITLE
{Suggestion] Show not completed objectives alongside completed objectives in the mission select screen

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#87]
**Is your feature request related to a problem? Please describe.**
When I wanted to complete everything in the demo, I realized I found myself flipping through every mission and checking the play log, to see if I completed all objectives.

**Describe the solution you'd like**
Show possible objectives in a level that aren't completed yet alongside the completed objectives, perhaps using just a hollow border rather than a green icon.

**Additional context**
I have some additional thoughts about this:

I noticed that a level can change objectives, for example the first mission can change from "Survive" to "Reclaim". I don't know if this is 4RPL or lower level manipulation... If it is 4RPL, then I have several questions:

I'm curious if this means that it is not possible to undoubtedly determine what objectives a level truly has, because different 4RPL code paths could change the objective to something else at any point?

If the above is true, does it mean cheaters can submit bogus scores for objectives that a map isn't programmed to have? 

Furthermore, if level 1 is 4RPL, does it mean mapmakers don't have to complete every objective, meaning some maps could be marked as having an objective, but that objective may be impossible? (You can only complete Survive or Reclaim, but not both at once. So if uploading a map required beating all objectives, uploading a map like this would be impossible).

Answers to these questions will sway my interest in this feature, because I wouldn't want the game showing me objectives that are impossible to complete, for one reason or another - whether it be cheaters or mapmakers who marked a map as having an objective, but never completed it.

**Comment by Karsten75** [comment]
I'm moving this into the "Evaluation" aspect, sine knucracker said that he'll consider implementing visual indicators  for available but not yet obtained  objectives iin the Demo and story missions. 

In Colonies, all known objectives ar listed on each map. We do not have a methiod the retroactively add 4RPL objectives, so that will jsut be punted. 

As for cheaters, the community will hopefully report the map (as they did where completion of maps in CW3 was only  possible via CRPL cheat) and then the maps will be redacted from Colonies.

**Comment by grabz-dev** [comment]
> In Colonies, all known objectives are listed on each map
So mission 1 objectives are manipulated in engine? Okay, that simplifies things a lot.

Does the mapmaker have to beat every objective in a finalized map in order to upload it?

When I mentioned cheaters, I wasn't sure if people could upload a score for any objective they want through illicit means, but now I understand that maps have a specific set of objectives that's set in stone which is good.

**Comment by knucracker** [comment]
I now show the possible objectives along with the completed ones. For the built in missions, this affects the icons that show above the planet names. I can also manually massage them to compensate for changes made mid mission.  For the custom (Colony) maps, the best I can do is show what the mission has declared. So a mission badge will show what objectives are declared when the map is finalized. If scripting changes them after the mission starts, that will be something the community has to decide if it likes.

I don't plan on making a person complete every objective before uploading a map. That could change over time (enforced on the server), but I'm not starting out that way.
