### ISSUE TITLE
[Suggestion] A way to see the range of all "coverage based" weapons (Sniper, Missile)

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#870]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to have proper coverage of Snipers and Missiles for my bases. I have to either guess, check every unit one by one, or use the somewhat confusing and hard to read map view for missiles.

**Describe the solution you'd like**
I wish that on the selection of one of the range based weapons the range of all the others would also be highlighted.

**Describe alternatives you've considered**
#### Missiles
- Select all of them by hand. Slow, error-prone.
- Use the map view. Does not show height (well it does kinda), hard to interpret.

#### Snipers
- Select all of them by hand. Slow, error-prone.

**Comment by PRG-YouTube** [comment]
For missiles this is already available in the minimap as can be seen in the image below. I would however be helpful to show same when building snipers.

![image](https://user-images.githubusercontent.com/68601223/117296265-24fe8a00-ae75-11eb-882c-e36971732709.png)

**Comment by matjojo** [comment]
Yeah I describe that in the `Alternatives you've considered` section.
The minimap would ironically be good enough for snipers, as they are purely flat. But for missiles, as they are also height dependent, the minimap doesn't really provide enough information (for me). to judge coverage easily.

**Comment by PRG-YouTube** [comment]
But even if you would activate all missile ranges at the same time, I highly doubt if that is going to be clear though.

Snipers are also affected by the terrain quite a lot.
