### ISSUE TITLE
[Suggestion] Make the mouse move with screen shake on explosions

### ISSUE THREAD

**Issue by matjojo** [KnuckleCracker/CW4-bug-tracker#875]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the screen shakes and I cannot click accurately.

**Describe the solution you'd like**
I'd like the game to move my mouse the same as the screen is shaken when an explosion happens so that I can keep playing the game.

**Describe alternatives you've considered**
- Pausing: I don't like doing this because it somewhat ruins the flow of an intense moment.
- Clicking in the wrong place: I do this too often.

**Comment by PRG-YouTube** [comment]
Agree that the shake is annoying when placing units etc, this would fix that
