### ISSUE TITLE
[4RPL] SetRasterSize causes crash in certain situations.

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#878]
If you try to set the raster size to bigger than the map by a certain threshold, the game will instantly crash to desktop in most situations.  

Reproduction:

Create an efficient sized map (any small sized map will do, the key seems to be setting the raster to a certain size bigger than the map).
Run the following script in console for a single execution.  It's part of the sample code on the wiki with a set raster size function thrown in there, but with stuff not relevant to the crash removed.  
```
V4(0 1 0 1) ->green
ShowRaster(true)

SetRasterSize(400 400)

do(5000 0)
	SetRaster(GetRandMapCell <-green)
loop
```

The game will almost certainly instantly crash to desktop, with an error log like this.  

[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6449326/Player.log)

Observations:
Creating a small raster first, and then a big one seems to work fine a lot of the time.
Sometimes, putting a value that was slightly too high wouldn't crash the game immediately, but have lines of graphic corruption running horizontally across parts of the screen, and the game would crash instantly if you tried to close the run script window.   I had a screenshot of this but lost it, and couldn't reproduce it.  
The game seemingly does all 5000 loops fine (A debug instruction there logs all 5000 to the player log), the crash happens at some point afterwards.  

Edit: Ah, I found it again. This is the rare intermediate state, where it crashes the instant you click on the red X to close the script window. 
![Screenshot 2021-05-09 231119](https://user-images.githubusercontent.com/75511563/117604798-e9d1b480-b11b-11eb-891a-11cddc77c6f4.png)

**Comment by knucracker** [comment]
Enabling the raster initialized it to the size of the map.  Setting the size later increased the raster size, bit was not updating the raster buffer reference to the new (larger) size. So the crash could come at any point after a call to Set because of that problem. I've updated the code to properly grab the new raster buffer after a size change.
