### ISSUE TITLE
Spore/Egg Countdown Covering HUD Art

### ISSUE THREAD

**Issue by Reid203** [KnuckleCracker/CW4-bug-tracker#88]
This bug is recreated when there's a spore or egg nest right behind the top left HUD. Hovering to select a weapon or structure will cause the countdown timer to cover up the art of the cannon, missile, miner, etc. The mouse has to be over both the image and objective. Further testing shows that all popups (like from totems when in need of liftic) cause the same issue. Included the following screenshots to help understand the small issue. Hope this helps!

![image](https://user-images.githubusercontent.com/72884008/96025223-73393680-0e1a-11eb-9e72-8fe355000544.png)

![image](https://user-images.githubusercontent.com/72884008/96025620-fc506d80-0e1a-11eb-9615-687421336089.png)

![image](https://user-images.githubusercontent.com/72884008/96026097-ae883500-0e1b-11eb-8b86-768fee219317.png)

**Comment by knucracker** [comment]
Fixed for the standard blue popup. It will get fixed for the totem and resource pod when they are switched to the standard popup.
