### ISSUE TITLE
[Bug] Cursor vanishes on mission and on main menu

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#880]
On map #1485, unpausing, going into FPS mode (Custom1) and dying will leave you with a hidden cursor until the mission is restarted or the whole game is restarted.

Note that the cursor also remains hidden on the main menus when exiting the mission!

See: https://youtu.be/YLsgZL-vZc8

Minor suggestion: Also trying to move through the menus with a hidden mouse is difficult because some buttons do have a mouseover glow but others do not, suggest to make all the (most important) UI buttons glow on mouseover.

**Comment by Karsten75** [comment]
Anything in the player.log file when this happens?

**Comment by PRG-YouTube** [comment]
Nothing in the player.log. Is the issue reproducible on your end as well?

**Comment by Durikkan** [comment]
Duplicate / Related to #849

**Comment by knucracker** [comment]
Should be fixed by the changes made for #849
