### ISSUE TITLE
[4RPL Addition] FindUnitEnemy for finding Anticreeper

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#883]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get Deepest or nearest Anticreeper is to GetCreeper for all cells in range.  This option causes significant lag for units with large range or a large number of units.

**Describe the solution you'd like**
Any of the following:
FindUnitEnemy to look for AC if the unit specified is an Enemy
An additional argument for FindUnitEnemy to look for Creeper vs Anticreeper
A new function identical to FindUnitEnemy that looks for Anticreeper.  This seems the best solution as it won't break existing scripts.

**Comment by Karsten75** [comment]
I'm sitting here wondering why it was called "FindUnitEnemy" in the first place. It seems non-intuitive, as has been remarked in #752. I'm also curious about the late addition date - well after release of the full game, which makes me think that it was a late addition although I can't find any other mentions of the command in GitHub.
