### ISSUE TITLE
[Bug.Minor] Moving walls sometimes creates minor issues

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#887]
### I'll start by saying this is relatively minor, so it's up to you if it's worth the effort to address or not, just bringing it to your attention.

If you drag and move a crazonium wall in the map editor, it will leave its line of sight blocking component behind, and the old location will block things such as tower lines, and the new location won't.  Advancing a frame will cause the new location to block, but the old location will still block as well until you save and reload.  Saving and loading will get rid of the old blocker, and will usually create the new blocker (but not always, sometimes it also requires a frame advance).    **So the combination of loading and advancing the frame generally clears up all lingering side effects.**  

This also applies to normal walls, but is less impactful because they don't block connection line of sight, but they still leave a creeper blocker in every tile it's positioned in (which are cleared on save/load).  Moving a wall will also cause it's charge to drop to 0, and charge up independently for any tile it's moved to (and moving back to one of the previous tiles will put the charge where it was)

This save has some of the partial crazonium walls that will fix themselves if you advance a frame, but it allows you to place down a tower to claim the item through the wall before you advance a frame.  

![walls](https://user-images.githubusercontent.com/75511563/118907276-d88b6380-b8e4-11eb-9d33-4af09defa093.jpg)

[walls.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6512355/walls.zip)

**Comment by Karsten75** [comment]
I recall looking at a map that manifested this issue some months back. Map 941. Knucracker may recall the conversation. Your finding explains how it comes about.
