### ISSUE TITLE
[Bug] Filtering search by multiple 'NOT Tags' shows maps with one or more of the tags, but not all

### ISSUE THREAD

**Issue by synystersparx** [KnuckleCracker/CW4-bug-tracker#893]
4. Screenshots

Not FPS:
![image](https://user-images.githubusercontent.com/56812592/119438584-2be72280-bce6-11eb-8e77-11925d1fd0e6.png)

Not PAC:
![image](https://user-images.githubusercontent.com/56812592/119438629-45886a00-bce6-11eb-8971-571fb5ca3176.png)

Not FPS, PAC showing some FPS and PAC:
![image](https://user-images.githubusercontent.com/56812592/119438734-75d00880-bce6-11eb-8a68-541395788ebe.png)

5. Describe the bug 
   When searching by NOT Tags, if you have two comma separated values in the input, it will show all maps that do not have ALL tags listed. For example, if 'PAC, FPS' is in the input, it will still show maps that have PAC and FPS tags, but not maps that have both FPS and PAC. This seems like a bug as I'd like to see only maps that don't have either of the listed tags.

**Comment by Durikkan** [comment]
This seems to be a result of the tag system or-ing all of the tags, when it might make more sense to and the tags, or at least have it as an option (I think someone searching for eggs and ac probably wants both, not all maps that have at least one of those things).  Switching to not makes it not the two tags, and then or them, so it only returns a map if either of the nots return true (i.e. the map has at most one of the tags).

**Comment by synystersparx** [comment]
AND-ing for wanted tags and OR-ing for unwanted tags seems like the easiest solution, but a toggle to switch between might be useful as well.

**Comment by Karsten75** [comment]
Requesting additional features is not a bug issue. I think this issue is more a request to expand and alter the way tag filtering works. Still valid, but it results in changes, so more work.

**Comment by synystersparx** [comment]
I wouldn't call it a request for additional features. The way I see it, it is not filtering properly. Adding a tag with "not" search checked shouldn't show more, it should only show less. I guess it depends on how you think filtering data should work, but to me this is a flawed filter. 

If I were making a suggestion I would ask that the tag filter be changed to use a "!" or "-" for prepending to tags the searcher wishes to exclude, that way "PAC -tedious" would work.

**Comment by knucracker** [comment]
Added "-tag" support.  See if this meets the need.
