### ISSUE TITLE
[Bug] Rain orbital creates ghosts of it's projectiles

### ISSUE THREAD

**Issue by MiaMesa** [KnuckleCracker/CW4-bug-tracker#897]
Using the Rain Orbital, on Chronom : May 28, 2021 created ghosts of the exploding projectiles, the map has been lightly edited and a small, unrelated script has been run here's the full detail of what has been done when editing the map just in case:

-Added a little bit of mesh.
-Disabled creeper cutoff.
-Increased max eggs.
-Applied a theme.
-Enabled Script "Time Stop Bank.cpack" which sole purpose is to prevent pausing after a set amount of time paused.

The script has been disabled in the screenshot and save I sent for the purpose of being able to pause the game, the glitch remain active.

Reloading the save keeps the glitch active.

Script used : 
[Time Stop Bank.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6571131/Time.Stop.Bank.zip)

Save :
[SaveGlitchRainGhost.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6571093/SaveGlitchRainGhost.zip)

Log :
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6571083/Player.log)

Screenshot :
![RainGhostsBug](https://user-images.githubusercontent.com/74882806/120213084-1799ad00-c233-11eb-8be4-4338a6d3dd8f.PNG)

**Comment by Karsten75** [comment]
This was opened at my behest due to a misunderstanding. On closer inspection, I don't believe there is anything here that is not intended.

**Comment by Karsten75** [comment]
The case has been made that in top-down, this adds visual clutter to the view. On that basis and since I assume it's relatively trivial to restore the issue to the pre-mverse status, I'm re-opening this for further consideration.

**Comment by knucracker** [comment]
Removed animus creation from raindrops
