### ISSUE TITLE
[Bug] Game crashes when raster script executes

### ISSUE THREAD

**Issue by RealArgonwolf** [KnuckleCracker/CW4-bug-tracker#898]
When the attached 4RPL script runs it crashes the game with an access violation error.
[RasterCheck.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6580114/RasterCheck.txt)

Error log:
[error.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/6580127/error.log)

**Comment by Karsten75** [comment]
We need the player.log file as well, please.

**Comment by knucracker** [comment]
Probably the same as #878.  If so, try the mverse build of the game (right click the game in steam, select properties, then betas.  Select "mverse".  That version will become the shipping version in a month or less.

If you still have a problem just make a new bug with the details.

**Comment by RealArgonwolf** [comment]
Updating to the beta appears to have fixed the issue.
