### ISSUE TITLE
[4RPL Addition] GetUnitsInBounds

### ISSUE THREAD

**Issue by Up-Level** [KnuckleCracker/CW4-bug-tracker#905]
**Is your feature request related to a problem? Please describe.**
This would be useful for situations where all units inside a zone want to be found, such as all units above/below a specific height on the map.

**Describe the solution you'd like**
A function similar to GetUnitsInRange, but takes a Vector3 bound for range instead, searching for units inside that boundary. 

**Additional context**
I'm trying to damage all units below a certain height on a map I'm working on. Currently I'm getting all units on the map with GetUnitsInRange and iterating over them to check if their height is below the specified height. This appears to cause performance problems with high numbers of units.

**Comment by RealArgonwolf** [comment]
What you need according to your context is already available. GetUnitsInRange lets you specify a 3D cubic search area. So if your code contains something like "GetUnitsInRange(V3(0 -300 0) 301.1 true true false 2 0 0)" that would get you all friendly units at or below 301.1 (300 is just an arbitrary number, it can be scaled up for longer maps) allowing them to be damaged. Granted, you can't specify the individual dimensions of the volume checked and are stuck with a cube, but that's not a problem in your particular case.

That being said, I have no idea if it is noticeably more performant than your existing method, just that the functionality you need already exists to some degree and is just a bit niche and found in a possibly unexpected place.

I played your map by the way and I absolutely love it.

**Comment by Up-Level** [comment]
I should've mentioned that I did try GetUnitsInRange the way you suggested, but it never worked for some reason and would return all units on the map regardless. Maybe I missed something though.

**Comment by RealArgonwolf** [comment]
> 
> 
> I should've mentioned that I did try GetUnitsInRange the way you suggested, but it never worked for some reason and would return all units on the map regardless. Maybe I missed something though.

You didn't miss anything, but I believe you found a bug. It appears the square range search ignores the is3d parameter and just goes by 2d distance.

**Comment by knucracker** [comment]
Take a look at the comments on #650 and let me know if this applies to anything here.

**Comment by RealArgonwolf** [comment]
> 
> 
> Take a look at the comments on #650 and let me know if this applies to anything here.

Yes, it seems the GetUnits method uses isSquare correctly in tandem with is3d. That's good to know. Maybe at this point you should just discard the existing GetUnitsInRange function and have the compiler recognize it as an overload of the GetUnits function, what with it not working in 3d squares and that bug on the wiki that says it can't find units that don't occupy land.
