### ISSUE TITLE
[Bug.Minor] MVerse button overlapping with Colonies

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#906]
The MVerse button invisibly extends to roughly the red line I drew, overlapping the Colonies button

![image](https://user-images.githubusercontent.com/68601223/121552088-77047380-ca10-11eb-8dec-bdeea68442fc.png)

**Comment by knucracker** [comment]
The mverse button was moved and resized and this issue resolved in the process.
