### ISSUE TITLE
[bug] Couldn't build a weapon with hidden UI

### ISSUE THREAD

**Issue by mu2so4** [KnuckleCracker/CW4-bug-tracker#91]
I just did these actions:

1. Hid the UI
2. Selected "Structures" in the build menu
3. Hid it
4. Switched on "Weapons" using Controls
5. Also using Controls chose Mortars. However, the game decided I need Pylons
6. Opened the build menu. The "Structures" overlayed the "Weapons"
7. Switched on the "Weapons" but the "Structures" displayed instead of it

It happens whenever I hide the UI
I hope you can fix this bug. Have a good day)

P. S. Sorry for my bad English
[Creeper World 4 2020-10-17 07-46-04.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5395333/Creeper.World.4.2020-10-17.07-46-04.zip)

**Comment by knucracker** [comment]
A surprisingly difficult thing to fix. The build buttons were doing some initialization during their Start function. The Toggle control also doesn't fire events when hidden. So I had to manually set the visual state of the tabs when hidden (and pressing F1, F2, etc). Also had to manually initialize the build buttons when the UI was hidden.
