### ISSUE TITLE
[Suggestion] Let Mist and Unit Debug Text Render Through Creeper

### ISSUE THREAD

**Issue by RealArgonwolf** [KnuckleCracker/CW4-bug-tracker#918]
**Is your feature request related to a problem? Please describe.**
Mist and unit debug text cannot be consistently seen through creeper and anti-creeper, presumably since they both use a translucent shader and instead of correctly alpha-blending they simply don't show up if obscured by creeper (debug text occasionally flickers on and off when covered with creeper).

**Describe the solution you'd like**
Allow mist and debug text to render when submerged in creeper. Though it's not what I'd call a bug, it would be helpful to anyone using debug text or mist particles as a core feature of their map to have them render more consistently.

**Describe alternatives you've considered**
Unit popup text renders just fine, which makes sense because it seems to be part of the UI (doesn't change size with distance). This wouldn't work at all with mist since it has to have a 3d position in the world, and though it would probably work alright with debug text, that would require either removing its size with distance or writing additional code to compensate.

**Comment by knucracker** [comment]
Depth sorting on transparent geometry.... pain.  The creeper is broken up into sectors and each has a geometric center that is used to determine its depth sort. The same is true for the debug text.  So as you rotate around you might get a creeper sector (which is a 32x32 area of creeper) that snaps in front of or behind the debug text.

For the DebugText I have switched it to an overlay material (it overlays the creeper and the terrain). That makes it consistently visible.  Now it trades off visual inconsistency for consistency.... that is always on top of terrain or creeper.  I don't know if this is better or worse (and it I'm having deja vu about this whole topic :) )

As for the mist... yeah... same thing but I can't always snap it in front so I'll have to leave it as is.

**Comment by RealArgonwolf** [comment]
I know transparent shaders don't always play nicely together, and I'm very glad you were willing to address it. I figured a cutout shader might do it for the text but yeah, since mist relies on its partial transparency to look right I can see it wouldn't work, nor would modifying the render queue which is how it sounds like you fixed the text. But the text was definitely the more important issue in my experience since I like using it to display unit data, and having it show through anti-creeper is just the tops.
