### ISSUE TITLE
[Bug] Booting multiple multirun instances quickly generates sharing violation

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#919]
Opening a second multirun instance while the first is on the loading screen generates the following warning:

![image](https://user-images.githubusercontent.com/68601223/122377198-27203200-cf65-11eb-8ae7-ab72abdea819.png)

**Comment by Karsten75** [comment]
The Some files are serialized during opening. This is unavoidable. Please wait until 1st instance has fully loaded  before launching a 2nd instance of the game.

**Comment by Karsten75** [comment]
Worth noting that this sharing violation might also occur on the RPL.TXT fle and as such that does present an issue. #921 provided a solution for that.
