### ISSUE TITLE
no update yet it states one is needed

### ISSUE THREAD

**Issue by glitchtraper** [KnuckleCracker/CW4-bug-tracker#926]
Help us help you. 

1. The vast majority of issues encountered will go away after a reboot of your computer. This is our experience over many games over many years. Please try that. If the issue persist across a restart of your  computer, then proceed. 
i tried that no dice
2.  **It is very important that you NOT restart the game before you save the output log**
 Log file location: 
   ** Windows 10** (currently the only supported platform)
      The log file location is here under Windows 10 (currently the only supported platform). 
           `c:\Users\YOUR_USER\AppData\LocalLow\Knuckle Cracker\Creeper World 4\Player.log`
      Alternately, copy and paste this short-form file location into the address bar of Windows File Explorer
             `%LOCALAPPDATA%Low\Knuckle Cracker\Creeper World 4`
it caused an error when i tried that
3. If the error persists over a save and reload of the game, please provide the save file as well (You may have to zip it up, as the .cw4 file type is not supported as a direct upload in GitHub)
  Each part of the game (Farsite, Chronom, Mark V, etc.( has a folder underneath the game's home directory.
         `%HOMEPATH%\Documents\My Games\creeperworld4\saves\`
   If you were saving in the Map Editor, then the save is in the folder for the map in 
         `%HOMEPATH%\Documents\My Games\creeperworld4\editor\`
it also did not work for some weird reason
4. Screenshots help us to **see**the problem. 
  Screenshots are here
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

   Use F11, or F12(steam screenshot) and take a screenshot of the game (if you use both, that's also great).  If you refer to a specific part of the screen, a smaller, localized screenshot helps, but the large screenshots let us see if something else in the game is an issue. 

![bug part 1](https://user-images.githubusercontent.com/64903525/122603974-d67b0880-d03a-11eb-81c1-38e09b6cf8b5.png)
![Screenshot 2021-06-18 134045](https://user-images.githubusercontent.com/64903525/122603981-d975f900-d03a-11eb-8bfc-61c8b1ef7e84.png)
![bug p 2](https://user-images.githubusercontent.com/64903525/122603984-da0e8f80-d03a-11eb-97dc-28ea68642133.png)

5. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 
the bug is that despite the game being fully updated. 
it says that a update is needed

**Additional context**

**Comment by glitchtraper** [comment]
it does not allow me to play some maps because of the bug

**Comment by knucracker** [comment]
The update will be out in a few days. Some beta testers have uploaded maps made with the new version.  In the mean time, you can switch to the "mverse" branch on steam if you want to update now. Right click the game in steam and go to properties. Then betas.  From there select "mverse" in the dropdown.
