### ISSUE TITLE
[Bug.Minor] Launching a spore at its start location causes it to hover in place forever

### ISSUE THREAD

**Issue by RealArgonwolf** [KnuckleCracker/CW4-bug-tracker#927]
Help us help you. 

4. Describe the bug 
    When a spore is fired at the same x and z coordinates it was launched from (either via 4rpl code or setting a spore launcher's target location to itself in the editor menu), it never moves from its starting position and (at least as long as I'm willing to wait before manually deleting it) never detonates or disappears. As a player, I would expect a spore fired at its own starting location to either fly up and down in a straight line, releasing its payload on contact with the ground as usual, or possibly just depositing its creeper as soon as it spawns without even visually appearing, similar to how a blob targeted to its own nest does.

**Additional context**
It doesn't cause any major issues that I'm aware of other than the possibility of multiple frozen spores stacking up and creating a glare that makes it hard to see in a small area around the launcher.

**Comment by knucracker** [comment]
The ballistics equation I used for the spore trajectory fails when the lateral distance is zero.  In that case I was setting the returned flight parameters to have a velocity of 0 and a 'gravity' of 0.  That in turn makes a spore that just hovers at the launch position.  I have changed the parameters to have a small gravity in the case of a failed ballistics calculation.  That will make the spore fall straight downwards from its launch height (which is 2.5 above the terrain).
