### ISSUE TITLE
[4RPL Addition] GetMesh/GetMeshHealth

### ISSUE THREAD

**Issue by bryanbader** [KnuckleCracker/CW4-bug-tracker#928]
**Is your feature request related to a problem? Please describe.**
I'm currently building the Sleeper mode in CW4, and I'm finding it difficult to provide a decent quality-of-play for base mode, playing against the sleeper.
As the FPS, it's easy enough to directly attack and destroy Sleeper units, but for base mode, apart from a custom unit I've created that can directly target the Special Type of Custom1, the core base weapons (cannon,mortar,bomber,bertha etc) are relegated to a secondary role.
In CW3, the workaround for this was using digitalis, and getting the health of the digitalis directly underneath the sleeper unit - in CW4, you can call DamageMesh but there's no way to find out the current health of the mesh.

**Describe the solution you'd like**
Have the ability to call on a cell, to see what the health of the mesh is. This would allow me to tie the unit health to the damage taken by the mesh, and allow faux-targeting of the sleeper units by the core CW4 weapons.

**Additional context**
This would be instrumental in advancing the Sleeper CW4 mode - but admittedly I can't think of any other use cases for this.

**Comment by knucracker** [comment]
In 2.0.1 there are now:
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getmeshhealth
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:setmeshhealth

Note that 
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:setterrainspecial 
and 
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:setunitgrowsmesh 
may also be necessary APIs depending on exactly what thing is being done with mesh.
