### ISSUE TITLE
[4RPL Addition] ActivateMesh variable on units

### ISSUE THREAD

**Issue by bryanbader** [KnuckleCracker/CW4-bug-tracker#929]
**Describe the solution you'd like**
Currently, the only unit in the game that can activate mesh is an emitter. Having a flag or a variable that can be set on custom units to activate mesh would mean this is no longer the case.

**Describe alternatives you've considered**
The usual alternative is to set a 0-strength emitter sitting below the terrain, but this then causes the emitter to appear on the minimap and if it doesn't have a negative strength, to count in the nullify list.

**Comment by knucracker** [comment]
In 2.0.1 there is now : https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:setunitgrowsmesh
