### ISSUE TITLE
[4RPL Addition] More player actions able to be executed in 4rpl scripts.

### ISSUE THREAD

**Issue by RealArgonwolf** [KnuckleCracker/CW4-bug-tracker#930]
**Is your feature request related to a problem? Please describe.**
I'm attempting to build a simple AI that controls the Rift Lab and all of its buildings as an enemy for a "play-as-creeper" type map. Though all units can be constructed and moved around, many of their functionalities are locked and can only be initiated by the player via the UI or a hotkey. This results in many units being totally unusuable by the AI due to their entire functionality revolving around aforementioned UI interactions.

**Describe the solution you'd like**
Allowing various units to be controlled from script with the same granularity that the player can control them would allow AI creation to be significantly improved, in addition to any other custom maps that might want to use computer-controlled vanilla units.

Specifically:
 - Set ERN portal to want ERNs for specific upgrade slots
 - Set units' "ERN Wanted" status (functionality already exists to get their current state)
 - Tell movable units whether or not to avoid creeper
 - Set miners to produce either energy or anti-creeper (functionality already exists to get their current state)
 - Mark terrain to be de-contaminated by terps
 - Tell porters where (and what) to deliver
 - Control sprayers' pull fields, always-on and ore collection abilities
 - Tell cannons whether to prioritize mesh or creeper
 - Control which targets snipers will attack
 - Set bombers' and AC bombers' start and end targets (if they're set to the same place, drop all AC at once/circle target the same as if the player had only given a single target point)
 - Tell bombers and AC bombers to return to base
 - Call down orbital strikes (functionality already exists to get and set the number of available orbitals)

**Describe alternatives you've considered**
I considered simply spawning in a very large number of pre-configured units and hiding them off-map before finalizing the map, then the units could be teleported in at will and swapped in and out to simulate changing modes. This would, however, require a fairly sizable overhead as units would have to have their health, ammo and active/armed/resupplied states copied before swapping, a large number of unused off-screen units would probably bog down GetUnits calls, and this solution would not solve the issue of setting porter/bomber targets or calling in orbital strikes.

I know it's a lot to ask, but even just a single method that takes an int/string parameter that can read/modify each unit's data would do the trick (except probably for the orbital strikes, since they're not subordinate to any unit).

**Comment by bryanbader** [comment]
The Orbital Strike is already possible - I've got code that does this in a couple of maps (One is "Stargate", map 1283).
It hinges around that you can create the Orbital strike units, which handle the effect and timer automatically.
