### ISSUE TITLE
[4RPL Addition] Callback Function when the game is saved.

### ISSUE THREAD

**Issue by Up-Level** [KnuckleCracker/CW4-bug-tracker#931]
**Is your feature request related to a problem? Please describe.**
I want to store data about units on a map, which is then read when the game is loaded from a save. The data needs to be accurate for the frame the game was saved on. Collecting all of this data is quite expensive, so doing it every frame is not feasible.

**Describe the solution you'd like**
A built-in function callback that runs just before the game is saved, so changes made by the script are in the save file.

**Describe alternatives you've considered**
Running code every frame - for performance-heavy code this slows the game down too much.
Running code every x seconds - data will likely be wrong for when the game gets saved.
Asking the player to press a key before saving - this can be inconvenient and players would likely forget sometimes.

**Comment by knucracker** [comment]
Added this: https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:msg_savegame
