### ISSUE TITLE
[4RPL Addition] GetMVersePlayerName

### ISSUE THREAD

**Issue by Up-Level** [KnuckleCracker/CW4-bug-tracker#932]
**Is your feature request related to a problem? Please describe.**
I would like to link data to players joining a session on save they had previously been on.

**Describe the solution you'd like**
A function that returns the username the client player used on the join screen.

**Describe alternatives you've considered**
Using GetMVersePlayerNum means players have to join in the same order to link data properly, which is not ideal.
Having players press a key 1-4 to identify themselves, but some players might forget.

**Comment by knucracker** [comment]
I've added this:
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getmverseplayers
