### ISSUE TITLE
[4RPL Addition] (getCreeperInRadius, getUnitInCreeper, getsetUnitDestroyable

### ISSUE THREAD

**Issue by mandrake789** [KnuckleCracker/CW4-bug-tracker#935]
getCreeperInRange/Radius - tally up the total creeper in a givin radius, say you wanna code up a creeper limit for a custom emitter, so that it only stops once the total creeper around it reaches a certain level, not the whole screensworth of- lovely blue soda :sip:

getUnitInCreeper - check if a unit is being touched by creeper. probably best used by something like a flipmitter because of how physics work in this game. 

get/setUnitDestroyable - similar to being "impervious" except it can take damage, the unit in question just wont die; please feel free to mock me publicly if impervious does exactly what i just said and im dumb. mostly because health could be used as a variable in many weird funky contexts.

**Comment by knucracker** [comment]
Added: https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getcreeperinrange
Added: https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getunitincreeper

I didn't add anything related to making units take damage but not actually destroy. That's a bit harder to do.
