### ISSUE TITLE
[4RPL Addition] Some way to tell a player has disconnected

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#936]
Some way to tell if a player has disconnected from a mverse match would be useful, that way 4rpl content can also gracefully remove them from whatever mechanic operates under the assumption that they are still in play. That said I'm not sure how it can be done, I was thinking it could be a message but it'd be nice to get a parameter of which player left (0 1 2 or 3) and I don't know if messages can put things on the stack. Alternatively there could be a function that returns a list of which players are still connected, and that could be used to determine a disconnection.

**Comment by knucracker** [comment]
I've added this routine:
https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:getmverseplayers

I think this should work for this purpose as well as at least one other (getting the player names for the players).
