### ISSUE TITLE
[Bug] Relocating the rift lab on the same frame it's placed allows you to stack units on top of it.

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#937]
With the new feature enabling you to move the rift lab on the same frame it's placed, it is currently possible to stack units on top of the rift lab. Submitted on behalf of Hypnotic22 in the discord.

Repro steps:

1. Load up any map with more than 1 spot you can land the rift lab.
2. Designate landing spot for rift lab.
3. Without unpausing, move designated rift lab landing spot to a different location.
4. Observe that the rift lab footprint no longer takes up space in either the original location or the new one, allowing for unit stacking.

![image](https://user-images.githubusercontent.com/32053682/123541189-c6cd8500-d708-11eb-8081-f3a143fee5ff.png)

**Comment by knucracker** [comment]
Changed to deploy footprint after repositioning.
