### ISSUE TITLE
[Bug] SetDecalSize requires save/load to apply correctly.

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#941]
The SetDecalSize 4rpl command will change the decal box visible in editor mode, but will wither not change the decal itself or cause it to scramble itself.

Code used for testing was:
SetDecalSize(12712 V2(15 15))
And the starting decal was:
![image](https://user-images.githubusercontent.com/68219054/123713831-40698e00-d843-11eb-9275-8fcf4e5ecf46.png)

Setting the dimensions of the decal bigger than the original will cause the decal to not update itself:

![image](https://user-images.githubusercontent.com/68219054/123713651-dea92400-d842-11eb-99ae-b0b9a3a6a862.png)

Setting the dimensions of the decal smaller than the original will cause the decal to do this:
![image](https://user-images.githubusercontent.com/68219054/123713957-7f97df00-d843-11eb-8b6f-03e39126e1b8.png)

Saving and loading causes the decals to render correctly.

**Comment by knucracker** [comment]
This could also cause a recurring exception in some cases.  The decal mesh wasn't being reinitialized, so changing the width and height could cause all sorts of problems.  I have changed the SetDecalSize api to refresh the mesh.  I have also added range checks on the width and  height to  [0,1024].
