### ISSUE TITLE
[Bug] Farsite level is currently broken due to SetTimerObeyPaused

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#944]
Fireswamp on the discord pointed out to me that the emitters on the Farsite level are not producing any creeper in the current version of the game. To be clear, this is the second level of the Farsite Expedition, the one named Farsite. 

After some brief investigation, we determined that the culprit seems to be the SetTimerObeyPaused command. When activated, the relevant timer does not count down regardless of whether the game is paused or not which causes the emitters to never burp the creeper out. GetPaused still seems to be working properly as intended, it seems to only be the timer which is causing issues.

repro steps (probably redundant here, but for posterity)

1. Load the second mission in Farsite Expedition
2. Observe the creeper cracks, that they do not emit any creeper whatsoever
3. (optional) remove line 124 from mission.4rpl (the one pertaining to SetTimerObeyPaused) and observe that the cracks begin to emit again.

**Comment by knucracker** [comment]
Hmmm, looks like I broke this when I fixed #839.  Reviewed the logic and corrected it for good this time (I hope).
Fix is in 2.1.3.
