### ISSUE TITLE
[Bug] ToCell is off by one with negative inputs

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#946]
5. Describe the bug 
   A clear and concise description of what the bug is. Can you recreate it? What steps is needed to recreate it? 

The coords given by ToCell are one too high when given numbers less than -0.5. `V3(-2 0 -2) ToCell Trace2` returns `-1 -1`. 

ToCell also always rounds `n.5` up, while the 4RPL round function rounds those cases to the nearest even number. Those are both valid, but I'm mentioning it because it might be related.

I tested with this script, which starts from (5,5) and goes down 0.1 each time, comparing ToCell with Round.

```
#Decrement coords 
<-x 0.1 sub 2 round ->x
<-z 0.1 sub 2 round ->z

V3(<-x 0 <-z) ToCell ->cellZ ->cellX
<-x 0 round ->roundedX
<-z 0 round ->roundedZ

#Trace the results
<-x <-z "->" <-cellX <-cellZ

#Check if it's equal to the round function's answer
if(<-roundedZ <-cellZ eq <-roundedX <-cellX eq &&)
	" *eq*"
else
	" Rounded gives" <-roundedX <-roundedZ 
endif
TraceAllSp

:Once
	5 ->x
	5 ->z
```

**Comment by knucracker** [comment]
Fixed in 2.1.4.  Also, I kept the 'always round 0.5 up' behavior rather than rounding to the nearest event. This seems to make the most sense for an api that is mostly used to position things on a map.
