### ISSUE TITLE
[Mverse] unable to join games via proton

### ISSUE THREAD

**Issue by spion06** [KnuckleCracker/CW4-bug-tracker#948]
**Describe the bug**
When joining a game though mverse on linux with proton there is a connection error after "downloading data" comes up.

**To Reproduce**
1. Run Creeper world 4 with proton
2. Join mverse game though steam invite or code

**Expected behavior**
I am able to join a game hosted on mverse

**Screenshots**

proton-experimental: https://gist.github.com/spion06/f799aa5826de8474ec3bb70936ea20ff
proton-ge 6.12: https://gist.github.com/spion06/37b28105bda611d61f7d05fa45fa51ed
![creeperworld4error1](https://user-images.githubusercontent.com/1733718/126053236-feb958c1-604a-4c5f-9182-bb91fde4fc0d.png)
![creeperworld4error2](https://user-images.githubusercontent.com/1733718/126053237-3e31a55b-eb5d-49f6-b8db-fd56635ff5bd.png)

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Proton version: Proton experimental, proton 5.13, or proton-ge (have tried 6.8 and 6.12)

**Additional context**
No issues joining the same game on windows. Please let me know if you would rather i log this with proton/proton-ge

**Comment by knucracker** [comment]
Yeah, I'm not sure I can do much about this.  The game uses EOS (Epic online services) and their library. So the problem is most likely somewhere between them and proton

**Comment by spion06** [comment]
Yeah no worries. I'll log the issue against proton. Thanks for taking a look!

**Comment by vermeeren** [comment]
@knucracker Me and a friend had the same issue with Proton-6.20-GE-1 (GloriousEggrol), which we initially used as it was mentioned this fixes the cutscenes.

Then we tried Proton experiment (Valve's official one), currently 6.3, and it connected and worked immediately without any issue.

Perhaps worth updating the pinned FAQ on Steam? https://steamcommunity.com/app/848480/discussions/0/2445965890668303819/

Thanks!
