### ISSUE TITLE
[Bug.Minor] Map Editor doesn't undo shattered land correctly.

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#949]
If you place shattered land, and then hit the undo key, it removes the shattered land, but leaves this invisible corrupted terrain that will fall 1 elevation level the first time creeper touches it, and then stay at that new level permanently.

You can clear it by running clear terrain or it, or changing it to another other type of special terrain, but it can confuse the map editor or players by having the terrain act unpredictably without a visible cause.   

Edit, it looks like #388 is the same issue, but this one identifies the cause of that issue.

**Comment by knucracker** [comment]
The undo manager was not saving all of the data structures related to shattered terrain. There was a minHeights array as well as another int[] that kept track of the current decayable state.
