### ISSUE TITLE
 {Suggestion] Implememnt Unit Limit specification

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#95]
In past games many maps made relied on limited numbers of units or unit increments  via pick-ups as the game progressed. 

In CW3 it was also possible to vary unit build costs, although maps based on this were generally less successful so I don't consider this a high priority for implementation. 

Please add a "unit limit" field in the gmae menu where units are enabled or disabled on a per-map basis.  Optionally, please consider exposing these parameters via the previously-discussed 4RPL "reflection" method ( #47)

![image](https://user-images.githubusercontent.com/22965021/96450459-dd1b5c80-11db-11eb-8c3f-b582eca40ab0.png)

**Comment by WithersChat** [comment]
This... I want this...

**Comment by Regallion** [comment]
Solved by #292

**Comment by Karsten75** [comment]
Duplicate of #292
