### ISSUE TITLE
[Bug.Minor] Missiles fall down to planet facing the wrong way

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#951]
Missiles that return to the planet after they go to the skies because of missing their target don't actually turn around, falling in upwards position instead. I don't think that's how aerodynamics are supposed to work?

I found out about this because I made a map with a spore tower that shoots 10 spores a second at the same location or something like that. Missiles struggle to reach the nearest (lowest) spore before it hits the ground. Not going to make an issue out of that though as I can already see exactly how I'm going to use that in my next map.

My suggestion would be to turn the missiles around after/when they reach the highest point of the "Let's fly to space" trajectory, though of course it's not my game so feel free to do whatever you think is best.

In case there's somehow any questions, just see the image. I think it explains almost everything pretty well.
![Schermopname (21)](https://user-images.githubusercontent.com/75793635/127362696-12adf6c7-a706-4e90-9c1a-a1c904036b9a.png)

**Comment by Karsten75** [comment]
Assume they're derived from similar tech as SpaceX or Blue Origin rockets making landings on Earth. Unfortunately, they've expended all their fuel in trying to reach the spores and can't make a successful landing.
