### ISSUE TITLE
[4RPL] SetUnitCanBuild cannot change buildability of custom units

### ISSUE THREAD

**Issue by thexa4** [KnuckleCracker/CW4-bug-tracker#954]
**Is your feature request related to a problem? Please describe.**
Right now custom units can only be hidden from the build menu by setting their player string to `""`. Unfortunately because there is no way to fetch the current player string and tab when doing that the label and tab of the unit have to be supplied out of band. This makes it hard to create scripts that do stuff with arbitrary custom units.

**Describe the solution you'd like**
SetUnitCanBuild is able to handle any value that can be returned by `GetBuildUnit`

**Describe alternatives you've considered**
Alternatively a way to fetch which build tab a unit is in and what the label is. (inverse of `SetCModPlayerMenuName`)

**Comment by Karsten75** [comment]
Custom map 1161 in Colonies ("The Aquarium") has implemented somehting along the lines you seek. :) 

```haskell
once
    SetCModPlayerMenuName("d276adb3-acbb-4483-afa3-9054c186cf7f" "" 3)
endonce
```

And then later in a different part of the code:
```haskell
# Wait until the user selects the Special units build tab.
if (<-custobjstate 3 eq)
    ShowUIIndicator("moabtab" "buildtab3")

    if (GetOpenBuildTab 3 eq)
        4 ->custobjstate
    endif
endif
```

This should allow you to proceed, since a fix/update  is not likely in the near term.
