### ISSUE TITLE
[Suggestion] Make creeper meshes available for custom units

### ISSUE THREAD

**Issue by thexa4** [KnuckleCracker/CW4-bug-tracker#955]
- [x] I have read, understood and agreed to the [policy](https://github.com/KnuckleCracker/CW4-bug-tracker/blob/master/Suggestion%20policy.md) regarding submitting material to Knuckle Cracker

**Is your feature request related to a problem? Please describe.**
I am trying to make a custom unit that acts as a spawner. In order for the player to understand that it's a spanwer I'd like to make it look like (a modified) one. Unfortunately the spawner model assets don't seem to be available in the builtin meshes.

**Describe the solution you'd like**
Add the animated submeshes to the builtin mesh list and add an `SetObjTimestamp (float time)` equivalent 4RPL call.

**Describe alternatives you've considered**
Alternatively having static versions of them would already be a big help. If that's not possible having them in a format that would allow importing them as a static mesh would also be useful.

**Comment by Karsten75** [comment]
We had a look at this. It's not the first time this came up either. 

Unfortunately it's not easy. Many of the units were made by an animator and are not compatible with the formats supported for import and export. For units made in Qubicle the meshes are stored in-game in a texture atlas. Extracting them and packaging these in a format that will be compatible with import into the CPACK editor for the game is not trivial and most likely the work would exceed the benefit.
