### ISSUE TITLE
[Bug.Minor] Spore trajectory short/far drawing speed difference

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#956]
Spore trajectories going short are being drawn too slow. They are slower than the spore itself. Trajectories of spores going far are drawn faster than close spore trajectories.

In this image you see a spore being launched short and far. The far trajectory is already done drawing, the short is still not half way, behind the spore itself.
![image](https://user-images.githubusercontent.com/68601223/128928304-cff952bb-852b-4554-bbca-7b150be67916.png)

**Comment by Karsten75** [comment]
I thought that this either got fixed or that no fix was possible, either way, closing.
