### ISSUE TITLE
[Bug] Greenar mother doesn't generate crystals in Campaign Mission 'The Experiment'

### ISSUE THREAD

**Issue by Spyrano** [KnuckleCracker/CW4-bug-tracker#961]
GoG version 2.1.4

Restarted level, game, computer. No crystal generation from Greenar Mother in The Experiment after at least 30 minutes. Other campaign missions tested still have crystal generation.

**Comment by Karsten75** [comment]
Do you have a specific map number to enable me to find the map you refer to?  Screenshot will also be helpful. Save file as well as log file.

**Comment by Karsten75** [comment]
It must be something specific to your setup. 9 seconds in, the first node appears.

![image](https://user-images.githubusercontent.com/22965021/129606396-3467b58e-a71d-4de2-a721-9ab311c4d0d2.png)


Do you have a screenshot, a save game, a log, anything to allow further investigation?

**Comment by Spyrano** [comment]
Don’t know what happened, but it started working today! Can't think of what could have fixed it that I didn't try yesterday, but closing bug report. Thanks for the responses!
