### ISSUE TITLE
[4RPL] Issues creating unit types "tower" and "pod"

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#966]
A "tower" unit type spawned with 4rpl that is then set to be instantly constructed appears to not generate soylent:
```
CreateUnitOnTerrain("tower" 20 20 NULL) ->unitUID
ConstructUnit(<-unitUID 9999)
```
![image](https://user-images.githubusercontent.com/51026936/130157724-45a0a61a-df56-4df6-82f6-0f151f2dedc2.png)

A "pod" type unit spawned with 4rpl does not connect to network and cannot be clicked at all. Doesn't matter if the unit is constructed with ConstructUnit or not, but without ConstructUnit it appears to spawn in build mode.
```
CreateUnitOnTerrain("pod" 20 20  "Resource" 0, "Size" 100, "CreeperDamages" TRUE, "Impervious" FALSE, "PlayerCanDestroy" TRUE   5 TableN) ->unitUID
ConstructUnit(<-unitUID 9999)
```
![image](https://user-images.githubusercontent.com/51026936/130157895-cb492e0d-6901-4231-96e2-9b3c0d87e24d.png)

**Comment by knucracker** [comment]
For the pod issue, see if this has anything relevant: #842

**Comment by knucracker** [comment]
For the tower, it looks like it was not being told to refresh  after the call to ConstructUnit. I've added that.  Note that if the tower was disconnected and then reconnected to the network, it would refresh.  This would have to occur across frames, though (could not be done in the same frame back to back).

For the pod issue, if anything remains after looking at #842 just open a new bug for it.
