### ISSUE TITLE
[bug] Solar panels do not show their energy contribution  in the Energy Totals 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#97]
![image](https://user-images.githubusercontent.com/22965021/96627800-ffde6b80-12d6-11eb-8628-3ff93a54912a.png)

Rift Lab still generates only 1 energy despite being connected to a large Panel.

**Comment by knucracker** [comment]
The display wasn't hooked up for the panels. While I was at it I reviewed the output. The large panel outputs 0.5 energy per sec and I have made the small panel output 0.2 per second (previously it was 0.18 per second).
