### ISSUE TITLE
[Bug.Minor] ERN can go UNKNOWN

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#976]
ERNs can go 'UNKNOWN'. Happened to me on map 1601 (a PAC map by Ankheg). I spot the lost ERN at ~13:29 in this video https://www.youtube.com/watch?v=jdgGwRg4N4Q  Note: ERN used to be docked in a mortar right about where it is located on the minimap

![image](https://user-images.githubusercontent.com/68601223/131529428-9f64abd2-4b38-4e75-8abf-218f78865e56.png)

I only noticed this once, so is probably a minor minor issue.

edit: Always seems to happen on this map, directly after start of the mission.

**Comment by PRG-YouTube** [comment]
**KnuCracker**: "Something odd is going on in that map. At the start of the mission that mortar with the ern moves. But the ern doesn't move with it. You can even destroy the mortar and the ern on the minimap will remain at the same location. So there must be some sort of ern or left over remnant of an ern associated with the minimap. If an icon on the minimap shows "UNKNOWN" that means the icon is no longer associated with any on-map unit"

**Comment by Solarmax2** [comment]
I saw your message on Discord this morning so when I got home from work, I went on my test map and "destroyed" an ERN docked in a mortar. I have gotten the same bug along with some other interesting events. [https://drive.google.com/file/d/1gxkuY_2t5Cz3gEn0cuZm6B3oX_moGfKU/view?usp=sharing](Video)
