### ISSUE TITLE
[bug]  Attempting to delete map in Map Editor fails if subfolders are present

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#98]
![image](https://user-images.githubusercontent.com/22965021/97089191-dafe3700-15fb-11eb-828c-64279304b3fc.png)

Attempted to delete a map. Dialog completed but map was not removed from editor pane. Hovering over it shows a white suare instead of map preview. 

Further investigation reveals that folder is still present and CPAKS sub-folder is also present. Surmised that full deletion/removal failed as a result of sub-folders that was not removed. 

I have thought on this some more. I understand your reluctance to delete folders on users' computers. Would it work, if instead of deleting folders, you open up the new file browser and let the user do a manual delete from there?

**Comment by Karsten75** [comment]
I'm moving this back into triage, because there are several log errors when the map editor encounters a folder where the map has been deleted, but the CPACK folder prevents deletion of the entire project. 

Unfortunately, due to how I restarted the game, the log file was NOT preserved. 

I will attempt to recreate, but no promises :(

**Comment by ProfessorOcecat** [comment]
I can confirm this: I added CPACK to a map and it refused to delete properly. Attached is the log file.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5580540/output_log.txt)

**Comment by Regallion** [comment]
Can confirm that this also occurred to me
