### ISSUE TITLE
[4RPL][BUG]GetUnitAmmo returns 0 when constructing unit with energy but returns a nonzero value when constructing with other wares with the same ammo type

### ISSUE THREAD

**Issue by Solarmax2** [KnuckleCracker/CW4-bug-tracker#980]
GetUnitAmmo returns 0 when constructing unit with Energy and the ammo ware is Energy, but it returns a nonzero value when constructing with other wares and the ammo type is the same ware as the construction ware.

**Comment by Fireswamp** [comment]
Adding additional information:
The easiest unit to see this with is the shield:
![image](https://user-images.githubusercontent.com/68219054/131947596-cc8028d5-a6ee-48b2-948e-5ae1a55b84be.png)
code was GetUnitAmmo(97) trace.
Cannon for comparison:
![image](https://user-images.githubusercontent.com/68219054/131947825-065e6caf-2e95-4436-8755-c13be4705060.png)
