### ISSUE TITLE
[4RPL] _UICallback not called for all units when multiple units are selected

### ISSUE THREAD

**Issue by zer0ner** [KnuckleCracker/CW4-bug-tracker#985]
When using `:_UICallback`, only the first unit in a group of selected units receives the callback.  However, all of the units change their state.

I assume this occurs because the game uses the first selected unit's state for the UI and doesn't want 100 units potentially impacting the display.

However, that means there is no callback or other function available to notify all selected units that their UI state was changed, so each unit therefore has to check their own state every single frame rather than efficiently waiting for the state to change.

**Comment by knucracker** [comment]
I'm not able to reproduce this, so I must be missing something. I've created a script on a custom unit:
```
:_UICallBack 
PrintAllSp("DATA" self <-_DATA GetUnitUIState(self <-_DATA))
```
I've added a 'choice' dropdown with three items to the UI definition for the unit.  It has choices of 'a', 'b', 'c'.
I have set the unit to prebuilt and added it to the player unit's build menu.  I place three instances of the unit on the map then double click one to select all three.

If I then change their choice in the UI, all three get called back and print their messages.  If the units are in a mixed state, they all still work.  Note when in a mixed state the choice will show "-----" to indicate the selected units are a mixture of choices.

The game's code appears to want to go through a snapshot of all selected units and send them an event:
```
            foreach (UnitManager um in GameSpace.instance.inputManager.selectedUnits.ToArray()) {
                if (um is CModUnitManager) {
                    (um as CModUnitManager).InvokeCoreEvent("_UICALLBACK", new RplCore.Data(slot));
                }
            }
```

So there must be some scenario I'm missing...  Just let me know if there is anything I'm not grokking.  I'll leave the issue open...
