### ISSUE TITLE
[4RPL] [MINOR BUG] Calling DestroyUnit() in Awake only works 50% of the time

### ISSUE THREAD

**Issue by zer0ner** [KnuckleCracker/CW4-bug-tracker#987]
Discovered while working on Colonies map 2352 with the Munchkins custom unit that has a limited range in which it will operate.

To keep players from building units that won't do anything, the unit attempts to self-destruct in Awake.  However, this only works exactly 50% of the time.  The first unit's `DestroyUnit()` call works inside Awake while the second unit's doesn't.  I ended up working around the issue by having the first frame of the unit execute the same removal code that was used in Awake.

I consider this issue to be a minor bug, although it might waste a packet of energy or ware due to being active for one frame.

**Comment by knucracker** [comment]
"Awake" initialization was protected from running more than once per script. The variable that was checked for "Has Run Preprocessing" was set to try after preprocessing was performed.  Preprocessing is what runs the Awake call.  If DestroyUnit was called in Awake that would dispose of the unit and clear the "Has Run Preprocessing" variable.  But, the call to preprocessing was setting the "Has Run Preprocessing" variable to true after the Awake call returned.  It should have set it before the call to Awake.  Cores are pooled after being reset, so the next attempt to build a unit was getting a script core from the pool and it has the preprocessing variable set to true when it should have been false.  This in turn prevented the Awake call from running on the second instantiation.
