### ISSUE TITLE
[Bug] Rift lab stops sending ammo to nullifiers when the Build checkbox is unchecked

### ISSUE THREAD

**Issue by zer0ner** [KnuckleCracker/CW4-bug-tracker#988]
When the `Build` checkbox under Dispatch Packets is unchecked, the Rift Lab no longer sends ammo to Nullifiers even if the `Ammo` checkbox is checked.

Checking the `Build` checkbox sends ammo to Nullifiers again.

**Comment by knucracker** [comment]
I'm not seeing this in a simple test.  Was it on a specific map or was scripting involved?
