### ISSUE TITLE
[Bug] Sweeper beams can be duplicated into ghost beams

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#992]
Build a sweeper, set a new ROTATE_RATE, hit apply. The old beams will freeze into static ghost beams and a new pair of beams with the new rotation rate is spawned.
![image](https://user-images.githubusercontent.com/68601223/136343105-bbf5a828-64cf-4e52-99d1-275e521f4f42.png)

All the old beams are merely ghosts and do not function though.
![image](https://user-images.githubusercontent.com/68601223/136343331-606b17f7-d6ce-42c1-b404-9b26a1f7c244.png)

**Comment by grabz-dev** [comment]
The sweeper doesn't clean up old beams, here's an example of something that could be added to sweeper's code to make it do so
```
:awake
   once
      Self DestroyAllAttachedBeams
   endonce
:once
   @awake
```
Probably not worth changing at this point, but yeah.

Alternative is for users to call `DestroyAllBeams` using the 4RPL console.
